### ISSUE TITLE
Login issue: Users aren't asked for login on reconnect

### ISSUE THREAD

**Issue by lethevimlet** [ForgeEssentials/ForgeEssentials#1065]
Users should be asked for login every time they connect to the server as long as the forceEnabled flag is set to true, but currently they are only asked once and the next time they reconnect they retain their group permissions, even thou they aren't logged, this is most likely due the fact that ModuleAuth.java is currently tracking the unLogged users and the logic should go the other way around where the system tracked the logged ones.

As a hot fix users **MUST** be added to unLogged set onJoin since they are remove onLogout event, and permissions (or groups) **MUST NOT** be granted to users if they aren't logged (or if they are in the unLogged set provided that onJoin did add them).

**Comment by arruda** [comment]
Hi there, @luacs1998  I'm not sure but this fix isn't present in the latest release (FE 1.3.04) right? And I saw this would be the last release for 1.6.4, so is there anyway that another minnor release containing this fix could be added?
Or maybe a link to a `forgeessentials-1.6.4-1.3.0.4-auth.jar` that contains this fix =/
Thanks

**Comment by luacs1998** [comment]
No more fixes. What's stopping you from upgrading to 1.7.10?

**Comment by arruda** [comment]
I'm using some mods that only have support for 1.6.4 =((
