### ISSUE TITLE
Custom crafting recipes

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1164]
Add feature in FE to define and use custom crafting recipes.
Recording the crafting recipe might be done with a little trick by monitoring the crafting table a player uses. There already exist a mod like this, but it's only for 1.6.4.
This feature has lower priority and can be implemented once somebody has some time for it, or someone specially requests it.

**Comment by luacs1998** [comment]
Use Minetweaker - it's far more powerful and specialized for this (and is also available for 1.7.10 now)

**Comment by liach** [comment]
How about 1.8? Although Minetweaker is availiable on Minecraft 1.8, but if you want to use it on the server you need it on both server and client side ([reference](https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC18-Main/src/main/java/minetweaker/mc18/MineTweakerMod.java#L59)).

**Comment by olee** [comment]
You **ALWAYS** need a client mod for that, because recipes are checked on the client as well.
However what I meant with this feature is defining custom recipes **while the server is running**.
This is still something that would be great to have as a feature for many players without having to rely on Minetweaker....
