### ISSUE TITLE
Sign editing

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#1169]
Should be simple to implement as part of signtools module.

**Comment by luacs1998** [comment]
Packets are working. Noclip decided to work for me one day out of the blue.

**Comment by olee** [comment]
@luacs1998 please check the status of this issue and if it's already done, close it please.

**Comment by luacs1998** [comment]
Not done. Haven't managed to get it to sync properly, gotta resurrect the old feature branch to find out exactly what's wrong.

**Comment by luacs1998** [comment]
Shit, I deleted the old feature branch...

Gotta do it over.

**Comment by olee** [comment]
Seriously? When you do it be sure to only allow sign editing, if `fe.protection.break....sign` **and**  `fe.protection.place....sign` sign are granted which would be the same as removing the old and placing a new one.
