### ISSUE TITLE
Apply permissions on passive interact events

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#1240]
Permissions should apply to occurrences like:

- [x] **Player triggers pressure plate / tripwire**
- [x] Player tramples on crops
- [ ] Maybe a few others

Will most likely require ASM patching.

**Comment by olee** [comment]
Pressure-plates have highest priority imho and might even be possible without a hook (hopefully).

**Comment by olee** [comment]
@luacs1998 Totally forgot about this one... We should definitely do this.

**Comment by luacs1998** [comment]
Still interested in a crop trampling event?

**Comment by olee** [comment]
:laughing: @ that event name

**Comment by luacs1998** [comment]
(CropGettingTrampledEvent e) (CropGotTrampledEvent e)

**Comment by luacs1998** [comment]
Also, as a note, tripwires also call doesEntityNotTriggerPressurePlate.

**Comment by olee** [comment]
So they are the same - is the block that was checked passed in the event?
If not it should be added and then we could make the check more detailed.

**Comment by Techjar** [comment]
We have crop trampling now, not sure what would constitute "others" though. If anyone thinks of anything, jot it down here.

**Comment by olee** [comment]
Fixed with https://github.com/ForgeEssentials/ForgeEssentials/commit/bd4f1fb26beba9f9d25ac175a57bffebd905c76c
