### ISSUE TITLE
Mcbans intergration

### ISSUE THREAD

**Issue by kerts93** [ForgeEssentials/ForgeEssentials#1283]
It would be nice if you guys could implement MCbans plugins. I've used it on all of my servers and would like to use it on our Forge server also.

http://mcbans.com/

**Comment by luacs1998** [comment]
Can be done, but will most likely be disabled by default and require you to get a MCBans API key before you can use it.

**Comment by luacs1998** [comment]
I waited eight months and haven't heard back from MCBans. It should be easy enough for MCBans to implement a plugin directly on Forge/Sponge.
