### ISSUE TITLE
More detailed permissions for permission commands

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1355]
From IRC:
````
[17:30:11] <bb> hey guys is there a way to specify that members of a group may set the group of other players to their own group but nothing higher?
[17:31:33] <bb> i'd like to give members the ability to set the group of new players to members but not to admin or any group with more power
````
I.e. better permissions on permission control itself.
This should be implemented.

**Comment by olee** [comment]
@luacs1998 There was a reason I named it like that - this should not only include promoting but other permission control as well.

**Comment by olee** [comment]
Added a promotion command to allow server operators (not admins) to set player-groups, without giving them full access to permissions.

Usage: `/promote <player> <group>`
Groups available for remote need to have the permissions `fe.internal.group.promotion` allowed.

**Comment by luacs1998** [comment]
I would think that the original request has been fulfilled - open another issue if you want to do more.

Closing.

**Comment by olee** [comment]
Actually not - this was supposed to allow permissions for setting permissions - i.e. to allow "sub admins".
However I think this indeed adds way too much complexity so this is a no-do.
