### ISSUE TITLE
Fix permissions API

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#1375]
As underlined in https://gist.github.com/luacs1998/686a57f2690c0006dd72

Then maybe we can try to make a PR again.

**Comment by olee** [comment]
Fixed a lot of the old design in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/5a708b9d7c335ed87c963e0522ecad737f25d868
Should convert this into a Forge PR then.

**Comment by luacs1998** [comment]
Can I close this then?

**Comment by olee** [comment]
Well we still should try to make a PR...

**Comment by luacs1998** [comment]
@olee I'm thinking about redesigning permissions to use the Capability API that was introduced in Forge 1.8.9. What do you think?

**Comment by olee** [comment]
Capability API? 
Sounds interesting - get me some links :wink:

**Comment by luacs1998** [comment]
https://github.com/MinecraftForge/MinecraftForge/tree/master/src/main/java/net/minecraftforge/common/capabilities

**Comment by luacs1998** [comment]
We'll see what happens with #3155 - maybe we might adopt that.

**Comment by yuuka-miya** [comment]
Closed, since Latvian's PR got accepted (a long time ago).
