### ISSUE TITLE
Client questioner keybindings

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1452]

**Comment by luacs1998** [comment]
I'm still thinking how best I want to do this.

A popup in the corner, asking for attention? Or another approach? This should be as unobtrusive to the player as possible

**Comment by Pyeroh** [comment]
In Forestry, when you get a mail, the sky starts to flicker (can be desactivated) and you have a little notification in the top-left corner. Maybe this can be reproduced with FE and questions =)

**Comment by evernife** [comment]
dont forge to reproduce a sound, it would be more helpful than everything

**Comment by olee** [comment]
A simple popup window in the top left / right corner should be good.
Because it is easy to just press YES or NO, it doesn't really matter even if it is a little bit obtrusive.

**Comment by evernife** [comment]
I dont think the top is so good. Thaumcraft take the left top (or even the damage indicators) and on the top right there is the Minimap.

Suggetion: Botton Left.

**Comment by liach** [comment]
Suggestion: use in game config to change gui display corner.

**Comment by evernife** [comment]
:D

**Comment by olee** [comment]
Bottom left is the worst place ever - blocks chat.
It's no problem to place that popup above minimap or other stuff for a few seconds.

**Comment by liach** [comment]
Haha then a pop up in chat.

**Comment by evernife** [comment]
Better :D
Players aways look at the chat :D
If is not a ETERNAL pop up, it will be really useful, and as the suggestion made by our friend liach it could be configurable.

**Comment by olee** [comment]
Guys please don't keep throwing random and obvious suggestions into the issue one after another.
1) We already have clickable YES and NO links for questioner in the chat
2) The popup would only be small and go into whatever corner or even the center of the screen but that will probably be adjustable by configuration anyway so please no more "it should go here / it should go there stuff"

**Comment by luacs1998** [comment]
I'm thinking if the clickable YES/NO links are enough to close this issue.

**Comment by olee** [comment]
I think they are not enough which is why I opened this issue.
We have the FE client and we should actually make use of it.
Also it would be cool to have a little dialog with a bar showing the timeout as well and if the FE client is present, the (often long) question would not spam the chat any more.

**Comment by olee** [comment]
I heard from a friend that this is actually useless as a GUI.
It would be just to annoying to always have it pop up and it needs to enable mouse mode which is annoying, too.
The idea he told me was just using key-bindings to answer questions (only listen to keys with highest priority over other mods while a question is active though).

**Comment by luacs1998** [comment]
I don't think a priority system for keybindings exists on MC, so it's not a good idea.

The best approach is probably the clickable yes/no links that are currently implemented. We should probably make them more obvious.

Voting to invalidate this.

**Comment by olee** [comment]
I still think that a keybinding - and not using the mouse - is the best solution.
On my server we are using `/trade` and `/sell` all the time and all agree on having a key binding is the most useful solution.
And what I mean with getting the key events with higher priority is that once the question is active, it should try to get the key event if possible, and if no question is active it should let it pass for other mods to use it for shortcuts so we are not blocking any keys.

**Comment by luacs1998** [comment]
It's to be done, but we'll configure function keys by default.

**Comment by luacs1998** [comment]
Alright, this is simple enough. F5 for yes, F6 for no.
