### ISSUE TITLE
Loose money from wallet when dying

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1461]
Allow to set up loosing a configurable amount of money from wallet when dying (absolute **and** percentage)

**Comment by luacs1998** [comment]
This should be a permprop, and is easy enough to do. I'll do it.

**Comment by Zethalion** [comment]
Percentage part is not correctly implemented yet.

**Comment by spacebuilder2020** [comment]
This issue has been closed for 3 years.  If the feature was not correctly implemented,  a defect should be created as a new issue.  Closing!
