### ISSUE TITLE
ForgeEssentials Clearing MySQL Zone Table on server start

### ISSUE THREAD

**Issue by Zoryn4163** [ForgeEssentials/ForgeEssentials#1554]
Title. Running latest Jenkins build (beta08 build 693)
It happens when the server has fully loaded. The console states "[20:14:56] [Server thread/INFO] [ForgeEssentials/]: Saving permissions..." and the table is _immediately_ cleared and re-populated with the default values.

Full FML log: https://drive.google.com/open?id=0B-_iReN21PiIUlpLQUdhN3ZEZjg&authuser=0 (too big for pastebin)

I'm testing if this occurs in FlatFiles now..
Edit: This is also occuring in FlatFiles including with all default configs.
Note: Server is running Ubuntu 14, Server is being ran as 'root', the logged-on user has full access to all necessary files.

**Comment by olee** [comment]
It should normally clear everything and then write the loaded values.
When saving permissions, FE will (currently) delete all files / rows and then save it's current state.
This is indeed not quite a good solution, but it works (at least it's supposed to).
However I plan to rewrite it to write only the changed permissions like it's supposed to be.

**Comment by Zoryn4163** [comment]
FlatFile appears to randomly be working. It's doable for now but I don't understand why one would work and not the other.

**Comment by olee** [comment]
Why did you even switch to MySql?
If you don't have a reason for it, you should not switch.
I am even thinking of completely removing it, as remote access to permissions can now easily be realized through remote which is also safer.

The default save format for permissions is not without a reason flatfile as it works more efficient and is easy to edit.

**Comment by Zoryn4163** [comment]
I'd switched to SQL because I felt it'd be more secure and via PhpMyAdmin it's easy to edit. I'm not familiar with how remote works and see no documentation on it. And if you read the first post FlatFile originally *wasn't* working. It started to for reasons I don't understand but seems to now be stable. Regardless having MySQL as an option should either be working or removed, your choice, but you shouldn't include it if it only leads to problems.

**Comment by olee** [comment]
@Zoryn4163 https://github.com/ForgeEssentials/PHPRemoteLib can help you then.
With that it's easy to access this data.

As for SQL, I at least added a not that it really "should not be used yet" as it was tested by far not enough. My fault for not making that clear earlier.

About flatfile: This should work reliably. The only problem it has is if files are locked by some other program in the permission directory. But I am working on a fix for that.

**Comment by luacs1998** [comment]
Is this still an issue?

**Comment by olee** [comment]
Yes.
SQL permission storage should be rewritten with hibernate sometime.
That would make it a lot more efficient and safe.

**Comment by maximuslotro** [comment]
Closing as Probably fixed in the past decade.

**Comment by spacebuilder2020** [comment]
Doubt it was ever fixed cause SQL code was never rewritten to use hibernate...  But at this point it is unsupported
