### ISSUE TITLE
Extended console

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#1566]
A special UI to send commands over 200 characters, due to the chat/command character limit.

~~Due to the 200 character limit for commands (and chat), it is impossible to file detailed tickets. A GUI for FEClient should be added, so we have a nice UI and can also work around this restriction.~~

**Comment by aschmois** [comment]
Would be nice to extend this view for other types of commands. i.e. WorldEdit generate can't create crazy structures because some functions are larger than 200 characters.

**Comment by olee** [comment]
I support this in that we should try to increase maximum message length or at least allow a special UI to send larger commands (i.e. a text box with multiline support that can be used to run commands)

**Comment by luacs1998** [comment]
I really think this should be a separate mod, but is it just me?
