### ISSUE TITLE
player logger mysql not working

### ISSUE THREAD

**Issue by Goten87** [ForgeEssentials/ForgeEssentials#1569]
hello FE team
when i set my playerlogger config to mysql and update the stuff to what it needs to be it will crash my server

i have  tryed `S:DB_url="localhost:3306/fe_logger"`
and `S:DB_url=localhost:3306/fe_logger`
with both its crashing its username password and type are correct but it keeps crashing
when i set it to H2 type it works but with mysql it crash my server

i'm on Build 731

**Comment by luacs1998** [comment]
Logs?

**Comment by Goten87** [comment]
I Will upload my log tomorow not at my pc anymore

**Comment by olee** [comment]
@Goten87 use H2 database and **not MySql**.
The only sane reason to use MySql would be accessing playerlogger data externally, though I intend to allow doing that with remote instead.

I am even thinking of removing the MySql support because it really makes no sense.
MySql database is just too slow compared to H2 to use it efficiently for playerlogger.

Also: logs!

**Comment by Goten87** [comment]
Well i was making a website for it so thats why i want in on mysql and i Will gave logs soon was not on my pc today

**Comment by olee** [comment]
You might want to use remote then which (will) have better support for stuff like that then.
We have a [PHP wrapper](https://github.com/ForgeEssentials/PHPRemoteLib) for remote which easily allows requesting data from it. The only thing left is to add the necessary handlers to query playerlogger data.

As for MySql db I can check it once I have the log.

**Comment by Goten87** [comment]
https://gist.githubusercontent.com/Goten87/d0fc334e6cf64703e068/raw/fml-server-latest.log
there u go the log of my whole server startup i realy donno what is going wrong
sins it will just stop working with no crash at all

**Comment by olee** [comment]
Something is wrong with the connection string:
````
MySQLNonTransientConnectionException: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "3306/fe_logger""'
````
Something seems to be wrong with the database connection url, but I cannot see any problems with it.
Hibernate documentation tells me it should look like `jdbc:mysql://localhost:3306/dbname` for example. ForgeEssentials itself prepends the string that is set in the config with `jdbc:mysql://`.

This would mean your full connection url looks like `jdbc:mysql://localhost:3306/fe_logger` which seems correct.

**Comment by olee** [comment]
After looking around a bit, I suspect you did not use a normal `/` after the port number.
Maybe you used some unicode character instead?

**Comment by luacs1998** [comment]
Is this still an issue?

**Comment by Goten87** [comment]
i have no idear @luacs1998 my server broke and have not yet fixed it so i cant test it anymore

**Comment by luacs1998** [comment]
Alright, then I'll close this issue. Reopen if it still occurs.
