### ISSUE TITLE
Random world respawn

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentials#1592]
Hello,

I'm trying with FE scripting to check if bed spawn is set by player on respawn after death, how could I do that?

I would like to use randomtp mod to respawn players randomly in the world if they don't have a placed bed and have used it at least once.

Thank you for your time.

**Comment by luacs1998** [comment]
Don't think it's possible yet.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you for reply luacs, please keep what i wrote in mind for future development/feature request.

Keep up the good work!

**Comment by olee** [comment]
I can maybe think of something, but doing a random respawn in the world is not simple.

**Comment by luacs1998** [comment]
Wouldn't it be a case of moving the player from the predefined spawnpoint to randomly defined coordinates?

**Comment by olee** [comment]
I think it would be easiest if we just make a random-teleport command in which you can specify an area (by parameters or by an area-id used by permissions). That command would then teleport the player to any location in that area that is considered safe. After that this command only needs to be run from a script on player respawn.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you so much guys for looking into it.

**Comment by spacebuilder2020** [comment]
I just added a random script argument in my latest pull request, so that should at least make a random teleport possible command possible.  All we would need now is a safe teleport function that moves the player to a nearby location that is safe.

**Comment by olee** [comment]
@spacebuilder2020 think you can quickly add this?
Should be very easy to code.

**Comment by luacs1998** [comment]
Isn't the current teleport command already 'safe'?

**Comment by olee** [comment]
Afaik yes (it checks if there are at least a no solid blocks where the player wants to teleport).

**Comment by Techjar** [comment]
Can't you achieve this using the vanilla /spreadplayers command?

**Comment by olee** [comment]
Didn't know MC had that command.
I guess then we can close this.
Only interesting thing would be an extension that allows specifying an area name / WE selection for the command.

**Comment by Techjar** [comment]
It should now be possible to implement this properly with the new JScripting module. See #2165.

**Comment by olee** [comment]
Not yet, but will be.

**Comment by Techjar** [comment]
No it definitely is. There's a respawn event, you can call commands, and I added the bed location thing.
