### ISSUE TITLE
Do away with overwriting methods in mixins

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#1619]
We should move to safer (injecting-at-point) mixins (both for better compatibility and because overwriting methods is quite crude)

**Comment by luacs1998** [comment]
Moving to our own in-house patcher should make things easier.

**Comment by kashike** [comment]
Mostly done with https://github.com/ForgeEssentials/ForgeEssentials/commit/300aa28473a06125ff2089ef9ffeaff9c693ce78 for 1.7.10/develop - only a few remain, either because we want to actually overwrite the methods in question, or because others can't be done easily/at all otherwise.

**Comment by luacs1998** [comment]
I guess we're done with this then.
