### ISSUE TITLE
Fix BlockPortal mixin

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentials#1649]
hey guys!

yes i wondered about our portals (created with /portal) because now there are glas panes instaed of vanilla portal blocks. The portal works if we walk through it. Destroying the block dont work.

Any ideas ?

using latest dev builds

**Comment by luacs1998** [comment]
Known, it got reverted due to some bugs with the patch.

**Comment by jogi01** [comment]
ok thx!

**Comment by luacs1998** [comment]
Do we still want this?

**Comment by olee** [comment]
Well it's necessary to build portals with real portal surfaces and not some fake glass.

**Comment by maximuslotro** [comment]
Issue closed. Open a new issue if the issue persists.
