### ISSUE TITLE
Command Sign crashes users with the client side

### ISSUE THREAD

**Issue by BossLetsPlays** [ForgeEssentials/ForgeEssentials#1659]
If one of my server staff members or a player has the client side of this mod installed then using the command signs will crash them.

**Comment by olee** [comment]
Please attach a crashlog!

**Comment by BossLetsPlays** [comment]
Apologies for the late reply. We've been testing several things on our server and while testing we learned the user doesn't always crash. Sometimes it works, sometimes you get a message saying an unknown error occurred while attempting to perform command, and when the user does crash it looks like this: http://pastebin.com/LBRiBNZz

**Comment by luacs1998** [comment]
Any and all command signs, or only particular ones?

**Comment by BossLetsPlays** [comment]
Sorry for late response... so far we have only tested using the warp command.

[command]
warp
survival1

That would be an example of how we use warp signs. Will test other commands later. Also this error doesnt happen for everyone or all the time. So far it has only happened to 3 of my staff who use the client side.

**Comment by luacs1998** [comment]
Well that's something that isn't exactly supposed to happen.

We use string joining to join together all 4 lines of the sign, so if the string joining only fails in some cases...

**Comment by luacs1998** [comment]
I am unable to reproduce this.

Server build 919, client build 919, sign text is

`[command]`
`give luacs1998`
`dirt 64`

**Comment by BossLetsPlays** [comment]
Any chance its a bug with the warp command then? We've yet to see the issue with other commands. Also on a side note, is there a way to let users use the signs but not be able to directly use the /warp command? Enabling sign perms but disabling warp perms doesnt work

**Comment by luacs1998** [comment]
This still a thing? I am unable to reproduce...
