### ISSUE TITLE
[playerlogger] Fire logging

### ISSUE THREAD

**Issue by BossLetsPlays** [ForgeEssentials/ForgeEssentials#1665]
There are items in the mod on my server that lets players use lighting. One player accidently used it to burn down an entire wooden castle of another, however using `/rb` doesn't seem to help. Did some testing and it only seems to rollback blocks broken and placed. I don't know if this is a bug or a request, but it would be nice to be able to rollback damages from blocks burning, exploding, etc.

**Comment by olee** [comment]
Yes - by now it only works for normal block breaking + explosions.
Fire checking is one of the things I definitely want to add.
Not only just logging the spread / damage of fire, but also disable it's spread / destruction completely via permissions, too.

**Comment by luacs1998** [comment]
Disable fire destruction is available with the `doFireTick` gamerule. Not that sure about spread.

Will a "notification" event (non-cancellable) do?

**Comment by olee** [comment]
Of course cancable.
Otherwise it would be useless for permissions.
And there should be either two types of events, or a flag on the event which specifies, if the event is about fire *spread* or *destruction*.
The gamerule always changes both, but with the event we should be able to control both individually.

**Comment by luacs1998** [comment]
Events added in #1758 - @olee 's turn to add the permissions and PL hooks.

**Comment by luacs1998** [comment]
Permissions have been added - now just for the PL hook.

**Comment by Techjar** [comment]
This was added in 505197f.
