### ISSUE TITLE
TPA not working with multiple dimensions

### ISSUE THREAD

**Issue by BossLetsPlays** [ForgeEssentials/ForgeEssentials#1668]
I run the official DivineRPG server which has 8 new dimensions. For some reason when a user `/tpa` to someone, if it is accepted then they are sent high in the air in one of the dimensions (Eden) and end up falling to the void and dying. Not sure if this is a conflict with our mod or a bug in FE.

**Comment by olee** [comment]
This might be the same issue as #1612

**Comment by olee** [comment]
Too old issue - might not be relevant any more.
Closing.
