### ISSUE TITLE
rcon - You do not have permission to use this command

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentials#1671]
hey again ;)

I have searched the last hour how to set permissions to rcon. I am confusing because it worked a few weeks ago :(
Now every commands ends in "you do not have permission..." except help command that works..
Is there a "fakeuser" which i have to give permissions ? Nothing found yet...
We are using forgeessentials-1.7.10-1.4.1.830-server
thanks for help !
-jogi

**Comment by olee** [comment]
There should be no need to configure permissions for console at all.
However I think you can get the same message with "You do not have permission..." when the command is just not usable from console.

**Comment by LemonLake** [comment]
Can confirm, this happens with all op only commands, usable from console or not.

**Comment by olee** [comment]
So let me verify this again:
Only commands that need OP permission and **are** usable from console, are not usable via rcon?

**Comment by jogi01** [comment]
here some tests:

whitelist
You don't have permissions to use this command!
say test
You don't have permissions to use this command!
p group
You don't have permissions to use this command!
p
/feperm user|group|global|list|test|reload|save|debug: Displays help for the subcommands
p list groups
You don't have permissions to use this command!
help

--- Showing help page 1 of 9 (/help <page>) ---//fewand [rebind|unbind|ITEM] Toggles the wand//help [<command>]Commands provided by Applied Energistics 2 - use /ae2 list for a list, and /ae2 help _____ for help with a command./afk: Mark yourself as away./back: Teleport you to your last death or teleport location./bed [player] Teleport you or another player to the bed last used./buildcraft help

**Comment by olee** [comment]
(A simple yes would have done it, too :sweat_smile:)
Will investigate this in the next time.
Instead of RCON however I recommend you use https://github.com/ForgeEssentials/FERemoteClient instead, which will allow you to run commands **and much more** on the server through FE and all access is controlled by permissions.

**Comment by jogi01** [comment]
ok i usually use the ssh shell its for the co-ops :) i will try it out, thx!

**Comment by olee** [comment]
The good thing is that you can give co-OPs a bit less permissions by only giving access with remote.
Remember however that FE remote is still in development - if you have questions regarding it ask on IRC or open an issue on the [issue tracker of FERemoteClient](https://github.com/ForgeEssentials/FERemoteClient/issues)

**Comment by olee** [comment]
@jogi01 Sorry but I don't even manage to use MC rcon in any way.
From what I read on the web that rcon implementation of Minecraft is pretty much crap.
Could you tell me how you use it? I tried using http://sourceforge.net/projects/mcrcon/ but it causes an exception on the server directly after connecting...

**Comment by olee** [comment]
Wow that was really true - that rcon is not just crap - its literally a piece of shit any 3rd class programmer could do better than those guys at Mojang...
````java
    public void run()
    {
        while (true)
        {
            try
            {
                /* READ AND PROCESS ONE MESSAGE */
            }
            catch (SocketTimeoutException sockettimeoutexception)
            {
                break;
            }
            catch (IOException ioexception)
            {
                break;
            }
            catch (Exception exception1)
            {
                field_164005_h.error("Exception whilst parsing RCON input", exception1);
                break;
            }
            finally
            {
                this.closeSocket();
            }

            return;
        }
    }
````
These stupid guys alway close the socket in the loop making it impossible to send more than one command at all and that also only if password authentication is disabled. Otherwise the client will be disconnected after authentication making it impossible to send any other commands :sweat:

**Comment by olee** [comment]
Ok this is worse than I imagined. These guys at Mojang are not even able to properly implement that rcon interface. As far as I can see from the code, it's impossible for this thing to work.
@jogi01 are you sure you got at least _anything_ to work with rcon?

**Comment by luacs1998** [comment]
https://bugs.mojang.com/secure/Dashboard.jspa just saying

**Comment by jogi01** [comment]
hi, i use an exe program that supports gui where i can select my server and connect to it. than i can control my server with ease i dont need to connect to ssh shell and then connect to the screen.
More comfort gives the several smartphone apps which supports rcon. 
I ever thoght this is standard and integrated :)
Well, your tested rcon program must work too, my program is from a older source which i have forgotten and i think you dont want a exe program from me where you dont know from where it is, dont you :) If you want it i can upload it for you to our gameservers webspace.
In the case of security issues i cant understand why mojang didnt do anything or prevent hacking methodes. But - every server needs accessible administration features and i had more than twenty situations where i solved server issues via smartphone with rcon apps :)

the sourceforge program works too, i have changed the batch file and editied the default ip adress and the password, our server is native forge maybe that there will come errors with cauldron ?

**Comment by olee** [comment]
Well I tested it with just forge with no luck...
@luacs1998 can you maybe try and see if you get it to work?

@jogi01 Well we are (more or less) working on an Android app to allow authenticated remote control of the server (kinda like rcon - just way better. However the development on this one is halted for now because @aschmois is a but busy in RL.

However I am also working on an Admin panel that will basically allow you to do the same stuff and it will be mobile optimized as well. You can try it out when it's done (note: not an official FE project *yet*)

**Comment by luacs1998** [comment]
http://wiki.vg/Rcon

**Comment by jogi01** [comment]
hi, that sounds great! ok i am an apple user but.. in case of emergancy i have a ssh shell app to connect to the console - it is just very inconvenient but it works :)

**Comment by jogi01** [comment]
top! many thanks !!

**Comment by racinmat** [comment]
Hi, using version forgeessentials-1.12.2-12.3.27-server still have this problem.

**Comment by spacebuilder2020** [comment]
This issue was closed and confirmed fixed on August 17th, 2015!

If this is an issue in newer builds please open a new issue.

**Comment by byteduck** [comment]
This is an issue again.
