### ISSUE TITLE
[Solved] Sponge incompatibility

### ISSUE THREAD

**Issue by Billabonga** [ForgeEssentials/ForgeEssentials#1674]
Hi, after installing FE Minecraft did not start.

[13:41:17] [Client thread/INFO]: Setting user: Toothpick
[13:41:21] [Client thread/INFO]: LWJGL Version: 2.9.1
[13:41:25] [Client thread/INFO]: Reloading ResourceManager: Default
[13:41:26] [Client thread/ERROR]: Couldn't initialize twitch stream
[13:41:26] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:41:26] [Thread-8/INFO]: Initializing LWJGL OpenAL
[13:41:26] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:41:26] [Thread-8/INFO]: OpenAL initialized.
[13:41:26] [Sound Library Loader/INFO]: Sound engine started
[13:41:30] [Client thread/INFO]: Created: 512x512 textures-atlas
[13:41:51] [Client thread/INFO]: Stopping!
[13:41:51] [Client thread/INFO]: SoundSystem shutting down...
[13:41:51] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

What went wrong?

**Comment by luacs1998** [comment]
Proper logs?

**Comment by Billabonga** [comment]
I dont have a Pro Acc with Pastebin. So the log files would be too large to paste here.
However, I am using Sponge and there seems to be a conflict with Craftbook 4 and / or Sponge Essential Cmds

**Comment by luacs1998** [comment]
1) gist.github.com - it's free and uses your existing github account

2) Yeah Sponge is not fully supported yet. A lot more work on our part, but something awesome is coming (#1031)

**Comment by olee** [comment]
OT: I never even tested any kind of Sponge and I think you should not expect a plugin like "Sponge Essential" to be ~~necessary if you use~~ compatible with FE.

**Comment by luacs1998** [comment]
He probably means the Sponge port of BukkitEssentials.

**Comment by olee** [comment]
I know - and FE started out as a port of Bukkit Essentials as well, didn't it?
If one adds Sponge Essential and ForgeEssentials at the same time, most commands would be doubles.

**Comment by Billabonga** [comment]
Thanks for your comments, guys. - For your info, there is a plugin for Sponge called SpongeEssentialCmds which covers eg /sethome, /home, /setwarp, /heal etc. I suggest you have a look at it. It's pretty neat.

https://forums.spongepowered.org/t/spongeessentialcmds-v1-6/8576

Someone else also started a multi world plugin but seemed to have stopped in his tracks ... Maybe you can collaborate with him? - It's only an idea.

Sponge definitely seems to be the real thing and all developers are going great guns to make it the successful alternative to Bukkit. As I mentioned before, Craftbook 4 is almost complete and most other plugins have been or are nearing completion.

https://forums.spongepowered.org/

**Comment by luacs1998** [comment]
@olee no it didn't, abrar just used the same name.

@Billabonga the plan is to allow FE to interact with sponge plugins, meaning you can have things like craftbook use FE perms and stuff. FYI I am following the Sponge Project, and am keeping myself up to date with what's going on as far as I am able to.

**Comment by olee** [comment]
@Billabonga you know that **all** these commands are already in ForgeEssentials so that sponge mod is useless? And if there would be anything of those commands not already in FE, it's something we can add :wink: 
(Actually we had that stuff before Sponge Essential so it's a bit weird for you to tell us to check that stuff out that we had since ages ago :smirk: )

**Comment by luacs1998** [comment]
So, what actually needs to be done?
