### ISSUE TITLE
no chat

### ISSUE THREAD

**Issue by ollem99** [ForgeEssentials/ForgeEssentials#1699]
i'm hosting a pixelmon server (mod: pixelmon and forgeessentials) and i can use commands but when i 
just normal wanna talk it doesn't show command like /say work but that not normal any 1 know wat the problem is??

**Comment by olee** [comment]
What exactly is the problem?
Do chat messages now show up, unless you use the `/say` command?
Please fix your english - I can't understand what you wanted to say at all...

**Comment by ollem99** [comment]
o sry for my english uhhm the thing is that chat does not show not even in the console it only work when i use/say

**Comment by olee** [comment]
Probably one of your other mods causing this or you messed around with chat config.

Try removing FE and see if you get the chat back.
If not, blame yourself for not testing that before reporting here.

If removing FE fixes the issue, try deleting `ForgeEssentials/Chat.cfg` and see if that solves the issue.

**Comment by ollem99** [comment]
i tryed to remove fe before i posted this and i give my chat back. the other mod in there is pixelmon.
and i just tryed to remove forge essentails chat config but that didn't fixed that problem

**Comment by olee** [comment]
If you configured any permissions, then try removing all of them for a moment (by moving `world/FEData/permissions` somewhere else for a moment).

If that does not fix the problem it must be some problem with pixelmon and we will need to check the problem in detail.

**Comment by ollem99** [comment]
i'm running 1.8.0.26 i moved the perm file still not able to chat normaly

**Comment by olee** [comment]
Ok this is interesting - the same thing happened to me now on my modded server which is kinda interesting, since I didn't change anything instead of updating FE.
In the dev environment it works without a problem though.
Maybe it is caused because of some changes in forge...

**Comment by ollem99** [comment]
so i need to downgrade forge or .??

2015-08-18 4:32 GMT+02:00 Björn Zeutzheim <notifications@github.com>:

**Comment by OvermindDL1** [comment]
It is worth trying.

**Comment by ollem99** [comment]
but the problem is the new pixelmon mod need forge 1450 so that would be a problem

**Comment by olee** [comment]
@ollem99 Did you check if maybe any error is thrown on the sever when someone tries to send a chat message? Just for verification.

**Comment by ollem99** [comment]
No nothing shows i look add the chat log(server log) and even there is nothing. Exept the other commands those show

**Comment by ollem99** [comment]
uuhm so the problem is that the forge essnetials is not fully working with the lastest forge

**Comment by olee** [comment]
No... I just tried running latest pixelmon with FE and there were no problems at all with chat.
Did you try setting up a simple test server yet with only FE and pixelmon?
Either you have another mod added which causes this problem or you changed something in the configs making this not work. Please report back after testing it with a completely clean config or at least try deleting `./ForgeEssentials/Chat.cfg` and then see if it works.
