### ISSUE TITLE
Command Signs always report "Unknown command"

### ISSUE THREAD

**Issue by siameseSerpent** [ForgeEssentials/ForgeEssentials#1704]
Signs with the [command] text in the first line always return "Unknown command", regardless of formatting. Following the example on the wiki of
[command]
help
also returns unknown command.
http://puu.sh/jGtsT/f21367aabb.jpg

**Comment by olee** [comment]
@siameseSerpent Is this on 1.7.10 or on 1.8?

**Comment by thijskosterman** [comment]
I have this too, running 1.8. 
Just the "unknow command" error.

**Comment by olee** [comment]
Can someone confirm if this works properly on 1.7.10?

**Comment by luacs1998** [comment]
I checked in 1.7.10 when the previous issue was reported, it is working properly.

**Comment by siameseSerpent** [comment]
This is indeed a 1.8 issue, sorry for not stating it in the original post!

**Comment by luacs1998** [comment]
Oops, it didn't close.
