### ISSUE TITLE
Extended playerlogger checking

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#1723]
Something like a /pl info <x> <y> <z> that displays the playerlogger info (what you get by right-clicking with a clock) for the chosen block.

If no coordinates are specified, the block the player is looking at should be used.

**Comment by olee** [comment]
Instead of that I intended to add playerlogger commands that use the current selection for checks.

**Comment by olee** [comment]
Tracked in #2143 now
