### ISSUE TITLE
Failed to add FE as a dependency in mc 1.8

### ISSUE THREAD

**Issue by liach** [ForgeEssentials/ForgeEssentials#1762]
[Developer Documentation] (https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Developer-documentation)
Yes it works pretty good in 1.7.10 (FE 1.4), grabbing files correctly, but when building with gradle it says that pom file could not be resolved. Using ForgeGradle 1.2. No problem with `gradlew setupDecompWorkspace`, but with `gradlew build`.

Note: Log would be presented later.

EDIT: Log: (not too long so paste it here, running `gradle build`)
```
****************************
 Powered By MCP:             
 http://modcoderpack.com/    
 Searge, ProfMobius, Fesh0r, 
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : snapshot_nodoc_20141130
****************************
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava
Download http://files.minecraftforge.net/maven/com/forgeessentials/forgeessentials/1.8.0/forgeessentials-1.8.0.pom

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve com.forgeessentials:forgeessentials:1.8.0.
  Required by:
      mod.uhcreloaded:UHC-Reloaded:Alpha-rv1
   > Could not resolve com.forgeessentials:forgeessentials:1.8.0.
      > Could not parse POM http://files.minecraftforge.net/maven/com/forgeessentials/forgeessentials/1.8.0/forgeessentials-1.8.0.pom
         > Unable to resolve version for dependency ':unspecified:jar'
   > Could not resolve com.forgeessentials:forgeessentials:1.8.0.
      > Could not get resource 'https://libraries.minecraft.net/com/forgeessentials/forgeessentials/1.8.0/forgeessentials-1.8.0.pom'.
         > Could not HEAD 'https://libraries.minecraft.net/com/forgeessentials/forgeessentials/1.8.0/forgeessentials-1.8.0.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.82 secs

```

**Comment by luacs1998** [comment]
`com.forgeessentials:forgeessentials:1.8.3-SNAPSHOT`

**Comment by liach** [comment]
The same.

**Comment by luacs1998** [comment]
Paste dependencies{} block of build.gradle

The second report is the exact same as the first one. You are specifying the wrong version of FE - it should be `1.8.3-SNAPSHOT` instead of 1.8.0.

**Comment by liach** [comment]
Unfortunately I left the code on the laptop at home... Could you show me the log using `1.8.3-SNAPSHOT`? I might have tried this one.

**Comment by liach** [comment]
The build log using `1.8.3-SNAPSHOT` (`gradle build -i`): http://paste.md-5.net/xiyuropimi.mel
The `build.gradle`: http://paste.md-5.net/podetarabo.vbs

**Comment by luacs1998** [comment]
Build error on our part - I'll see what I can do.

**Comment by luacs1998** [comment]
Try again, with the exact same buildfile. I have updated some things on the server's end.

**Comment by liach** [comment]
More weird this time...
http://paste.md-5.net/niguhoveka.pas

**Comment by liach** [comment]
Now I guess I need to ship we in libs?

**Comment by luacs1998** [comment]
@sk89q? I can resolve perfectly fine...

**Comment by sk89q** [comment]
Am I not publishing -dev releases?

Why is it not working suddenly? Or was a change made recently to FE's POM?

**Comment by luacs1998** [comment]
I'll test it again on a fresh project. The artifact resolves fine for me.

@liach try --refresh-dependencies?

**Comment by sk89q** [comment]
There shouldn't be a core-dev actually, only forge-dev.

**Comment by luacs1998** [comment]
Well, that means either I'm generating [bad POMs (this is the latest build)](http://puu.sh/kjcs0/1c2c4b102b.pom) or maven derped again.

**Comment by liach** [comment]
I agree 
`      > Could not parse POM http://files.minecraftforge.net/maven/com/forgeessentials/forgeessentials/1.8.0/forgeessentials-1.8.0.pom`

**Comment by sk89q** [comment]
That POM has a classifier for core.

**Comment by luacs1998** [comment]
Yep, just realized what's happening, doing a test publish now to make sure my fix works. Thanks for your time.

**Comment by liach** [comment]
I'll close it for now and test it again. Thanks.
