### ISSUE TITLE
Thaumcraft Golem can't place items

### ISSUE THREAD

**Issue by Alaberti** [ForgeEssentials/ForgeEssentials#1763]
FE 965

I had them previously working, so I'm assuming some kind of permission error on my part. That said, server console tosses me the following NPE whenever a use golem attempts to place a sapling:

http://pastebin.com/raw.php?i=T2kQzB1z

My Perms are as follows:
http://pastebin.com/raw.php?i=QmQfkJcq

Help? Thanks!

Edit: Moved the perms to a pastebin to prevent italics.

**Comment by paintballlaws** [comment]
use /p debug to see what permissions it may need

**Comment by Alaberti** [comment]
Only seems to tell me what permissions I'm using when I interact with it. How would I use it to explain what actions the golem entity is attempting to make?

**Comment by paintballlaws** [comment]
Be near the golem when he try's to place a sapling and it should come up with some kind of interact or building perm

**Comment by Alaberti** [comment]
No good, nothing shows up. The console goes crazy, but I don't get any messages about what the golem is trying to do.

**Comment by paintballlaws** [comment]
Interesting maybe @olee has some ideas?

**Comment by olee** [comment]
Just like @paintballlaws described. `/p debug` would show any checks FE performs.
You need to use that command and then let the golem to what he should do (place saplings or whatever). If will show any checked permissions in your chat (range about 32 blocks).

**Comment by Alaberti** [comment]
No really. When I enable /p debug and stand next to the golem attempting to place a sapling, I see only the messages for permissions related to when I interact with the golem in any way (such as place and damageto) - however, no messages appear for when the golem is attempting to place the items. As noted, every attempt the golem does make appears to be logged in the console as the error in the first post.

I apologize if I'm not being clear with what is happening, or if it is not happening to your expectation, but I am attempting to provide my observations in line with the advice and directions you are providing me, and I am attempting to do so in a logical, objective manner.

**Comment by Alaberti** [comment]
![2015-09-16_20 54 00](https://cloud.githubusercontent.com/assets/10929796/9915072/4a98a60a-5cb5-11e5-992a-ba69170a9236.png)
![2015-09-16_20 54 34](https://cloud.githubusercontent.com/assets/10929796/9915074/4a9a74da-5cb5-11e5-89a4-04f27ab45370.png)
![2015-09-16_20 54 52](https://cloud.githubusercontent.com/assets/10929796/9915073/4a98b41a-5cb5-11e5-9c13-5b67393aab8a.png)

Attached are screenshots that I hope better demonstrate what I am trying to describe.

**Comment by olee** [comment]
Thanks - I will try this out in my development environment if possible and see what happens.
Could you give me a short manual on how to test this?
I never used thaumcraft and especially the golems yet.

**Comment by Alaberti** [comment]
Absolutely.

Items required:
- Golem (any will do)
- Golem Animation Core: Use
- A Chest with saplings in it
- A golemancer's bell

Place a chest, put saplings in it, then place the golem on the chest. Right click the golem animation core onto the golem. Right click the golem, use one of the 6 filter slots to display the sapling. Ensure the options say "Right click" and "block"  on the golem with the bell, then mark a place with right click on dirt.

Attached are screens which should help if you need it.
![2015-09-19_21 44 34](https://cloud.githubusercontent.com/assets/10929796/9977662/476a2098-5f18-11e5-8f9c-2ebecad8d337.png)
![2015-09-19_21 45 22](https://cloud.githubusercontent.com/assets/10929796/9977663/476acb24-5f18-11e5-874f-f0f7228fcfda.png)
![2015-09-19_21 45 27](https://cloud.githubusercontent.com/assets/10929796/9977664/476bf558-5f18-11e5-971b-dd98cfd14b7f.png)
![2015-09-19_21 45 32](https://cloud.githubusercontent.com/assets/10929796/9977665/476ddab2-5f18-11e5-92e4-9bdfbfb9453e.png)
![2015-09-19_21 45 52](https://cloud.githubusercontent.com/assets/10929796/9977667/4772d13e-5f18-11e5-9f9d-2b784dc9a2d4.png)
![2015-09-19_21 45 56](https://cloud.githubusercontent.com/assets/10929796/9977666/477252ae-5f18-11e5-8261-070c05a606b6.png)
![2015-09-19_21 46 16](https://cloud.githubusercontent.com/assets/10929796/9977668/4793d78a-5f18-11e5-9940-e15c55f48118.png)
![2015-09-19_21 46 20](https://cloud.githubusercontent.com/assets/10929796/9977669/47945a02-5f18-11e5-88e5-ab08bcb5b54a.png)

**Comment by Alaberti** [comment]
Has there been any success figuring out this issue? Thank you.

**Comment by olee** [comment]
Sorry... no time :sweat: 
@luacs1998 could you try this out please and see if you can find the problem?

**Comment by Alaberti** [comment]
Hello. Has there been any luck understanding this issue? Thank you.

**Comment by luacs1998** [comment]
The most I can think of is that thaumcraft fakeplayers are doing things incorrectly.

**Comment by Alaberti** [comment]
I will attempt this on that build and report back.

**Comment by Alaberti** [comment]
There has been no change after updating to 1002, I am still receiving the same error and the golem is unable to place saplings.

The modpack I use is: http://www.technicpack.net/modpack/grimoire-magus.317216

I run this on a dedicated server. What are testable factors that may contribute to this issue? For example, if you are not seeing this issue on FTB Departed in a dedicated server environment, but I am on my modpack, what FE perms are you running so that I can test those? Thank you.

**Comment by luacs1998** [comment]
I am running with the default permissions, which blanket-allows `fe.protection.*` for the `_FAKEPLAYERS_` group.

**Comment by luacs1998** [comment]
@olee I need your input here.

The following is an example UserIdent from a thaumcraft golem:

`"ident": "(31a11ff9-1826-3505-8676-9eaea7a05de2|FakeThaumcraftGolem)",`

From the crash logs that @Alaberti and I have received, the GameProfile detection falls back to your "stupid mods who set the UUID to null" checking. I have no idea how or why, but `UserIdent playerIdent = UserIdent.byUsername.get(player.getCommandSenderName());` is giving me a null ident (and there is no checking for this!) Null ident -> null game profile -> crash.

**Comment by luacs1998** [comment]
@Alaberti does it work now?

**Comment by Alaberti** [comment]
Confirmed, solution works. Thank you for all the work you two did diagnosing this problem!

**Comment by luacs1998** [comment]
I'll close the issue then.
