### ISSUE TITLE
Commands despite being disabled

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentials#1766]
Testing my server as a regular player (_ALL_ group), and trying out commands. The following commands seem to work, even though they are disabled in the Commands.cfg.

/afk
/getcommandbook
/jump
/kit
/push
/remove
/rules

**Comment by PitchBright** [comment]
Deleted Commands.cfg and let it regenerate on restart. Apparently the options to enable/disable individual commands have all been removed from the config. I'm assuming that access to the commands is now solely based on permissions?

**Comment by olee** [comment]
Yes, exactly.
The commands.cfg is solely for configuring aliases (solving name-conflicts) and some config options for some commands.
