### ISSUE TITLE
Upgrade from 1.8 version 32 to 1.8 version 40 crash

### ISSUE THREAD

**Issue by paleym** [ForgeEssentials/ForgeEssentials#1767]
1.8:
Forge - 11.14.3.1499
Dynmap-2.2-alpha-3-forge-1.8.0
NBTEdit-1.8.jar
Pixelmon-1.8-4.0.7

When we upgraded to version 40, the server crashed immediately upon the first player joining.

Crash log - http://pastebin.com/PJ6psPib

**Comment by olee** [comment]
Looks like you set the `fe.protection.zone.command` permission to `false` instead of a value (or nothing) which makes the script parser fail. I will add a fix for that soon. For now I recommend you delete that permission (`/p ... clear fe.protection.zone.command`).

**Comment by luacs1998** [comment]
Shall I do this?

**Comment by olee** [comment]
I actually already fixed it, but changes are still on 1.7.
Will be fixed once changes are merged to 1.8
