### ISSUE TITLE
Multiworld not respecting game rules

### ISSUE THREAD

**Issue by scj643** [ForgeEssentials/ForgeEssentials#1769]
Multiworld dimensions do not respect game rules like doMobSpawning.

**Comment by Zethalion** [comment]
1.7.10 or 1.8? Any other relevant conditions? /p debug info?

**Comment by liach** [comment]
I guess they are supposed to have the same game rules applied...

**Comment by scj643** [comment]
It's 1.7.10

**Comment by Robijnvogel** [comment]
I have this issue as well. As soon as I add a multiworld level, natural mobSpawning stops in the overworld (DIM0) as well.

Please fix this asap.

**Comment by Robijnvogel** [comment]
I'm not trying to be a prick by the way. You are awesome people and I get that maintaining this mod costs a lot of time and effort.

**Comment by Robijnvogel** [comment]
Ok, so I have found that since your last update, the $SERVER player is part of the _GUEST_ group by default. As I had all (*) permissions disabled for the _GUEST_ group, the $SERVER did not have the right to spawn any hostile mobs naturally it seems.
So MY version of the issue is most likely not caused by Multiworld. I will continue to investigate

**Comment by olee** [comment]
$SERVER is a virtual player but it has a player permission `* = true` assigned so it cannot cause that problem. 
This will need some debugging

**Comment by Robijnvogel** [comment]
I moved my issue to #1816 to avoid confusion with the original issue here. I am not experiencing the original issue though, so I wonder what is special about @scj643 's setup.

**Comment by jogi01** [comment]
i had a similar issue with mobgriefing.. witherboss does not make block damage in the overworld but in other created dimensions.

**Comment by olee** [comment]
Will need to properly debug this when I am back from my trip (about 2 weeks left)
