### ISSUE TITLE
Question - Clarification on plot settings

### ISSUE THREAD

**Issue by Bloodmorphed** [ForgeEssentials/ForgeEssentials#1778]
# fe.economy.plot.limit.size = 
    # Maximum total size of all plots a player can claim
    S:limit.size= 10000

    # fe.economy.plot.size.max = 
    # Maximum size of one plot axis
    S:size.max= 50

    # fe.economy.plot.size.min = 3
    # Minimum size of one plot axis
    S:size.min= 9
I understand this feature isn't finished so, I may have found something that's not completely done, but still asking to make sure if its not me being dumb or w/e.

I'm confused on these options. I would think they would be squared. So like the minimum I have set for 9, I figured that would be a 9x9 area but I can claim a 2x2 area. Which is not good, peopel claiming 2x2 areas can get a little spammy. I'm just curious if this part of plots is finished or if I am being a dumb.

Also what is "plot axis" as I thought these options were for the x and z dimension of the plot. That little bit there has me wondering if I am wrong.

If I am wrong, would be hard to create settings where we can customize how big or small it can be, as I was thinking it might be.

Thanks!

**Comment by olee** [comment]
Setting it to 9 should make it that plots need to be of a minimum size of 9x9.
(9x20 is OK, 8x20 or 18x8 would not be OK).

If this does not work, this seems to be a bug.
