### ISSUE TITLE
Question/Request? - Banning Items

### ISSUE THREAD

**Issue by Bloodmorphed** [ForgeEssentials/ForgeEssentials#1779]
While there is WorldEdit disallow-items it doesn't seem to work... at all. I might be doing something wrong of course.

So I guess this is more of a request than a question, adding a banned items config or someing similar to WorldGuard's plugin. (Unless it is already in it?)

**Comment by olee** [comment]
Read the docs... and don't throw in some words with no foundation.
 1. What the heck do you mean with WorldEdit disallow-items?  
  Do you perhaps mean WorldGuard instead?
 2. [DOCS](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Protection-%28world-guard%29) and [MORE DOCS](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Guide-%23-Protection-%28world-guard%29)
 3. (I am not angry at all - just want to make clear that there is some proper etiquette for this stuff)

**Comment by paintballlaws** [comment]
Or just use permissions to ban/ disallow items works pretty well for me
