### ISSUE TITLE
TPS drops by half when adding FE

### ISSUE THREAD

**Issue by Siriuo** [ForgeEssentials/ForgeEssentials#1780]
TPS seems to drop by half when adding FE. 

With FE removed we get a solid 20 tps all the time. As soon as its added it drops to 10 tps.

Anyone else having this issue?

**Comment by olee** [comment]
Never seen something like that.
Something must be either wrong with the mods or the settings you use.
Normally FE would never be able to cause such a performance drop.

Try disabling playerlogger module in `main.cfg` and see if that fixes it.
If that does not help, try a few other modules maybe.

**Comment by luacs1998** [comment]
Reopen if this is still an issue.
