### ISSUE TITLE
Kit issue

### ISSUE THREAD

**Issue by Darktilldawn** [ForgeEssentials/ForgeEssentials#1783]
Whenever I change a kit ingame using /kit daily set 86400 and then use /yes to confirm I want to overwrite the kit. It overwrites it with the new items and then said Could not give some kit items. And doesn't give me anything. It's happened to me a few times whenever I try to overwrite a kit the entire kit is broken and deleting the kit and starting over yields the same results. Until I make a new kit uner a different name.

**Comment by luacs1998** [comment]
This sounds like an issue with the data API - could things not be deleted properly?

**Comment by Darktilldawn** [comment]
Well I went into jsons and kits after I delete said kit and make sure its not still in there when I do /kit dailys del before I remake the kits using /kit dailys set 86400 for a daily cooldown and it woks once to give me the kit then breaks on me.

Sent from Yahoo Mail on Android
