### ISSUE TITLE
Itemframes can be broken by breaking the block off it

### ISSUE THREAD

**Issue by Bloodmorphed** [ForgeEssentials/ForgeEssentials#1784]
So the shop works for the most part, well all of it does really. The only issue I'm having is the itemframe isn't protected like I thought it would be, or at least it seems like its not.

You can punch the block off it, I've tried restricting break, interact, and other breaking permissions I thought could prevent it. I know crops have a similar issue because they don't really count for anything. Is this the case for item frames as well?

**Comment by luacs1998** [comment]
> Item frames are entities and not blocks - you need to deny interaction to protect them - I think I will add them to the list of permissions considered to be chests so they are protected by default.

**Comment by Bloodmorphed** [comment]
I did that, and I was still able to punch the block out. Not only me but others as well, which shouldn't matter though, as I used the _ALL_ group so I shouldn't have been able to, as well as others. I put it in it's own zone and protected it that way. /p group _ALL_ zone ZONE deny fe.protection.interaction.* is what I did. (If that command is incorrect I am sorry I don't know it by heart yet, but I did do the correct one in-game)

**Comment by luacs1998** [comment]
/me groans

Will need to take a dive into the item frames code then

**Comment by Bloodmorphed** [comment]
Sorry! Lol, I understand your pain, did a script in RGSS3 some time ago and it gave me so much problems. Took me some help to get it the way I wanted. Cheers!

**Comment by olee** [comment]
Hm. I am pretty sure (99,99%) I added code to protect the item frames and even tested it.
Maybe I broke it while working on the shops again, or it is a problem related to some mod.

PS: I also want to support other signs (e.g. Bibliocraft) to be used as shop signs - this needs to be checked as well.

**Comment by olee** [comment]
@luacs1998 why do you always decide soo quickly that everything needs a hook?
Keep calm!
This is a problem which can simply be solved by the already existing events.
And as I said it should actually already work which means it is probably just a small bug.
I will take a look at it later.

**Comment by liach** [comment]
I think it is likely to be block interaction issue instead of an item frame issue.

**Comment by Bloodmorphed** [comment]
This seems to still be a probelm @olee 

I'll do some more testing though. (I updated to build 994)

**Comment by luacs1998** [comment]
Still want my hook? :D

**Comment by olee** [comment]
@Bloodmorphed interacting with item frames **definitely** can be controlled by permissions.
However they will not show up in PermissionList.txt and can only be found out by using `/protectdebug` or `/p debug`.

I am pretty sure the newest build should fix the issue with shop item frames being unprotected.
If it does not work it might even be a mod issue... will just have to try it out again.

**Comment by Bloodmorphed** [comment]
Oooohhhhh okay, I didnt you were actually doing damage to an item frame though. I thought it was just a pseudo interaction thing they did. Makes sense though, as you actually ARE punching the damn thing. Funny thing is I actually thought of this and wrote it off as stupid without trying... whose stupid now? Lol This guy right here.

**Comment by olee** [comment]
@Bloodmorphed well the stupid one is neither you nor me - it's Mojang :laughing:
