### ISSUE TITLE
Request - Dimensional Banning of Various things

### ISSUE THREAD

**Issue by Bloodmorphed** [ForgeEssentials/ForgeEssentials#1785]
Please forgive me if this is already in here, I can't seem to find it.

Would be cool to ban say the BC quarry completely (which I can already do) But also ban the ender quarry ONLY in the world dimension (0? I think is). 

I'm not too sure how hard this will be, but I think it would be awesome :)

Secondly, maybe ban other things? Like flying in a certain dimension, when they try to fly it just puts them back on the ground or something like that.

**Comment by luacs1998** [comment]
Each dimension has a dimension-wide zone - just deny the requisite permissions in that zone.

**Comment by Bloodmorphed** [comment]
Oh wow, I'mma dumb, I saw this before and forgot about it. Thank you.

**Comment by Darktilldawn** [comment]
That won't solve the problem of players using the fly command before entering the zone and able to fly inside of it correct? Unless there is a protection node against that I'm missing

Sent from Yahoo Mail on Android

**Comment by luacs1998** [comment]
The idea is that the permission is re-checked if the player enters a new zone. But I'll need to check if that's implemented.

**Comment by Bloodmorphed** [comment]
The command isn't the problem, it is the modded rings and other things that allow it. If an item is already equippend and I baned the use of it in a certain dimension would it still be able to fly or not. I will check that out!

**Comment by olee** [comment]
Ah you are probably talking about the oh-so-overpowered Angel Ring from Extra Utilities.
You might want to try the [flight table mod](http://minecraft.curseforge.com/mc-mods/231861-gakais-flight-table-fly-block) I thought of (and let a friend code) that could replace the Angel Ring and then just disable it.

Anyway we cannot really prevent other mods from making players fly. We would just be trying to counteract what they do. If you want a real solution, you will have to ask the mod authors to add permission checks into their mods.
