### ISSUE TITLE
urls in motd message at login (chat.cfg)

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentials#1787]
hey guys!
we provide some links in our motd message at login. Is it possible to make these URLs linked with underline so somebody can easily click on link to open ? Now the URLs are not recognized automatically i think or is there a formatting code i have to use ?

thanks in advance

-jogi

**Comment by luacs1998** [comment]
FE version?

**Comment by jogi01** [comment]
oh sorry...
version is forgeessentials-1.7.10-1.4.3.931-server.jar

**Comment by luacs1998** [comment]
I think it may be fixed, but I'll have to look into it.
