### ISSUE TITLE
[1.8] Update to ForgeGradle 2

### ISSUE THREAD

**Issue by liach** [ForgeEssentials/ForgeEssentials#1788]
On 1.8/develop build.gradle
[L22] (https://github.com/ForgeEssentials/ForgeEssentials/blob/18/develop/build.gradle#L22): `classpath "net.minecraftforge.gradle:ForgeGradle:1.2-SNAPSHOT"` to `classpath "net.minecraftforge.gradle:ForgeGradle:2.0-SNAPSHOT"`;
[L41] (https://github.com/ForgeEssentials/ForgeEssentials/blob/18/develop/build.gradle#L41): `apply plugin: "forge"` to `apply plugin: "net.minecraftforge.gradle.forge"`
[L69] (https://github.com/ForgeEssentials/ForgeEssentials/blob/18/develop/build.gradle#L69): `version = "1.8-11.14.3.1450"` to `version = "1.8-11.14.3.1516"` or some other later versions.
[L256] (https://github.com/ForgeEssentials/ForgeEssentials/blob/18/develop/build.gradle#L256) `task sourceJar(type: Jar) {` to `sourceJar {` maybe?

[Between L293-L306] (https://github.com/ForgeEssentials/ForgeEssentials/blob/18/develop/build.gradle#L293-L306) There were some issues because some function of old `reobf` task was removed. And the new task name is `reobfJar`. I have no way to resolve this issue for now.

[L301,L302] (https://github.com/ForgeEssentials/ForgeEssentials/blob/18/develop/build.gradle#L301-L302) Change `addExtraSrgFile` to `addSecondarySrgFile`.

I do not know a lot about gradle so I could not make a pr. Sorry.

**Comment by liach** [comment]
Btw you might pull 1.7 into 1.8 to update gradle wrapper.

**Comment by luacs1998** [comment]
Not going to update to FG2 in the short term - there may be some issue in deps.

**Comment by liach** [comment]
@luacs1998 1.8.8 has came out. Will you make a branch for it?

**Comment by olee** [comment]
I think we rather update FE 1.8 to 1.8.8 - I don't think we need to have one version at 1.8.
At least the current 1.8 version is ok and can be used by people until they upgrade to 1.8.

**Comment by luacs1998** [comment]
That's what I plan to do - kill 1.8.0 and move to 1.8.8.

**Comment by RlonRyan** [comment]
While you are at it, why not:
- Separate out the client from the main repo: (simplifies the buildscript)
- Change source compatibility to 1.8 to force usage of latest Java version. (Sponge requires it anyway!). (Lambda is awesome!). (Garbage collector is nicer too!).
- Format the buildscripts.
- Remove the automation stuff from the buildscript, or at least to a separate script file. (The system really isn't intended to automatically post builds. Plus, it inflates the build script to massive.)
- Update all the wrappers to Gradle 2.9

**Comment by luacs1998** [comment]
1) no, it makes things difficult - I'd have to do a lot of fucking up, especially with the common repository.

2) not when sponge compat hits the mainstream builds, which won't be before the new year

3) PR

4) automation stuff? You mean the maven things? Those have to be in the buildscript

5) PR (change wrapperVersion in the buildfile, make sure you have local gradle installed, run `gradle wrapper` and commit the files it spits out in addition to the changed buildfile)

**Comment by RlonRyan** [comment]
1) Yeah, it is feat to setup.
2) I thought I saw something that said Mojang was bundling the latest java versions (i.e. 1.8)
3) Yup
4) I meant the auto-release stuff. Or I am not sure what I meant.
5) The wrapper task might as well be removed from buildscript. It's built in to Gradle, to the point that no updating of the buildscript is needed when updating the Gradle wrapper version.

**Comment by RlonRyan** [comment]
I guess what I am advocating for is redoing the buildscript from scratch... aren't I?

**Comment by luacs1998** [comment]
2) that's for clients only

4) I have no recollection of any of the "auto-release" stuff you speak of.

5) If you remove the wrapper task, you'll need to add it back the next time you want to run `gradle wrapper`. Better to just leave it.

**Comment by luacs1998** [comment]
Continue in #1141
