### ISSUE TITLE
Plot region selection use worldedit wand permission has some problems

### ISSUE THREAD

**Issue by honyihon** [ForgeEssentials/ForgeEssentials#1792]
I want to do a plot region selection when i am a normal player (not op ) ,//fewand command now has been removed in forgeessentials-1.8-1.8.3.40-server ,after allow **worldedit.wand** and **worldedit.selection.chunk** permission and i couldn't use wand to select the plot region .....
after allow the **worldedit.selection.pos** and we can plot selection but the other worldedit function works ex: //cut ...  
How to set permission let normal player could do plot region selection?

**Comment by luacs1998** [comment]
I'll try to make what I can of this, but the grammar...

**Comment by honyihon** [comment]
Even I use command **/p global allow worldedit.selection.pos** 
When I check the **/p debug** the **worldedit.selection.pos=false**
and I check the **/p list perm** the **worldedit.selection.pos=true** under the  _SERVER_
any suggestion for the setting ?
http://imgur.com/RmaL7zk
http://imgur.com/r4EYR1C

**Comment by olee** [comment]
@honyihon you might have set up some other group that denies the permission again.
Simply doing `/p global allow worldedit.selection.*` should give access to all selection features.
Though I am not that sure if everything works correctly on 1.8 as well.

**Comment by honyihon** [comment]
@olee  selection is Ok , but the point is how to use **worldedit.selection.*** just for plot area selection,and disable other worldedit function , if doing **/p global allow worldedit.selection.* **
that will be enable like **worldedit.clipboard.cut=true** ,it's not suitable for normal player using the worldedit ,right ?

**Comment by honyihon** [comment]
@luacs1998 do you have any idea about use the worldedit.selection without enable the other worldedit permission?, or it will be fixed at the next version ?

**Comment by olee** [comment]
@luacs1998 WHY U NO TAKE CARE OF This? xD

@honyihon did you even read that command `/p global allow worldedit.selection.*`? 
It **only** allows the selection permission and not stuff like clipboard.

**Comment by honyihon** [comment]
@olee i know , it should be only allow  the selection permission ,but when i test it will enable other worldedit function ,are u really test in normal player mode under enable /p global allow worldedit.selection.* ? I have to confirm whether it is bug or not .

**Comment by honyihon** [comment]
@olee  I test the version 
forgeessentials-1.8.1.30
the worldedit problem doesn't happened , so , 	
forgeessentials-1.8.3.40 will really something error at worldedit permission
