### ISSUE TITLE
Possible to Add Permissions from other Mods using FE?

### ISSUE THREAD

**Issue by tyrantfenrir** [ForgeEssentials/ForgeEssentials#1793]
On a private Pixelmon server hosted by a friend and we're trying to enable commands from a few side mods that are currently only available to OPs. I tried adding them in game via /p group _PLAYERS_ allow com.wondertrademod.wondertrade.commands.­WonderTrade (What is listed as the permission node) as well as wondertrademod.* and wt.* yet nothing is working.

I'm unsure if this is possible to execute with FE or if there is a specific syntax that needs to be used. Any help is much appreciated.

Thank you very much

Currently using:
forgeessentials-1.8.3.40
Forge 11.14.3.1450
Pixelmon 4.0.7

**Comment by Darktilldawn** [comment]
Your typing in your permission nodes incorrectly and need to be putting those permissions under _ALL_ not players. I'll send you the correct permission if you'd like. I run a pixelmon server as well with full functional ability using forge essentials.

Sent from Yahoo Mail on Android

**Comment by tyrantfenrir** [comment]
That would be of great help, thank you.

**Comment by Darktilldawn** [comment]
you'll use the command in game, /p group _ALL_ true command.wondertrade

**Comment by Darktilldawn** [comment]
To find the correct permission for any mod you add into go into your ForgeEssentials folder, Go down to Permissions.list and search through there. It is an auto updating file that will have EVERY permission node you need to add or remove. If you have the Multicraft access or access to the PC that is running the server. Any other questions for Pixelmon and Forge just add me on Skype at: Darltilldawn(Yes an L) Dang typos. Lol.
