### ISSUE TITLE
More plots issues

### ISSUE THREAD

**Issue by Darktilldawn** [ForgeEssentials/ForgeEssentials#1797]
Still having an issue with any player able to delete anyone's plot. And are the plot's supposed to be able to be double claimed? A player can claim over another players plot, plus with the Delete issue this isn't any sort of GriefPrevention o.0

**Comment by luacs1998** [comment]
Verify your groups settings.

Post a screenshot of /p debug.

**Comment by luacs1998** [comment]
Reopen if it's still an issue.

**Comment by Darktilldawn** [comment]
The plot deleting is fixed thank you, But they can still claim over another players claim using /plot claim even with everything denied inside the permissions for the plot
