### ISSUE TITLE
Allow /p debug to "attach" to another user

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#1798]
This expands /p debug to target another user, but report their permission checks to the command sender.

Would be useful for troubleshooting fake players (#1763 and #1773)

**Comment by luacs1998** [comment]
EDIT: I'm a derp, I don't know how /p debug works.

**Comment by olee** [comment]
Why did you close this?
I don't think this feature is possible yet...

**Comment by luacs1998** [comment]
I assumed /p debug only debugged permission actions for the player who issued it.

Didn't realize it sent ALL permission debug messages to the player.

**Comment by olee** [comment]
Oh yeah now that you say it, I missed that, too xD
