### ISSUE TITLE
Sever crash when breaking Minecraft Comes Alive - Villager's Bed

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentials#1799]
Not sure what exactly caused this… hopefully you guys can tell just by looking at it.

http://pastebin.com/kBHS0kxg

FE 1.7.10-1.4.3.967

**Comment by PitchBright** [comment]
Forgeessentials-1.7.10-1.4.3.967

**Comment by DPxKnightxZero** [comment]
@luacs1998 I will try and verify if issue exists using latest MCA and FE release tested against the recommended forge build. I will post the results right away.

**Comment by PitchBright** [comment]
Confirmed fixed in FE v.1003
