### ISSUE TITLE
Crash when newer h2database is in use

### ISSUE THREAD

**Issue by simon816** [ForgeEssentials/ForgeEssentials#1801]
From this Sponge forum topic: https://forums.spongepowered.org/t/having-complications-with-forge-essentials/9450

When using FE with Sponge, an exception is thrown with PlayerLogger's database config
```
org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:ForgeEssentials/playerlogger". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-189]
```
FE uses an old version of h2 (1.3) but Sponge uses 1.4.
A change introduced in 1.4 is that a relative database path must begin with `./`, so the default of `ForgeEssentials/playerlogger` should now be `./ForgeEssentials/playerlogger`

**Comment by luacs1998** [comment]
Oh good, something easy to fix for one!
