### ISSUE TITLE
Crash - Multiworld 

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1804]
Here is the crash log ->

https://gist.github.com/DPxKnightxZero/d1195485477eb8a89e1c

**Comment by liach** [comment]
@DPxKnightxZero I think a full log helps instead of a crash log.

**Comment by CodingMonkeyXYZ** [comment]
Me too. Full Forge log attached. Let me know if you need any other file.

Brand new client installation. Brand new world. I downloaded the version from Curse, just now and tried to create another world using the command /mw create. It crashed. Literally the first thing I did.

[fml-client-latest.log.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/40928/fml-client-latest.log.txt)

**Comment by liach** [comment]
@CodingMonkeyXYZ  those two issues are quite different.
