### ISSUE TITLE
CME on saving world before backup

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#1806]
http://puu.sh/kBhSs/14a7de850d.txt

**Comment by DPxKnightxZero** [comment]
Could this mess up the permissions tables? If so YES! YES! THIS IS A BUG!!! :'(

**Comment by Goju-Sulfam** [comment]
I have the same kind of error in my log : http://gojusulfam.no-ip.biz/goju/crash_log/fml-server-latest.log

I run a Resonant Rise 1.7.10 server, with Fastcraft 1.22-ctest15, FE 1.4.3.1006, Dynmap 2.2.143 and OPIS. the full mod list is here : http://gojusulfam.no-ip.biz/goju/crash_log/modlist.txt

**Comment by luacs1998** [comment]
I am unable to recreate this on 1034 - closing.
