### ISSUE TITLE
Add help / wiki info for /portal

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1807]
I am looking to have a a wand feature that allows me to set a portal with a pos1 set current location and pos2 destination location and have it be a one way trip used for like a server hub world.

**Comment by olee** [comment]
Portal feature already exists in teleport module. It's just not in the wiki yet. 
You need to select a 1xWxH area with wand which will become the portal surface, move to the target location and then issue `/portal create <name>`

**Comment by DPxKnightxZero** [comment]
Can you also add help menu info XD it was not present.

**Comment by olee** [comment]
Some time ... some time.

**Comment by luacs1998** [comment]
https://github.com/ForgeEssentials/ForgeEssentials/wiki/Portals
