### ISSUE TITLE
Feature Request - DimList and DimPerms

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1808]
I need a way to quickly see a list of dims and the mod they are using example TwilightForest-#18

**Comment by olee** [comment]
That is quite simple by showing the class name of the world provider. @luacs1998 can you quickly make a small command like /feworldinfo? If, please try using the ParserCommandBase class as it makes things a lot easier and already has a parseWorld function in CommandParserArgs which should make this really simple.
