### ISSUE TITLE
Feature Request - List all info with number #XX | "custom name".

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1809]
Sometimes after working on zones, plots, and worlds you forget what each number stands for and unless your a business accountant I don't think you keep a ledger is it possible to have any command that uses "List" as a sub command to list it the way it is so example #84 but also add the custom name 

so example
#84 | "MyPlotOne"

?

**Comment by olee** [comment]
You mean for `/p global zone <x>`? 
You can use names for areas there I think but I don't know about worlds...

How about this then? 
````
/p global area<name>
/p global world <dim>
````

**Comment by DPxKnightxZero** [comment]
Um Sure I am not sure what your saying can you explain it differently?

**Comment by olee** [comment]
From what I understood you have problems setting permission for certain zones because it is difficult to reference them by I'd  right?

**Comment by DPxKnightxZero** [comment]
Yes correct some of the /help commands are also not well explained. Is it possible when you return to add the fe."Autocomplete.This.Command.By.Pressing.Tab.*" ?

**Comment by DPxKnightxZero** [comment]
Oh yeah and I would prefer it also have the /mw list be /mwDim since that is what it is making. If they have there prefixes next to the names they listed so for example if I made a /mw create TestPlace | when I type the /mw list it would say something like #12 - mwDIM "TestPlace"

**Comment by olee** [comment]
*facepalm*
Next time **tell me beforehand** that you were talking about multiworlds. Stuff like this makes me waste a lot of time :sweat_smile:...

**Comment by luacs1998** [comment]
Does https://github.com/ForgeEssentials/ForgeEssentials/commit/c156f1075940153c6d884d5ae95615455493c38c this resolve the issue?

**Comment by olee** [comment]
It only helps a bit, but does not solve this issue here.
