### ISSUE TITLE
Severe Issue - Permissions table not respecting settings

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1811]
After I blocked spawns from a single users plot somehow it overwrote the entire server. Please note* now players cannot interact with or be killed by anything.

**Comment by DPxKnightxZero** [comment]
Alright ... so yeah the permissions table and everything related to it just broke. It happened after restarting the server.

**Comment by olee** [comment]
I think there is no way to set up default permissions for plots yet. 
Sorry,  will have to wait until I am back.

**Comment by olee** [comment]
continue in #1810
