### ISSUE TITLE
/calcpricelist save doesn't work

### ISSUE THREAD

**Issue by wulfbear** [ForgeEssentials/ForgeEssentials#1812]
Hi there!
When trying to save the calculated prices from prices.txt into economy.cfg by typing "/calcpricelist save" as proposed by the console it gives out following lines: "Unknown command. Type in /help for list of commands" 
Tried /help, but it doesn't list the command. Is it not yet implemented or is it a bug?

**Comment by olee** [comment]
Seems like a bug...

**Comment by wulfbear** [comment]
How can I transfer the values manually? Which format do I have the use in the economy.cfg?

**Comment by olee** [comment]
The command generates a `prices.txt` and some other files like `prices_log.txt` and so on.
You can just copy the lines from `prices.txt` into the correct block in economy.cfg.

**Comment by luacs1998** [comment]
The correct command should be `/sellprice save`.

Assuming @olee doesn't want to change this, it's a user error.
