### ISSUE TITLE
Paying for command usage

### ISSUE THREAD

**Issue by wulfbear** [ForgeEssentials/ForgeEssentials#1813]
I've seen that olee wrote in #1496 he'd fixed or added an event handler that allows to charge players for using a command. However I cannot figure out how to set the prices. Same question as before: Is it not fully implemented yet or am I just dumb?

**Comment by olee** [comment]
Just not documented. 
Use `/p debug` to see the permissions which are used to set prices. 
Use `/p global value fe.cmdprice.tp 100`(should be some permission like that) to set the price.

**Comment by wulfbear** [comment]
Sorry to respond on a closed topic, but I've just /p global value and I get this response from the console: "Set fe.teleport.jump for group _ALL_ to 500 in zone _SERVER_". Also tried to set the value via /p groups TESTGROUP value , same response in the console, however the players don't get charged in both cases for using the command. Any idea what's going on?
BTW: I'm using the latest build (1008)

**Comment by olee** [comment]
Who said you should set `fe.teleport.jump`? :laughing: 
You should set the `cmdprice` permission to a value.
That's why I said to use `/p debug`.
