### ISSUE TITLE
Scripting and case sensitivity

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentials#1814]
Hello,

I'm trying to create an /island command for a skyblock-like, here is the script:

http://pastebin.com/3jFemMyN

It's nowhere near finished and it's not the best since I'm learning while trying.

So now for the real issue, the dimension get created using the username but if a user has an uppercase letter things screw up because the dimension name is lower case.

When a user named (for example) Pinko will create a dimension it will not teleport them there saying the dimension does not exist, but with mw list I can see the lowercase dimension name.

I personally have a all-lowercase name so I did not notice the problem at first. Am I just doing it completely wrong or is it something to be/that can be fixed in the mod?

And on a side note, is it possible to reload the scripts without restarting?

Thank you for your time and of course whenever it's in a clean working state I don't mind to share it, many people could make use of a script like this.

\o/

**Comment by olee** [comment]
`/feinfo reload` for reloading config. 
The other thing is probably a big that needs to be fixed.
