### ISSUE TITLE
Update - Fastcraft now works with FE as long as they use this version 

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1817]
fastcraft-1.22-ctest15

Users please use this link to obtain it. http://files.player.to/tmp/fastcraft-1.22-ctest15.jar

**Comment by Zethalion** [comment]
It is a well known fact the 1.22-test versions do seem to work with FE but 1.22 is not officially released. The official version is 1.21 which is not compatible

**Comment by DPxKnightxZero** [comment]
Its a well known facts until now the test version DIDN'T work. If you don't have something productive please don't post. >_>

**Comment by Zethalion** [comment]
ctest10 did work fine. ctest14 had a few errors. I'll be happy to test ctest15 soon. But please stay polite.

**Comment by olee** [comment]
This is not an issue at all.
Closing (you can continue conversation though if you want to)
