### ISSUE TITLE
New Issue with Kit cooldowns post 1008

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentials#1818]
I am now having a issue with getting kit cooldowns past 2 week timers to function. If you set a cooldown to say a 165 week CD the cool down still shows as only 2 weeks. If you go beyond 165 weeks the cooldown shows as accepted but the player can spam the cooldown.

commands used 
/kit test set 9999999 = 16 week CD but only shows only as a 2 week cd when player tried to use kit again.
/kit test set 99999999 = 165 week CD but only shows only as a 2 week cd when player tried to use kit again.
/kit test set 999999999 = 1653 weeks CD but players can still spam the kit.

**Comment by blkwind** [comment]
![error1](https://cloud.githubusercontent.com/assets/12201821/10461342/82e75a08-719e-11e5-81b5-9e29fdec349f.PNG)
![error2](https://cloud.githubusercontent.com/assets/12201821/10461345/875a857e-719e-11e5-9a2b-f22d32094909.PNG)

**Comment by blkwind** [comment]
I checked for console errors but there are no events registering.

**Comment by olee** [comment]
Probably need to change the cooldown from seconds to minutes to make it easier to set.
As for the display problem: @luacs1998, this is your job.

**Comment by blkwind** [comment]
Thanks Olee!

**Comment by luacs1998** [comment]
The problem is not with the display, it is working fine.

The problem is in PL incorrectly setting the end time of the cooldown.
