### ISSUE TITLE
protection.inventory permission

### ISSUE THREAD

**Issue by Mandelsage** [ForgeEssentials/ForgeEssentials#1819]
Hi all,

I have two, related, questions...

I'm trying to use fe.protection.inventory for a specific item (the Angel Wings Ring from Extra Utilities) but it doesn't want to work. It works for fe.protection.inventory.*=false where all items pop out of the inventory but not for fe.protection.inventory.item.extrautils:angelRing=false (which I looked up in a permissions list generated from my server).

I also tried changing the end like so:
fe.protection.inventory.item.ExtraUtilities:angelRing=false
because the name looks like that in a dump gotten from NEI but it also didn't work.

I've tried many variations, all to no effect.

The other issue is that, when I use fe.protection.inventory.\* the angelRing does not pop out of the inventory if it is in a Baubles slot. Pops out just fine in normal inventory.

Hoping you an help! Thanks.

**Comment by olee** [comment]
Use `fe.protection.inventory.item.extrautils.angelRing` not `fe.protection.inventory.item.extrautils:angelRing`.
As for baubles, that shouldn't be a problem when the other permission works because players probably won't even be able to get it into their inventory.

**Comment by Mandelsage** [comment]
Thank you for the fast reply =)

I have definitely tried the dot in place of the colon and it still didn't work =/ 

And the baubles slot is an issue because I'm allowing the Angel Ring in one world (using MultiWorld) but not in WORLD_0, so they are able to keep their wings when pwarping over by keeping it in the baubles slot.

**Comment by luacs1998** [comment]
This may be a problem with Extra Utilities.

We only check the 3x9 inventory of the player - we don't have access to any extra slots. Unless there is a way to get them...

**Comment by olee** [comment]
This is a problem caused by Baubles.
We would have to especially add their API as a dependency to be able to access the special Baubles inventory slots... This should be added as a compatibility module...

**Comment by luacs1998** [comment]
https://github.com/ForgeEssentials/ThirdPartyModWorkarounds

Feel free to go to town on that.

**Comment by olee** [comment]
Derp.
Referenced incorrect issue in commit.

**Comment by HeberonYT** [comment]
Hi.
Is this issue resolved?
I am using FE 1.4.4.1182 and have trouble crafting ingots unstable, you can get creative but also prevents them for other crafteos.
Nor does the Autonumus of Thermal Expansion Activator.
Greetings.

**Comment by spacebuilder2020** [comment]
Does not look like it.  I am going to look at a lot of these issues and try to get some solved

**Comment by spacebuilder2020** [comment]
@Mandelsage Can you try with the latest version of FE 1.7.10 (or 1.10.2)  Baubles integration was recently added so that might fix this issue.

**Comment by spacebuilder2020** [comment]
@Mandelsage If we do not receive a response from you in a week, this issue will be closed as part of an effort to clean up stale issues.
