### ISSUE TITLE
Unable to login to server

### ISSUE THREAD

**Issue by CaitlynMainer** [ForgeEssentials/ForgeEssentials#1821]
With FE version forgeessentials-1.7.10-1.4.3.1008-server.jar, forge 1448 installed server side no one is able to connect to my server The console spits this out: http://paste.pc-logix.com/view/raw/78b36954  And the client reports "Internal Server Error"  I've tried clearing the permissions which did nothing.

**Comment by liach** [comment]
Looks like a galaticcraft bug.

**Comment by CaitlynMainer** [comment]
The mention of GC is just because it replaces the player entity, this has been working fine with the same exact mod set for 3 weeks on this pack.

**Comment by CaitlynMainer** [comment]
Damn that was quick, thanks!

**Comment by olee** [comment]
No problem :wink: 
You are lucky that I just had a small break here.
Going into the city again now to watch more of the festival going on here :smile:

**Comment by liach** [comment]
Does this sort of *fix* work well? I afraid that this type of fixes may cause more bugs as it does not investigate the source of the issue.

**Comment by luacs1998** [comment]
@liach if you have a better fix in mind, by all means your PR is welcome.

**Comment by olee** [comment]
@liach actually that is the correct fix for this problem, because as long as this one field is set, the following code will work properly.
It was just that fakeplayers do not have that field which is just for real, connected players.
