### ISSUE TITLE
Stopping mobs from spawning in a zone

### ISSUE THREAD

**Issue by Sunconure11** [ForgeEssentials/ForgeEssentials#1822]
Is it possible to stop mobs from spawning in a specific zone? Because I have Lycanites Mobs on my server, and because my spawn is by a beach, players keep dying near spawn. How do I stop mobs from spawning in a defined zone?

**Comment by olee** [comment]
Read the wiki on permissions.
You need to deny the mob spawn permission of the mob you want to prevent from spawning.
You should find all possible mob permissions in [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentials/wiki/PermissionList.txt)
