### ISSUE TITLE
Minor issue, maybe more of a question regarding plot configs.

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentials#1824]
So I am now at the point where I need to start testing and working with plot and ect. I know plots are still a work in progress but I am not entirely sure about its current config settings.
![plot questions](https://cloud.githubusercontent.com/assets/12201821/10556084/3d6e4d8e-7440-11e5-8759-19f3ebda95ee.PNG)

When regarding the max and min sizes for player plots. What are the units of messure its asking for exactly, is it in blocks of chunk? Also if its chunk and I put 4 for max then could the players make a plot 4 chunks in what ever shape or must it be square? Examples * = 1 chunk
:      * *    <--- Square plot 4 chunks     or ------> * * * * Line plot made of 4 chunks
:      * *

**Comment by DPxKnightxZero** [comment]
It goes by blocks however if you set column mode true it also calculates the price from 255 and down. Do not know whether it covers custom heights past 255 :D hope this helps. Think of it this way; if a plot is 3x3 its 9 x 255 so it ends up being 2295 coins.

**Comment by blkwind** [comment]
Wow so if it calculates price by every block in the chunk with column mode turned on for the price thats 65,536 blocks a chunk or 65,536 coins for a 1 chunk plot? thats intense lol.

**Comment by blkwind** [comment]
Also, while I have you here. Has a way to expand a already existing plot been implemented. I have only been able to expand by buying a second plot next to the existing or deleting and reclaiming.

**Comment by DPxKnightxZero** [comment]
Nope XD just delete and rebuild.

**Comment by olee** [comment]
@DPxKnightxZero You are wrong in one aspect. If column mode is enabled, it will just calculate `3 * 3 * <price per block>`. 
The 255 height gets ignored.

**Comment by blkwind** [comment]
Just wanted to update after tinkering around with the plot commands for anyone else who may look at this post for answers. The command "/feconfig plot.size.min 16" will make the minimum plot size = 1 chunk. 1 chunk will cost 256 coins from level 0 to 255 "with column mode enabled". In the FE configs there is a option to increase the plot price multiplier to increase the cost of plots. I set it to 4 to bring the cost of each chunk plot to 1024 coins.

As of this moment there is no option to expand a plot. Cant wait to see that feature implemented. It will really push the FE plot system forward. Also would be nice to see a sub plot system similar to grief protection pluggins sub claim feature. It would really make it efficient for people wanting to make player towns.

**Comment by olee** [comment]
Yeah expanding plots is really necessary.
I have even an idea for new claiming with that:
 - Use a command which will claim a fixed area around the player
 - The player can go slightly outside the plot and use a command to expand the plot to where he stands (if he has enough coins to pay for it)

Also stuff like merging plots etc. is necessary.
This will all become even easier if I finally get to implement complex areas - i.e. areas composed of multiple boxes, cylinders and ellipses.

**Comment by blkwind** [comment]
Awesome thanks Olee and as always great work!
