### ISSUE TITLE
[Request] - I request a grabage frame for selling

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1825]
So basically I really love forge essentials shops I have but a single request a frame that works like this place frame and leave it blank and then make a sign place underneath and type 

[FEShop]
Trash
Sell for x

To show its active I want a trash can to appear in the frame.

Can my awesome modding team do it :D much love to TeamFE

**Comment by luacs1998** [comment]
There's already a sell command.

Put up a command sign with

`[command`
`sell`

and get your players to right click that.

**Comment by DPxKnightxZero** [comment]
Really? Thank you :D
