### ISSUE TITLE
Crash - Not sure what caused it but its the latest fe release 

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1826]
https://gist.github.com/DPxKnightxZero/31c032cdac88b00f09eb
============================================================================
No more information is found. I don't want to remove fastcraft test15 because it is highly effective.

**Comment by liach** [comment]
https://gist.github.com/DPxKnightxZero/31c032cdac88b00f09eb#file-gistfile1-txt-L478-L482
NEID patched fastcraft and caused issues. Remove either NEID or fastcraft.

**Comment by DPxKnightxZero** [comment]
Okay I am aware ... please not I am giving the creator of fastcraft a place of reference please make sure you keep this open until issue is resolved.

**Comment by liach** [comment]
No my fault... It's NotEnoughID bug. You just need to leave fewizz/NotEnoughIDs#22 open.
