### ISSUE TITLE
Question: How to change the default group from _GUEST_ to other.

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentials#1827]
I found a thread posted for a while back but the solution was just a link to the permissions command wiki. I read through the entire thing several times and found nothing referencing changing the default join group. Did the permission change or was removed? Only thing I found that I thought  may work was the group priority command, but im not sure how that would work or if it would work. 

What I am trying to  do  is change the starting group from _Guests_ to a custom group setup by me.

**Comment by olee** [comment]
Do not change it. PERIOD.
Modify it to suit your needs.
It is in internal group that every player automatically gets, if he is in no other group.
You can do everything properly with the internal guests group and it is useless to change that group name.

PS: If you really want to have players in some group by default, there might be ways to do that with scripting but it is useless and I don't have the time right now to take care of this.
