### ISSUE TITLE
Suppress FakePlayer death messages

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentials#1833]
used version: 1.4.3.1008-nightly
hey guys!
we are getting some more death messages from mob farms like
... was slain by [EioKillera]
Mighty Skeleton was slain by [Minecraft]
is there a feature to disable messages completely OR can you fix this messages produced by non players entities eg machines ?

greetings

-jogi

**Comment by olee** [comment]
We could think about it....

But on the other side, messages like *"... was slain by [EioKillera]"* should be there so you actually know who died :confused:

**Comment by DPxKnightxZero** [comment]
It is pretty spammy.

**Comment by olee** [comment]
How many times die players through FakePlayers?
I never even had that happen to myself .... I wouldn't even know how to do it....

**Comment by DPxKnightxZero** [comment]
Um ... well with headcrumbs and hates ... about 7 fake players can die every 5 mins.

**Comment by Entoarox** [comment]
Do you have Cofh Core installed? Cause that causes death messages to show up for any named non-player entities that die, and there is a config option to disable that.

**Comment by DPxKnightxZero** [comment]
Thank you @Entoarox I will look into it.

**Comment by luacs1998** [comment]
@DPxKnightxZero does changing the cofh core settings work? Can I close this?

**Comment by DPxKnightxZero** [comment]
No it failed.

**Comment by spannerman79** [comment]
Perhaps move this notification into a permission node?

For example `fe.chat.notification.death` default: true so if you want it negated just add `-fe.chat.notification.death` to user/group

**Comment by olee** [comment]
The problem is that these death messages are not from FE, but from MC itself...
But we can think about it.

@luacs1998 could you take a look into where the messages are generated?

**Comment by luacs1998** [comment]
I've found it.

Forge should have added a check for players but I assume it didn't.

Not really sure if it's our place to fix stupidity, though.

**Comment by spannerman79** [comment]
Personally I find it amusing to see those messages but if it really bothered you @DPxKnightxZero & @jogi01 open an issue over at the forge issue tracker or post on the forge forums.

This is something that I think forge dev team needs to look at, address or dismiss

**Comment by olee** [comment]
Exactly.
FE *could* do this, but FE is not really the right place to do this...

**Comment by luacs1998** [comment]
Should I close this?

**Comment by spannerman79** [comment]
@luacs1998 I think this issue should be closed, this is not a specific FE issue but needs to be resolved from Forge dev team themselves if/when they decide to
