### ISSUE TITLE
Block fire spread?

### ISSUE THREAD

**Issue by incorpusyehtee** [ForgeEssentials/ForgeEssentials#1834]
I saw this https://github.com/ForgeEssentials/ForgeEssentials/commit/4cfaed3ecab556e2ffeee6fabd5ee5b87291f741 commit, and was wondering how to block fire spread in a zone.

Thanks

**Comment by olee** [comment]
[PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentials/wiki/PermissionList.txt)
