### ISSUE TITLE
Banning MineFactoryReloaded Sacred Sapling

### ISSUE THREAD

**Issue by Dmitchell94** [ForgeEssentials/ForgeEssentials#1838]
Hi,
I was looking to ban the placement of the MineFactoryReloaded sacred Rubber sapling and i do not see it in the permission list for items or blocks and am trying to ban it as its growth will crash any server. how would i go about banning the sacred sapling but not the regular sapling?

**Comment by liach** [comment]
Ref [ban item command] (https://github.com/ForgeEssentials/ForgeEssentials/blob/develop/src/main/java/com/forgeessentials/protection/commands/CommandItemPermission.java). Holding a sacred Rubber sapling and typing `/itemperm place deny` is supposed to work.

**Comment by olee** [comment]
However as he said, this will ban all versions of the sapling.
Instead you will need to find out the meta value of the sapling to ban it.
(I think 2 is the meta value of the sacred one. 1 should be the little smaller magic one).
To ban it, use `/p global deny fe.protection.place.<minefactoryreloaded-bla-bla>.<sapling-id>.2`.
You can find out the exact permission (the one above is just a sample) by using `/itemperm` while holding the item in your hand.
