### ISSUE TITLE
KCauldron is a continuation request Cauldron Support for FE

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1841]
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 10/29/15 1:29 AM
Description: Exception in server tick loop

java.lang.RuntimeException: Sanity check failed: Detected Cauldron, bad things may happen to your server. Shutting down as a precaution.
	at com.forgeessentials.core.environment.Environment.check(Environment.java:75)
	at com.forgeessentials.core.ForgeEssentials.<init>(ForgeEssentials.java:147)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1517.168
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 164012736 bytes (156 MB) / 519110656 bytes (495 MB) up to 2075918336 bytes (1979 MB)
	JVM Flags: 9 total; -Xms512m -Xmx2048M -XX:PermSize=256m -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 143 mods loaded, 143 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (custom.jar) 
	UC	Forge{10.13.4.1517} [Minecraft Forge] (custom.jar) 
	UC	kimagine{0.2} [KImagine] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.118} [Not Enough Items] ([Universal]-NotEnoughItems-1.7.10-1.0.5.118.jar) 
	UC	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	mcdiscord{2.0.0} [MC Discord] (minecraft.jar) 
	UE	ForgeEssentials{1.4.3} [Forge Essentials] ([Server]-forgeessentials-1.7.10-1.4.3.1013-server.jar) 
	UC	JourneyMapServer{1.0.5_MC1.7.10} [JourneyMapServer] ([Server]-JourneyMapServer1.0.5_MC1.7.10.jar) 
	UC	CoFHCore{1.7.10R3.0.3} [CoFH Core] ([Universal]-CoFHCore-[1.7.10]3.0.3-303.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] ([Universal]-Mantle-1.7.10-0.3.2b.jar) 
	UC	Waila{1.5.10} [Waila] ([Universal]-Waila-1.5.10_1.7.10.jar) 
	UC	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] ([Universal]-[1]-TConstruct-1.7.10-1.8.8.jar) 
	UC	nevermine{2.3} [AdventOfAscension] ([Universal]-AoA-2.4.B.jar) 
	UC	Natura{2.2.0} [Natura] ([Universal]-natura-1.7.10-2.2.1a2.jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] ([Universal]-BiomesOPlenty-1.7.10-2.1.0.1462-universal.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] ([Universal]-Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	Botania{r1.7-228} [Botania] ([Universal]-Botania r1.7-228.jar) 
	UC	MetallurgyCore{4.0.4} [Metallurgy Core] ([Universal]-MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UC	Metallurgy{4.0.8} [Metallurgy 4] ([Universal]-Metallurgy-1.7.10-4.0.8.97.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] ([Universal]-Pam's HarvestCraft 1.7.10k.jar) 
	UC	ExtraTiC{1.4.5} [ExtraTiC] ([Universal]-[1]-ExtraTiC-1.7.10-1.4.5.jar) 
	UC	abyssalcraft{1.8.9.6} [AbyssalCraft] ([Universal]-AbyssalCraft-1.7.10-1.8.9.6.jar) 
	UC	acheads{1.2.0} [AbyssalCraft Heads] ([Universal]-AbyssalCraft Heads-1.7.X-1.2.0.jar) 
	UC	acintegration{1.2.6} [AbyssalCraft Integration] ([Universal]-AbyssalCraft Integration-1.7.10-1.2.6.jar) 
	UC	BuildCraft|Core{7.1.12} [BuildCraft] ([Universal]-buildcraft-7.1.12.jar) 
	UC	BuildCraft|Energy{7.1.12} [BC Energy] ([Universal]-buildcraft-7.1.12.jar) 
	UC	ActuallyAdditions{1.7.10-0.0.9.4} [Actually Additions] ([Universal]-ActuallyAdditions-1.7.10-0.0.9.4.jar) 
	UC	aobdbb{1.0.6} [Another One Bites The Dust: Berry Bushes] ([Universal]-AOBDBB-1.0.6.jar) 
	UC	Aquaculture{1.2.3} [Aquaculture] ([Universal]-Aquaculture-1.7.10-1.2.5.15.jar) 
	UC	atum{0.6} [Atum] ([Universal]-Atum-1.7.10-0.6.77.jar) 
	UC	Backpack{2.0.0} [Backpack] ([Universal]-backpack-2.0.0-1.7.x.jar) 
	UC	betterrecords{@VERSION@} [Better Records] ([Universal]-BetterRecords-1.7.10-1.2.0.jar) 
	UC	BiblioCraft{1.11.3} [BiblioCraft] ([Universal]-BiblioCraft[v1.11.3][MC1.7.10].jar) 
	UC	ExtrabiomesXL{3.16.3} [ExtrabiomesXL] ([Universal]-extrabiomesxl_1.7.10-3.16.3.jar) 
	UC	BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] ([Universal]-BiblioWoods[ExtraBiomesXL][v1.4].jar) 
	UC	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] ([Universal]-BiblioWoods[Natura][v1.5].jar) 
	UC	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] ([Universal]-BloodMagic-1.7.10-1.3.3-13.jar) 
	UC	BuildCraft|Builders{7.1.12} [BC Builders] ([Universal]-buildcraft-7.1.12.jar) 
	UC	BuildCraft|Transport{7.1.12} [BC Transport] ([Universal]-buildcraft-7.1.12.jar) 
	UC	BuildCraft|Silicon{7.1.12} [BC Silicon] ([Universal]-buildcraft-7.1.12.jar) 
	UC	BuildCraft|Robotics{7.1.12} [BC Robotics] ([Universal]-buildcraft-7.1.12.jar) 
	UC	BuildCraft|Factory{7.1.12} [BC Factory] ([Universal]-buildcraft-7.1.12.jar) 
	UC	buildhelper{1.0.0} [Build Helper] ([Universal]-BuildHelper_v1.0.0.jar) 
	UC	CarpentersBlocks{3.3.7} [Carpenter's Blocks] ([Universal]-Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UC	chancecubes{1.7.10-1.4.2.38} [Chance Cubes] ([Universal]-ChanceCubes-1.7.10-1.4.2.38.jar) 
	UC	IC2{2.2.790-experimental} [IndustrialCraft 2] ([Universal]-industrialcraft-2-2.2.790-experimental.jar) 
	UC	Railcraft{9.8.0.0} [Railcraft] ([Universal]-Railcraft_1.7.10-9.8.0.0.jar) 
	UC	chisel{2.9.2.8} [Chisel] ([Universal]-Chisel-2.9.2.8.jar) 
	UC	cosmeticarmorreworked{1.7.10-v4} [CosmeticArmorReworked] ([Universal]-CosmeticArmorReworked-1.7.10-v4.jar) 
	UC	lootablebodies{1.3.6} [DrCyano's Lootable Bodies] ([Universal]-CyanosLootableBodies-1.7.10-backport_1.3.6.jar) 
	UC	deathlog{1.2a} [Death Log] ([Universal]-deathlog-1.2a.jar) 
	UC	dungeonpack{1.7.10-1.0} [Dungeon Pack] ([Universal]-dungeonpack-1.7.10-1.0.jar) 
	UC	Enchiridion{1.3} [Enchiridion] ([Universal]-Enchiridion 2-1.7.10-2.0.2a.jar) 
	UC	Enchiridion2{2.0.2a} [Enchiridion 2] ([Universal]-Enchiridion 2-1.7.10-2.0.2a.jar) 
	UC	endercore{1.7.10-0.2.0.30_beta} [EnderCore] ([Universal]-EnderCore-1.7.10-0.2.0.30_beta.jar) 
	UC	EnderIO{1.7.10-2.3.0.417_beta} [Ender IO] ([Universal]-EnderIO-1.7.10-2.3.0.417_beta.jar) 
	UC	evilcraft{0.9.0} [EvilCraft] ([Universal]-EvilCraft-1.7.10-0.9.0.jar) 
	UC	extraores{4.0} [Extra Ores] ([Universal]-Extra Ores[1.7.10-V4].jar) 
	UC	fastleafdecay{1.3} [Fast Leaf Decay] ([Universal]-FastLeafDecay-1.7.10-1.3.jar) 
	UC	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UC	FloatingRuins{1.7.10.r02} [FloatingRuins] ([Universal]-FloatingRuins-universal-1.7.10.r02.jar) 
	UC	Forestry{4.0.11.40} [Forestry for Minecraft] ([Universal]-forestry_1.7.10-4.0.11.40.jar) 
	UC	GardenContainers{1.7.10-1.6.8} [Garden Containers] ([Universal]-GardenStuff-1.7.10-1.6.8.jar) 
	UC	GardenCore{1.7.10-1.6.8} [Garden Core] ([Universal]-GardenStuff-1.7.10-1.6.8.jar) 
	UC	GardenStuff{1.7.10-1.6.8} [Garden Stuff] ([Universal]-GardenStuff-1.7.10-1.6.8.jar) 
	UC	GardenTrees{1.7.10-1.6.8} [Garden Trees] ([Universal]-GardenStuff-1.7.10-1.6.8.jar) 
	UC	globbypotato_rockhounding{3.00} [Rockhounding Mod] ([Universal]-globbypotato_rockhounding-1.7.10-v3.14.jar) 
	UC	GraveStone{2.13.0} [GraveStone] ([Universal]-GraveStone-2.13.0.jar) 
	UC	headcrumbs{1.6.2} [Headcrumbs] ([Universal]-Headcrumbs-1.6.2.jar) 
	UC	heartdrop{1.3.2} [Heart Drop] ([Universal]-HeartDrop-1.7.10-1.3.2.jar) 
	UC	HardcoreQuesting{The Journey (4.3.0)} [Hardcore Questing Mode] ([Universal]-HQM-The Journey (4.3.0).jar) 
	UC	InfernalMobs{1.6.0} [Infernal Mobs] ([Universal]-InfernalMobs-1.7.10.jar) 
	UC	infiniteinvo{1.0.44} [InfiniteInvo] ([Universal]-InfiniteInvo-1.0.44.jar) 
	UC	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] ([Universal]-InventoryTweaks-1.59-dev-152.jar) 
	UC	JABBA{1.2.1} [JABBA] ([Universal]-Jabba-1.2.1a_1.7.10.jar) 
	UC	levelup{0.10} [Level Up!] ([Universal]-LevelUp!-0.10(1.7.10).jar) 
	UC	LogisticsPipes{0.9.3.61} [Logistics Pipes] ([Universal]-logisticspipes-0.9.3.61.jar) 
	UC	lycanitesmobs{1.13.0.3 - MC 1.7.10} [Lycanites Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	arcticmobs{1.13.0.3 - MC 1.7.10} [Lycanites Arctic Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	demonmobs{1.13.0.3 - MC 1.7.10} [Lycanites Demon Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	desertmobs{1.13.0.3 - MC 1.7.10} [Lycanites Desert Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	forestmobs{1.13.0.3 - MC 1.7.10} [Lycanites Forest Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	freshwatermobs{1.13.0.3 - MC 1.7.10} [Lycanites Freshwater Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	infernomobs{1.13.0.3 - MC 1.7.10} [Lycanites Inferno Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	junglemobs{1.13.0.3 - MC 1.7.10} [Lycanites Jungle Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	mountainmobs{1.13.0.3 - MC 1.7.10} [Lycanites Mountain Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	plainsmobs{1.13.0.3 - MC 1.7.10} [Lycanites Plains Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	saltwatermobs{1.13.0.3 - MC 1.7.10} [Lycanites Saltwater Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	shadowmobs{1.13.0.3 - MC 1.7.10} [Lycanites Shadow Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	swampmobs{1.13.0.3 - MC 1.7.10} [Lycanites Swamp Mobs] ([Universal]-LycanitesMobsComplete 1.13.0.3 [1.7.10].jar) 
	UC	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] ([Universal]-magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UC	magicalcropsdeco{4.0.0_PUBLIC_BETA_4a} [Magical Crops: Decorative] ([Universal]-magicalcropsdeco-4.0.0_PUBLIC_BETA_4a.jar) 
	UC	malisiscore{1.7.10-0.12.10} [MalisisCore] ([Universal]-malisiscore-1.7.10-0.12.10.jar) 
	UC	malisisdoors{1.7.10-1.10.1} [Malisis' Doors] ([Universal]-malisisdoors-1.7.10-1.10.1.jar) 
	UC	Mariculture{1.7.10-1.2.4.2a} [Mariculture] ([Universal]-Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UC	MariTech{1.0} [Marine Technlogy] ([Universal]-Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UC	metallurgychisel{1.0.0.11} [Metallurgy Chisel] ([Universal]-MetallurgyChisel-1.7.10-1.0.0.11.jar) 
	UC	morechisels{@VERSION@} [More Chisels] ([Universal]-MoreChisels-1.7.10-1.0-28.jar) 
	UC	AS_MultiMine{1.4.3} [Multi Mine] ([Universal]-MultiMine-1.7.10.jar) 
	UC	NEIAddons{1.12.13.38} [NEI Addons] ([Universal]-neiaddons-1.12.13.38-mc1.7.10.jar) 
	UC	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] ([Universal]-neiaddons-1.12.13.38-mc1.7.10.jar) 
	UC	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] ([Universal]-neiaddons-1.12.13.38-mc1.7.10.jar) 
	UC	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] ([Universal]-neiaddons-1.12.13.38-mc1.7.10.jar) 
	UC	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] ([Universal]-neiaddons-1.12.13.38-mc1.7.10.jar) 
	UC	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] ([Universal]-neiaddons-1.12.13.38-mc1.7.10.jar) 
	UC	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] ([Universal]-neiaddons-1.12.13.38-mc1.7.10.jar) 
	UC	neiintegration{1.0.13} [NEI Integration] ([Universal]-NEIIntegration-MC1.7.10-1.0.13.jar) 
	UC	newdungeons{0.3} [New Dungeons] ([Universal]-NewDungeons-0.3(1.7.10).jar) 
	UC	recipehandler{1.7.10} [NoMoreRecipeConflict] ([Universal]-NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UC	pokecube_adventures{0.1.0} [Pokecube Adventures] ([Universal]-pokecube-1.5.25rc6.5.jar) 
	UC	PokecubeCompat{1.0} [Pokecube Compat] ([Universal]-pokecube-1.5.25rc6.5.jar) 
	UC	pokecube{1.5.25-6.5} [Pokecube] ([Universal]-pokecube-1.5.25rc6.5.jar) 
	UC	pokecube_generations{7.0.0} [Pokecube Generations] ([Universal]-pokecube-1.5.25rc6.5.jar) 
	UC	pokecube_lineage{0.9} [Pokecube Lineage] ([Universal]-pokecube-1.5.25rc6.5.jar) 
	UC	pokecube_ml{0.1.0} [Pokecube Model Loader] ([Universal]-pokecube-1.5.25rc6.5.jar) 
	UC	pokecube_origin{1.5.25-6.5} [Pokecube Origin] ([Universal]-pokecube-1.5.25rc6.5.jar) 
	UC	pokecube_world{0.0.1} [Thut's WorldGen: Pokecube Edition] ([Universal]-pokecube-1.5.25rc6.5.jar) 
	UC	Roguelike{1.3.6.3} [Roguelike Dungeons] ([Universal]-roguelike-1.7.10-1.3.6.3.jar) 
	UC	AS_Ruins{14.7} [Ruins Spawning System] ([Universal]-Ruins-1.7.10.jar) 
	UC	secretroomsmod{4.7.1} [The SecretRoomsMod] ([Universal]-secretroomsmod-1.7.10-4.7.1.413.jar) 
	UC	SilentGems{1.3.03} [Silent's Gems] ([Universal]-SilentGems-1.7.10-1.3.03-140.jar) 
	UC	simpleblocks{0.1} [SimbleBlocks] ([Universal]-SimpleBlocks.1.0.0.jar) 
	UC	Testerino{0.04} [Testerino] ([Universal]-Testerino-0.04.jar) 
	UC	TinyStorage{1.20.5_191} [Tiny Storage] ([Universal]-TinyStorage-1.20.5_191.jar) 
	UC	Translocator{1.1.2.15} [Translocator] ([Universal]-Translocator-1.7.10-1.1.2.15-universal.jar) 
	UC	TravellersGear{1.16.6} [Traveller's Gear] ([Universal]-TravellersGear-1.7.10-1.16.6.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] ([Universal]-Treecapitator-universal-2.0.4.jar) 
	UC	universalcoins{1.7.10-1.6.36} [Universal Coins] ([Universal]-UniversalCoins-1.7.10-1.6.36.jar) 
	UC	wailaevents{1.0.0} [Waila Events] ([Universal]-WailaEvents-1.0.0.jar) 
	UC	WailaHarvestability{1.1.2} [Waila Harvestability] ([Universal]-WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UC	wailaplugins{MC1.7.10-0.1.2-21} [WAILA Plugins] ([Universal]-WAILAPlugins-MC1.7.10-0.1.2-21.jar) 
	UC	wawla{1.3.1} [What Are We Looking At] ([Universal]-Wawla-1.3.1-1.7.10.jar) 
	UC	witchery{0.24.1} [Witchery] ([Universal]-witchery-1.7.10-0.24.1.jar) 
	UC	WitchingGadgets{1.1.10} [Witching Gadgets] ([Universal]-WitchingGadgets-1.7.10-1.1.10.jar) 
	UC	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar) 
	UC	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] ([Universal]-[1]-IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UC	aobd{2.8.4} [Another One Bites The Dust] ([Universal]-AOBD-2.8.4.jar) 
	UC	JustAnotherSpawner{0.17.6} [Just Another Spawner] ([Universal]-JustAnotherSpawner-0.17.6.jar) 
	ForgeEssentials: Running ForgeEssentials 1.4.3.1013 (dd1ace1). Modules loaded: 
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

Reason being need a plugin called clear lag.

**Comment by luacs1998** [comment]
Don't use cauldron with FE.

Didn't you see the big and scary warnings?

**Comment by olee** [comment]
@luacs1998 shouldn't FE still **try** to boot with KCauldron?
But instead it crashes without even trying to boot....
