### ISSUE TITLE
Cleear Lagg - Style Addition

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1842]
So after going to great lengths to attempt to find a plugin that automates removal of garbage by dead entitites I have come up empty ... anyway you guys could add an affect like this?

http://www.curse.com/bukkit-plugins/minecraft/laggremover

**Comment by luacs1998** [comment]
Will look into it...

**Comment by olee** [comment]
@DPxKnightxZero if you need something like clear lag on your server, you are (probably) doing something wrong. Also there are forge versions of such a mod, too. I recommend you just use one of these.

**Comment by DPxKnightxZero** [comment]
Some of my players decide they are going to mine and drop blocks everywhere and not clean up. I am looking for a way to auto clean invisible entities which build up after about 2 hours. Its not unreasonable and it would effectively remove the need for bukkit 1.7.10

**Comment by DPxKnightxZero** [comment]
This mod is not longer kept up 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2161485-1-6-4-1-7-2-1-7-10-1-8-forge-entity-lagfix-2-0-2 Last update 2014 Dec and download link is dead :/

**Comment by DPxKnightxZero** [comment]
Edit it appears to only be a hidden curse download. The project site is gone. Or curse is hacked again ...
http://www.curseforge.com/projects/228404 it brings you to spam.
