### ISSUE TITLE
Chat Formatting

### ISSUE THREAD

**Issue by micmou** [ForgeEssentials/ForgeEssentials#1843]
Does anybody have any clear instructions on how the Chat formatting works?

What I am trying to do is set it up so that for instance It will look like this

Admin - micmou

The admin is red and micmou is healthcolor

**Comment by olee** [comment]
Configure group prefix for your `_OPS_` group (or your own admin group).
As for the health color, I need to check it out myself, too.

**Comment by luacs1998** [comment]
https://github.com/ForgeEssentials/ForgeEssentials/wiki/Script-Arguments

Put the healthcolour arg at the end.

So means your prefix would be %red%Admin - %reset%@healthcolour
