### ISSUE TITLE
Bug with target selector arguments

### ISSUE THREAD

**Issue by JunnQS** [ForgeEssentials/ForgeEssentials#1844]
Hello,

I set a command block with a command that would add players in a specific team to a group.
The command looked like that:
/p user @a[team=TEAM] group add GROUP
At first it worked fine. However, the next time I launched minecraft it didn't work anymore. This is what the previous output said:
[15:54:36] Player @a[team=TEAM] added to group(s) GROUP
Somehow it decided that "@a[team=TEAM]" was nothing but a nickname. 
The same argument worked fine with vanilla commands but refused to work with ForgeEssentials.

Then I decided to replace team with coordinate:
/p user @a[x=10,y=20,z=30,r=4] group add GROUP
Again, it worked at first, but two days later the same problem appeared. Somehow "@a[x=10,y=20,z=30,r=4]" is now considered to be a nickname. 

It would be less confusing if it didn't work since the beginning but no, it was fine. What's the problem? 

Thank you in advance.

**Comment by olee** [comment]
Oh that is really a problem.

I guess the following happened:
When the code ran the first time, it could not find any player with the name `@a[team=TEAM]` and searched for a matching player. Once it found one, it added a kind of player entry with the name `@a[team=TEAM]` and the ID of the found player to the list of players. When it checks `@a[team=TEAM]` after that again, it will always return the same player from the first time.

This is a bug in `UserIdent` that I will need to fix.

**Comment by olee** [comment]
Ok it was slightly different.
It did not cache the correctly found players, but instead it cached the entries when no player was found for the selector. This means it saved a player `@a[team=TEAM]` as a not-existing-player once the selector did not match for the first time.
