### ISSUE TITLE
Client Permissions GUI

### ISSUE THREAD

**Issue by Scravey** [ForgeEssentials/ForgeEssentials#1846]
On the client page here: http://minecraft.curseforge.com/projects/forge-essentials-client
It says "Permission overlay" but I could not find any other information about this anywhere. Just curios as to what it actually does.

Another question. Would it be possible to some how convert Permissions EX permissions to the way Forge Essentials does permissions?

**Comment by luacs1998** [comment]
The permission overlay draws a (X) over items in your hotbar that you're not allowed to use.

No, sorry, PEX and FE use very different permissions - you'll need to start afresh.

**Comment by Scravey** [comment]
Okay, thanks!

**Comment by olee** [comment]
But converting / reading some of PEX permissions should be easily possible. IIRC they use YAML to save some permissions and we could allow to at least import some global permissions.
However that would still be 99% only block / item permissions so this would not help much in the end anyway.
