### ISSUE TITLE
Feature Request: Passive Mode - Cannot harm or be harmed

### ISSUE THREAD

**Issue by Baaleos** [ForgeEssentials/ForgeEssentials#1848]
Idea comes from GTA 5
For those moments when you would rather not be bothered by other players.
Turn on Passive Mode - Now you cannot harm them, and they cannot harm you.

Possibly make a perception sort of filter for passive players.
Eg: Normal Players cannot see or interact with Passive players
      Passive Players cannot see anyone who is non-Passive
      Passive Players can however collaboratively work together for building projects. (See eachother)

Passive vs Normal = No Visibility (bothways) & No Damage capabilitiy
Passive vs Passive = Visibility & No Damage Capability

**Comment by olee** [comment]
You can even do that just with permissions and pattern commands yourself...
Just make a small group "passive" that has the correct permissions set and a command that allows players to enter / leave that group.

Any1 of our regulars up to the task?
@Baaleos you can of course do it yourself - just read up a bit on the wiki (might be a bit difficult though)
