### ISSUE TITLE
Protection NPE whilst handling locked Thermal Expansion machines in Draconium Chest

### ISSUE THREAD

**Issue by RoyCurtis** [ForgeEssentials/ForgeEssentials#1849]
When a player has the Draconium Chest GUI open, they are able to specify an auto-crafting recipe. One such recipe is surrounding a Thermal Expansion machine with [Signalum Security Lock](http://ftbwiki.org/Signalum_Security_Lock) and nuggets to add player protection.

If a player attempts to set a recipe using an *already locked* machine, they will be kicked from the server. This is because of a NullPointerException from ForgeEssentials' protection module. The Draconium Chest's GUI will then become inaccessible from this NPE.

## Details

* [Stack trace](https://gist.github.com/RoyCurtis/17884b5667bb41738d65)
* [FTB Infinity 2.0.2 1.7.10 live server](http://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2264804)
* ThermalExpansion-[1.7.10]4.0.3B1-218.jar
* Draconic-Evolution-1.7.10-1.0.2-Snapshot_3.jar
* [ForgeEssentials Jenkins build 1016](http://ci.forgeessentials.com/job/FE/1016/)

## Reproduction

*For this reproduction, a Tesseract is used. Other Thermal Expansion machines, such as the Redstone Furnace, may be used.*

1. Set up a creative flatland server with ForgeEssentials
2. [Place a Draconic Chest in-world](http://i.imgur.com/ROIZHrf.png)
3. Right-click the chest to open its GUI
4. In the crafting grid on the bottom right, [surround a new Tesseract with two Signalum Nuggets on the left, bottom and right. Place two Signalum Security Locks on the top.](http://i.imgur.com/MDwWgUD.png)
5. Craft the Tesseract. [Observe its tooltip now has an "Owner" field.](http://i.imgur.com/etfaANE.png)
6. [Place the Tesseract back into the middle of the crafting grid.](http://i.imgur.com/PHQvCvK.png)
7. Observe now that you are kicked from the server, with either "Internal Server Error" or a "Forcibly closed connection" error. A stack trace may print on the console.
8. Reconnect to the server and right-click the Draconic Chest again. Observe the same error happens.

## Theory

Normally, because the Tesseract is already locked, [the crafting recipe will have no output](http://i.imgur.com/Medyh8g.png). I theorize that Thermal Expansion is dynamically cancelling that recipe if it determines the Tesseract is already locked, and that ForgeEssentials' protection system does not anticipate this.

## Notes

* This bug was discovered and tested by a player on our FTB Infinity server
* I have been attempting to disable FE's protection module entirely to work around this, but was unable to find a config option or method to do so

**Comment by liach** [comment]
Yes FE crashed because the recipe output is `null`... Easy fix.

**Comment by RoyCurtis** [comment]
Cool; thank you for the fix!
