### ISSUE TITLE
Permissions Schedule may not be activating properly

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentials#1852]
It's entirely probable that I'm doing something wrong, as I've never used the Permissions Schedule feature before, but in my first experiment with it I've not been able to get it to work.

-I enabled the module in main.cfg
-I created a simple schedule to allow/disallow sleeping at certain times of the day 
-I placed the schedule in the json/PermissionSchedule/ folder

Players can still interact with beds during the day. Perhaps my schedule is incorrect? http://pastebin.com/gZZyjCU6

**Comment by olee** [comment]
Permission scheduler works properly.
Try adding the default sample if it is not there yet:
````json
{
  "isRealTime": false,
  "isDelay": false,
  "zoneId": 1,
  "group": "_ALL_",
  "times": [
    6000,
    18000
  ],
  "permissions": {
    "some.test.permission": {
      "on": "true",
      "off": "false"
    }
  }
}
````
And then try using `/p test some.test.permission` at day / night.
It will show `true` during day and `false` in the night.
