### ISSUE TITLE
Translations config may not be adding new entries

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentials#1853]
In testing Permission Schedule, I inverted default "on" state to set sleep permissions to false. The message that players receive is "You do not have permission to sleep here." (or something very similar).

I would like to create a translation for that message. I know that the wiki is still under construction so I haven't quite figured out how to do a translation properly yet, but in speaking with Olee on IRC, I think I understood that the first instance of a chat message from the server was to appear in the Translations.cfg file, to serve as a template for editing.

I didn't see an entry for "You do not have permission to sleep here."

However, it may be that the translations.cfg also seems to be auto-regenerating after each server restart, thereby overwriting the previous translations.cfg

**Comment by olee** [comment]
It works now. As an example of what I put in translations.cfg:
````
You are not allowed to sleep here=§cIt is not nighttime yet!
````

**Comment by Pet9948** [comment]
By the way, I also didn't find the problem with translations.cfg always being rewritten when the server starts... You can't write anything to it...
