### ISSUE TITLE
Protection NPE + server crash whilst handling Twilight Forest leaves harvestDropsEvent

### ISSUE THREAD

**Issue by RoyCurtis** [ForgeEssentials/ForgeEssentials#1854]
Whilst a player is breaking Twilight Forest leaves in dimension 0, the protection module hits a NullPointerException whilst attempting to check harvest permissions.

# Details

* Crash log [one](https://gist.github.com/RoyCurtis/56b2d284db09646439b1), [two](https://gist.github.com/RoyCurtis/7fe37528c2a16d9cc0e2), [three](https://gist.github.com/RoyCurtis/c9d41020b150740fa1a9)
* [FTB Infinity 2.0.2 1.7.10 live server](http://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2264804)
* `twilightforest-1.7.10-2.3.7.jar`
* [ForgeEssentials Jenkins build 1021](http://ci.forgeessentials.com/job/FE/1021/)

# Notes

* This crash was discovered by a few players on our server
* Please excuse the terse issue report

**Comment by olee** [comment]
Please try with latest version again.
If it crashes agaon, it will show where the problem actually came from.

**Comment by RoyCurtis** [comment]
Done, with new crash logs:

* [Player kick exceptions](https://gist.github.com/RoyCurtis/4a95b22ec692c0e3e800)
* [Server crash](https://gist.github.com/RoyCurtis/cce7906f94ffc3a8169e)

I also now have a reliable reproduction, from Infinity Evolved 2.1.1 and `twilightforest-1.7.10-2.3.7`:

*If this reproduction does not work, repeat from step 2*

1. Set up a creative mode server
2. In dimension 0, [create a 1x1 tower of Beanstalk Leaves](http://i.imgur.com/YtlsZtk.jpg)
3. Land on top of the tower and switch to survival mode
4. Start breaking the leaves with fist until the server crashes, or kicks you with "Internal server error"

**Comment by olee** [comment]
Bingo!
This is a bug from Twilight Forest which drops stacks that have `null` - as to speak NOTHING set as dropping item. So it's not that they drop nothing, but they drop stacks of nothingness...

This needs to be reported on the Twilight Forest bug tracker.
I could fix the crashes it causes in FE, but this would prevent such bugs from being noticed completely which is not good for future development.

**Comment by olee** [comment]
Ohhh.... it seems this was already reported in a way: https://github.com/Benimatic/twilightforest/issues/31

**Comment by RoyCurtis** [comment]
Understood; thank you for looking into this and the prompt response

**Comment by olee** [comment]
>by @Yanniclord
>...adressing the Twilight Forest dev is dumb, because he never responds anyway and the last update is a long time ago now.

I can add a switch in FE that will not only log the errors and crash, but fully catch them.
This will not make it work as it should, but it will stop the server from crashing.

**Comment by Yanniclord** [comment]
Hey olee. I just wonder what build you added the switch to, because i am using build 1034, but the server is still crashing.

**Comment by RoyCurtis** [comment]
@Yanniclord: FWIW, we are using 1034 without this crash. Ensure the switch is `-Dfe.safemode=true`, e.g. `java -server -Xms6G -Xmx6G -Dfe.safemode=true -jar server.jar`

**Comment by luacs1998** [comment]
@Yanniclord any self-respecting MC server admin panel should allow you to change the startup arguments. MCMyAdmin should be able to do it, for example.

**Comment by Yanniclord** [comment]
Again, not every host allows you to change the startup arguments, and such panels are for custom servers. If i were to host it on lets say CreeperHost or OMGSERV or so, they dont allow such, and afaik, neither does Nitrado.

**Comment by luacs1998** [comment]
Use ssh if your host allows it, if not, ask them.

Or I may add a diagnostic command that allows to enter safe-mode for the current run, but that would already require you to be able to access the server.

**Comment by olee** [comment]
@Yanniclord then they cannot use this mode which should not be used normally anyway.
As long as it fixes the crash for you now, it's ok.
I'm expecting TF to fix the bug on their end sometime soon anyway.

**Comment by Yanniclord** [comment]
Well it doesnt fix it for me because i cannot change the startup arguments. Also, i really dont think that the TF dev will fix it at all, the last release is some time ago now as i said previously.

**Comment by olee** [comment]
>You are forgetting some people are not hosting their servers on a VPS or home

Then you should have mentioned that this is the case for you - this sounded like "there might be someone else..."

**Comment by olee** [comment]
Latest version adds the option to the main.cfg config
