### ISSUE TITLE
Teleport Cooldown reset on logout

### ISSUE THREAD

**Issue by BushTrocity** [ForgeEssentials/ForgeEssentials#1855]
The cooldown timer on /home and /spawn is reset if u logout and back in. It will let you teleport again bypassing the timer. Im on the latest dev build 1021 for 1.7.10.

**Comment by olee** [comment]
@luacs1998 the new cooldown system I wrote covers such cases.
The problem is just that the teleport cooldown is not saved.
````java
    @Expose(serialize = false)
    private long lastTeleportTime = 0;
````
