### ISSUE TITLE
Ticking Block

### ISSUE THREAD

**Issue by Yanniclord** [ForgeEssentials/ForgeEssentials#1861]
So this crash is what is starting to go me on the nerves, i cannot have ForgeEssentials in for more than 6 hours, before something goes wrong with it. This time, this: http://pastebin.com/3Fmu74yE

**Comment by Yanniclord** [comment]
This one here is also related to the one at [1854](https://github.com/ForgeEssentials/ForgeEssentials/issues/1854)

**Comment by olee** [comment]
Do you also have Twilight Forest installed?
If so, this is probably the same issue.

**Comment by Yanniclord** [comment]
Ye, its in the log. And yes, i do.

**Comment by Yanniclord** [comment]
Closed, why? I wont remove TwilightForest to use ForgeEssentials, its this mod that should work together with every mod, not vice versa.

**Comment by Yanniclord** [comment]
Also, adressing the Twilight Forest dev is dumb, because he never responds anyway and the last update is a long time ago now.

**Comment by olee** [comment]
I closed this one in regards to #1854 
Take a look there and post requests there please.
