### ISSUE TITLE
Command issues with Server Modpack

### ISSUE THREAD

**Issue by Expansing01** [ForgeEssentials/ForgeEssentials#1862]
Command "xxx" registered twice
and then my modpack server won't start corectly.
i need help

**Comment by olee** [comment]
LOGS!
(and "Command XXX registered twice" is just info - not really an error)

**Comment by Expansing01** [comment]
okay i make a screen

**Comment by Expansing01** [comment]
okay sorry for the thread it was a problem with my NEI integration and addon... why it has crashed

**Comment by spannerman79** [comment]
If it was an issue with how you have your modpack setup and if its resolved then please close this issue @Expansing01
