### ISSUE TITLE
[Enhancement] Bridge FE Economy module with other economy mods

### ISSUE THREAD

**Issue by spannerman79** [ForgeEssentials/ForgeEssentials#1863]
As the title suggests, is there a way to bridge the Economy module with say - for example - [Universal Coins](https://github.com/notabadminer/UniversalCoinsMod)?

I know you have stated in the topic title on mcf of "vault" ability in MyTown2 hence why this issue.

**Comment by luacs1998** [comment]
Theoretically, you can add a value to the items added by the mod in question, then have your players "sell" them to the server to get FE credits.

Or set up a chest-shop to perform trading.

**Comment by spannerman79** [comment]
Hm this is giving me something to think about.

I sort of was hoping for something a little more streamlined, hoping towards an actual VaultAPI type setup if that makes any sense.

Doing it that way a player would have - in effect - two separate account systems.

But on the other hand it might be able to be used as you suggested, FE Economy focused on MyTown2 plots etc and Universal Coins for shops - only cause I like the way that Universal Coins has an ATM and Vending block that can buy/sell anything without needing a frame/sign type setup that FEShop needs.

**Comment by olee** [comment]
We could add a system that uses items as currency... but it would be more efficient if Universal Coins would just provide a currency interface for FE (they would need to implement the Wallet interface FE provides).

However FE is able to manage the money players have even if they are offline - i.e. for plot fees (WIP) - which is (probably) fundamentally different from UC which needs to have online players with the coins in there inventory (I don't know the mod but that's what I would guess).

**Comment by spannerman79** [comment]
No, a user doesn't need to have the physical items in their inventory as each user has an "account" per say.  Easiest way is to think how Essentials (bukkit plugin) works but with a card/ATM ability added as well.

A first time user (Bob) would do this (with universal coins mod)
1. Join the server
2. Go to an ATM - first time user so gets assigned a card (no limit on number of cards as each player has an "internal" account)
3. Deposits coins/withdraws coins into account.

Then the user uses that card to link into any other player based shops using Universal Coins mod to create a store. A player store (Trade station) can both buy and sell an item at the same time.  Store owner goes offline.

New User 2 (Jane) Joins server follows steps 1 - 3, goes to Bob store and buy/sell to store - transaction status dependant on coin deposit in step 3 if Jane has enough to buy or store owner (Bob) has enough to buy from new user.  The store owner (Bob) only needs to rejoin to check their account or stock status but Bob doesn't need to be online for the transaction/s to happen

**Comment by olee** [comment]
So it has a physical currency (coins) and also a digital version stored via ATMs?
If that's the case they could simply provide a Wallet implementation for FE.
That would be most efficient, because FE's Wallet is kept really really simple and it's ok to give up the wallet implementation to them. Please create an issue on their side and reference this issue.

UC devs would need to provide these two interfaces:
````java
public interface Economy
{
    public Wallet getWallet(UserIdent player);
    public Wallet getWallet(EntityPlayerMP player);
    public String currency(long amount);
    public String toString(long amount);
}

public interface Wallet
{
    public long get();
    public void set(long value);
    public void add(long amount);
    public void add(double amount);
    public boolean covers(long value);
    public boolean withdraw(long value);
    public String toString();
}

// Finally set APIRegistry.economy = <own-instance-of-Economy-interface>;
````

**Comment by spannerman79** [comment]
Done.  I already had an open issue with @notabadminer

**Comment by luacs1998** [comment]
So this is not our problem?

**Comment by spannerman79** [comment]
No its not @luacs1998 but please keep this issue around as I have reference it to the UC dev/s.

**Comment by luacs1998** [comment]
I guess this is done?

**Comment by olee** [comment]
Waiting for the ok from UCM devs.

**Comment by olee** [comment]
No more response - seems it worked.
