### ISSUE TITLE
Kit's still throwing error's

### ISSUE THREAD

**Issue by Darktilldawn** [ForgeEssentials/ForgeEssentials#1864]
http://pastebin.com/F6BiCFxi
Error when using a kit, I receive the Items and it throws me weird errors in game and console.
Also wondering if the config for giving a starter kit has been fixed yet or does it still cause a crash when a new player joins?

**Comment by olee** [comment]
Before you report errors, always update to latest version.
This has been fixed since quite a while.
The line number in your error message does not match the current code any more.

**Comment by Darktilldawn** [comment]
I am on the latest version. forgeessentials-1.8-1.8.3.51-server.jar That's like server 101.

**Comment by olee** [comment]
Yeah .... if you would tell us **beforehand** that you are using 1.8 and not 1.7.10 -.-'

**Comment by Darktilldawn** [comment]
Yeah, sorry I completely forgot you have a 1.7.10 version as well.. My bad.. 
But hey at least I kept the code out of your face ;)
