### ISSUE TITLE
MinecraftEdu Compatibility

### ISSUE THREAD

**Issue by darkflux** [ForgeEssentials/ForgeEssentials#1865]
Not sure if it really matters to anyone, but all versions up to the latest ForgeEssentials worked with MinecraftEdu, and now version 1.4.3.1021 causes the server to crash as it is loading the world.
I am running Minecraft 1.7.10 Build 20 .
To clarify, forgeessentials-1.4.3.958 works just fine. 1.4.3.1021 crashes.

**Comment by luacs1998** [comment]
Logs?

**Comment by darkflux** [comment]
crash-report: http://pastebin.com/6tGuFS6K
latest: http://pastebin.com/L9UBrDVj
fml-server-latest: http://pastebin.com/xiR1rAHg
fml-junk-earlystartup: http://pastebin.com/Ectq94iw

**Comment by luacs1998** [comment]
I don't know what MinecraftEdu is doing, but from a quick inspection of your logs you're using an old version of Forge that FE doesn't support.

You'll either need to get the MinecraftEdu guys to update, or find a way to manually update Forge yourself.

**Comment by darkflux** [comment]
yeah, i thought about that. did you guys switch Forge versions with this latest release? because the previous release worked just peachy.

**Comment by luacs1998** [comment]
We were already compiling on 1448 for a while - I just had to force it to add some new stuff.
