### ISSUE TITLE
Have installed kCauldron 1.7.10-1481.148 and forgeessentials 1.7.10-1.4.3.958, but plugin is not recognized

### ISSUE THREAD

**Issue by kyler45** [ForgeEssentials/ForgeEssentials#1866]
Hello! For some odd reason, kCauldron is working fine, but with ForgeEssentials in my plugin folder it is not working! When I type /bukkit plugins it says there are 0 plugins running.

**Comment by luacs1998** [comment]
FE is a forge mod and not a bukkit plugin.

Do not use kCauldron with FE.
