### ISSUE TITLE
FE with bungeecord

### ISSUE THREAD

**Issue by Darktilldawn** [ForgeEssentials/ForgeEssentials#1867]
So I've recently got my Spongeforge server linked into my bungeecord proxy and everything works as it should until I add FE to my sponge server. When i do that i am unable to connect to it through bungeecord. I'm not sure if it's ForgeEssentials causing the issues or Bungeecord. Any idea's? 
Also using Forge version 1563 and sponge dev 814 with the 1.8 #51 forge essentials

**Comment by luacs1998** [comment]
Does it work without FE?

**Comment by Darktilldawn** [comment]
Yes, once I remove FE from the sponge server I can connect through bungee to it

**Comment by luacs1998** [comment]
This is odd...

But in the meantime since you have sponge I'd recommend you look into sponge alternatives.

**Comment by Darktilldawn** [comment]
I have been... no grief prevention. And permissionsex for the permission system. That's the big problem lol sponge is still WIP and your mod had everything in one nice big package. But I was going to let you know about the bungee issue in case it was something you wanted to fix

**Comment by olee** [comment]
If you use FE - why do you use sponge?
And try disabling remote module and see if you can connect then.

**Comment by olee** [comment]
@Darktilldawn anything new on this?
I will close this for now until we hear back from you...
