### ISSUE TITLE
Request - Change the block that portal frames are made of

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1868]
My title says it all.

**Comment by luacs1998** [comment]
It is possible with a custom renderer.

But whether that custom renderer is something FE should do is another question altogether. FE is a server mod, not a client beautification mod.

I'll leave this open if anyone has feedback to make.

**Comment by spannerman79** [comment]
> What I can do, though, is allow one to change the portal block - this will allow the implementation of custom renderers

This would be better, that would give the choice and it would be up to the server admin to either keep it as is or use a modded block type that they would already have via another mod or
