### ISSUE TITLE
Request - Create portal that links to nearest defined biome

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1869]
One the things that would be totally awesome would to create something called the biome portal. How it could work is a player would enter it and in the text box a player could click on a biome. The portal would than port the player to the center of the biome they select. The portal would only be a one way portal. 

1 - Player enters portal
2 - Player chooses desired biome
3 - Player is ported to desired biome
4 - Portal creates an unbreakable 7 by 7 slab with portal gate.
5 - Portal closes player cannot go back through though slab remains to show player that none admins can not mess with created spot. (When a player attempts to break it have a message saying "Notch won't allow this." By creating a small structure it also shows the player the exit point of the portal and that they cannot build on or near this 7 x 7 x 7 cube.)

**Comment by spannerman79** [comment]
There are several mods already that can direct a player to a particular biome type.  Take for example botania just from off the top of my head.

And even then Botania doesn't always finds the the wanted biome type closest to the player - yes it does find one but never always and every time closest.

For server resource wise it would be better if you actually located the particular biome (for example desert type for Mekanism Solar Evap Tower) and set up a mini safe zone from that point to where your main server portal/teleport system is located

**Comment by olee** [comment]
I know we do a **lot** of stuff in FE.... actually already more than we are supposed to.
But this time I really have to say - get a proper mod for this :sweat_smile: 
And if there is no mod to do this yet, find someone who wants to code this.
This is already clearly a gameplay feature and not a server management feature.
The only thing **we** might add would be a command to locate (or teleport to) the nearest biome of a certain type.
Considering we don't have much manpower anyway and still a lot to do, I would either close this request or set it to `wontfix`.
