### ISSUE TITLE
Blood Magic overwrites the death chest.

### ISSUE THREAD

**Issue by chrisbecke** [ForgeEssentials/ForgeEssentials#1870]
I'm not sure if this is a Blood Magic or Death Chest issue. Well, I think it is probably Blood Magics issue - but on the off chance it isn't...

If player dies in the vicinity of a Blood Magic demon invasion, their death death chest (head on a stick) appears normally. However, Blood Magic Demon Invasions grow over time, placing new buildings and roads as they go, and in at least one instance i've replaced a players stuff as a building spawned and overwrote the deathchest.

Because the deathchest is meant to be protected, this concerns me that Demon invasions will be able to overwrite players claims.

**Comment by olee** [comment]
You need to contact the mod author to trigger proper block place events.
When the deathchest gets destroyed (we listen to that event), it will automatically be reconstructed.
You can try it for example by dying and then replacing the deathchest block with worldedit.
It will (visually) disappear, but if you click the block where your deathchest was before, you can still access it.
