### ISSUE TITLE
Deathchest despawns with items

### ISSUE THREAD

**Issue by chrisbecke** [ForgeEssentials/ForgeEssentials#1871]
Steps to reproduce:
As an OP, equip at least one item.
enter /kill to kill your character near the respawn point.
Loot the death chest, but before closing the window, put one item back.

The death chest will despawn when the window is closed, with the item in it.

**Comment by olee** [comment]
Was it empty before?

**Comment by chrisbecke** [comment]
The scenario is, take everything out, change your mind before closing the GUI, and put something back in. e.g. if you have no space in your inventory for everything.

**Comment by luacs1998** [comment]
Can you try with this build http://ci.forgeessentials.com/job/FE/1039/
