### ISSUE TITLE
FE white list function does not take effect

### ISSUE THREAD

**Issue by ProgrammedSoul** [ForgeEssentials/ForgeEssentials#1872]
The auth model is enabled and FE white list is set to true in config file, but is does not take effect. The server white list option is disabled.
Some things looks wrong:
Anyone can login even white list is enabled.
When execute /whitelist toggle the first time after the server is started, it returns "FE Whitelist was on, it is now turned off". After that I cannot turn it back on, toggle command returns "The whitelist is not enabled. You can enable it in server.properties or your auth config file....". If restart the server, whitelist option in config is not changed. Same pattern repeats on every server restart.
After server started it warns whitelist command (alone with some other FE commands) was registered twice.
Any other commands begin with whitelist other than whitelist toggle produce no output at all.
The IRC support channel is down.
I was using 1021 version, found this (maybe) bug, then I switched to 1.4.3.1039 build, nothing changed.
The forge version is forge-1.7.10-10.13.4.1558. All other mods are feature mods that does nothing in terms of server managing.

**Comment by luacs1998** [comment]
I am thinking of removing FE's whitelists and bans - the vanilla ones are more than good enough, AND mcbans/whatever should be able to find a way to hook into the vanilla server's bans.
