### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kittykiller** [ForgeEssentials/ForgeEssentials#1875]
This is the second time this has happened. I don't have the crash log from the first time.

http://pastebin.com/8Qsg2Ca5

**Comment by liach** [comment]
Sir please enable safe mode.
How to:
when launching minecraft server add argument `-Dfe.safemode=true`

**Comment by kittykiller** [comment]
Done.

**Comment by liach** [comment]
Fixed?

**Comment by kittykiller** [comment]
Hard to say, it doesn't happen on server boot and I don't know how it caused the server to crash so I can't really test.

**Comment by olee** [comment]
@kittykiller FYI - we changed the launch argument back to a config option in main.cfg in newer builds.
You should also perhaps contact Biomes'O Plently to fix that bug on their side (they are dropping an item stack with `null` as item):
````
at biomesoplenty.common.blocks.templates.BOPBlockWorldDecor.dropIfCantStay
````
