### ISSUE TITLE
[Suggestion]Add string arguments type

### ISSUE THREAD

**Issue by ProgrammedSoul** [ForgeEssentials/ForgeEssentials#1876]
I'm trying to create a series shortcut scripts for the server. The existing arguments in script model gives a limit. For example, you cannot use it with come commands with string arguments because it does not support string arguments. Also it makes you unable to pass a offline player name because @p force check online player.

**Comment by olee** [comment]
Oh the thing with @p is a problem.
As for string arguments I will need to see....
I could perhaps add something like @* to match all the rest.

**Comment by luacs1998** [comment]
Do we even support offline players?

**Comment by liach** [comment]
Yes you always should

**Comment by olee** [comment]
Well as for @p, the online check should be changed to a is-known-player check maybe.
Also @ProgrammedSoul, you can use just an **@** instead of **@p**, to match just a string.

**Comment by olee** [comment]
Example
````
{
    "name": "confirm",
    "usage": "/confirm",
    "extraPermissions": {},
    "patterns": {
        "@+": [
            "confirm @0*"
        ],
        "": [
            "confirm no message specified"
        ]
    }
}
````
The syntax for insertion is `@[idx]*` where `[idx]` sepcify the start index of the arguments for insertion.
I.e. `@1*` would start from the second argument and insert all the remaining ones.
