### ISSUE TITLE
Chat Color Codes Permission?

### ISSUE THREAD

**Issue by Solidflip** [ForgeEssentials/ForgeEssentials#1877]
Hello,

This is probably a simple answer, but ive never used this mod before. I looked for a way to restrict the use of color codes in chat to certain groups but cant find it. I tried the IRC but didnt receive an answer and it says to make an issue.

**Comment by luacs1998** [comment]
`fe.chat.usecolor`

**Comment by Solidflip** [comment]
Thank you

**Comment by olee** [comment]
http://localhost/FERemotePanel/web/module/permissions
