### ISSUE TITLE
Lag and time-outs since running a pregen/filler

### ISSUE THREAD

**Issue by Flenix** [ForgeEssentials/ForgeEssentials#1878]
Hey all.

I run a server which uses a mod called MCHeli. If you haven't used it, it lets you fly big fast planes around (Considerably faster than Flan's or others). As such, when I first generated the world I decided to use the pregen to make it nice and big, so users wouldn't ever hit generation issues.

I have a 4TB drive on my server, so set the border to 100k and generated. This was in roughly september 2014, and everything went fine - we had a nice big world, and all was well.

HOWEVER, a couple of weeks ago I was getting user requests to expand the world a bit. Most of the world was ice and ocean, and they wanted more to play with, which seemed fair. I'd still barely touched the drive space either, so agreed to expand it to 150k. Generation went fine (Although I was stopping and starting periodically, as the server is now live and I didn't want to disrupt online players too much) - but ever since doing that, the server has been lagging intensely when the players enter any incomplete chunks (IE, chunks that FE generated but haven't been explored yet, so don't have decorations). As soon as players start to explore these areas (Generated in either the old or recent pregen), the server times out and kicks all online players. TPS and ping seem to be totally unaffected.

I'm also getting Can't Keep Up logs printed to the console a lot more since doing this, with anything between 500ms and 15,000ms of lag. The game apparently runs fine with no notable lag so long as users stay within their generated areas - but those logs are still printed.

Any ideas what may have caused this or how I can fix it? It's effectively a world-breaker if they can't explore so I really want to try and fix it. I wasn't sure if maybe Minecraft just struggles with such a large world even if the chunks aren't loaded, or if there's something weird going on even though the pregen has been stopped?

I've tried asking on IRC a few times but no one was around :(

Thanks

**Comment by olee** [comment]
Ok this sounds like a really troublesome issue.
AFAIK if you restart the server and don't touch pregen and it still lags, you probably have some other issue with either FE or another mod.
I tried to make pregen work the best I could, but worldgen is really one of the ugliest things you can find in Minecraft and messing around with it in pregen is not easy.

I don't know if I can do anything for you here except recommending you to take a plane and do pregen yourself by flying around...
Pregen is not really a feature I can reasonably invest soo much time into.
I will see when I have some time to look into this.

**Comment by Flenix** [comment]
Have mentioned this in IRC and pinged you but in case you didn't see:

I've been running a test server with a pregen, 150k by 150k. It had been running about 3 days and I started to get the same time out issue, I'd log in and within around a minute, I'd time out again.

I stopped the pregen, reloaded the server, and it wouldn't complete startup. It reaches the point where it tries to load the spawn region, and then prints this:
http://pastebin.com/fMqdr86X

Obviously the pregen doesn't auto restart so I don't think that's the issue. The world had generated roughly 5% of the full area, and is less surface area than our old existing world (which worked for over a year before hitting issues) so I don't think that's it either. I manually explored quite a lot before running the pregen, also without any issues (and even a bit in the first day while it was running)

Going to try removing FE for a minute to get the world loaded and see what happens, but just posting this to keep you updated.

**Comment by Flenix** [comment]
Alright, I've done a lot of experimenting, and it is an odd one.
Generating large amounts (Over about 15km squared) seems to cause the issue, you get a time out kick when entering areas as it populates them. Even after removing FE, this issue persists.

HOWEVER, doing similar sized generations with alternate mods (Eg ProfMobius' Admin Command Toolbox pregen, or using KCauldron with the World Border plugin's fill command), work absolutely fine. It's worth noting both of these actually load the chunks and do the population as well as generating landscapes. Could that be part of the issue?

(That being said it's easier for me to just use the cauldron one now, as it's already running - Just forwarding my results in case others have the issue and a fix is still needed)
