### ISSUE TITLE
Permissions issue!

### ISSUE THREAD

**Issue by Likton** [ForgeEssentials/ForgeEssentials#1879]
Hi! 

I have some troubles with permissions. I'm running a forge server on minecraft 1.8 . I've done some permissions for the group _GUESTS_ who can't interact, place and break blocks for buildings security reasons. In the same time, after my players are accepted, they are in a new group, allowing them to craft, interact, place and break blocks. But, when I put a player in this last group, he keep the same permissions of _GUESTS_ . I think, it's not a normal way. I've follow your tutorial, but I didn't see any particular informations about switching group. Maybe I've forget sommething ?

Furthermore, I'd like to know how can I add some commands permissions nodes of my mods who requiring them. My players can't makes commands at all (even if I use the moder advised syntax, example: com.pixelmonmod.pixelmon.commands.example). If you have any advise too, I will be happy to be helped! :)

(PS: I put my two config permissions files for the two groups I talked about before )
[_GUESTS_.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/45227/_GUESTS_.txt)
[DRESSEUR.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/45228/DRESSEUR.txt)

**Comment by olee** [comment]
As for groups, you need to add players to them with `/p user <name> group set <group>` or `/p user <name> group add <group>` (the first one removes all other groups the player belongs to before adding him to the new one).

As for mods: 
That's all up to the mod authors.
They need to support FE permissions because forge currently does not have a common permission interface.

**Comment by Likton** [comment]
I've done this command for sure ! -_- but the perms are not considered as much. Even if the command /p user <user> perms  list the  good perms , these I would to applicate. 

Okay, thanks for thé help, I will try something with the mod author

**Comment by olee** [comment]
If the permissions do not show up in [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentials/wiki/PermissionList.txt) (of course the one on your own server - not the wiki version), they will (most certainly) not work.

You will need to contact the mod authors.
Feel free to link to this issue or mention me there with @ olee (without space of course)

**Comment by Likton** [comment]
There are on my permission list.txt because it's the permissions of ForgeEssentials. ^^ (the perms  of the mod are effectivly not into this file son maybe i'll try with sponge)
