### ISSUE TITLE
Groups unable to use /warp or teleport across dimensions

### ISSUE THREAD

**Issue by Solidflip** [ForgeEssentials/ForgeEssentials#1880]
I have the permissions for a certain group to be able to use /warps including the fe.teleport.warp and .from/.to etc. However the chat tells them "you dont have permission to use this warp".

I tried this as an op and i could use the warp just fine. I was wondering if there is another permission they need (i gave them all of the fe.teleport ones and sill ran into this issue as a test)

The second issue is that even as an OP i get the message "you are not allowed to teleport across dimensions" The only way to overrule this is to not use the fe teleport commands and use cofh tpx commands.

**Comment by Solidflip** [comment]
I figured it out, by looking into the code...

The /warp issue was due to the group not having the fe.teleport.warp.<warpname> which isnt in the perms list but is needed to do any warps that are named.

The inability to teleport across dimensions was due to the missing fe.teleport.crossdim permissions missing which i had to look at the teleporthandler for

**Comment by olee** [comment]
Well - that would have shown up with `/p debug`, too.
That's what happens if `* = false` is used.

**Comment by Solidflip** [comment]
I didnt use the *= false, this was from a new group so they didnt have any of them

**Comment by luacs1998** [comment]
Wiki had been updated.

https://github.com/ForgeEssentials/ForgeEssentials/wiki/Teleport-Module
