### ISSUE TITLE
Setting potion effects for an area do not work.

### ISSUE THREAD

**Issue by Roadcrosser** [ForgeEssentials/ForgeEssentials#1881]
I am able to set a permission node to give players potion effects while in a zone, but while the permission node is successfully set, the potion effects do not appear.

UPDATE: They work when you relog, it seems.

**Comment by PitchBright** [comment]
Please close the issue then.

**Comment by PitchBright** [comment]
Thanks :)

**Comment by olee** [comment]
I just read the thing on IRC when I came back.
The thing with these permissions is, that they only get checked when you change the zone you are currently in.
So relogging or changing dimensions will work, too.
