### ISSUE TITLE
[Question] Command to force load dimension on server start?

### ISSUE THREAD

**Issue by Alaberti** [ForgeEssentials/ForgeEssentials#1883]
Is this something within FE's scope? I believe Galacticraft has a command for it, but that's a lot of mod I wouldn't be using just for that functionality. Chickenchunks can force load a dimension, but seems to cause other problems with mods due to its implementation. Thank you for any assistance/advice you can provide on this matter.

**Comment by olee** [comment]
AFAIK chickenbones chunkloader works perfectly and it has the small version which you can place in your dimension to load just one small chunk. This should work without problems.

We don't have any chunkloading functionality in FE and there are a lot of other mods that can do this just fine. Please ask again only if other solutions don't work. 

We currently don't have the time to implement this.
Sorry

**Comment by luacs1998** [comment]
It's something I think may be beyond FE's scope as well - there are a lot of things we do, but we can't do everything, especially when there are far better solutions out there.

**Comment by Alaberti** [comment]
Fair enough, by never hurts to ask the question. Thanks!
