### ISSUE TITLE
Shop's item frames can be emptied by shooting an arrow at it.

### ISSUE THREAD

**Issue by maxanier** [ForgeEssentials/ForgeEssentials#1885]
Hello,

apparently you can shoot an arrow at the shop's item frame to get the item out of it even though you are not allowed to create or destroy shops. This might also work with eggs.

I tried denying fe.protection.use.minecraft.bow.* and fe.protection.use.minecraft.arrow.* for the zone the shops are in, but somehow this does not work all the time.
Somehow the shoot action is only sometimes interrupted (this is not only client side/after reconnecting the arrow was still laying there and the shop destroyed).
The client side mod also shows that it is forbidden to use that bow.

I read  #1784, @olee mentioned the damageto permissions, but fe.protection.damageto.EntityItemFrame does not help (and probably does not even exist).

I'm running ForgeEssentials 1.7.10-1.4.3.1041 with Forge 7.99.36.1558.

Hopefully you can fix that, if you need any further information I'm happy to help.

**Comment by luacs1998** [comment]
I smell a hook coming...

**Comment by olee** [comment]
@luacs1998 do you remember what I said about hooks before?
Most times we **do not even need them**.

In this case we can just check the damage permission.

**Comment by maxanier** [comment]
I investigated the Minecraft/Forge code a little bit. For it does not seem as if Forge throws any event when an arrow hits a EntityItemFrame. The arrow code looks for very near entities (in onUpdate), if it finds one it simply calls attackEntityFrom on it, since the ItemFrame does not inherit from EntityLivingBase no AttackLiving event is thrown. The item frame then drops the displayed item. Not sure how how FE works, but using the current Forge hooks/events this does not seem possible.

But there might be another solution for this specific problem: The itemframe seems to check for isEntityInvulnerable() before dropping the item, so you could set the corresponding field via reflection when the shop is created and make it vulnerable again when the shop sign is destroyed or maybe check the AttackEntityEvent when the player hits the sign with his hands to make it destroyable as long as he is permitted to.

**Comment by luacs1998** [comment]
What I was having in mind is actually an ItemFrame.Set and ItemFrame.Destroy events.

Hooks don't just benefit us - as and when I get around to making the necessary Forge PRs everyone gets a free ride as well.

I'll see how that idea works - reflection is messy though.

**Comment by glixyl** [comment]
I am getting around this for now by encasing FEShop items/item frames with forge multipart's strengthened glass covers combined with protections.

**Comment by maxanier** [comment]
Pretty good idea, I did not think about that ^^, thanks :). I'm using glass panes now, since I'm not using multiparts, but they seem to work as well. This is at least a pretty good workaround for now.

**Comment by olee** [comment]
@maxanier well - I already investigated it on my own and came to the same resolution :smile: 
But I am working on this and have an idea for a fix.
For now, please try to protect your shops from projectiles by other means.
Sorry for the inconvenience.
