### ISSUE TITLE
[Suggestion] /r to reply to last sender of /msg

### ISSUE THREAD

**Issue by Alaberti** [ForgeEssentials/ForgeEssentials#1887]
Just a low-priority courtesy feature request to have /r reply to last sender for a /msg. Please keep up the hard work, but don't miss out on the holidays either!

**Comment by Zethalion** [comment]
It already exist in that form.

**Comment by olee** [comment]
Already exists in FE

**Comment by Alaberti** [comment]
I'm such a derp; thanks for letting me know!
