### ISSUE TITLE
basic question about update

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentials#1888]
hey,

i have an old version (1.4.3.1008-nightly) installed..
the latest is 1044 now. if i only replace the jar's i guess that something with the configs will go wrong or recognizes the mod automaticially new config sections and iserts the new one or have i to delete the whole config folders for new fresh generation ?

thx in advance!

-jogi

**Comment by olee** [comment]
Unless you upgrade from old beta versions, you can continue using the same configs.

**Comment by jogi01** [comment]
cool thx !
