### ISSUE TITLE
How to make the Votifier work?

### ISSUE THREAD

**Issue by KaneHart** [ForgeEssentials/ForgeEssentials#1891]
I enabled it in the main but I don't see much else besides that. More and more people will want it just because the main MCF site now supports it.

Server example:
http://www.minecraftforum.net/servers/813-feed-the-beast-infinity-evolved

Votifier Config:
http://i.imgur.com/Su8DzKR.png

**Comment by liach** [comment]
Ah its reward system is broken.

**Comment by luacs1998** [comment]
I blasted the reward system to oblivion - now you use scripting module.

https://github.com/ForgeEssentials/ForgeEssentials/commit/57482b2f59429e1e8cd8d7db6f140b3415e5b464

**Comment by luacs1998** [comment]
You ran into #1744 on IRC, so I'll close this.

**Comment by Temcoin** [comment]
cant seem to find an example script.
trying to reward players for servervote.

**Comment by spacebuilder2020** [comment]
there is no example script, but just follows the pattern used on all other server scripts.

See https://github.com/ForgeEssentials/ForgeEssentials/wiki/Scripting#server-scripts
