### ISSUE TITLE
How to disable certain feature? 

### ISSUE THREAD

**Issue by MineMine** [ForgeEssentials/ForgeEssentials#1893]
I want to disable WorldBorder and Pregen feature for replace it to WorldBorder-Forge 

and some other features either

**Comment by luacs1998** [comment]
/pregen is a command - simply don't use it.

To disable worldborder, go to main.cfg, look for `WorldBorder=true` and change `true` to `false`

**Comment by MineMine** [comment]
Thanks to fast replying
