### ISSUE TITLE
Server Crashers when trying to load

### ISSUE THREAD

**Issue by sweeneyc** [ForgeEssentials/ForgeEssentials#1894]
I am using the MinecraftEDU Server system and I am trying to get ForgeEssential to run. I have placed the MOD in the MOD folder, under Servertools and I enabled it in the MOD tab when opening the browser. But now it seems that when I launch the server, it immediately crashes

Am I missing something? am I doing this wrong?

**Comment by liach** [comment]
Give a fml-server-latest.log after reproducing the crash. Btw the mod jar should be put in mods folder.

**Comment by sweeneyc** [comment]
[fml-server-latest after crash.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/67210/fml-server-latest.after.crash.txt)

**Comment by luacs1998** [comment]
MCEdu uses an old version of forge - go pester them to update, it's nothing we can control.
