### ISSUE TITLE
Kit issues with FE 1.8 #56 & #58

### ISSUE THREAD

**Issue by Celethras** [ForgeEssentials/ForgeEssentials#1897]
So FE 1.8 #54 worked fine. When I updated to #56 the /kit function would not work anymore. By this I mean that when I went to load a kit it would say...

Could not give some kit items
Kit Dropped

However nothing would drop into my inventory. Old kits from #54 would work. However new ones would not work. I even tried using the same items as a kit made in build #54. and it still wouldn't work.

in #58 build for some reason I was unable to write on signs.

**Comment by luacs1998** [comment]
Does 1.8.3.58 work with kits? I changed some things related to signs so I know that's broken. Will have to debug.

**Comment by Celethras** [comment]
I'll have to check.

**Comment by olee** [comment]
Try with the updated 1.8 version from today 
https://github.com/ForgeEssentials/ForgeEssentials/commit/cafbc0d0631abf8181bc8601683167273c8c18f7

**Comment by luacs1998** [comment]
Nope, seems that the updates didn't fix this.

**Comment by luacs1998** [comment]
This does not seem to happen with build 68.

Closing, please reopen if not fixed.
