### ISSUE TITLE
"kicked" from server when harvesting anything from resourceful crops

### ISSUE THREAD

**Issue by pskitz** [ForgeEssentials/ForgeEssentials#1900]
http://pastebin.com/tBu2UBtL Server log of the problem. Updated client and server to the latest build (1055) and still had the issue.

**Comment by olee** [comment]
Do you have Twilight Forest installed?
They just drop null-stacks sometimes.
You can prevent such crashes by using FE's safe-mode.
See main.cfg for the setting.
