### ISSUE TITLE
One-time use Kits

### ISSUE THREAD

**Issue by t0mmyxbl** [ForgeEssentials/ForgeEssentials#1901]
When setting a kit I believe setting the cooldown as -1 should make it a one-time only use, although it doesn't, you can use it as many times as possible. If there is a way to make it one-time only that isn't that, then I'm not sure what it would be. While I'm at it as well, how do you put colour on signs? I can't seem to find a way.

**Comment by glixyl** [comment]
how timely.  I was just trying to figure out if it was possible to do this myself today.

**Comment by luacs1998** [comment]
Colour on signs follows the same syntax as colour on chat.

**Comment by t0mmyxbl** [comment]
When I did &9test for example on a sign it doesn't colour it, it shows the &9

**Comment by glixyl** [comment]
hrmm this issue is misleading.  why are we talking about color chat on signs?  a one-time kit is the subject.

**Comment by t0mmyxbl** [comment]
I added it onto the end of the comment, dw about it

**Comment by olee** [comment]
Please do **not** mix two questions in one issues. Makes it pretty confusing to track these things :wink: 
As for the kit cooldown - I took care of it with the last commit.
You can now use cooldown `-1` to have infinite (actually 10 year) cooldowns.

**Comment by glixyl** [comment]
when a player leaves the game and rejoins, the kit is then again available to them when using the -1 flag

**Comment by t0mmyxbl** [comment]
I forgot to mention that this is in 1.8, so if this fix could be carried over to the 1.8 version that would be great

**Comment by olee** [comment]
Yeah, we will do a 1.8 migration very soon.
Please be patient.
