### ISSUE TITLE
Can't "use" items when looking at the sky

### ISSUE THREAD

**Issue by GunArm** [ForgeEssentials/ForgeEssentials#1902]
I was having an issue, I found a way around it but I think there is still possibly a  bug involved so I want to put it out there.

I set the \_GUEST\_ account to *deny fe.protection.use.**
I understood this could cause problems with guests eating food etc which I was fine with because until they are added to "members" they aren't real players anyway.
I also set *deny fe.protection.use.** in the spawnzone which is protected, but small and the issues are outside that zone.

Problem is, I started seeing all kinds of weird issues related to *fe.protection.use.** for _members_.  The *fe.permissions.use.** permissions were all unset in the members group, meaning to me it should implicitly utilize the default (allowed?) *fe.protection.use.** permissions.

But its not so simple as they were just denied.  Rather, users could not do any *fe.protection.use.** action __while looking at the sky__.  They had to be looking at blocks.  This includes eating food, activating openblocks hangglider, opening a bag of holding, things with thaumcraft wands, throwing eggs, etc.  These actions would all work when looking at a block, but they would not work when looking at the sky.  When the user was made an OP, they could "use" while looking skyward.  

All of the players did pass through \_Guest\_ on the way to the "members" account, in case that's relevant.

Finally I explicitly added */p group members allow fe.protection.use.**
and it got me around the problem.

It seems like a bug that it was necessary to explicitly allow this on one group.  And also   I'm not even 100% sure that it being denied on the guest account is related but I assume so.  Also making me think it's unwanted behavior is that it was looking-at-the-sky-dependant.

More information from _before_ I added the *allow fe.permissions.use.**

__When a non-op member looked at the *GROUND* and threw an egg:__
/protectdebug would say:
> fe.protection.use.minecraft.egg

/p debug would say
> fe.protection.use.minecraft.egg = true 
> zone[_ROOT_] group [_All_]

__when a non-op member looked at the *SKY* and threw an egg:__
/protectdebug would say:
> fe.protection.use.minecraft.egg

/p debug would output nothing, not true, not false, not null

**Comment by olee** [comment]
I think this should solve it.
The problem was that it used the world coordinates [0,0,0] when checking for permissions while looking into the sky. Maybe you had some spawn area set up around [0,0,0]?

Try again if it works now.

**Comment by GunArm** [comment]
I would be willing to try to test it on my server when there is downtime, however I am not set up to build java projects.  I don't suppose there is a place I could get a build?

In any case my spawn (with the use.* protection) *is* at 0,0 and goes down to the bottom of the map, so I'm fairly certain this was precisely my issue.

**Comment by olee** [comment]
Ehhh.... just download it from our [Jenkins build server](http://ci.forgeessentials.com/job/FE/) ?
You should take a look at the front page on github :wink:

**Comment by olee** [comment]
Well - I will close this for now already.
I tested it myself and it worked properly.
If you still have problems, report back here.
