### ISSUE TITLE
CommandHandler mixin crash with newest CoFH core

### ISSUE THREAD

**Issue by Grovert11** [ForgeEssentials/ForgeEssentials#1903]
When launching my server I get a big error regarding Forge Essentials.
I tried builds 1021 and 1060, but they give the same error.
When disabling FE, the server starts just fine.
Log file: http://pastebin.com/8iUiDGfX

**Comment by Grovert11** [comment]
There seems to be a conflict between FE and the latest alpha build of COFH Core

**Comment by Haggle1996** [comment]
Haggle1996/RevolutionPack#145

**Comment by olee** [comment]
CoFH is doing some shit to CommandHandler.
Probably a broker ASM transformer.
They need to fix it on their side.

**Comment by olee** [comment]
Might not be directly related to CoFH... needs more investigation

**Comment by luacs1998** [comment]
SpongePowered/Mixin#86

**Comment by mcsnetworks** [comment]
Almura fixed this conflict by adding:
 MixinEnvironment.getDefaultEnvironment().addTransformerExclusion("cofh.asm.CoFHAccessTransformer");

to our AlmuraLaunchTweaker.java class.

**Comment by olee** [comment]
Thanks for the info!
We will try this out and add it to FE if it works.

**Comment by luacs1998** [comment]
Or we could update mixin, but IDK if @mumfrey is up to something... There seems to be no stable version after 0.4.4.
