### ISSUE TITLE
Two linked Issues: with Plots altering players assigned groups and //deselect command permissions

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentials#1905]
When ever a player joins/added to /creates a plot and enters it for the first time they are being removed from the _guest_ group and just assigned to just the  _players_ group. This would allow the people just assigned to _players_ to use commands restricted as _guests_ such as //copy //cut.

As a temp fix I had to inherit the groups so that _players_ shares _guests_ permissions. However this creates another problem as _op_ member are also tied to _players_ which causes the _op_ group to be affected by another group / command issue with having to do with  //deselect command not working for people under _guests_.
 to fix the //deselect issue I have tried

/p group _GUESTS_ allow command./deselect
/p group _GUESTS_ allow command.//deselect
/p group _GUESTS_ allow worldedit./deselect
/p group _GUESTS_ allow worldedit.deselect
/p group _GUESTS_ allow worldedit.deselect.*
Any many other variations. I have looked through the permissions file in the forgeessentials directory and noticed that it lists majority of the available commands for worldedit but it does not list the deselect command at all as a available command.

**Comment by olee** [comment]
Hm... this is indeed a little problem.
Players are automatically part of _GUESTS_, when they are in no other group.
But by entering their plot, they are part of the plot owner group, breaking this functionality.
I will probably need to make in include guest before adding area-based groups.

**Comment by blkwind** [comment]
Your the man Olee, thank you!
