### ISSUE TITLE
Two linked Issues: with Plots altering players assigned groups and //deselect command permissions

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentials#1906]
When ever a player joins/added to /creates a plot and enters it for the first time they are being removed from the _guest_ group and just assigned to just the  _players_ group. This would allow the people just assigned to _players_ to use commands restricted as _guests_ such as //copy //cut.

As a temp fix I had to inherit the groups so that _players_ shares _guests_ permissions. However this creates another problem as _op_ member are also tied to _players_ which causes the _op_ group to be affected by another group / command issue with having to do with  //deselect command not working for people under _guests_. On top of that it also prevents my admins from using other world edit clipboard commands.

 to fix the //deselect issue I have tried

/p group _GUESTS_ allow command./deselect
/p group _GUESTS_ allow command.//deselect
/p group _GUESTS_ allow worldedit./deselect
/p group _GUESTS_ allow worldedit.deselect
/p group _GUESTS_ allow worldedit.deselect.*
Any many other variations. I have looked through the permissions file in the forgeessentials directory and noticed that it lists majority of the available commands for worldedit but it does not list the deselect command at all as a available command.

**Comment by luacs1998** [comment]
There are some additional commands under the `fe.core.pos` node, you may want to allow those as well.

**Comment by olee** [comment]
@luacs1998 this doesn't really have anything to do with the issue at hand :laughing: 

@blkwind ok this seems to be a fault on @sk89q's side.
There seem to be some commands that do not register permissions for themselves.

These are:
````
[/searchitem, /l, /search, searchitem]
[/sel, ;, /desel, /deselect]
[/toggleplace, toggleplace]
[schematic, schem, /schematic, /schem]
[superpickaxe, pickaxe, sp]
[worldedit, we]
````

@sk89q we rely on your ForgePermissionsProvider to be called for every command you register.
It seems like that is not the case for all your commands.
Could you check / fix this or will we have to do some magic on our side?

**Comment by olee** [comment]
Ok I talked to wizjany and confirmed, that there are no permissions for some WE commands.
@blkwind you will have to give players the `command./sel` permission.

**Also definitely update to latest version of FE, because I noticed a huge security issue in WE default permissions (OP / non-OP were swapped)**
This caused everyone to be able to use WE commands, but only OPs to use selection commands (instead of the other way round)

**Comment by blkwind** [comment]
Awesome thanks agian Olee!
