### ISSUE TITLE
Fe.protection.explosion.blockdmg permission missing

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentials#1909]
Hello agian. I just recently uograded FE from like 1011ish to the latest version. I noticed the permission fe.protection. explosion.blockdmg no longer exists. This was really useful for disabling mobgriefing in specific zones without having to disable it server wide. I run a multiworld server where one world world is super hardcore and the basic overworld is easier. Will this permission be back in future updates? Currently i have disabled explosions all together in the overworld but it just makes the creepers just vanish as apposed to dealing dmg but not breaking blocks as the old command did.

**Comment by luacs1998** [comment]
http://forgeessentials.com/2015/12/updated-explosion-permissions/

**Comment by blkwind** [comment]
Awesome thanks !
