### ISSUE TITLE
/timedtask is broken

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1910]
@luacs1998 just noticed the code for timedtask to be completely broken.
Can probably removed and replaced with the new cron feature of scripting.
Needs some investigation.

**Comment by luacs1998** [comment]
Please do.

**Comment by olee** [comment]
Closed in https://github.com/ForgeEssentials/ForgeEssentials/commit/327a00a6fad61bbd9fd79401ca3255aefbc15b35
