### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by kittykiller** [ForgeEssentials/ForgeEssentials#1912]
Using version 1.7.10-1076

http://pastebin.com/EQ7Lmpbd

**Comment by olee** [comment]
Looks like an invalid grave object.
Delete all files in `./world/FEData/json/Grave`.
Will try to add a safeguard for this.

**Comment by olee** [comment]
Or try out latest version and see if it loads correctly.
You probably removed a dimension in one way or another.
That's why it breaks when it cannot find the dimension the grave was in.

**Comment by kittykiller** [comment]
I've already deleted the files and it loaded up correctly.

**Comment by Drethic** [comment]
I've just received this error with the 1.4.3.1021 version on CurseForge and again with the 1.4.4.1137 version on Jenkins.  Both times I had to remove the world/FEData/json/Grave/*.json files for the server to boot.

Here is the latest log file to help you squash that bug.  If I had been thinking I would have grabbed the grave file for you.

http://pastebin.com/Uu2BKW6X

**Comment by olee** [comment]
@Drethic this is a totally different issue.
I opened #1979 for you.
