### ISSUE TITLE
Crash with FastCraft

### ISSUE THREAD

**Issue by bengelbaer** [ForgeEssentials/ForgeEssentials#1914]
Essentials will chrash if Fastcraft is aktive.

**Comment by olee** [comment]
1. Learn English
 2. [Learn reading](http://ci.forgeessentials.com/job/FE/)

>Don't use FastCraft with FE.
>If you really need it, get the 1.22 test builds from the end of player's thread.

**Comment by bengelbaer** [comment]
Yes sir ;-)
