### ISSUE TITLE
No main manifest attribute in forfeessentials

### ISSUE THREAD

**Issue by PetoFeFe** [ForgeEssentials/ForgeEssentials#1915]
Hello,
I have a problem with forgeessentials-1.7.10-1.4.3.1021-server.jar, i want to run it with command 
java -Xmx1024M -Xms8M -jar forgeessentials-1.7.10-1.4.3.1021-server.jar

When I try to run server, it write:
no main manifest attribute, in forgeessentials-1.7.10-1.4.3.1021-server.jar

I have Ubuntu server with Java 8, Thanks for help and sorry for my english :)

**Comment by liach** [comment]
Run the `minecraft-server-1.7.10.jar`. Forge Essentials jar should be put into the `mods` folder since it is a forge mod. And do not forget to install forge on vanilla minecraft server.

**Comment by PetoFeFe** [comment]
Ok, thank. I'll go to try it. :)
