### ISSUE TITLE
Not able to set permcheck error message.

### ISSUE THREAD

**Issue by DeForce** [ForgeEssentials/ForgeEssentials#1917]
I'm trying to create command script, but for some reason permcheck is sending only "default" error message "You don't have the permission to use this command" instead of:

      "permcheck czt.world.created You have already created the world! Lame You!",
      "permset user @player allow czt.world.created",
      "notify You are prepared"

Maybe i'm doing something wrong? But on wiki it is as this.

**Comment by olee** [comment]
Looks nice... but FE seems to fail this time.
Give me a moment to check this...
