### ISSUE TITLE
permcheck 'value'

### ISSUE THREAD

**Issue by DeForce** [ForgeEssentials/ForgeEssentials#1918]
Is it possible when writing scripts to check the value of the permission. Not just "true/false" but if I set it to something like world.id = "World12" and then check it like that:

permcheckval world.id World12 [error message]

I were not able to find the appropriate permcheck for that kind of logic.
Also another logic will be really cool (dont know if it is already in place):
permcheck world.id @p

so for example I have permission 
world.id "MyNickname"
and
permcheck from user "MyNickname" will be positive in this case of the example.

Would be really nice in writing scripts with more complicated logic.
Best Regards.

**Comment by olee** [comment]
Sounds interesting, why not?
Will probably add it with the next update.
