### ISSUE TITLE
permcheck result

### ISSUE THREAD

**Issue by DeForce** [ForgeEssentials/ForgeEssentials#1919]
Hey,

if I run permcheck for permission that doesn't exists it passes it as "success".
Is it by design or not?
ex:
permcheck czt.test.value.please.ignore
$/say check is complete

Passes

/p user CzT deny czt.test.value.please.ignore
permcheck czt.test.value.please.ignore
$/say check is complete

results in error.

Best Regards

**Comment by olee** [comment]
Yes, by design if a permission was not registered by a mod, it will return true by default.
You can also see this in the output of `/p debug`.
