### ISSUE TITLE
Plot permissions aren't working, version #60 and #65

### ISSUE THREAD

**Issue by operation404** [ForgeEssentials/ForgeEssentials#1920]
To sum up, I'm hosting a small server with friends, and one day I was notified my friend could use someone else's chest. Upon further testing, we discovered that people could break place and use anything in other people's plots. They were working on version #54, but I upgraded and on #60 is when I first noticed the issue.
I checked the permissions for each individual player group and plot, but they all appear to be correct. The plots just don't protect anything. I tried updating to #65, and the problem persists.
I haven't tried downgrading yet, I'll give it a try in a bit, but I'm completely boggled as to the source of the problem.
I have limits on plot sizes and count if that means anything.

**Comment by operation404** [comment]
Tried going back to version #54 and the issue persisted. It might be something with the config files but I couldn't spot anything odd.

**Comment by olee** [comment]
After creating plots, player first need to define what other people are allowed to do in their plots.
They should use `/plot perms chest false` and maybe `/plot perms interact false` while standing in their plot.

**Comment by operation404** [comment]
Plot permissions were set using those commands. The commands were processed and each person reported the chat feed saying the permission was changed, but no effect took place.

**Comment by Krater107a** [comment]
Excellent Plugin. I especially enjoy the forge sigh shops :)
But it seem that anyone can use "/plot delete" and delete a land claim weather owner / opped or not. I messed with a few different permission nodes and couldn't figure out how to solve the problem. I did a /p debug and it seems the /plot delete isn't checking the proper node?
