### ISSUE TITLE
Mob Zone Spawn Deny

### ISSUE THREAD

**Issue by hero887** [ForgeEssentials/ForgeEssentials#1921]
Mobs keep spawning even after I run /p global Zone <area> fe.protection.mobSpawn.natural.* Did I do something wrong? Is there a typo? Wrong command? I am referencing from here: https://github.com/ForgeEssentials/ForgeEssentials/wiki/Protection-%28world-guard%29#mob-permissions

Mobs are still spawning in the area regardless of the commands I try. What I want to do is prevent all mobs from spawning in a predefined area. I'm currently running this version of FE: forgeessentials-1.8-1.8.3.54-server

**Comment by luacs1998** [comment]
`/p global deny fe.protection.mobspawn.natural.*`

**Comment by hero887** [comment]
Ok. But wouldn't that command remove the mods from the entire world? I just want to remove them from spawning in one predefined area. Would this work? "/p zone <area> deny fe.protection.mobspawn.natural.*"

**Comment by hero887** [comment]
Ok so "/p zone deny fe.protection.mobspawn.natural.*" does not work. But this seemed to do the trick and prevent mobs from spawning in the predefined area called "spawn" "/p zone spawn deny fe.protection.mobspawn.natural.*"

**Comment by olee** [comment]
You forgot your zone name (at least in your post).
The correct snytax is `/p global zone <zone> deny fe.protection.mobspawn.natural.*`.
You can get your zone-name or ID by using `/p list zones` while standing in the area.
