### ISSUE TITLE
Help kill command not working 

### ISSUE THREAD

**Issue by superkid333** [ForgeEssentials/ForgeEssentials#1923]
I just installed Forge Essentials. I added groups like_GUEST_ and I turned off the edit wand. That is all. 

Now the kill command doesn't work, no player loses health or hunger. I checked the /god command and it's not on any player. My server is just a survival type. 

Please help

**Comment by luacs1998** [comment]
What does `/p debug` say?

**Comment by olee** [comment]
You probably just set `*=false` permission.
Don't do it if you don't know what you do.
Read the [Permission Tutorial](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial) - more exactly the chapter about [Deny-default](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial#deny-default)
