### ISSUE TITLE
Setspawn

### ISSUE THREAD

**Issue by Noobsloth** [ForgeEssentials/ForgeEssentials#1924]
It seems like setspawn doesn't save the direction the player is looking at. It'd be nice if this could be done but it's not a huge issue. (Please correct me if I'm derping on this issue.)

Thank you very much for your work,

Noobsloth

**Comment by Noobsloth** [comment]
To add, It seems as if setting a spawn per dimension does not work correctly either.

**Comment by Techjar** [comment]
I don't actually know why this command exists, /setworldspawn is already a thing in vanilla. As for the rotation, of course that doesn't work because vanilla doesn't store that.

**Comment by olee** [comment]
Actually the correct command is `/p <user|group|global> [user|group] spawn here` because spawn is a setting tied to permissions which allows it to be individual for each player / area.

As for orientation - yes, we should add that.
