### ISSUE TITLE
Issue with FE build 1090 and Hardcore Ender Expansion

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentials#1926]
When I first installed the 1090 build I began getting a crash on server startup. I dropped the crash report in the post. I was able to fix it by deleting my End dim. I just wanted to give you a heads up. I went from build 1060ish to 1090. Soon as I get my client side updated I will go back into the end to see if it replicates the issue. Hoping it just has to do with a change in code / permissions not correcting in the old end dim file.
[crash-2015-12-30_15.41.58-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/75215/crash-2015-12-30_15.41.58-server.txt)

**Comment by blkwind** [comment]
Just confirmed as soon as someone logs into the server it creates the crash again. If I roll back to the FE build  1061 the issue goes away. Took a capture of the server console during crash.
![capture](https://cloud.githubusercontent.com/assets/12201821/12059242/580c6910-af1d-11e5-9521-45bf7aa158ce.PNG)

Here is the crash log for that event.
[crash-2015-12-30_17.42.08-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/75277/crash-2015-12-30_17.42.08-server.txt)

**Comment by blkwind** [comment]
Further more, I found deleting the deminsionaltransiever.json in the enderio directory allowed players to join; however, as soon as someone does something like /spawn it causes the error again.

**Comment by blkwind** [comment]
I have started testing every FE build between earliest available version and the latest 1090 to pin point at which build changes has caused this issue.

**Comment by blkwind** [comment]
I was able to test FE builds 1081 through build 1090 and was able to pin point exactly where the crashes start happening. Builds 1081 through 1087 work great. Starting at build 1088 is where the crash starts happening. Hopefully this helps pin point the exact issue.

**Comment by olee** [comment]
Seems to be an issue with my new patch to `attackEntityFrom` event (I am actually surprised it's only the Ender Dragon that is causing a crash with this new event).
Did you test, if it works with just FE?

It could be that another mod patches the `attackEntityFrom` method from `EntityBossDragon` which makes it crash. This will need some investigation.

**Comment by olee** [comment]
I checked it and it doesn't crash without other mods.
Probably some conflicting patches - I will need to test this a bit more...

**Comment by olee** [comment]
I checked the [source code of HEE](https://github.com/chylex/Hardcore-Ender-Expansion/blob/master/src/main/java/chylex/hee/entity/boss/EntityBossDragon.java#L458-L461) and found this:
````
	@Override
	public boolean attackEntityFrom(DamageSource source, float amount){
		return false;
	}
````
It might be that my patching fails to apply source code modifications correctly on empty (return-only) functions.

**Comment by blkwind** [comment]
I tried build 1092 an it started working agian, going to try build 1096 now and see. Just being curious I also tried testing 1091 and crashes still happened.

**Comment by olee** [comment]
So it works with latest builds?

**Comment by sylphio** [comment]
i got the same error/callstack on the last build 1097. http://pastebin.com/HCdWyJpi

**Comment by spacebuilder2020** [comment]
Any update on this?

**Comment by olee** [comment]
@sylphio or @blkwind do you know if this is still an issue?
There have been a lot of changes and I think this was probably fixed as part of those.
I will close this for now but we can reopen it if the problem persists.
