### ISSUE TITLE
1.8.8+ Update/Compatibility 

### ISSUE THREAD

**Issue by hero887** [ForgeEssentials/ForgeEssentials#1927]
Would FE 1.8 work for Forge & Minecraft ver. 1.8.8+? If not, is there a release coming soon for that supports that version?

**Comment by luacs1998** [comment]
We're working on some really big things right now, after that's done I intend to start looking at 1.8.9.

**Comment by luacs1998** [comment]
Dupe of #1141 anyway, so closing.
