### ISSUE TITLE
Permissions issues regarding the new Explosion Perms

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentials#1928]
Gearing up to really make use of the explosion perms on my server and found some items that are bypassing the new permissions. All explosives from Industrialcraft , Balkon's WeaponMod, Hardcore Ender Expansion will bypass the explosion perms. I will post some captures of the debug log during one of the tests and a capture showing all of the itemperms of the items that bypass the permissions.

The blocks used in the test are minecraft.stonebrick.2 "cracked stone bricks" and the Twilightforest.tile.TFUnderbrick.2 "the Red bricks". The Red bricks shouldnt be affected by the explosion. The Cracked stone bricks should be affected by the explosion. When using normal MC tnt or other forms of explosions it functions correctly.

![brokentnt1](https://cloud.githubusercontent.com/assets/12201821/12069087/26110566-afe4-11e5-92cf-544a0539aa00.PNG)
![brokentnt2](https://cloud.githubusercontent.com/assets/12201821/12069107/e0c2fa36-afe4-11e5-8f95-66bd938e0183.PNG)
![brokentnt3](https://cloud.githubusercontent.com/assets/12201821/12069108/e3aca184-afe4-11e5-8f12-348ec198a5f3.PNG)

I restricted placement of these items on my server but I figured you may want to know.

**Comment by luacs1998** [comment]
They'd need to implement the explosion event. It's in Forge already, nothing we can do.

**Comment by olee** [comment]
Just as @luacs1998 said.
These mods for some reason do not cause any explosion event or are not using the return value of it correctly.
