### ISSUE TITLE
Server Crashing problem

### ISSUE THREAD

**Issue by MaroKoss** [ForgeEssentials/ForgeEssentials#1935]
Hi. I have a problem with Serwer, i will make a FtbInfinity serwer with your mode. I started the server on my own PC (Windows 7 and Linux Ubuntu) and everything work well but when i uploaded files on a dedicated server with Debian, crash, i tried to lunch clean forge serwer only with ForgeEssenitals and all the time that same. 
Crash report: http://pastebin.com/Fu79AemS
I'm sorry for my vary bad english.

**Comment by olee** [comment]
Update to Java 8 (or update FE to latest builds).
Still you should update to Java 8.
