### ISSUE TITLE
Jenkins artefact are no longer available!

### ISSUE THREAD

**Issue by sylphio** [ForgeEssentials/ForgeEssentials#1936]
Hi, 

  Most of the build from the jenkins can no longer be downloaded including the last stable build 1086 

Thank

http://ci.forgeessentials.com/job/FE/Stable/

**Comment by liach** [comment]
http://ci.forgeessentials.com/job/FE/

This link might be better.

**Comment by sylphio** [comment]
I put the link as a matter of convenience. Try your own link and you will see that all older build don't have any downloadable file in the status section.

**Comment by luacs1998** [comment]
We do this on purpose so that the server doesn't overload with old builds that nobody downloads (limited disk space)

If you want old releases they're available on CurseForge.

**Comment by olee** [comment]
If you need old builds for any reason, you can build them yourself from the sources or get them from CurseForge.
There should be no need for them though.

**Comment by sylphio** [comment]
Thank for the answer.  No problem for me. I already recompiled a version for myself.  This issue was just to notice you that the lastest starred / stable was already deleted.

Thank :)
