### ISSUE TITLE
Double Player entity? Probably causing issue with another mod.

### ISSUE THREAD

**Issue by Fexcraft** [ForgeEssentials/ForgeEssentials#1937]
So ye.. from observation I guess that ForgeEssentials is spawning 2 player entities for the same player (did not look into the code so I don't say stuff for sure...).

The thing is, that another Mod is saving NBT stuff into the Playerdata, so far no problem,
but, on one item when eating it, the function from it get's performed 2 times.
Hope the screenshot is selfexplaining :I (and so in end effect, the player get's unnecessarly killed)
![fe_fsu_bug](https://cloud.githubusercontent.com/assets/11726534/12121633/83156842-b3d6-11e5-8f28-efb05279b22b.PNG)

I tried it on a raw forge server without ForgeEssentials and it worked fine.
(screenshot)
![2016-01-05_18 02 05](https://cloud.githubusercontent.com/assets/11726534/12121706/042445fc-b3d7-11e5-8e80-94a2dd040711.png)

Is there any way to "fix" this?

Sorry in case posted in wrong place, but don't found own forums for this, and on curseforge is written post issues here.

**Comment by olee** [comment]
Hm this is really weird.
As long as you didn't change any permissions, FE should not change much that could cause such errors.
I will need to test this myself...
Is this item one you use instantly or where you have to hold right mouse until it is used up?

**Comment by Fexcraft** [comment]
I tried it on 2 servers, on both same error,
on one I don't remember how did I setup perms
but on the new one I did not touch anything (except adding guest rank like in wiki example),
yet same thing happens.

**Comment by olee** [comment]
So it's an item that you have to "keep" using until it is actually used up? (Like bow and food?)

**Comment by Fexcraft** [comment]
Yes, it's like food. *checkin code*
the whole code is performed in "onFoodEaten()"

The mod in case needed:
http://fexcraft.net/files/FSU/FSU-Client-0.002.jar
http://fexcraft.net/files/FSU/FSU-Common-0.027.jar

**Comment by olee** [comment]
Nice, I will try it these days - probably on the weekend.

**Comment by spacebuilder2020** [comment]
@Fexcraft Does this issue still occur in the latest 1.7.10 version or has it gone away.

**Comment by Fexcraft** [comment]
Uhm, this is years away, I stopped using 1.7.10 long ago.
And on 1.12.2 I got my own "protection" mod so I don't use anything else like FE 🤔 

On second though, I even think that mod was for 1.8;

**Comment by spacebuilder2020** [comment]
Ok, I am closing this then.  I have been going through our old issues and cleaning them up now that FE 1.12 is in Alpha.
