### ISSUE TITLE
Playerlogger is logging despite PlayerLogger=false

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentials#1939]
hey :)

one little thing: i want to disable the playerlogger and as i saw in the main.cfg, the playerlogger=false is set. In log directory there is still growing the playerlogger flatfile.

Has this config switch changed in the past ?

version is forgeessentials-1.7.10-1.4.3.1097-server.jar

many thanks!

-Jogi

**Comment by luacs1998** [comment]
What do you mean? Is the Playerlogger logging when it's not supposed to?

**Comment by olee** [comment]
Tell us the path of the file you mentioned growing in size.

**Comment by jogi01** [comment]
hi,
in minecraft/logs/PlayerActivity.log
oh i see its already 674MB big since my last post so i have to delete it now.

**Comment by luacs1998** [comment]
I don't think that file would have anything to do with FE...

**Comment by olee** [comment]
@jogi01 that file is not from FE.

**Comment by jogi01** [comment]
oh ok.. then i have to ask the mod developer team. sry!
