### ISSUE TITLE
XP to Money isn't working AND being kicked for AFK

### ISSUE THREAD

**Issue by Zeplitor** [ForgeEssentials/ForgeEssentials#1942]
These are apparently the default settings in settings.cfg. I've edited them a million times before, and they saved. They always revert back to default. Even when it says autokick is False, we still get kicked for AFK when it has never happened before. Also, I always change the value of xpmultiplier to 1, and it reverts it back to 0 so we don't have any other way to get coins in our /wallet.
````
# Configuration file

afk {

    # fe.commands.afk.autokick = false
    # Automatically kick a player, when he is AFK
    S:auto_kick=

    # fe.commands.afk.autotime = 480
    # Auto afk time in seconds. Set to 0 to disable.
    S:timeout=

    # fe.commands.afk.warmup = 10
    # Time a player needs to wait before he can go afk with /afk
    S:warmup=
}

economy {

    # fe.economy.currency = coins
    # Name of currency (plural)
    S:currency_name=

    # fe.economy.currency.singular = coin
    # Name of currency (singular)
    S:currency_name_singular=

    # fe.economy.deathtoll = 
    # Penalty for players to pay when they die. If set to lesser than 1, value is taken as a factor of the player's wallet balance.
    S:death_toll=

    # fe.economy.xpmultiplier = 0
    # XP to currency conversion rate (integer, a zombie drops around 5 XP, 0 to disable)
    S:money_per_xp=

    # fe.economy.startbudget = 100
    # Starting amount of money for players
    S:start_budget=
}
````

**Comment by olee** [comment]
You should change the settings only when the server is shut down, or you have to use `/fereload` after changing them.

Also you should know that these settings only specify default for permissions.
This means that you can still overwrite those settings by other permissions.

**Comment by Zeplitor** [comment]
/fereload doesn't seem to work on my server. I also shut down the server for a few mins to change the settings.cfg to make changes. They still reverted back.

**Comment by Zeplitor** [comment]
Apparently, upon starting the server. The settings revert.

**Comment by TerdyTheTerd** [comment]
I've had no issues with this, what version are you using? Also make sure you save the file before starting the server back up (if there's any syntax errors it will make a fresh default .cfg file and create a copy of the edited on with "errored" in the name)

**Comment by Zeplitor** [comment]
I'm using forgeessentials-1.4.3.1021 for my modded 1.7.10 server.

**Comment by Zeplitor** [comment]
Am I able to edit these with commands through the game?

**Comment by olee** [comment]
Use `/feinfo reload` instead then. 
After changing config files, you can (nearly)always use this to reload configuration

**Comment by Zeplitor** [comment]
I just used the /feinfo reload command and it just reverted the changes I made.

**Comment by Zeplitor** [comment]
Would the fact that I'm using Multicraft to edit the files have anything to do with it?

**Comment by olee** [comment]
Then I guess you are doing something wrong.
Post a copy of your config file.

**Comment by olee** [comment]
Probably...

**Comment by Zeplitor** [comment]
The "Permissions.cfg" file?

**Comment by Zeplitor** [comment]
# Configuration file

Permissions {
    # Choose a permission persistence backend (flatfile, sql, json). DO NOT use SQL, unless you really need to use it.
    S:persistenceBackend=flatfile

    SQL {
        # If this is true, settings will be taken from the parent, most probably the Main or Core config. This is only taken into effect with remote databases.
        B:checkParent=false

        #  valid types: H2_FILE, MySQL
        S:chosenType=H2_FILE

        H2_FILE {
            # this may be a file path as well.
            S:database=./ForgeEssentials/permissions
        }

        MySQL {
            S:database=ForgeEssentials
            S:host=localhost
            S:pass=password
            I:port=3306
            S:user=FEUSER
        }

    }

}

**Comment by Zeplitor** [comment]
# Configuration file

afk {
    # fe.commands.afk.autokick = false
    # Automatically kick a player, when he is AFK
    S:auto_kick=

    # fe.commands.afk.autotime = 480
    # Auto afk time in seconds. Set to 0 to disable.
    S:timeout=

    # fe.commands.afk.warmup = 10
    # Time a player needs to wait before he can go afk with /afk
    S:warmup=
}


afterlife {
    # fe.afterlife.debuffs = 
    # Potion effects to apply on respawn (comma separated list of id:duration:amplifier)
    S:respawn_debuffs=

    # fe.afterlife.food = 
    # Respawn food
    S:respawn_food=

    # fe.afterlife.hp = 
    # Respawn HP
    S:respawn_hp=
}


economy {
    # fe.economy.currency = coins
    # Name of currency (plural)
    S:currency_name=

    # fe.economy.currency.singular = coin
    # Name of currency (singular)
    S:currency_name_singular=

    # fe.economy.deathtoll = 
    # Penalty for players to pay when they die. If set to lesser than 1, value is taken as a factor of the player's wallet balance.
    S:death_toll=

    # fe.economy.xpmultiplier = 0
    # XP to currency conversion rate (integer, a zombie drops around 5 XP, 0 to disable)
    S:money_per_xp=

    # fe.economy.startbudget = 100
    # Starting amount of money for players
    S:start_budget=
}


grave {
    # fe.afterlife.deathchest.block = 
    # If set, use this block ID for graves
    S:block=

    # fe.afterlife.deathchest = true
    # Allow creation of deathchests
    S:enable=

    # fe.afterlife.deathchest.fence = true
    # Put the skull on a spike
    S:fence=

    # fe.afterlife.deathchest.xp = 0.25
    # Ratio of XP that you want to allow someone to keep in a grave. 1 keeps all XP, 0 disables XP recovery.
    S:recoverable_xp=

    # fe.afterlife.deathchest.safetime = 300
    # Time in seconds a grave is protected. After this time anyone can take all stuff
    S:safetime=
}


plots {
    # fe.economy.plot.column = true
    # If true, all plots will always extend from bottom to top of the world. Price will only depend on X and Z dimensions.
    S:columnmode=

    # fe.economy.plot.limit.count = 20
    # Maximum number of plots a player can claim
    S:limit.count=

    # fe.economy.plot.limit.size = 
    # Maximum total size of all plots a player can claim
    S:limit.size=

    # fe.economy.plot.price = 1
    # Price multiplier for plots (plot size will be multiplied with this value)
    S:price=

    # fe.economy.plot.size.max = 
    # Maximum size of one plot axis
    S:size.max=

    # fe.economy.plot.size.min = 3
    # Minimum size of one plot axis
    S:size.min=
}


teleport {
    # fe.teleport.cooldown = 5
    # Allow bypassing teleport cooldown
    S:cooldown=

    # fe.teleport.warmup = 3
    # Allow bypassing teleport warmup
    S:warmup=
}

**Comment by Zeplitor** [comment]
Sorry if I didn't post what you needed. I'm still new to this stuff.

**Comment by olee** [comment]
@Zeplitor ok I don't know what you are doing wrong so I will just write you a manual to get it working step by step:
- Method a)
  1. Start server
  2. Use the command `/fesettings economy.money_per_xp 1`
  3. If you then check `Settings.cfg` it should contain that value properly.
- Method b)
  1. Stop server
  2. Change `S:money_per_xp=` to `S:money_per_xp=1` in `Settings.cfg`
  3. Start server
- Method c)
  1. Keep server running
  2. Change `S:money_per_xp=` to `S:money_per_xp=1` in `Settings.cfg`
  3. Use the command `/feinfo reload`

I tested it myself and the setting properly persists.
