### ISSUE TITLE
How Apply Potion Affects in Zones

### ISSUE THREAD

**Issue by hero887** [ForgeEssentials/ForgeEssentials#1943]
I want to apply potion affects to players when a certain area. I have the zone set up already as "spawn". I want keep the player fed. I want to enable speed. And I want to heal the player. What commands do I need to do for that zone to make those potion affects happen (but only when in that zone)?

**Comment by TerdyTheTerd** [comment]
All the info you need is [here](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Guide-%23-Protection-(world-guard)) and [here](https://github.com/ForgeEssentials/ForgeEssentials/wiki/PermissionList.txt).
Visit [here](http://minecraft.gamepedia.com/Potion_effects#Parameters) for a list of potion parameters.

**Comment by olee** [comment]
@TerdyTheTerd JUST GREAT! :laughing: 
That really made me laugh!

But you forgot to link [here](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Protection-%28world-guard%29#zone-permissions), too :wink:
