### ISSUE TITLE
Admin can use shops but not other players (build 1.8.3.54)

### ISSUE THREAD

**Issue by hero887** [ForgeEssentials/ForgeEssentials#1945]
I set up shops and tested them. They work for me (admin), but not for other players that are in the default group. In my zone I have the fe.protection.break.*, place.* mobspawn.* etc. denied for _ALL_ (except me exclusively). Is there a reason for why the default other players cannot use the shops? Is it fe.protection.interact.* or something I missed?

**Comment by olee** [comment]
You probably missconfigured some permissions.
Check with `/p debug`.
Players need the interact-permission to be able to use shops.
Ask again here if you still cannot resolve this.
