### ISSUE TITLE
Promoting myself from _GUESTS_ to member will show a forbidden symbol

### ISSUE THREAD

**Issue by ErikSteiner** [ForgeEssentials/ForgeEssentials#1946]
I configured the permission system like it was described in the little introduction tutorial. One thing is very strange. I promoted myself from _GUESTS_ to members and I am now allowed to build, but the strange thing is, that my crosshair is a "forbidden symbol". I am allowed to break and build blocks anyway, but the symbol will only vanish on those blocks that were broken by myself and placed again.

![2016-01-12_14 38 32](https://cloud.githubusercontent.com/assets/2684018/12265525/cf3a63e6-b93d-11e5-8dbd-766aff6fb4ec.png)

**Comment by TerdyTheTerd** [comment]
Use <code>"/p debug"</code> to get info on what permissions are being checked for the group and user, and see which ones return as allow or deny, then go from there.

**Comment by ErikSteiner** [comment]
Thank you. It turned out that this is a visual bug. After I promoted myself to members I got this thing written above. When I closed the client and started it again the forbidden symbol was gone. This is however reproducable, so if you are at first a guest that is not allowed to mine or build and is then promoted to a group that is allowed, I will get this forbidden symbol. Restarting the client will solve this issue.

This is what I got with the /p debug command:
![2016-01-12_16 19 02](https://cloud.githubusercontent.com/assets/2684018/12267569/01e59116-b949-11e5-9b39-da1686d7459e.png)


Server:
Forge Server 1.7.10 - 10.13.4.1558
forgeessentials-1.7.10-1.4.3.1100-server

Client:
Forge 1558
forgeessentials-1.7.10-1.4.3.1100-client

**Comment by olee** [comment]
This is the permission overlay from the FE client. 
It should also disappear, if you just reconnect to the server after being promoted. 
I will fix this so it happens automatically.

**Comment by luacs1998** [comment]
Doesn't it already update in the tick events?

Or should a "reset" message be sent on a permission/group change event?

**Comment by ErikSteiner** [comment]
I guess that this question is not addressed to me, because I don't know what is going on during a tick event :-) To be clear, everything is working correctly as it should after promoting myself. This seems to be only a visual issue.

**Comment by olee** [comment]
@luacs1998 a reset message needs to be sent, because the client caches all deny-messages it gets.

**Comment by luacs1998** [comment]
Then I should be able to do it.
