### ISSUE TITLE
Disable Fire spreading log?!

### ISSUE THREAD

**Issue by Nightreaver** [ForgeEssentials/ForgeEssentials#1953]
Hello

I searched for a way to disable logging of 

CONSOLE: thread/INFO] [STDOUT]: [net.minecraft.block.BlockFire:func_149674_a:52]: Injector: Fire spreading to other block from .... to ...

spam

Its about 30 lines per second, and really sucks.
How can i get rid of it?

**Comment by Nightreaver** [comment]
Thank you! :)

**Comment by olee** [comment]
Sorry, forgot to remove those debug messages

**Comment by Nightreaver** [comment]
no problem... its fixed :)
