### ISSUE TITLE
Area created with WoldEdit plugin is always 1 block size at [0,0,0]

### ISSUE THREAD

**Issue by ArtyomShegeda** [ForgeEssentials/ForgeEssentials#1954]
**Minecraft version:** 1.7.10 Forge 1614
**Essentials version:** 1.4.4.1114
**WorldEdit version:** worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar
**No other mods installed on the server.**
**Actions made:**
//wand
LB-click at -33, 64, 268
RB-click at -36, 64, 268
/area define test
/area info test
**Result seen:**
Area "test"
start = [0,0,0]
end = [0,0,0]

![image](https://cloud.githubusercontent.com/assets/630657/12368307/e2786766-bbf2-11e5-9503-ae3120bf9594.png)

**Comment by luacs1998** [comment]
Have you tried defining an area that's not 1 by X by 1 (where X is a number)

**Comment by olee** [comment]
Does it work correctly now with latest version?
