### ISSUE TITLE
FEPregen messages spam

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentials#1957]
Hi, is there any way to suppress the pregen spam to the clients and console? A way to limit those would be very useful. Like _OPS_ only or console only and once per X seconds maybe?

While I'm at it, if I try "/fepregen start auto 0" it fails. The speed setting as in [number|auto] is not clear in it's purpose. What does that speed number stands for in relation to the CPU? Is it per core or all cores together? Is in percentage?

**Comment by luacs1998** [comment]
Define "pregen spam"?

**Comment by olee** [comment]
Only players with the pregen permission see those messages.
Deny that permission for _OPS_ group and just give it to yourself (or use server console) and you won't be bothered any more.

**Comment by Zethalion** [comment]
Thanks!

But still, I wonder what the speed number stands for. If I put in 0 it works, but slowly. 
1 And higher, it locks up. The CPU won't be heavily used either. Putting auto generates an error.

In this example it fails: /fepregen start auto 0
Invalid number: auto

In this example the server locks up with in seconds: /fepregen start 1 0
No crash and no disk activity writing region files.
