### ISSUE TITLE
Worldedit crash with microblocks

### ISSUE THREAD

**Issue by Sastas** [ForgeEssentials/ForgeEssentials#1960]
If I use copy-paste in worldedit, the microblocks(which cut with a saw in forgemicrobolcks) Looks like not copied. And If I try to replace them, with hand, the server crushes with internal server error. After a server-restart I can replace them with hand.

The building what I try to copy is on the pic. The resoult the building a bit away(there are couple of blocks on it,  we place for measure). 
![screenshot 2016-01-17 21 41 50](https://cloud.githubusercontent.com/assets/16676227/12379856/6e0d2ed0-bd63-11e5-99bb-2ed1e9deeacd.png)

And a logfile from the crash. 
[consolelog.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/93601/consolelog.txt)

There are other bugs with the worldedit, Should I made a new topic for it?

**Comment by olee** [comment]
Not our problem -> https://github.com/Chicken-Bones/ForgeMultipart/issues/345
