### ISSUE TITLE
Interact perms on HarvestCraft crops don't seem to work as I thought they would

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentials#1966]
I have a group where they do not have permissions to interact with a harvestcraft crop on right click.

Harvestcraft allows players to right click a crop to harvest the produce, without breaking the crop block (requiring reseeding).

When my group right clicks the mature crop, /p debug shows that they do not have perms to do it, but the crop still transforms from meta:7 to meta:0 and drops the produce.

**Comment by olee** [comment]
The correct solution would be to contact the mod dev and make him fire the correct interact event.

**Comment by PitchBright** [comment]
I filed an issued on PHC git, although I'm not sure she checks her git issues.

I think I found the spot where the right-click takes place:
https://github.com/MatrexsVigil/harvestcraft/blob/master/java/com/pam/harvestcraft/BlockPamCrop.java#L67
