### ISSUE TITLE
banning items for global

### ISSUE THREAD

**Issue by scootashy** [ForgeEssentials/ForgeEssentials#1967]
i tried banning items like tnt and that in global and tested in groups but they can still be placed used and appear in the zone and inventories i tried the fe.protection.exist false in commands using deny and it shows it added and all but it doesnt seem to do anything same with fe.protection.damageto.wolf for example that would deny hitting certain mobs but this also doesnt work. and i cant find no clear tut on the commands to use to do that if it is that causing it or something else. This is what shows up in my global _ALL_ file after doing the commands

#Permissions for group _ALL_
#DO NOT MODIFY OR REMOVE fe.internal PERMISSIONS UNLESS YOU KNOW WHAT YOU DO!
#After you modified permissions in this file, remember to directly run "/feperm reload", or the changes get overwritten next time permissions are saved by the server.
#Fri Jan 22 13:14:19 PST 2016
fe.internal.group=false
fe.internal.group.name=players
fe.internal.group.priority=0
fe.protection.damageto.wolf=false
fe.protection.exist.tnt=false
fe.protection.exist.tnt.46=false
fe.protection.fire.destroy,=false
fe.protection.fire.spread=false
fe.remote.chat.send=false
some.test.permission=true

**Comment by scootashy** [comment]
I also tried /p global deny fe.protection.inventory.animalbikes.reindeerbike.* to test on the reindeerbike it still stayed in inventory so i tried it on the group members and tested the group out still remained same with fe.protection.exist.animalbikes.reindeerbike.* it still wont get destroyed and remains in inventory same with tnt and the item tnt_minecart.

**Comment by olee** [comment]
OK there are quite some mistakes in those permissions:
 -  `fe.protection.exist.tnt=false` is wrong - it should be something like `fe.protection.exist.minecraft.tnt=false`
 -  Check the PermissionList.txt for details on permissions
 -  Use `/p debug` to actually see what permissions are checked 
 - `exist` permissions are only checked under certain conditions (picking up an item, going to another zone,  joining the server, etc.)  
  Just changing the permission won't directly remove items from your inventory 

Ask again if you need more help, but please read the tutorials on the wiki an check your PermissionList.txt first.
