### ISSUE TITLE
Teleporting from End(DIM1) results in target world not rendering

### ISSUE THREAD

**Issue by ruphskunk** [ForgeEssentials/ForgeEssentials#1968]
Leaving the End via portal works fine.
Leaving the End via teleport(/spawn, /back, /warp) takes you to the location intended, but the world does not render. All sky.

Problem does not manifest when FE is disabled.
Last version tested 1133
forgeVersion: 1558
mcVersion: 1.7.10
FTBInfinity 2.3.5

No error messages.

**Comment by luacs1998** [comment]
I am also facing this issue as well - made debugging that end-portal issue rather troublesome :D

**Comment by olee** [comment]
We need to check our teleport code >_<

**Comment by olee** [comment]
Wow ... this is actually a kinda bug in Minecraft itself -.-'
There is some code that refuses to properly teleport the player if he originates from dimension 0.
Damn shitty MC code.
