### ISSUE TITLE
Build 1134 crashes with NPE

### ISSUE THREAD

**Issue by ruphskunk** [ForgeEssentials/ForgeEssentials#1969]
java.lang.NullPointerException: Exception in server tick loop

http://pastebin.com/VbnPGFfr

Crash happens during startup.

**Comment by olee** [comment]
Your permission storage seems to be broken, which causes the area to be `null`.
Can you please tell me the value of the setting `persistenceBackend` in `Permissions.cfg`?

**Comment by ruphskunk** [comment]
S:persistenceBackend=singlejson

**Comment by olee** [comment]
Can you please pastebin me the `./FEData/permissions.json` file?

**Comment by ruphskunk** [comment]
http://pastebin.com/ZPbQQMjr

**Comment by olee** [comment]
This is a bug I caused with new permission backend.
Will be fixed quickly.
