### ISSUE TITLE
Unable to buy or sell plots - Invalid Command Occurs?

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1971]
Using version forgeessentials-1.4.4.1134

**Comment by luacs1998** [comment]
What's the exact syntax you're using?

**Comment by DPxKnightxZero** [comment]
//wand

Right click and one spot move a bit a way then Left click another area

/plot claim 

An unknown error has occured while attempting to perform this command
![2016-01-23_19 54 19](https://cloud.githubusercontent.com/assets/10351221/12533989/4570b2a6-c20b-11e5-84ce-bcce71d44caf.png)

**Comment by luacs1998** [comment]
Server log?

**Comment by DPxKnightxZero** [comment]
Okay
[DEBUG INFO!.zip](https://github.com/ForgeEssentials/ForgeEssentials/files/102121/DEBUG.INFO.zip)

**Comment by olee** [comment]
@DPxKnightxZero it seems you sent the wrong log - I could not find any place where you used `/plot` in there. Be sure to set `B:logCommands=true` in main.cfg and test it again.

**Comment by olee** [comment]
This is caused by #1971.
Will be fixed together with that issue.

**Comment by olee** [comment]
This is caused by #1969.
Will be fixed together with that issue.
