### ISSUE TITLE
Fails to load during preload

### ISSUE THREAD

**Issue by unknowjondoe** [ForgeEssentials/ForgeEssentials#1973]
I am new to this mod but every time I try to load it my server spits out the same issue and then crashes. Here is the part of the log from the loading of FE and the crash.

3:44:53 PM CONSOLE: [FML]: Forge Mod Loader version 11.14.4.1563 for Minecraft 1.8 loading
3:44:53 PM CONSOLE: [FML]: Java is OpenJDK 64-Bit Server VM, version 1.6.0_37, running on Linux:amd64:3.13.0-74-generic, installed at /usr/lib/jvm/java-6-openjdk-amd64/jre
3:44:53 PM CONSOLE: [FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.8-1.8.3.54-server.jar
3:44:53 PM CONSOLE: [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
3:44:53 PM CONSOLE: [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
3:44:53 PM CONSOLE: occurred running the Server launcher.
3:44:53 PM CONSOLE: [STDERR]: [java.lang.Throwable:printStackTrace:478]: java.lang.reflect.InvocationTargetException

**Comment by unknowjondoe** [comment]
I should also mention I am running Minecraft version 1.8.9

**Comment by olee** [comment]
Wow... you gave the answer why it doesn't run yourself.
There's nothing left to say for me.

**Comment by unknowjondoe** [comment]
Then can you explain it to me? Because I seem to be missing something.

**Comment by luacs1998** [comment]
FE 1.8 is not compatible with MC 1.8.9.

**Comment by unknowjondoe** [comment]
You might need to post somewhere that it is incompatible because I spent 3 hours working with it before I posted here and this is the first I am hearing it doesn't work with 1.8.

**Comment by unknowjondoe** [comment]
Oh and Olee please be nicer to people you don't know. Most mods I have worked with work with newer versions then their version number. And since your site says NOTHING ABOUT IT I had no way of knowing. Oh and since your Wiki Troubleshooting link is broken I had no way to know if I was doing something wrong off the bat. Sorry I didn't realize your mod wasn't forward capable.

Please realize that most people trying to set up servers are people who are learning most of these things for the first time. And if you act like an ass to them we have the possibility of scaring away future developers and system engineers. Next time take the 5 minutes to be a decent person and explain what they missed.

-From a fellow coder and technology professional

**Comment by PitchBright** [comment]
Yeah Olee. Don't be such a dick.

**Comment by luacs1998** [comment]
Most mods are not FE.

We have so many tendrils in the minecraft code that as much as I'd like to, I can't guarantee compatibility between versions.

Yes, this is my fault, I didn't say so.

**Comment by PitchBright** [comment]
No for real @unknowjondoe … if this is your first time settin' up a server and messin' around with Minecraft… ForgeEssentials might be a bit too steep for you to be gettin' your feet wet on. Try just basic server setup… spend some time lookin' around how mods are versioned and labelled… get familiar with the way things are done. Then when you get back here you'll come at it a lot stronger.

Also… you're running Java 6… and I'm not sure that's the greatest idea. It's ancient. Like Noah's Ark ancient.

**Comment by luacs1998** [comment]
PS. If you think olee's a dick, you have not seen my true form yet.

And FE will crash with Java 6 - that's probably another reason why you can't start the server. Thanks PitchBright for pointing that out.

**Comment by unknowjondoe** [comment]
I am running 6 because it is on a Ubuntu 12.04 virtual machine. I was debating on moving it to Windows just so Java runs better but since it is just a test server I figured Ubuntu is easier to refry if needed.

I used to run a bukkit server for 2 year but shut it down about 2 years ago and coming back to servers with no bukkit I had to pick either Forge or Spigot and I am more familiar with forge because of modpack making.

Thanks for the help. Hope the mod gets updated soon.

**Comment by luacs1998** [comment]
Ubuntu 14.04 is already out if you want LTS... And 16.04 is expected in a while.

Why not update the VM?

**Comment by unknowjondoe** [comment]
I use 12.04 because it is less processor intensive. Grated I would use 11 if it was still usable. Since it is a test server I didn't want to give it a ton of resources. I might switch to Ubuntu Mate I am not one to give up a GUI on a server.

**Comment by olee** [comment]
Yeah sorry - that was not meant in a mean way but more the funny way.
Because at first I read your initial post and thought "What could be wrong here?" and then had to laugh when your second post was litterally the answer.

Though who knows if FE might actually work with 1.8.9 if you at least use Java 7 - FE will not run on Java 6. This is actually quite nice - Sponge for example requires even Java 8.

**Comment by luacs1998** [comment]
The client definitely won't - quite a lot of rendering code was broken between 1.8.0 and 1.8.9.

There may be some other issues as well - you can see what I had to change in [this commit](https://github.com/ForgeEssentials/ForgeEssentials/commit/bfc9c83f527e3273202e568330450cbec7cb08dd).
