### ISSUE TITLE
Auth Module

### ISSUE THREAD

**Issue by rufo123** [ForgeEssentials/ForgeEssentials#1975]
The Auth Module on my server isn't working. When i join server i can do thing whitout logging or registering.

**Comment by luacs1998** [comment]
You have to turn it on in the config.

`B:forceEnable=true`

**Comment by rufo123** [comment]
It is! 
# Configuration file

##########################################################################################################
# Auth
#--------------------------------------------------------------------------------------------------------#
# AuthModule configuration
##########################################################################################################

Auth {
    # Allow players with the FEClient and the correct keys to automatically identify themselves with the auth engine.
    B:allowAutoLogin=false

    # Allows people to register usernames while server is offline. Don't allow this for primarily Online servers.
    B:allowOfflineReg=true

    # Enable the authentication service automatically if Minecraft auth services are not available
    B:autoEnable=true

    # Allow players not registered/not logged in with the authentication service to move in the world.
    B:canMoveWithoutLogin=false

    # Interval to check Vanilla Auth service in minutes.
    I:checkInterval=10

    # Encryption standard to use. Note that changing this will invalidate all passwords. Accepts the following: SHA1, SHA-256, MD5
    S:encryptionAlgorithm=SHA1

    # Forces the authentication server to be loaded regardless of Minecraft auth services
    B:forceEnable=true

    # The salt to be used when hashing passwords
    S:salt=z]u~3Hg.8[U
}

**Comment by olee** [comment]
@rufo123 we need some more information:
What do you mean with "When i join server i can do thing whitout logging or registering"?
Please give a detailed explanation of what you did and what happened.

**Comment by rufo123** [comment]
So the thing is: When I join server. Auth doesn't want from me to register or logging in. So in my server with offline mode, people can join with someone else account.

**Comment by olee** [comment]
Then you didn't enable Auth for some reason.
I can only recommend you to check all settings again.
Also check that it is enabled in `main.cfg`!

**Comment by rufo123** [comment]
I also checked the main.cfg but the problem is still there. :(

# Configuration file

##########################################################################################################
# Core
#--------------------------------------------------------------------------------------------------------#
# Configure ForgeEssentials Core.
##########################################################################################################

Core {
    # For modules that support it, place their configs in this file.
    B:canonicalConfigs=false

    # Add custom messages here that will appear when /help is run
    S:custom_help <
     >

    # Activates developer debug mode. Spams your FML logs.
    B:debug=false

    # Date-only format
    S:format_date=yyyy-MM-dd

    # Date and time format
    S:format_date_time=dd.MM HH:mm

    # Date and time format with seconds
    S:format_date_time_seconds=dd.MM HH:mm:ss

    # Time-only format with seconds
    S:format_time=HH:mm

    # Hide WorldEdit commands from /help and only show them in //help command
    B:hide_worldedit_help=true

    # Log commands to console
    B:logCommands=false

    # Specify the file where the modlist will be written to. This path is relative to the ForgeEssentials folder.
    S:modlistLocation=modlist.txt

    # Activates safe mode with will ignore some errors which would normally crash the game. Please only enable this after being instructed to do so by FE team in response to an issue on GitHub!
    B:safeMode=false

    # Check for newer versions of ForgeEssentials on load?
    B:versionCheck=true

    ##########################################################################################################
    # Modules
    #--------------------------------------------------------------------------------------------------------#
    # Enable/disable modules here.
    ##########################################################################################################

    Modules {
        B:Afterlife=false
        B:AuthLogin=true
        B:Backups=false
        B:Chat=true
        B:Commands=true
        B:Economy=true
        B:Multiworld=false
        B:PlayerLogger=true
        B:Remote=true
        B:Scripting=true
        B:ServerVote=false
        B:SignTools=true
        B:Teleport=true
        B:Tickets=true
        B:WEIntegrationTools=true
        B:WorldBorder=true
        B:factions=false
        B:mapper=true
        B:perftools=false
    }

    Misc {
        # Check if a player's name contains spaces (can gum up some things in FE)
        B:CheckSpacesInNames=true

        # Once this percent of player sleeps, allow the night to pass
        I:MajoritySleepThreshold=50
    }

    ##########################################################################################################
    # Output
    #--------------------------------------------------------------------------------------------------------#
    # This controls the colors of the various chats output by ForgeEssentials.
    # Valid output colors are as follows:
    # aqua, black, blue, dark_aqua, dark_blue, dark_gray, dark_green, dark_purple, dark_red
    # gold, gray, green, light_purple, red, white, yellow
    ##########################################################################################################

    Output {
        # Defaults to green.
        S:confirmationColor=green

        # Defaults to red.
        S:errorOutputColor=red

        # Defaults to aqua.
        S:notificationOutputColor=aqua

        # Defaults to yellow.
        S:warningOutputColor=yellow
    }

}


ItemPermissions {
    # Enable the item permission manager
    B:enabled=false
}


PermissionScheduler {
    # Enable the permission scheduler which can toggle permissions based on game / server time
    B:enabled=false
}


Where else can be the problem? :(

**Comment by rufo123** [comment]
Also is the module folder supposed to be clean?

**Comment by Fighter777** [comment]
hello, same issu for me

i can register / login (/auth register | /auth login)
but i can move and use the character without login

i have try with a new install with and without mod

the 1021 version is ok but crash with the last cofh core, with 1446, no crash but no auth function

[15:03:13] [Server thread/INFO] [ForgeEssentials]: Player "Fighter" used command "/auth "
[15:03:23] [Server thread/INFO] [ForgeEssentials]: Player "Fighter" used command "/auth login"
[15:03:29] [Server thread/INFO] [ForgeEssentials]: Player "Fighter" used command "/auth help"

`Auth {
    # Allow players with the FEClient and the correct keys to automatically identify themselves with the auth engine.
    B:allowAutoLogin=false

    # Allows people to register usernames while server is offline. Don't allow this for primarily Online servers.
    B:allowOfflineReg=true

    # Enable the authentication service automatically if Minecraft auth services are not available
    B:autoEnable=true

    # Allow players not registered/not logged in with the authentication service to move in the world.
    B:canMoveWithoutLogin=false

    # Interval to check Vanilla Auth service in minutes.
    I:checkInterval=10

    # Encryption standard to use. Note that changing this will invalidate all passwords. Accepts the following: SHA1, SHA-256, MD5
    S:encryptionAlgorithm=SHA1

    # Forces the authentication server to be loaded regardless of Minecraft auth services
    B:forceEnable=true

    # The salt to be used when hashing passwords
    S:salt=7l_<f{
}`

`    Modules {
        B:Afterlife=false
        B:AuthLogin=true
        B:Backups=false
        B:Chat=true
        B:Commands=true
        B:Economy=false
        B:Multiworld=true
        B:PlayerLogger=false
        B:Remote=false
        B:Scripting=false
        B:ServerVote=false
        B:SignTools=false
        B:Teleport=true
        B:Tickets=false
        B:WEIntegrationTools=true
        B:WorldBorder=true
        B:factions=false
        B:mapper=false
        B:perftools=false
    }`

**Comment by Fighter777** [comment]
hello, same issu for me

i can register / login (/auth register | /auth login)
but i can move and use the character without login

i have try with a new install with and without mod

the 1021 version is ok but crash with the last cofh core, with 1446, no crash but no auth function

[15:03:13] [Server thread/INFO] [ForgeEssentials]: Player "Fighter" used command "/auth "
[15:03:23] [Server thread/INFO] [ForgeEssentials]: Player "Fighter" used command "/auth login"
[15:03:29] [Server thread/INFO] [ForgeEssentials]: Player "Fighter" used command "/auth help"

Auth {
    # Allow players with the FEClient and the correct keys to automatically identify themselves with the auth engine.
    B:allowAutoLogin=false

    # Allows people to register usernames while server is offline. Don't allow this for primarily Online servers.
    B:allowOfflineReg=true

    # Enable the authentication service automatically if Minecraft auth services are not available
    B:autoEnable=true

    # Allow players not registered/not logged in with the authentication service to move in the world.
    B:canMoveWithoutLogin=false

    # Interval to check Vanilla Auth service in minutes.
    I:checkInterval=10

    # Encryption standard to use. Note that changing this will invalidate all passwords. Accepts the following: SHA1, SHA-256, MD5
    S:encryptionAlgorithm=SHA1

    # Forces the authentication server to be loaded regardless of Minecraft auth services
    B:forceEnable=true

    # The salt to be used when hashing passwords
    S:salt=X_Z_
}
Modules {
        B:Afterlife=false
        B:AuthLogin=true
        B:Backups=false
        B:Chat=true
        B:Commands=true
        B:Economy=false
        B:Multiworld=true
        B:PlayerLogger=false
        B:Remote=false
        B:Scripting=false
        B:ServerVote=false
        B:SignTools=false
        B:Teleport=true
        B:Tickets=false
        B:WEIntegrationTools=true
        B:WorldBorder=true
        B:factions=false
        B:mapper=false
        B:perftools=false
    }

**Comment by gilbertobitt** [comment]
same error here! with version forgeessentials-1.7.10-1.4.4.1146-server.jar

**Comment by Pordy** [comment]
Greetings! 
I experience the same issue.
I recently builded up my own modpack, and i carefully checked all the settings related to "auth" module. I am using forgeessentials-1.7.10-1.4.4.1159-server.jar currently.
I even tried to copy the forgeessentials-1.7.10-1.4.3.1021-server config folder to my new pack, but still, the joining players doesnt forced to use /auth register or /auth login commands.
How can i help you providing more information? (This is my first github issue report) 
There is no crash, or something valuable in the logs, but i can compress my modpack and upload to dropbox if you want it.

**Comment by AnrDaemon** [comment]
If client has FE client mod installed, autologin is used even if server configuration forbids it.
```
Auth {
    B:forceEnable=true
    B:allowAutoLogin=false
}
```
I register with server console, then login via client once, and it remembers password until I clear the FEAuthStore.
Server's `B:allowAutoLogin=false` setting is not in effect, it seems.

**Comment by AnrDaemon** [comment]
Obligatory @spacebuilder2020  summon!

**Comment by spacebuilder2020** [comment]
@rufo123 Has this issue been resolved?

**Comment by Zethalion** [comment]
Closing as it functions in 1.12.2
