### ISSUE TITLE
Request: Add argument 'zero' to subcommand /wb center

### ISSUE THREAD

**Issue by ruphskunk** [ForgeEssentials/ForgeEssentials#1976]
Add ability to set worldborder center to 0x 0z, perhaps by arg 'zero', or something.

Places like nether make using 'here' to set center to 0x 0z inconvenient.

**Comment by luacs1998** [comment]
I'm playing with the idea of retooling worldborder in 1.8.9.

MC already has theirs and I'm quite uncomfortable with having two worldborder systems together.
