### ISSUE TITLE
Request: add [dim] option to all worldborder commands

### ISSUE THREAD

**Issue by ruphskunk** [ForgeEssentials/ForgeEssentials#1977]
Would like to be able to not have to teleport to target dim just to set worldborder for it.
Also should be able to execute from console and/or script.

**Comment by olee** [comment]
You can directly edit the config files for that and do `/feinfo reload` after that
.Worldborder is something to setup statically so we even thought of not adding a command at all...
I don't think we need to especially add this which will make the syntax of the command just more complicated.
What do you think @luacs1998?

**Comment by ruphskunk** [comment]
I can live with directly editing the config files. As long as I can generate at least one, then I can copy it. I do not need [dim] arg to generate one world border.
