### ISSUE TITLE
Crash when grave drops items

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1979]
http://pastebin.com/Uu2BKW6X

@Drethic did you perhaps change the `fe.afterlife.deathchest.block` setting?

**Comment by Drethic** [comment]
@olee, No when I upgraded I removed all the configurations and let the server rebuild them.

Here is the grave block out of Settings.cfg:
```
grave {
    # fe.afterlife.deathchest.block = 
    # If set, use this block ID for graves
    S:block=

    # fe.afterlife.deathchest = true
    # Allow creation of deathchests
    S:enable=

    # fe.afterlife.deathchest.fence = true
    # Put the skull on a spike
    S:fence=

    # fe.afterlife.deathchest.xp = 0.25
    # Ratio of XP that you want to allow someone to keep in a grave. 1 keeps all XP, 0 disables XP recovery.
    S:recoverable_xp=

    # fe.afterlife.deathchest.safetime = 300
    # Time in seconds a grave is protected. After this time anyone can take all stuff
    S:safetime=
}
```
Here is the change I made in main.cfg
```
# Once this percent of player sleeps, allow the night to pass
I:MajoritySleepThreshold=10
```
And this is the change I made in Chat.cfg
```
# Interval in seconds. 0 to disable
I:inverval=0
```

**Comment by olee** [comment]
Does it work with newest build now?

**Comment by Drethic** [comment]
I've updated to 1.4.4.1146 and with the Grave folder empty it worked, and I found the grave file in a world backup, restored that and it worked.  Thank you for the quick response to this issue!
