### ISSUE TITLE
@a argument not supported

### ISSUE THREAD

**Issue by macman73** [ForgeEssentials/ForgeEssentials#1982]
Hello guys I am creating some simple scripts for voting links etc I want to use tellraw command in the script but I seem to have an issue using @a in the script, I did notice that @a is not in the list of arguments. @p works just fine.

Script
```
$/tellraw @a {text:"CLICK HERE TO VOTE",color:red,bold:true,underlined:true,clickEvent:{action:open_url,value:"https://goo.gl/M6JSDQ"}}
```
Console output below
```
[12:31:53] [Server thread/ERROR] [ForgeEssentials]: Error in script "player.txt": Unknown argument modifier "a"
```

**Comment by luacs1998** [comment]
We don't support the @a argument for now.

**Comment by olee** [comment]
@macman73 this is because in scripts you don't use those Minecraft `@` arguments.
These work completely different and wouldn't exactly work in scripts.
See the wiki page about [Script Arguments](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Script-Arguments) for more information.
