### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by darkdata** [ForgeEssentials/ForgeEssentials#1984]
with the new update from team cofh  ForgeEssentials now crashes on start im using forgeessentials-1.7.10-1.4.3.1021
[fml-server-latest.zip](https://github.com/ForgeEssentials/ForgeEssentials/files/107279/fml-server-latest.zip)

**Comment by Robijnvogel** [comment]
I can confirm. And I know how to use pastebin. :)
http://pastebin.com/k5rHDshD

**Comment by Robijnvogel** [comment]
And I can confirm that this was fixed by the FE release earlier today.
