### ISSUE TITLE
Server Stuck, Permission reset

### ISSUE THREAD

**Issue by mblob** [ForgeEssentials/ForgeEssentials#1985]
hi, 
So things were going smoothly till i start playing with permissions.

Then problems start occuring after a couple of hours or so.

Client trying to connect get a timeout message, but are still online when checkin server status through client interface. Client cant connect anymore.

Server side command-line get unresponsive to input. Then we got a message like
Can't keep up! Did the system time change, or is the server overloaded? Running 1900245ms behind, skipping 38004 tick(s)
after tht, client get effectively disconnected server side, command-line return to operationnal state.
after issuing a /stop command tons of errors (cf crash-log)
During the whole process cpu usage is ok.

A couple of other bugs.
When permission file format was set to json, file were written correctly but i couldnt get any permission info through command-line.
When permission file format was set to flat file write and read was ok.

After the crash permissions files get deleted, and default configuration get restored.
Many blocks are in unnormal status :+1: 
some pistons become transparent with unknown item title 
multiblocks get affected too all railcraft multiblocks needs to get one block broken then replaced to make them work again.

Server  is running under
Linux oedipe 4.1.12-gentoo-xxxx-ipv6-64 #3 SMP Thu Jan 21 13:45:05 CET 2016 x86_64 Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz GenuineIntel GNU/Linux
32Gigs of Ram

I maybe do something wrong. 
Sorry for my english.

[main.cfg.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/108181/main.cfg.txt)
[fml-server-3.log.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/108161/fml-server-3.log.txt)
[crash-2016-01-28_03.40.20-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/108162/crash-2016-01-28_03.40.20-server.txt)
[FEData.zip](https://github.com/ForgeEssentials/ForgeEssentials/files/108170/FEData.zip)

**Comment by spacebuilder2020** [comment]
Did you ever solve your problem?

**Comment by mblob** [comment]
I moved on Sponge :)

**Comment by spacebuilder2020** [comment]
ok
