### ISSUE TITLE
/portal bugged?

### ISSUE THREAD

**Issue by PRavenhold** [ForgeEssentials/ForgeEssentials#1993]
I've tried to use /portal to create a portal to end ive used //fepos1 and //fepos2
then  /portal create TheEnd noframe 100 50 0 1

now to the fun part.. IF the server has rebooted then it works to step trough the portal ONCE!
after that the server prints "Error Teleporting player, Target world is null" 

why does it become null after you have used the portal? 

I have 2 other portals  one that leads to a multiworld and one that leads to nether and those we can use as much as we want.. its just the END portal that stops working after 1 use.. is it a /portal bug or something else?

**Comment by PRavenhold** [comment]
at this time /mwtp end @p 100 50 0  displays the message couldnt find the world end

**Comment by PRavenhold** [comment]
The same happens with /mwtp  only works once after server restart and after that it cant find the world end

**Comment by PRavenhold** [comment]
but nether still works, and a mining world

**Comment by TerdyTheTerd** [comment]
I know the end dimension doesn't stay loaded, usually if you try to use commands to teleport into a dimension that isn't loaded it gives the null or empty world message. I know in my server unless I have at least one chunk loader in the end I can't /tp or /warp there

**Comment by PRavenhold** [comment]
well i can enhanced charm of dislocation there without a problem..

normal end portal works every time.. so why not /portal and mwtp?¨
but ill try a chunkloader..

**Comment by PRavenhold** [comment]
/tpx @p 1 0 50 0 works apparently..

**Comment by olee** [comment]
This is a bug in Multiworld. 
Only solution right now is to put a small chunk loader in the Multiworld. 
See #1751
