### ISSUE TITLE
/ticket del 1   gives an error

### ISSUE THREAD

**Issue by PRavenhold** [ForgeEssentials/ForgeEssentials#1995]
there is only one ticket with ticket id 1 on my server. which i put there as a reminder.. 
/ticket view 1 works fine... 
/ticket del 1   says 1 is a to big number and that 0 is the biggest there is.. 
try /ticket del 0 and it says ticket id 0 has been deleted.. 
/ticket list and no changes at all.. 
so to me it seems like a small index bug in the del subcommand

**Comment by luacs1998** [comment]
Can you give me screenshots?
