### ISSUE TITLE
Setting a Worldborder will only give a server error

### ISSUE THREAD

**Issue by ErikSteiner** [ForgeEssentials/ForgeEssentials#1996]
I tried to activate WorldBorder in the Overworld with /wb enable:

- ForgeEssentials: forgeessentials-1.7.10-1.4.4.1146
- Forge Version: 1558

Client: An unknown error occurred while attempting to perform this command.

Server:
`10.02.2016 11:20:08 [ERROR] Couldn't process command: 'wb enable'
10.02.2016 11:20:08 java.lang.NullPointerException
10.02.2016 11:20:08 at com.forgeessentials.worldborder.WorldBorder.save(WorldBorder.java:176) ~[WorldBorder.class:?]
10.02.2016 11:20:08 at com.forgeessentials.worldborder.CommandWorldBorder.parse(CommandWorldBorder.java:91) ~[CommandWorldBorder.class:?]
10.02.2016 11:20:08 at com.forgeessentials.core.commands.ParserCommandBase.func_71515_b(ParserCommandBase.java:20) ~[ParserCommandBase.class:?]
10.02.2016 11:20:08 at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
10.02.2016 11:20:08 at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
10.02.2016 11:20:08 at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
10.02.2016 11:20:08 at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
10.02.2016 11:20:08 at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
10.02.2016 11:20:08 at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
10.02.2016 11:20:08 at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
10.02.2016 11:20:08 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
10.02.2016 11:20:08 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
10.02.2016 11:20:08 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
10.02.2016 11:20:08 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
10.02.2016 11:20:08 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

I also uploaded the output to pastebin, because it is better sorted: http://pastebin.com/6RmMJ5Jk

I am wondering if the WorldBorder module is actually working, because the Wiki says something about a WorldBorder folder, but that doesn't exist.

**Comment by damonmensch** [comment]
I am also getting this same issue.

error message: http://pastebin.com/0mtebc5Q
mod list: http://pastebin.com/q0Z9N97B

**Comment by damonmensch** [comment]
I have tested it and the bug has been resolved.

**Comment by HeberonYT** [comment]
How to solve the problem?
How do I download the modified files?
Please help

**Comment by spacebuilder2020** [comment]
Go here http://ci.forgeessentials.com/job/FE/ to get the latest Jenkins builds

**Comment by HeberonYT** [comment]
Thank you for responding, I downloaded the FE version 1.4.4.1182 and if it works, thanks
