### ISSUE TITLE
Crash on server stop

### ISSUE THREAD

**Issue by CageU** [ForgeEssentials/ForgeEssentials#1997]
When I stop my server I get this crash. If I disable the Afterlife module the crash goes away.
Let me know if there is any other info I could provide that would be helpful in troubleshooting this.
I am using the latest version of the Forge Essentials mod for 1.7.10, 1.4.4.1146.

[crash-2016-02-10_13.14.14-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/125565/crash-2016-02-10_13.14.14-server.txt)

**Comment by luacs1998** [comment]
Grave issue, same as #2034 - if it doesn't fix itself, delete all files in world/FEData/json/Grave.
