### ISSUE TITLE
command register and login

### ISSUE THREAD

**Issue by ciula96** [ForgeEssentials/ForgeEssentials#1998]
why i haven't auth folder and in game i can't use command /register login?
how I can register and login in server?

**Comment by luacs1998** [comment]
Make sure auth-module is on.

If you can't find the folder, try looking for a file called AuthLogin.cfg.

**Comment by gilbertobitt** [comment]
and please the is another error regarding authModule with your is the same please see this!
https://github.com/ForgeEssentials/ForgeEssentials/issues/1975
