### ISSUE TITLE
Items do not stack after death

### ISSUE THREAD

**Issue by AryuSyrius** [ForgeEssentials/ForgeEssentials#1999]
It appears that items are being NBT tagged by with WITCPriIncUsr upon death and once retrieved from the gravestone. This is causing items not to stack.

Attached is a screenshot of the tags in NBtExplorer. These are two of the same item one with the tag and another without. The one retrieved from the gravestone is the one with the tag. In this case the two items are Nether Redstone ore, but this happens with any item.

![ctm97ts](https://cloud.githubusercontent.com/assets/11253751/13032011/321aab06-d2b1-11e5-8871-8be7794a090f.png)

**Comment by olee** [comment]
Blame Witchcraft.
I had the same problem once.
There is a config option in Witchcraft where you can disable the ritual to get items back after death.
