### ISSUE TITLE
Crash after update from 1146 to 1147 Afterlife Grave

### ISSUE THREAD

**Issue by Drethic** [ForgeEssentials/ForgeEssentials#2000]
I just upgraded my server from 1.1.4.1146 to 1.1.4.1147 and on start it crashes with the following error:
http://pastebin.com/u86SWsEn

The world/FEData/json/Grave folder is empty.  Here are snippets from my Settings.cfg:
```
afterlife {
    # fe.afterlife.debuffs = 
    # Potion effects to apply on respawn (comma separated list of id:duration:amplifier)
    S:respawn_debuffs=

    # fe.afterlife.food = 
    # Respawn food
    S:respawn_food=

    # fe.afterlife.hp = 
    # Respawn HP
    S:respawn_hp=
}
```
```
grave {
    # fe.afterlife.deathchest.block = 
    # If set, use this block ID for graves
    S:block=

    # fe.afterlife.deathchest = true
    # Allow creation of deathchests
    S:enable=

    # fe.afterlife.deathchest.fence = true
    # Put the skull on a spike
    S:fence=

    # fe.afterlife.deathchest.xp = 0.25
    # Ratio of XP that you want to allow someone to keep in a grave. 1 keeps all XP, 0 disables XP recovery.
    S:recoverable_xp=

    # fe.afterlife.deathchest.safetime = 300
    # Time in seconds a grave is protected. After this time anyone can take all stuff
    S:safetime=
}
```

EDIT: After setting the grave settings (from deathchest down) to the suggested default values the server was able to start.

**Comment by luacs1998** [comment]
`ForgeEssentials: Running ForgeEssentials 1.4.4.1137 (dc05d62). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper`

Erm... Are you SURE you're using 1147? This has been fixed.

**Comment by Drethic** [comment]
Pretty sure... I downloaded the server file from:
http://ci.forgeessentials.com/job/FE/1147/

And here is a screenshot of my mods folder on the server and the date it was uploaded.
http://imgur.com/LFyvSii

Not sure why the patch didn't work, but adding in the suggested defaults did let me go.  My config didn't have anything set as my snippet above showed.
