### ISSUE TITLE
Backup autoremove?

### ISSUE THREAD

**Issue by Cerber91** [ForgeEssentials/ForgeEssentials#2001]
In the standart FE 1.4.3 build 1021-server in the config file for backups I don't see the autoremove option, while I know I've worked with it before. The current options only state a minimum of files and no maximum is there. Is this intentional and where can I find the maximum setting if present anywhere? 

In the Backup folder there is are no config files, nor any max in the main config file.

**Comment by damonmensch** [comment]
It's there, just appears the wording is incorrect.

On my server `I:keep_backups=12` is in fact keeping 12 backups. The exception to this is that `I:keep_daily_backups=7` and `I:keep_weekly_backups=8` are adding additional backups beyond the 12. so I guess essentially your max is the sum of all 3.

And I have to give @olee props on that it's only making backups if changes are detected.

**Comment by Cerber91** [comment]
In the config it says "keep a minimum". That by itself doesn't suggest that there will be any autoremove. Does that mean they are kept at the minimum number at all times?

**Comment by damonmensch** [comment]
One again this is just from what I've observed.

It appears to always have a your minimum from the current day's backups. It'll go over that number to keep your requested daily and weekly backup minimums. I can however confirm it is automatically deleting my old backups that do not apply to the other two settings.

**Comment by olee** [comment]
The `keep_backups` value causes the *last n* backups to be always kept.
The daily and weekly backups work independent of that option.
For example you can set `keep_backups = 1` to only keep the last (2 I think) backups and keep other backups only with the daily option.
