### ISSUE TITLE
How do i unlock the weather set by forgeessentials /weather

### ISSUE THREAD

**Issue by ChristoCoder** [ForgeEssentials/ForgeEssentials#2002]
How can I return the weather to normally switching like vanilla minecraft instead of locked with /weather

Also how can I use the vanilla /weather instead of the fe /weather

**Comment by luacs1998** [comment]
Now that you mention it, I really need to look at the weather command someday...

**Comment by olee** [comment]
Just using `/wheather` command should tell you all the options :sweat: 
`/weather rain|storm [enable|disable|force]: Weather manipulation`
:arrow_right: `/weather rain enable` will enable rain like the normal MC behavior again.
