### ISSUE TITLE
Allow abbreviations for time durations where it is sensible.

### ISSUE THREAD

**Issue by AnrDaemon** [ForgeEssentials/ForgeEssentials#2003]
In commands like `/tempban` you're supposed to enter a duration, but it only allows number of seconds as valid input.
Would be wonderful if it would also accept abbreviated durations, like DNS zones do.
`<number>m` for minutes
`<number>h` for hours
`<number>d` for days
`<number>w` for weeks

**Comment by damonmensch** [comment]
You might be able to do this already with scripting. I'll test it and find out for you.

**Comment by luacs1998** [comment]
Are there any vanilla commands that also accept such a syntax?

**Comment by spacebuilder2020** [comment]
No, however bukkit Essentials tempban allows abbreviations.  For a lot of people migrating from bukkit abbreviating make things easier.
