### ISSUE TITLE
fe.teleport.home.other AND fe.teleport.spawn.other executed by NPCs or other mods

### ISSUE THREAD

**Issue by nullg** [ForgeEssentials/ForgeEssentials#2005]
Will not be a bug report however if executing commands such like fe.teleport.home.other AND fe.teleport.spawn.other by other mods like CustomNPCs or Progression is going to be enable so I would appreciate it. What I'm aiming is 1) Player login 2) Home or spawn locations are automatically set for the player at the coordinate without manual execution of the commands, or any similar functionality to be available on my server. Tried with "/home set @p" and also "/p user @p spawn here" by those mods but hasn't been working as yet. I'm sorry if I'm saying stupid stuff.

**Comment by damonmensch** [comment]
I noticed that my perms generated users with the following names.

- _COMMANDBLACK (as name suggests would be command blocks)
- _FE_ECONOMY (another obvious one...)
- _NPC (assuming this might be CustomNPCs)
- _RCON (not sure what this one is)
- _SERVER (assuming server console)

I also noticed it generated default groups which appear to be the different game modes, op mode, all players, and guests/players. There is also groups called "_FAKEPLAYERS_" which I assume is intended for the entity that mods create for automation, such as Quarries when digging and Fillers when building, and "_NPC_" which might be for CustomNPCs.

I would recommend trying to add those permission nodes to either one or both those "NPC" groups to see if that helps with your problem.

**Comment by nullg** [comment]
Thank you for the detailed explanations! My understanding now is not only groups setting but also each player to be defined which specific group they are belonging to at "playerPermissions" section where right above the groups is mandatory to make it work. I can see all players are registered automatically but NPCs are not in there while Progression is. Therefore successfully executing some of commands even /home set worked thru Progression but it sets home points at weird coordinates. As I think this may be because of a way Progression works so going to focus on CustomNPCs is my current stage. Right now "FE.teleport.*" are set on all groups even _GUESTS_.
FE restricts them from using commands on server (SSP without FE does not affect them as I confirmed) hence FE is somehow recognizing NPCs as something on its system but for some reason FE doesn't count them as configurable?? I have no clue though. Any advise is greatly appreciated!

**Comment by olee** [comment]
If I understood your issue correctly, you want to control permissions for NPCs?
@nullg did you try using `/p debug` while standing next to one doing the things you want them to do?

**Comment by nullg** [comment]
@olee That's helpful command to see what needs to be done. Though I see what I'm aiming should be nearly impossible however now I can let NPCs use commands without any issues so thanks for your advise!

**Comment by damonmensch** [comment]
@olee I think the real issue was trying to figure out which group custom npcs are assigned to.
