### ISSUE TITLE
How to restrict access to items with block values other than the default?

### ISSUE THREAD

**Issue by ryanstarr7** [ForgeEssentials/ForgeEssentials#2006]
I am trying to restrict access to crafting coarse dirt to select groups on my server, but I cannot seem to find the right format to do this. There are no crafting permissions for coarse dirt. The documentation is unclear if this is a possibility.

**Comment by damonmensch** [comment]
It's possible, you just need to get the appropriate block/item permission node, which should of been generated in the block list.

**Comment by olee** [comment]
@ryanstarr7 be careful with those permissions as they only work on default crafting tables and recipes for those. If it exists, you will find it in your own [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentials/wiki/PermissionList.txt)
