### ISSUE TITLE
Chest plot security issue.

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#2007]
{S}-forgeessentials-1.4.4.1147 - Players making a plot keep on having issues with security ... essentially by default peoples loot are unprotected. Griefers without permission can open and rob chests.

**Comment by luacs1998** [comment]
Run a /p debug and try to open the chest. Is it checking `fe.afterlife.deathchest.bypass`, and what is the result of that check?

**Comment by olee** [comment]
This needs some testing.
Could it be the chests used are non-vanilla chests?

**Comment by DPxKnightxZero** [comment]
No and no. I am sure this has to do with the weird bug that changes plot ownership to another player at random note at the time of post this version http://ci.forgeessentials.com/job/FE/1147/

**Comment by spacebuilder2020** [comment]
Can you give us a list of steps to replicate?

**Comment by DPxKnightxZero** [comment]
Oh after this was an issue I just stopped minecraft server modding XD I gave up because it was like the 1000th bug in a year. Sorry.

**Comment by spacebuilder2020** [comment]
ok....
