### ISSUE TITLE
[Auth] Add command to keep the same IP authenticated

### ISSUE THREAD

**Issue by Xodetaetl** [ForgeEssentials/ForgeEssentials#2008]
This is an idea to reduce the inconvenience of having to type `/auth login password` every time for servers where the auth module is always on.
You could add `/auth remember true/false`, only usable when you're already authenticated, which would automatically authenticate you if you reconnect under the same name and IP address.

Another suggestion: add the following aliases:
`/login` and `/register` for `/auth login/register` (or even better: a way to set our own custom aliases :)

**Comment by Entoarox** [comment]
Custom aliasses is already possible using command scripts, remembering could be a security issue since there is no guarantee the same username on the same IP is the same person.

**Comment by Xodetaetl** [comment]
It's a risk taken by the user at their discretion, it's supposed to be off by default and activated by the user if they trust the persons on their local network not to usurp their Minecraft identity.

**Comment by damonmensch** [comment]
It's a risk you take as the server owner as well. Especially if any users with any real access to commands does it.

Also you run a risk of folks who use vpns to log in as each other. Which in the online gaming community is getting more and more common.

**Comment by Xodetaetl** [comment]
I personally take no risk with the kind of server I run and the kind of people I play with. But what I wanted to say is that the fact that there are risks is not an argument for not including the feature. Just warn the admins and users of the risks and let them decide for themselves wether to use it or not.

**Comment by luacs1998** [comment]
Have you tried the auth autologin feature?

You'll need the client as well, download it from http://minecraft.curseforge.com/projects/forge-essentials-client

**Comment by Xodetaetl** [comment]
> Have you tried the auth autologin feature?

I didn't know about it. How does it work?

**Comment by luacs1998** [comment]
It should be automatic, but it's still a beta feature and I haven't really iron out the kinks yet.

Basically, once you /auth login, it saves a token on your client. Future logins read the token and use that to authenticate you instead of asking you to key in your password.

**Comment by Xodetaetl** [comment]
Nice, it should fit my needs then. Thanks
