### ISSUE TITLE
Best way of applying permissions

### ISSUE THREAD

**Issue by Dwaynewp** [ForgeEssentials/ForgeEssentials#2009]
Whta im aiming to make happen is for the first ppl that log in be able to walk around and chat. until promoted by any other plsyer in the game that has been there. but from what i read in the permissions.json file _GUESTS_ starting out with a lot of perms that im not really wanting them to have . I was thinking the easiest way for me is to clear out most of guest perms except for like chat.chat ect ect. and make that group promote to  lets say dirt level this will be low tier walk around talk. anyone other player would be able to promote to stone now they can walk around break blocks build and each rankpast that adding on more perms such /heal /back /home set
 example:

dirt:chat
stone: chat break build use
Coal: chat break build use home set warp

and work my way up from there. I guess really my question is would i be better clearingout the default perms on _GUESTS_ and starting from scratch and adding perms to each higher rank?

**Comment by olee** [comment]
Read up on the [permission tutorial](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial) - especially the section on [deny-default](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial#deny-default).
If you still have problems, ask here or on IRC again.
