### ISSUE TITLE
Portal made in wrong dimension.

### ISSUE THREAD

**Issue by damonmensch** [ForgeEssentials/ForgeEssentials#2012]
I'm trying to make a portal in my multiworld dimension (dim 10), however the server keeps creating it in dim 0 instead.

I have tried selecting the region with both the wand, and manually typing the positions with commands either method it is not creating the portal in the correct dimension.

I've even tried manually editing the json that is created, while server is offline, and it still isn't putting the portal in the correct dimension.

Also when I go to the same coordinates I'm trying to make the portal at, but in dim 0, the FE Client keeps showing me that's where my selection is, despite my selecting it in dim 10.

**Comment by damonmensch** [comment]
Update: I managed to get it working by editing the json directly. Apparently I misspelled the world name.

**Comment by damonmensch** [comment]
Why was this closed? It still makes it in the wrong dimension to begin with.

**Comment by olee** [comment]
Did you use the WorldEdit wand or the FE one?
Portals are created in the dimension where you made your selection and lead to the position where you stand when creating them.

**Comment by damonmensch** [comment]
I used the fe wand and manually specified the coordinates. The destination is being created correctly, the location of the portal itself is what the problem is.

**Comment by olee** [comment]
So just to make this clear - you either removed WorldEdit or disabled the WE integration (which gives you FE wand - **not** WE wand?

**Comment by damonmensch** [comment]
That is correct. Before disabling WE, I even tried assigning FE wand to a different tool.

It's selecting the coordinates, only in the wrong dimension.

**Comment by yuuka-miya** [comment]
I've tested cross-dimensional portals with latest FE and it works.
