### ISSUE TITLE
teleport to other player

### ISSUE THREAD

**Issue by krashing4** [ForgeEssentials/ForgeEssentials#2014]
Hello. So basically what am i looking for is a very simple teleport script for this mod.
I want it to be like in the essentials plugin (the command /tpo).
The only option i need is to teleport to other player without any confirm or option of cordianate teleportation or teleporting a player to me and i want the command to be /tpo.
Can someone please help me and post this script there because i dont know how to program.
Thank you.(sorry for my bad english)

**Comment by luacs1998** [comment]
Have you tried FE's /tp command?

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response  @krashing4

**Comment by maximuslotro** [comment]
Issue closed. Open a new issue if the issue persists.
