### ISSUE TITLE
Help with Multi-World dimension

### ISSUE THREAD

**Issue by Drethic** [ForgeEssentials/ForgeEssentials#2016]
I've created a new dimension via /mw create and have found that we cannot make a nether portal here.  Also, we are getting errors when someone puts down an Armor Imbuement Table from Ars Magica 2.

24.02 17:44:28 [Server] Server thread/ERROR [ArsMagica2]: Unable to obtain file handle!  The power system data for the chunk at -411, -213 will NOT be saved!  To fix this, make sure you have read/write access to the Minecraft instance folder.

Normally I'd report this to that mod author, however, I looked on the server and could not find the region dat files to confirm I had permission to them.

Here is a snippet from his mod on how he's checking for those permissions:
https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/power/PowerNodeCache.java#L97-L100

**Comment by spacebuilder2020** [comment]
I don't think nether portals ever worked in non overworld dimensions.

**Comment by olee** [comment]
Multiworld has been fixed now for the most part.

For the issue with ArsMagica: that is something they need to fix on their side (MWs are stored in a different directory and Ars Magica does not seem to use the correct functions to get that dir and instead just uses a hardcoded default).

The portals are as @spacebuilder2020 already said I think.
You could try again with latest versions and see if it works.
