### ISSUE TITLE
kickall / banall with timer?

### ISSUE THREAD

**Issue by melekaiah** [ForgeEssentials/ForgeEssentials#2018]
So we have an interesting issue. 
we have the server restarting every 4 hours to avoid some memmory leaks, and make sure things a re flowing and do a backup etc.

we would like to be able to kick or ban all the players with a message during this time. 
the reason being that just as the server is shutting down. there is a dupe bug. 

if you time it right, since mods and inventories seem to save BEFORE the player inventory. 
a player can remove a bunch of materials an me system or the like, and have them both in inventory and in the me system after restart.  

as such i was hoping essentials could offer a command to help with this.

**Comment by luacs1998** [comment]
So basically you want a "kick/ban all players after X hours" command?

**Comment by melekaiah** [comment]
yes pretty much.

**Comment by luacs1998** [comment]
You can do something like this with the new /delayedaction command.
