### ISSUE TITLE
Permissions not working for me.

### ISSUE THREAD

**Issue by Aphemra** [ForgeEssentials/ForgeEssentials#2019]
Using forgeessentials-1.7.10-1.4.4.1146-server.jar on a Technic modpack called The 1.7.10 Pack (v0.8.2)

When I try to add perms to a group (lets say _GUESTS_) and then when I go and check permissions by using the `/p group _GUESTS_` perms command, it turns up blank. Am I doing something wrong here?

Also, when I make a group and then use /group list, it also turns up blank even though it confirmed making the group and I can add people to the groups without a problem.

Same goes for the permissions problem. I add a permission and says I did in the green confirmation text, but they seem to no have access to said commands.

What I'm trying to do is make a spawn area with signs for people to warp to various map locations and when they warp there, a command block changes their group from one that can use warps to one that cannot (to prevent /back-ing and choosing a new warp or teleporting to somewhere else).

Is there any solution to this that I can get help from on here? I tried the IRC, but no one was answering.

**Comment by spacebuilder2020** [comment]
I have noticed this as well.  However, in a server with only forge essentials this does not happen.  Try removing fastcraft and see if you see any difference.

**Comment by Ihamfp** [comment]
I have the same problem on my server, there was no fastcraft installed but here is the list of mods installed:
 * Pistronics 2 v0.6.4
 * AsieLib v0.4.7
 * Bibliocraft v1.11.7
 * Chisel v2.9.5.11
 * Computronics v1.6.4
 * DiscordChat v2.1.1
 * FE v1.4.6.1341 (with the latest FE client installed on clients)
 * Forge Multipart v1.2.0.347, added after I had the problem
 * Minetweaker 3 v3.0.10B
 * Morpheus v1.6.21 (I'll remove this one)
 * OpenComputers v1.6.2.12
 * Worldedit v6.1.1

I'll update this message if I find anything causing this, the mod list isn't long, I can try removing mods 1 by 1.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @Aphemra
