### ISSUE TITLE
economy/FEShop

### ISSUE THREAD

**Issue by generaltazz** [ForgeEssentials/ForgeEssentials#2021]
wondering if there is a way to make it so i can use higher price ranges like 1k for 1000 or 1m for 1000000
in the FEShops example would be buying tome of knowledge for 1m

**Comment by luacs1998** [comment]
Sounds a lot like #2003 - I'll look into it.

**Comment by generaltazz** [comment]
awsome thank you i have been searching everywhere on the web and in the cfg files and nothing
