### ISSUE TITLE
Portal help

### ISSUE THREAD

**Issue by Enekuda** [ForgeEssentials/ForgeEssentials#2023]
i cant seem to find any info on how the current /portal command works, a walk through or anything and the Wiki isnt any help on portals... in game i try to use it and keep getting a "missing selection" error when i try to create a portal and have no clue what im doing wrong lol. any help would be amazing!

**Comment by luacs1998** [comment]
This *might* overlap with #2012 - will have to look into it.

**Comment by Enekuda** [comment]
you can kill this, i was unclear on how to obtain a wand (by using the //wand command with an empty hand) after that it all works great! (might want to add how to get a wand to the Wiki :smiley:  )

**Comment by luacs1998** [comment]
We use WorldEdit for selections, so you might want to use [their wiki](http://wiki.sk89q.com/wiki/WorldEdit) as well.
