### ISSUE TITLE
Trouble with another mod?

### ISSUE THREAD

**Issue by McHaddish** [ForgeEssentials/ForgeEssentials#2024]
Hi guys!  I am HIGHLY interested in this mod and will happily download it after someone kindly helps me out with this one small issue.  I uploaded this mod to my Forge test server and de-oped myself to try out all of this awesome commands when suddenly one of the commands from [another mod](http://www.instructables.com/id/Python-coding-for-Minecraft/) is not allowed for non-ops!  I talked to the mod creator and she had no idea how to resolve it considering she is new to modding and it was not focused on multiplayer servers, so neither of us have any idea what the permission node is.  I would normally just delete the mod or not let non-ops use it but this single mod is the entire focus of my server and cannot go without it.  Could anyone help me figure out  how to let non-ops use it?  I would be very grateful for some help.

Thank you for the help,
Jackson McHaddish

**Comment by luacs1998** [comment]
Run `/p debug`, try the command, and the respective permission node should show up in chat.
