### ISSUE TITLE
WB effects are not implemented!

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#2026]
@zethalion first pointed it out to me [here](https://github.com/ForgeEssentials/ForgeEssentials/issues/1983#issuecomment-192253968)

On further inspection, it seems that the code to actually configure effects, and the code to actually apply said effects, aren't in place yet.

How easy would it be to actually do it, and should I?

**Comment by olee** [comment]
Ok... but effects are coded [here](https://github.com/ForgeEssentials/ForgeEssentials/tree/develop/src/main/java/com/forgeessentials/worldborder/effect).

**Comment by luacs1998** [comment]
But you can't exactly add or remove effects to a worldborder, can you?

https://github.com/ForgeEssentials/ForgeEssentials/blob/develop/src/main/java/com/forgeessentials/worldborder/CommandWorldBorder.java

I'm working on some overall improvements as well - stay tuned.

**Comment by Zethalion** [comment]
Believe me, I am hooked to this. Effectively the WB is ineffective currently.

**Comment by olee** [comment]
@luacs1998 there is just no command config, because there are way too many options :smile: 
It is intended for the json file to be edited which is why it is created with all available effects already added.

**Comment by luacs1998** [comment]
Oh, I've found a way to solve that problem ;)
