### ISSUE TITLE
Worldborder: no border in game

### ISSUE THREAD

**Issue by ruphskunk** [ForgeEssentials/ForgeEssentials#2027]
MC 1.7.10, FE Build 1156. 
When worldborder is enabled, it actually doesn't do anything in game. There is no "border".
The file .json file gets created and is read at startup. /wb will show the settings correctly. There just isn't anything preventing players from crossing the defined border. I set border to 1000 and can travel right past it with no indication that I crossed the border and nothing preventing me from doing so.

Commands used:
/wb enable
/wb center here
/wb size 1000
/wb

Output:
Worldborder enabled
Worldborder center set to current location
Worldborder size set to 1000 x 1000
/wb enable|disable
/wb center here: Set worldborder center
/wb size <xz> [z]: Set worldborder size
/wb shape box|ellipse: Set worldborder center
Worldborder info:
  center  = [0, 80, 0]
  size    = 1000 x 1000
  start   = [-1000, 80, -1000]
  end     = [1000, 80, 1000]
  shape   = box
  enabled = true

0.json file contents:
{
  "enabled": true,
  "center": {
    "x": 0,
    "y": 80,
    "z": 0
  },
  "size": {
    "x": 1000,
    "y": 0,
    "z": 1000
  },
  "shape": "BOX",
  "effects": [],
  "dimID": 0
}

**Comment by damonmensch** [comment]
I'm 90% sure your problem is that effects is set to [ ]

**Comment by PRavenhold** [comment]
i have a diffrent problem with wb, json file is created but after server restart the original settings are back.. but it works as long as i edit it again.

**Comment by luacs1998** [comment]
@PRavenhold update to latest jenkins build

@ruphskunk I said this on IRC, but here it is again for the record - try a `/wb effect add knockback 0` as a stopgap measure to prevent players from crossing the border. I'll look into stopping players from moving through a worldborder.

**Comment by luacs1998** [comment]
Should be *somewhat* fixed in https://github.com/ForgeEssentials/ForgeEssentials/commit/af7057744bf009c23de0c333daecad10813de7ca

**Comment by babbajagga** [comment]
Sorry for reopening this, but I am new to this github and I have exactly that same issue, but the "should be somewhat fixed in af70577" ... tells me absolutely nothing.
What am I supposed to do with it?
I need to donwload a never version of FE? I am running mc 1.7.10 and I have the latest FE for it... WB has not even a config present O_o
