### ISSUE TITLE
fe.protection.pvp only applies to melee

### ISSUE THREAD

**Issue by VulcanForge** [ForgeEssentials/ForgeEssentials#2032]
Just as the title says, I can take damage from arrows shot by other players even when fe.protection.pvp is denied for me. I verified that the permission is valid because they can't hit me in melee. I play a mod which includes several new types of EntityProjectiles, so I would suggest making the fix apply to EntityProjectiles rather than simply EntityArrows.

**Comment by luacs1998** [comment]
Run a /p debug, and try to take damage from arrows again.

What do you see?

**Comment by VulcanForge** [comment]
Sorry it took so long to get back. I won't post the whole log here, but basically fe.protection.damageby.arrow = true while fe.protection.pvp = false. Might I suggest changing fe.protection.pvp to fe.protection.damageby.pvp and fe.protection.damageto.pvp and then adding normal smack damage and arrow damage under those two? Or whatever works for you.

**Comment by olee** [comment]
Afaik I added some code to handle projectiles like arrows by getting the source player from them and checking for permissions.
It might be though that this does not work that well yet....
Needs some investigation.

**Comment by DarthJimbo** [comment]
Is there an update on this issue? I'm setting up a 1.7.10 server right now and tested builds 1187, 1330 and newly released 1334 and encountered still the same problem...

**Comment by spacebuilder2020** [comment]
@VulcanForge Has this issue been resolved?

**Comment by VulcanForge** [comment]
@spacebuilder2020 I have no idea, I haven't run a server with Forge Essentials in two years.

**Comment by spacebuilder2020** [comment]
Ok, I am closing this then.
