### ISSUE TITLE
Permissions DB reset on start

### ISSUE THREAD

**Issue by Yggdresil** [ForgeEssentials/ForgeEssentials#2033]
Running ForgeEssentials, 1.4.4.1157 on 1.7.10, I've recently switched permissions storage to use the database system, first on MySQL, then H2 since I read in the issues MySQL was a poor choice for ForgeEssentials.

However, I've had the same problem on both systems: everytime the server restarts, the area table gets reset. I've noticed that it seems to clear and refill the whole database on save [as mentioned in this issue](https://github.com/ForgeEssentials/ForgeEssentials/issues/1554) but the areas and all associated permissions are never reinserted, meaning all zones have to be redefined on server restart.

**Comment by luacs1998** [comment]
I'll close this, as you can refer to the other issue.
