### ISSUE TITLE
Server crash on shutdown AssertionError in TypeAdapters.java:733

### ISSUE THREAD

**Issue by Robijnvogel** [ForgeEssentials/ForgeEssentials#2034]
My server crashed on this at (Multicraft) scheduled restart:
http://pastebin.com/08kQPfwd
I don't know if and what it broke, but I thought I should report it.

There are some other issues I'd like to point out as well:
1. My server doesn't save/load the worldborder on restart; it gets reset every time.
2. Everytime using an FE command, it returns an error to me. The command does have the intended effect though.
3. I've seen that you're integrating WorldEdit into Forge Essentials. Before, when using WorldEdit to select position 1 and 2, a box was rendered around the selected area. Right now, the only way I got such a box to render is with "/area select <name>". The expand commands or selecting new pos1's and pos2's don't update or trigger the render of this box.

If either of these have already been pointed out before, I'd like to know where. (refer without a hashtag please)
Otherwise I will file new issues for these with more information.

**Comment by Zethalion** [comment]
You are running build 1146. Upgrade to build 1157. That should fix the worldborder problems and other issues.

**Comment by Robijnvogel** [comment]
That version is not released on [CurseForge](http://minecraft.curseforge.com/projects/forge-essentials-74735/files) yet.
Now you've told me this, I know that there's a Jenkins somewhere though. Don't worry, I'll find it.

Does it fix the main issue here as well?

**Comment by luacs1998** [comment]
There's a corrupt grave somewhere - you can try removing all files in world/FEData/json/Grave.

**Comment by Robijnvogel** [comment]
Last night, after upgrading FE like Zethalion suggested, the server restarted without a problem. 
My guess is that that crash actively removed the erroneous FE Grave.
So I don't think I can verify this. :/

**Comment by luacs1998** [comment]
In that case then I'll close this.
