### ISSUE TITLE
Auth module problems in the 1159 build.

### ISSUE THREAD

**Issue by Pordy** [ForgeEssentials/ForgeEssentials#2037]
Greetings! 

Problem with the latest build AKA 1159/ (Mar 19, 2016 4:30:20 PM) http://ci.forgeessentials.com/job/FE/1159/

Earlier, my modpack use the "forgeessentials-1.7.10-1.4.3.1021-server.jar" and the auth module just works fine.

I recently builded up my upgraded modpack and tried the latest build of FE.
All mods running smoothly but if i create a server and running offline or online mode, the player who joins the server can use the "/auth register" and/or "/auth login" commands, but not forced to use them. I mean the player can move, use and break blocks even without using theese commands.

I am carefully checked all the settings related to "auth" module. All setting surely turned on,
From the previous version, i even tried to copy the forgeessentials-1.7.10-1.4.3.1021-server config folder to my new pack, but still, the joining players doesnt forced to use "/auth register" or "/auth login" commands.
How can i help you providing more information? (This is my first github issue report) 
There is no crash, or something valuable in the logs, but i can compress my modpack and upload to dropbox if you want it.

**Comment by luacs1998** [comment]
/auth login should be handled automatically now - unregistered players should still be forced to use /auth register.

**Comment by Pordy** [comment]
This is my config file, you can see that the autologin option disabled, and that was disabled from the begginning.
https://www.dropbox.com/s/z3ycbosn7y2odyq/AuthLogin.cfg?dl=0

And there is the asked files:
https://www.dropbox.com/s/fw7p2007fmtlwoc/PlayerInfo.zip?dl=0
https://www.dropbox.com/s/lgjya2qkpnrupzi/PlayerPassData.zip?dl=0
I even tried to disable the FE client.

**Comment by luacs1998** [comment]
Please try build 1161 and let me know if the issue is fixed.

**Comment by Pordy** [comment]
Problem solved, 1161 and 1162 builds working fine now! Thank you!
