### ISSUE TITLE
Permissions Breaking

### ISSUE THREAD

**Issue by MickScandalous** [ForgeEssentials/ForgeEssentials#2038]
I am having some problems, When I leave a zone I have the FE.* command in I can not do ANYTHING in the Server from commands too even having items in my inventory. I can not place or break blocks. Please help if this issue can be resolved. I have been everywhere trying to figure this out

**Comment by luacs1998** [comment]
Do a /p debug and see what it says

**Comment by MickScandalous** [comment]
I think I fixed it by using an older permissions file, I had recently made a zone on a plot and then that issue occurred. I then removed the plot and zone and just reloaded the older (unbroken) permissions.json and the problem was fixed.
