### ISSUE TITLE
Get Metrics R6 Lib

### ISSUE THREAD

**Issue by LeBoucEtMistere** [ForgeEssentials/ForgeEssentials#2039]
Hello,
I'm currently playing on Minecraft 1.4.2 and all works perfectly fine until I install the mod : i need to get the external libs and when i follow the link and download the zip on mediafire, there is a metrics-R7 but no metrics-R6 which is required by the server to start. And event with google, i cannot find the original R6 file so i wonder if someone still has it and is able to reupload it.
Have a nice day

**Comment by luacs1998** [comment]
http://www.mediafire.com/download/bqsz5sm4egk8x6b/metrics-R6-FEmod.jar

Should be this file.

**Comment by LeBoucEtMistere** [comment]
thanks a lot :)
