### ISSUE TITLE
Crash after server migration

### ISSUE THREAD

**Issue by Drethic** [ForgeEssentials/ForgeEssentials#2043]
My host had to migrate our server do to issues on their end.  However, when I try to start my server with FE 1.4.4-1154 I get the following error.  Based on what I'm seeing it looks like ZLib isn't installed or installed correctly, however, want to verify that before I ask my host to fix their server.

http://pastebin.com/tiMrVcZ9

**Comment by Yggdresil** [comment]
The error log mentions (l. 213) `Unexpected end of ZLIB input stream` so AFAIK, ZLib is correctly installed but the file passed to ZLib is either invalid or most likely corrupted.

**Comment by luacs1998** [comment]
Delete all files in ForgeEssentials/mapper directory.

**Comment by Drethic** [comment]
@luacs1998 that seems to have done it.  Thank you for the help.
