### ISSUE TITLE
Color codes on signs not working

### ISSUE THREAD

**Issue by D3adlyDreams** [ForgeEssentials/ForgeEssentials#2048]
color codes are not working on the sighs on the last update of the mod. It was working fine before.

**Comment by VulcanForge** [comment]
I have the same issue.

**Comment by VulcanForge** [comment]
Good that it's been noticed by luacs :)

**Comment by spacebuilder2020** [comment]
This has been solved with the most recent update 1182.

**Comment by luacs1998** [comment]
I'd like to add that it's only been *somewhat* solved - if you edit a sign, the colour codes don't apply properly.

But then again editing has always been shaky so it's not a high priority.

**Comment by spacebuilder2020** [comment]
xD
