### ISSUE TITLE
No guide on how to paste prices

### ISSUE THREAD

**Issue by MickScandalous** [ForgeEssentials/ForgeEssentials#2049]
I am not sure how to paste my prices into my Economy.cfg If anyone knows how to do this please tell me

**Comment by PRavenhold** [comment]
`# Configuration file

Economy {

    ItemPrices {
        I:"AWWayofTime:bloodMagicBaseItems"=384
        I:"AWWayofTime:bloodMagicIncenseItem"=32
        I:"AWWayofTime:itemMailCatalogue"=218
    }

}
`
it's the same as in prices.txt and prices_all.txt

**Comment by MickScandalous** [comment]
Okay thats what I needed was an example, When I copied it into the file it wasnt tabbed over correctly.
