### ISSUE TITLE
[Question] Any way to multiworld void world?

### ISSUE THREAD

**Issue by DeForce** [ForgeEssentials/ForgeEssentials#2053]
Good day,

Is it possible to create an empty (void) world for skyblock'ish type of maps?

**Comment by Zethalion** [comment]
I use Garden of Glass mod for skyblock dimensions. See http://botaniamod.net/downloads.php
Botania is not required to use this mod.

**Comment by luacs1998** [comment]
Not yet, but planned. See #1163
