### ISSUE TITLE
[Information Needed]

### ISSUE THREAD

**Issue by MickScandalous** [ForgeEssentials/ForgeEssentials#2059]
I just wanted to know exactly how to find the latest official build and how to Download it

**Comment by Yggdresil** [comment]
The [ForgeEssentials website](http://forgeessentials.com/) has links to the Jenkins for both the [1.8](http://ci.forgeessentials.com/job/FE-1.8/) and the [1.7.10](http://ci.forgeessentials.com/job/FE/) versions.
