### ISSUE TITLE
FE Minor Incompatibility - Thaumcraft 5

### ISSUE THREAD

**Issue by mlbarnes2** [ForgeEssentials/ForgeEssentials#2062]
There seems to be no way to 'use' (right click) a clock on a block while running FE.
The Playerlogger over-rides this.
This means you cannot place a clock into an infusion setup in Thaumcraft.
It seems the only way around this is to disable the server FE? - not yet tried...
Would it be more useful to have shift-right click to use the clock or some similar way to bypass the over-ride?
From another article, I think you might be replacing the clock system anyway?

**Comment by panda2134** [comment]
You can use a hopper to put the clock into the table XD

**Comment by mlbarnes2** [comment]
Ah! Superb idea, thanks for taking the time, I had still been stumped!

**Comment by luacs1998** [comment]
You can also deny `fe.pl.wand`. Though I'm considering shift-right click though.

**Comment by mlbarnes2** [comment]
Better still - I shall give it a try. Thanks both of you.

**Comment by olee** [comment]
As @luacs1998 stated, denying `fe.pl.wand` is the correct solution for this problem.
You could disable the playerlogger wand in general and enable it only for yourself when you need it:
````
/p group _OPS_ deny fe.pl.wand
/p user <name> allow fe.pl.wand
````

You could also make a [scripted command](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Scripting) to allow switching that wand permission easily.
