### ISSUE TITLE
Removing assigned groups does not return player to the default group

### ISSUE THREAD

**Issue by ruphskunk** [ForgeEssentials/ForgeEssentials#2063]
When a player has all assigned groups removed, it leaves an empty stub in playerGroups for that player. This has the effect of not returning them back to default group without manually editing permissions.json file. Does FE allow returning a user to the default group by removing all their assigned groups?

Command used to remove player from groups(per group): `/p user <USER> group remove <GROUPNAME>`

MC 1.7.10
FE 1145

**Comment by luacs1998** [comment]
I'll need @olee to give an answer, Is it intended functionality or a bug?

**Comment by spacebuilder2020** [comment]
Sounds like a bug to me.  I have experienced this several times with factions.

Since _GUESTS_ is supposed to include any player not in a group, removing a player from a group should return them to _GUESTS_.
