### ISSUE TITLE
World Border

### ISSUE THREAD

**Issue by MickScandalous** [ForgeEssentials/ForgeEssentials#2064]
The help portion of the Wiki seems outdated. I need to know how to apply the effects to the world Border and also make sure its set. I can not find a config file for it anywhere in my server files

**Comment by luacs1998** [comment]
`/wb effect <add [command|damage|kick|knockback|message|potion|smite] <trigger>`

**Comment by MickScandalous** [comment]
When I do this I get "An unknown error occurred while attempting to perform this command"

**Comment by MickScandalous** [comment]
/wb effect <add [knockback] <trigger> when I type this I get "wrong syntax! try /wb effect <add [command|damage|kick|knockback|message|potion|smite] <trigger> : remove <index>"

Please help soon i need to get this set up

**Comment by MickScandalous** [comment]
https://github.com/luacs1998

**Comment by MickScandalous** [comment]
I have to type it like so "/wb effect add block 2" , and it says effect added but I dont see the effect actually occuring any help on this?

**Comment by spacebuilder2020** [comment]
Sounds like a mod conflict

**Comment by spacebuilder2020** [comment]
Post the section of the console log at the point where you used the command and got unknown error

**Comment by MickScandalous** [comment]
I am doing it in game and when I do that I do not get anything on the console about me doing the command or its effect. If I enter in on the console I get "You do not have permision to use this command"

**Comment by spacebuilder2020** [comment]
I mean when you type the command in game, post what the console spits out.
It might help to enable logging of commands in main.cfg to true to help narrow down where the error is being spit out.

Also, if you are still not getting anything, enable debug mode.

**Comment by MickScandalous** [comment]
no this wasnt fixed as far as I know its an issue from 2 yrs ago so probably irrelevant now.
