### ISSUE TITLE
FE crash with BetterBoat (and Bookshelf) when placing a boat

### ISSUE THREAD

**Issue by temdur** [ForgeEssentials/ForgeEssentials#2065]
Create a new SSP world.
Place a boat.
Crash.

After that you can restart and rejoin the testworld. The boat is still in your hands. Unplaced.

Used Mods:
BetterBoat: 1.1.0
Bookshelf:  1.0.4.187 (dependency for BB)
Forge Essentials:   1164
crashlog: http://pastebin.com/qS7SZUY5

---

It also crashed with the TechnodeFirmacraft modpack. At SMP and SSP.
The difference Betterboat is maybe modified for TFC. It depended on "sapmanpack-1.7.10-2.5.1.jar" instead.

FE without BB don't crash.
BB without FE don't crash.

MC: 1.7.10
Forge: 10.13.4.1614 (Latest)
Java 8u77

Is it a FE or BB problem? Should I post the bug at the Betterboat too?

Edit: Better Boat not Boats

**Comment by olee** [comment]
Looks like Betterboats issue because of code patching.
The function affected is `Entity.onUpdate`.
I'd report this at Betterboats at least too.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @temdur
