### ISSUE TITLE
Changing permissions manually

### ISSUE THREAD

**Issue by Fillipuster** [ForgeEssentials/ForgeEssentials#2067]
I'd like to manually edit the permissions, as I do not believe the "inherit" is working with my build of ForgeEssentials. (1.6.4-1.3.0.4)

It says on the Wiki that permissions are stored under world/FEData/Permissions, but no such folder exists.

Where can I find the permissions? Can I maybe use the newest build on a 1.6.4 minecraft server?

- Puster

**Comment by PitchBright** [comment]
if you check in the folder for your "world" (whatever you called your world)… you'll see another folder called "FEData"… and then in there is "permissions"

**Comment by PitchBright** [comment]
That said, if you're using 1.6.4… I'm not sure that's the case. I don't think they support 1.6 at all anymore.

**Comment by olee** [comment]
1.6.4 support has ended already a long time ago.
