### ISSUE TITLE
Tpa / home / spawn command removed?

### ISSUE THREAD

**Issue by jonas13362** [ForgeEssentials/ForgeEssentials#2072]
Hello ,

After dissalowing the permission tppos the /tpa command isnt working anymore.
Incase i do /tpa (name) it says unknown command.
I tried to remove the permissions to dissalow tppos but it didnt work.

**Comment by spacebuilder2020** [comment]
Check your logs.  I have never experience this error, perhaps you entered something wrong and it caused a exception in the tpa command.  Look for exceptions related to Forge Essentials.   Finally it is hard to help you if you don't post both your crash log and your server log.

**Comment by jonas13362** [comment]
Excuse me sir but i didnt know there would be an error in the log as the server didnt crash or anything and i didnt see an error when i did the command
I doubt the errors i send u are from the /tpa and so as it shows something else.
http://pastebin.com/TRsiTnp7

**Comment by spacebuilder2020** [comment]
I need the entire log... I can't work with snippets

**Comment by jonas13362** [comment]
http://pastebin.com/89cAEPWC

**Comment by spacebuilder2020** [comment]
This is why, somewhere in your configs you have disabled the teleport module

**Comment by jonas13362** [comment]
Thank you very much, i have no clue how it got disabled

**Comment by spacebuilder2020** [comment]
No problem.  I was happy to help.
