### ISSUE TITLE
FE dependency not available

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentials#2073]
Can you make the 1.4.4 dev snapshot available on the maven? This tutorial says to use it: https://github.com/ForgeEssentials/ForgeEssentials/wiki/Developer-documentation but it's not there.

**Comment by luacs1998** [comment]
Try removing `-dev`

**Comment by PitchBright** [comment]
Take a look here: http://files.minecraftforge.net/maven/com/forgeessentials/forgeessentials#Downloads 

There's not 1.4.4 files at all. There should be, right?

**Comment by luacs1998** [comment]
Should be online now.
