### ISSUE TITLE
Having FE installed, makes ProjectE Items loose their EMC Value

### ISSUE THREAD

**Issue by SteelShot** [ForgeEssentials/ForgeEssentials#2075]
AS title says it all ProjectE items loose their EMC value when FE is installed, removed it, everything works fine, when i put FE back = no EMC.

MC Vanilla and Modded items that have an EMC value work fine, tho Philosphers stone is the only item that has a EMC value from ProjectE.

I have made an issue on ProjectE's github aswell in case it on their end.

I am using latest Forge, ProjectE, FE build 1166, Latest Forge Server and I am not using KCauldron.

**Comment by MaPePeR** [comment]
So, does Forge essentials do something weird to the crafting recipe list or something like that?

**Comment by SteelShot** [comment]
I dont know,  i have not changed anything that would be to do with recipes

**Comment by olee** [comment]
Well - the only thing FE does in regards to crafting is this Mixin
https://github.com/ForgeEssentials/ForgeEssentials/blob/300aa28473a06125ff2089ef9ffeaff9c693ce78/src/main/java/com/forgeessentials/core/preloader/mixin/item/crafting/MixinCraftingManager.java

It might be that ProjectE uses this function as well with `player` set to `null` which would make the function not return anything. I quickly patched it to check for that condition and you might want to try again with the latest version now.

**Comment by MaPePeR** [comment]
No, i don't think we use this method. Weird thing. Will try to take a deeper look at this later. Thanks for investigating.

**Comment by olee** [comment]
Report again after testing with the latest build and maybe it works.
If not we will have to try something else.

**Comment by SteelShot** [comment]
Still does not work, latest FE, with newly fresh permissions and setting regenerated in a fresh world, tho with all of my mods
gonna test just FE with PE and report straight away back here

**Comment by olee** [comment]
That's good to know.

**Comment by SteelShot** [comment]
Strange thing tho, removing FE from the main server, fixed the issues, but running just those 2 it works....

**Comment by SteelShot** [comment]
See the reference. JustEnoughCalculation was narrowed down.

**Comment by Towdium** [comment]
It is confirmed to be caused by me. I used an itemStack with null item as ingredient in the recipe and force to insert the itemStack using reflection.
Here is the code I used: [https://gist.github.com/Towdium/42f3cc97e4644af0eef8ff759933e5dd](https://gist.github.com/Towdium/42f3cc97e4644af0eef8ff759933e5dd)

**Comment by spacebuilder2020** [comment]
Well, we might want to look into some null checks to prevent this kind of crash from happening.
