### ISSUE TITLE
Scripting experience argument and method

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentials#2076]
This is a feature request, could you add a @exp argument and maybe a expcheck method?

Pardon me if this was already requested, I'm trying to reproduce bed and tpa commands to remove experience levels on use.

**Comment by olee** [comment]
Great suggestion!
Should be easy to add.

**Comment by spacebuilder2020** [comment]
If you guys want, I am willing to take a shot at this issue.

**Comment by luacs1998** [comment]
That would be cool, thanks in advance!

**Comment by spacebuilder2020** [comment]
np

**Comment by spacebuilder2020** [comment]
Finished

**Comment by Ganjalf-Amsterdoom** [comment]
You guys rocks!

**Comment by spacebuilder2020** [comment]
Fixed a few bugs from my last implementation, improved the documentation and added adder methods to make it easier (or possible) to remove experience in your commands.

**Comment by spacebuilder2020** [comment]
Fixed a bug with the expadd method where you could not remove experience.  You will need to update to get that fix.
