### ISSUE TITLE
Crash on server start involving null stack item and moduleprotection

### ISSUE THREAD

**Issue by Lemmmy** [ForgeEssentials/ForgeEssentials#2078]
---- Minecraft Crash Report ----
	// Don't be sad, have a hug! <3

	Time: 5/11/16 1:56 PM
	Description: Exception ticking world

	java.lang.RuntimeException: Error getting item permission. Stack item is null
		at com.forgeessentials.protection.ModuleProtection.getItemPermission(ModuleProtection.java:394)
		at com.forgeessentials.protection.ModuleProtection.getItemPermission(ModuleProtection.java:402)
		at com.forgeessentials.protection.ModuleProtection.getItemBanPermission(ModuleProtection.java:412)
		at com.forgeessentials.protection.ProtectionEventHandler.isItemBanned(ProtectionEventHandler.java:950)
		at com.forgeessentials.protection.ProtectionEventHandler.harvestDropsEvent(ProtectionEventHandler.java:635)
		at cpw.mods.fml.common.eventhandler.ASMEventHandler_611_ProtectionEventHandler_harvestDropsEvent_HarvestDropsEvent.invoke(.dynamic)
		at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
		at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
		at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
		at net.minecraft.block.Block.func_149690_a(Block.java:656)
		at net.minecraft.block.BlockLeaves.func_149690_a(BlockLeaves.java:241)
		at net.minecraft.block.Block.func_149697_b(Block.java:648)
		at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:225)
		at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:205)
		at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
		at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
		at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

	A detailed walkthrough of the error, its code path and all known details is as follows:
	---------------------------------------------------------------------------------------

	-- Head --
	Stacktrace:
		at com.forgeessentials.protection.ModuleProtection.getItemPermission(ModuleProtection.java:394)
		at com.forgeessentials.protection.ModuleProtection.getItemPermission(ModuleProtection.java:402)
		at com.forgeessentials.protection.ModuleProtection.getItemBanPermission(ModuleProtection.java:412)
		at com.forgeessentials.protection.ProtectionEventHandler.isItemBanned(ProtectionEventHandler.java:950)
		at com.forgeessentials.protection.ProtectionEventHandler.harvestDropsEvent(ProtectionEventHandler.java:635)
		at cpw.mods.fml.common.eventhandler.ASMEventHandler_611_ProtectionEventHandler_harvestDropsEvent_HarvestDropsEvent.invoke(.dynamic)
		at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
		at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
		at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
		at net.minecraft.block.Block.func_149690_a(Block.java:656)
		at net.minecraft.block.BlockLeaves.func_149690_a(BlockLeaves.java:241)
		at net.minecraft.block.Block.func_149697_b(Block.java:648)
		at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:225)
		at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:205)
		at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
		at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)

	-- Affected level --
	Details:
		Level name: world
		All players: 1 total; [GCEntityPlayerMP['Chaire'/140, l='world', x=419.67, y=142.67, z=-485.82]]
		Chunk stats: ServerChunkCache: 467 Drop: 0
		Level seed: -8660797390303483025
		Level generator: ID 00 - default, ver 1. Features enabled: false
		Level generator options: 
		Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
		Level time: 0 game time, 0 day time
		Level dimension: 0
		Level storage version: 0x00000 - Unknown?
		Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
		Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Stacktrace:
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
		at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

	-- System Details --
	Details:
		Minecraft Version: 1.7.10
		Operating System: Linux (amd64) version 2.6.32-573.22.1.el6.x86_64
		Java Version: 1.8.0_77, Oracle Corporation
		Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
		Memory: 1517642904 bytes (1447 MB) / 2112618496 bytes (2014 MB) up to 4260102144 bytes (4062 MB)
		JVM Flags: 4 total; -XX:MaxPermSize=512m -Xmx4G -Xms2G -Xincgc
		AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
		IntCache: cache: 0, tcache: 48111, allocated: 1, tallocated: 223
		FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 98 mods loaded, 89 mods active
		States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		UCHIJAAAA	CollectiveFrameworkCore{1.0.0-132} [Collective Framework Core] (minecraft.jar) 
		UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
		UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
		UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
		UCHIJAAAA	<CCTweaks ASM>{0.3.2} [<CCTweaks ASM>] (minecraft.jar) 
		UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
		UCHIJAAAA	ImmibisMicroblocks{59.1.2} [Immibis's Microblocks] (immibis-microblocks-59.1.2.jar) 
		UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
		UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
		UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
		UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
		UCHIJAAAA	PeripheralsPlusPlusCore{1.3.6} [Peripherals++ Core] (minecraft.jar) 
		UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
		UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
		UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
		UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
		UCHIJAAAA	autopackager{1.5.9a} [AutoPackager] (autopackager-1.5.9a.jar) 
		UCHIJAAAA	BiblioCraft{1.11.3} [BiblioCraft] (BiblioCraft[v1.11.3][MC1.7.10].jar) 
		UCHIJAAAA	Forestry{4.2.12.60} [Forestry for Minecraft] (forestry_1.7.10-4.2.12.60.jar) 
		UCHIJAAAA	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
		UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
		UCHIJAAAA	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
		UCHIJAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
		UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
		UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
		UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
		UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
		UCHIJAAAA	OpenPeripheralCore{1.3} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-7.jar) 
		UCHIJAAAA	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
		UCHIJAAAA	CCTweaks{0.3.2} [CCTweaks] (CCTweaks-1.7.10-0.3.2.jar) 
		UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
		UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
		UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
		UCHIJAAAA	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
		UCHIJAAAA	CollectiveFramework{1.0.0-132} [Collective Framework] (CollectiveFramework-1.0.0-132.jar) 
		UCHIJAAAA	endercore{1.7.10-0.2.0.34_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.34_beta.jar) 
		UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	EnderIO{1.7.10-2.3.0.424_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.424_beta.jar) 
		UCHIJAAAA	exnihilo{1.38-49} [Ex Nihilo] (Ex-Nihilo-1.38-49.jar) 
		UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
		UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
		UCHIJAAAA	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
		UCHIJAAAA	exastris{MC1.7.10-1.16-36} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-36.jar) 
		UCHIJAAAA	extracells{2.3.9} [Extra Cells 2] (ExtraCells-1.7.10-2.3.9b188.jar) 
		UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
		UCHIJAAAA	FloodLights{1.1.1-120} [Flood Lights] (FloodLights-1.7.10-1.1.1-120.jar) 
		UCHIJAAAA	ForgeEssentials{1.4.4} [Forge Essentials] (forgeessentials-1.7.10-1.4.4.1167-server.jar) 
		UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.460.jar) 
		UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.460.jar) 
		UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
		UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
		UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar) 
		UCHIJAAAA	ImmibisPeripherals{59.0.3} [Immibis's Peripherals] (immibis-peripherals-59.0.3.jar) 
		UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
		UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
		UCHIJAAAA	Mekanism{8.1.9} [Mekanism] (Mekanism-1.7.10-8.1.9.265.jar) 
		UCHIJAAAA	MekanismGenerators{8.1.9} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.9.265.jar) 
		UCHIJAAAA	MekanismTools{8.1.9} [MekanismTools] (MekanismTools-1.7.10-8.1.9.265.jar) 
		UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UCHIJAAAA	MoarPeripherals{1.7.10-1.7-1.53} [MoarPeripherals] (MoarPeripherals-1.7.10-1.7-1.53.jar) 
		UCHIJAAAA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
		UCHIJAAAA	NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41-mc1.7.10.jar) 
		UCHIJAAAA	NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41-mc1.7.10.jar) 
		UCHIJAAAA	NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41-mc1.7.10.jar) 
		UCHIJAAAA	NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41-mc1.7.10.jar) 
		UCHIJAAAA	NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41-mc1.7.10.jar) 
		UCHIJAAAA	NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41-mc1.7.10.jar) 
		UCHIJAAAA	NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41-mc1.7.10.jar) 
		UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
		UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
		UCHIJAAAA	openmodularturrets{2.2.2-217} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.2-217.jar) 
		UCHIJAAAA	OpenPeripheral{0.5.1} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-7.jar) 
		UCHIJAAAA	OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-7.jar) 
		UCHIJAAAA	PeripheralsPlusPlus{1.3.6} [Peripherals++] (Peripherals++-1.3.6.jar) 
		UCHIJAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
		UCHIJAAAA	RedLogic{59.1.13} [RedLogic] (redlogic-59.1.13.jar) 
		UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
		UCHIJAAAA	Torcherino{2.2s} [Torcherino] (Torcherino-1.7.10-2.2s.jar) 
		UCHIJAAAA	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar) 
		UCHIJAAAA	ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
		UCHIJAAAA	McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
		UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
		OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
		Class transformer null safety: all safe
		AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
		CoFHCore: -[1.7.10]3.1.2-325
		ThermalFoundation: -[1.7.10]1.2.3-112
		ThermalExpansion: -[1.7.10]4.1.2-240
		MineFactoryReloaded: -[1.7.10]2.8.1-174
		Mantle Environment: Environment healthy.
		TConstruct Environment: Environment healthy.
		ForgeEssentials: Running ForgeEssentials 1.4.4.1167 (e4aac9d). Modules loaded: Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Scripting, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper, perftools
		NetherOres: -[1.7.10]2.3.1-22
		ThermalDynamics: -[1.7.10]1.1.0-161
		EnderIO: Found the following problem(s) with your installation:
	                  * An unsupportted old RF API is installed (1.7.10R1.0.1 from Peripherals++-1.3.6.jar).
	                    Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions.
	                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
	                    Ender IO was build against API version rv2 and may or may not work with a newer version.
	                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
		AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
		Profiler Position: N/A (disabled)
		Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
		Player Count: 1 / 40; [GCEntityPlayerMP['Chaire'/140, l='world', x=419.67, y=142.67, z=-485.82]]
		Is Modded: Definitely; Server brand changed to 'fml,forge'
		Type: Dedicated Server (map_server.txt)

**Comment by Lemmmy** [comment]
The player said that they were using the Lamp of Cinders to burn thorns for the Twilight Forest, if that information helps.

**Comment by 247GradLabs** [comment]
Enable safe-mode in the config file for FE.
This is caused by invalid drops generated by TF (known issue - they just don't seem to fix it).

**Comment by olee** [comment]
Enable safe-mode in the FE config file.
This is caused by TF dropping invalid items (known issue - they just don't seem to fix it).

**Comment by Lemmmy** [comment]
Thank you!

**Comment by stopcraft** [comment]
Hello, I have same problem but can't find FE config file.
where can I find it and cawn you tell me config's name?
