### ISSUE TITLE
[Bug] God mode

### ISSUE THREAD

**Issue by spacebuilder2020** [ForgeEssentials/ForgeEssentials#2079]
There are a few errors in the god mode script.
1) For on @p /heal is applied to the sender not the player being set to god mode
2) For off @p there is a typo in the god mode argument resulting in it not turning off
3) For on /heal is not applied due to it the sender of /heal being console.

I am preparing a pull request that fixes these 3 issues.

**Comment by olee** [comment]
Good job noticing and fixing this!
