### ISSUE TITLE
WorldEdit

### ISSUE THREAD

**Issue by VulcanForge** [ForgeEssentials/ForgeEssentials#2081]
Your website advertises that WorldEdit is included with Forge Essentials. However, when I installed Forge Essentials, the console displayed a message telling me that WorldEdit was not installed. So I installed WorldEdit separately, but now I am warned that the integration tools will not be loaded because WorldEdit's version is incorrect. I have had to op players to give them access to the WorldEdit commands instead of creating a custom Builder rank.

**Comment by spacebuilder2020** [comment]
Did you install the bukkit version?

Also, the correct version of world edit is included in the libraries.zip file in the server jar.

**Comment by spacebuilder2020** [comment]
I am not sure why it is extracting automatically anymore though.

**Comment by VulcanForge** [comment]
Well, I was able to extract it from the jar and install it manually. Thanks for the tip.

**Comment by spacebuilder2020** [comment]
np
