### ISSUE TITLE
lagging super hard

### ISSUE THREAD

**Issue by foulblade1** [ForgeEssentials/ForgeEssentials#2087]
I have added it to my test server and the avg tick goes up to 90. It takes 8 seconds to break a block and for it to actually fall on the ground. Anyone know why it would lag the server so hard and if so is there something i could do to fix it. I have 200+ mods on my server. Could it be like block logger or something causing this?

**Comment by foulblade1** [comment]
using the version latest fo 1.7.10

**Comment by spacebuilder2020** [comment]
turn of the player logger then and let us know if the lag continues.

**Comment by liach** [comment]
Please use fastcraft

**Comment by TerdyTheTerd** [comment]
Is it an old world? On my server when I switched to forge+FE the server lags like crazy for about a minute after restart, but on a newly created one it doesn't
