### ISSUE TITLE
Forbid the use of nether portal

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentials#2091]
I'm trying to forbid the use of nether portals, is that possible with FE permissions?
If not, could it be implemented?

Thank you

**Comment by olee** [comment]
I think this has not been added yet, however you can prevent players from traveling to the nether with teleport permissions.

**Comment by Ganjalf-Amsterdoom** [comment]
I use WorldDrop mod to make players teleport between dimensions by jumping/climbing the void, so i want players to cross dimensions, just not via portals. Anyhow I worked around the problem for now by using LockedDimensions mod and by removing dimensions keys, so it will work also in single player, but it would be nice to have permission nodes for portals use.
Anyhow thank you for your time.

**Comment by spacebuilder2020** [comment]
np

**Comment by Techjar** [comment]
As of 9636042, you can prevent portalling to a dimension using the fe.teleport.crossdim.portalto permission, among others. So you'd just deny this permission on the WORLD_-1 zone to prevent players going to the nether via portal.

**Comment by olee** [comment]
It would also be just interesting to deny the construction (i.e. turning on with flint&stone) of portals.
We don't support that yet afaik, do we?

**Comment by Techjar** [comment]
No, but I think it's handled in BlockFire, and we already have a mixin for that.

**Comment by olee** [comment]
It might be possible to prevent it by preventing fire to be created.
But that is not a permission to create nether portals.
I think this might be an interesting feature....

**Comment by spacebuilder2020** [comment]
true
