### ISSUE TITLE
Command/Plugin

### ISSUE THREAD

**Issue by rcistano** [ForgeEssentials/ForgeEssentials#2092]
I was told that this mod had a /vanish option in it but I do not see such thing. How can I get the /vanish command/plugin?

**Comment by spacebuilder2020** [comment]
As I recall /vanish does not work properly. 
See 
https://github.com/ForgeEssentials/ForgeEssentials/wiki/Commands%20Module#outdated

**Comment by rcistano** [comment]
Does this mod work with 1.8.9?

**Comment by Zethalion** [comment]
Read https://github.com/ForgeEssentials/ForgeEssentials

**Comment by spacebuilder2020** [comment]
Currently there is no released 1.8.9 build, however, you can download the 1.8.9 source and build it yourself.  It will probably be buggy but from what I heard the server side component is fully ported.
https://github.com/ForgeEssentials/ForgeEssentials/tree/189/develop

**Comment by rcistano** [comment]
I have no idea how to code a mod, lol. the FE Server side is at 1.8.9?

**Comment by spacebuilder2020** [comment]
There are several branches
