### ISSUE TITLE
Specific block exception?

### ISSUE THREAD

**Issue by KremeChoco** [ForgeEssentials/ForgeEssentials#2093]
Quick question.
I'm making a spawn protected place. Obviously I want spawn to be protected.
However, I feel people will die and because I have gravestone mod, I want only gravestones to be able to be broken in the map. Anything else has to be protected. How do I go about doing this?

**Comment by spacebuilder2020** [comment]
Forge Essentials has its own gravestone feature.

As for whitelisting blocks, it is rather simple, just allow break perm for that block.
See https://github.com/ForgeEssentials/ForgeEssentials/wiki/Protection-%28world-guard%29 for more infomation.
