### ISSUE TITLE
Disable Home Command

### ISSUE THREAD

**Issue by Liqueseous** [ForgeEssentials/ForgeEssentials#2095]
Is there a way to disable a certain command. I want to disable just the home command because I already have another mod I want to use that allows the setting of multiple homes and I want to use that. Specifically FTB Utilities

**Comment by spacebuilder2020** [comment]
The only way to disable homes in forge essentials is to disable the entire teleportation module in the ForgeEssentials/main.cfg file.

However, You can have multiple homes in forge essentials, (12 with default perms).  Use /home for your main home, /bed for your bed home, and /pwarp for an additional home you want.

Let me know if this works for you.  Sorry for the late response @Liqueseous.

**Comment by olee** [comment]
You can just remove permission to use the command - that's what permissions are for.

**Comment by spacebuilder2020** [comment]
He wants to use the FTB Lib /home which conflicts with our /home

**Comment by olee** [comment]
Ok that is a problem....
I think that's a case where we should apply command aliases.

**Comment by spacebuilder2020** [comment]
Sounds like a plan.  I will take a look at fixing several of these issues over the weekend.

**Comment by luacs1998** [comment]
We already have getDefaultAliases - it's used for the kill command.

**Comment by olee** [comment]
Fixed in https://github.com/ForgeEssentials/ForgeEssentials/commit/07206c83954364e631770feb62511a4d993277e1

**Comment by Taknax** [comment]
Can i just rename the ccommand in the config?
do "plot" to "feplot"
Then i could use the modul fully.
Here is the error:

Server thread/ERROR [forgeessentials]: Command gamemode registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command worldborder registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias butcher of command febutcher registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias kill of command fekill registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias weather of command feweather registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command help registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias ? of command help registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command tp registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias reload of command fereload registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command plot registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias remove of command feremove registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias biomeinfo of command febiome registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias locate of command felocate registered twice
18.06 16:05:42 [Server] Server thread/ERROR [forgeessentials]: Command alias enchant of command feenchant

weird that command with the FE is dublicated too :S
