### ISSUE TITLE
Scripting engine should ignore lines that are empty.

### ISSUE THREAD

**Issue by AnrDaemon** [ForgeEssentials/ForgeEssentials#2097]
To reproduce, make a "$SERVER/ForgeEssentials/Scripting/login/join.txt" with a text similar to 
```

echo Welcome on our server @player!
```
(Note empty first line.)

When a player joins the server, it will error out with:

[01:32:52] [Server thread/ERROR] [ForgeEssentials]: Error in script "join.txt": Could not handle script action ""

I… Think it shouldn't do that?

**Comment by luacs1998** [comment]
@spacebuilder2020 do you want this?

**Comment by spacebuilder2020** [comment]
Sure

**Comment by spacebuilder2020** [comment]
Fixed by https://github.com/ForgeEssentials/ForgeEssentials/commit/33d297fe7c15af75b68d7170cbb79319c99368c0#diff-5209bc7547834412393ab984f4735423R266
