### ISSUE TITLE
Making a command that outputs a tellraw link

### ISSUE THREAD

**Issue by KremeChoco** [ForgeEssentials/ForgeEssentials#2098]
Hello,

So I decided to take a crack at it and make myself a simple command.
I was following the the example of the god script.

This is my script.

````
{
  "name": "site",
  "usage": "/site",
  "extraPermissions": {},
   "patterns": {
    "": [
      "$/tellraw @p Visit ["",{"text":"mysite","underlined":true,"clickEvent":{"action":"open_url","value":"http://mysite.net"}}] for more info!"
    ]
  },
  "aliases": []
}
````

This works when I put it in a command block, but when I put it in in a command, it doesn't work.

**Comment by spacebuilder2020** [comment]
$/ means that it is running the command as the server.  '@p' uses the sender as the argument.  As a result, the sender is the server and the server receives the message.

**Comment by olee** [comment]
You probably just didn't escape the json properly.
It should be
````
"$/tellraw @p Visit [\"\",{\"text\":\"mysite\",\"underlined\":true,\"clickEvent\":{\"action\":\"open_url\",\"value\":\"http://mysite.net\"}}] for more info!"
    ]
````

**Comment by KremeChoco** [comment]
Doing that outputs this
`Invalid json: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8`

**Comment by olee** [comment]
Use http://jsonlint.com/ for example to make sure your json is correct.

**Comment by KremeChoco** [comment]
It says it's valid. But I still get that error.

**Comment by spacebuilder2020** [comment]
Does this happens when the command is ran or when it is loaded with fereload?

**Comment by KremeChoco** [comment]
When the command is ran.
