### ISSUE TITLE
[Suggestion] Zones in dynmap

### ISSUE THREAD

**Issue by kerts93** [ForgeEssentials/ForgeEssentials#2100]
Would it be possible to integrate dynmap usage into FE so that the FE zones would be shown also on Dynmap Forge similary like it was on bukkit version of worldedit and dynmap?

**Comment by kerts93** [comment]
Optionally, it would be good if these zone can be seen on Dynmap also or any other way to actually see them, which should be possible since you also have client available.

**Comment by luacs1998** [comment]
#2050
