### ISSUE TITLE
blue text pop up

### ISSUE THREAD

**Issue by mightydanp** [ForgeEssentials/ForgeEssentials#2102]
blue text pop up in chat bar whenever i interact with anything.

**Comment by spacebuilder2020** [comment]
Can you provide some more background. Perhaps at the very least a screenshot so we can see what you are referring to.

**Comment by mightydanp** [comment]
http://imgur.com/BYOvgYZ
bottom left

**Comment by spacebuilder2020** [comment]
you might have /p debug on.  Try running it again to turn it off.

**Comment by spacebuilder2020** [comment]
Is this still an issue or not?

**Comment by spacebuilder2020** [comment]
@mightydanp Please respond.  Let me know if it was `/p debug` or not

**Comment by olee** [comment]
This output is from `/itemperm` command.
Using it again will disable it.

**Comment by spacebuilder2020** [comment]
This was recently brought up again and it has been determined that it is not the output of `/itemperm` but the output of `/protectdebug`
