### ISSUE TITLE
FE Crash

### ISSUE THREAD

**Issue by HeberonYT** [ForgeEssentials/ForgeEssentials#2104]
Good day,
I'm using FE 1.4.4.1182 my modded server 1.7.10 with Forge 10.13.4.1558.
The server worked well and normally, but a user notice me it was closed, and check the console had crashed, attached to the report and the last log.
I hope you can help identify the problem, just comment that FE does not seem to work with vip slots.
Thank you

**Crash Report:** http://pastebin.com/raw/vDiU25RB
**Log:** https://pastebin.com/raw/gJQw5MAS

**Comment by spacebuilder2020** [comment]
Looks like it is happening [here](https://github.com/ForgeEssentials/ForgeEssentials/blob/af7057744bf009c23de0c333daecad10813de7ca/src/main/java/com/forgeessentials/protection/ProtectionEventHandler.java#L893).  Though there is only 1 thing that could be null, (player.playerNetServerHandler).

Can you give me more information so I can replicate this error?

**Comment by spacebuilder2020** [comment]
@HeberonYT Please provide me more information about what mods you are using with forge essentials, etc.

**Comment by olee** [comment]
I guess this was a fakeplayer issue.
