### ISSUE TITLE
Cannot Clear a World Border

### ISSUE THREAD

**Issue by MCTyler** [ForgeEssentials/ForgeEssentials#2105]
Jenkins Build 1182, trying to disable World Border /wb disable has no effect on World Border. Problem is is that world border set in the Twilight Dimension and when player makes a portal in the overworld that's beyond the border it crashes the server. How can I get rid of the world border?

**Comment by spacebuilder2020** [comment]
Can you give us the entire server log when this is happening.

**Comment by MCTyler** [comment]
Nope, that would be a waste of both our time. The world border created by the Mod will not clear. There are no errors nothing, it just stays there.

**Comment by MCTyler** [comment]
If you could tell me where it stores that information about the border I could delete it, but unfortunately I think it permanently writes it to the DIM file itself, never to be removed.

**Comment by DomAmato** [comment]
I mean it would take like a minute and you could probably check the crash-reports for the server at least... but the world border information is in the [world name folder] /FEData/json/worldborder and the border is separated by world dimension id. There is also a backup in the FEData_backup in the same location so delete those and restart the server. That should delete the world border

**Comment by spacebuilder2020** [comment]
Enable debug mode (ForgeEssentials/main.cfg) and see if it throws anythign

Also post the crash reports.

**Comment by MCTyler** [comment]
Unfortunately, I already deleted that DIM since my players couldn't go to the Twilight World. Sorry I can't help more with this issue, but my original post was some time ago. If no one else is reporting this issue and all their World Borders are working fine, go ahead and close this issue. I would advise any Operator from ever creating a World border in different Dimensions due to this limitation.

**Comment by spacebuilder2020** [comment]
Ok, I am going to close this until someone else has the same issue so we can try and find it.

**Comment by MCTyler** [comment]
Ok, I think the main point is, when you type /wb clear, or whatever the command was the World border should go away but it does not. Thanks for your response.
