### ISSUE TITLE
Normal chat doesn't work

### ISSUE THREAD

**Issue by JunnQS** [ForgeEssentials/ForgeEssentials#2107]
When I try to use chat my messages don't show up unless i use /say. Basically, any command works but normal messages will not appear.

This problem appeared as soon as I installed FE on my server, before I had a chance to touch any configs. After that I tried to change permissions and enable public chat for all groups but this didn't help. I also tried to run FE on a clean server without other mods installed and the same thing happened. 

If I remove FE, the chat works again. 

What could be causing it?

Thank you.

**Comment by spacebuilder2020** [comment]
This has never happened to me.  What version of forge essentials are you using?

**Comment by JunnQS** [comment]
I'm using the latest build (1.8-1.8.4.77), also tried 1.8-1.8.3.54 and 1.8-1.8.3.40 and they all caused the same bug.

**Comment by spacebuilder2020** [comment]
The 1.8 builds have been discontinued in favor of 1.8.9
