### ISSUE TITLE
Not backing up mystcraft worlds.

### ISSUE THREAD

**Issue by Nicba1010** [ForgeEssentials/ForgeEssentials#2110]
Mystcraft worlds are not being backed up!

**Comment by olee** [comment]
Check the backup configuration.
There are simple rules on what is backed up and what not.
````
# Configuration file

Backup {
    # Backup all worlds by default
    B:backup_default=false

    # Automatic backup interval in minutes (0 to disable)
    I:backup_interval=60

    # Always backup worlds when loaded (server starts)
    B:backup_on_load=true

    # Always backup when a world is unloaded
    B:backup_on_unload=true

    # Folder to store the backups in. Can be anywhere writable in the file system.
    S:base_folder=.\ForgeEssentials\Backups

    # Define file patterns (regex) that should be excluded from each backup
    S:exclude_patterns <
        DIM-?\d+
        FEMultiworld
        FEData_backup
        DimensionalDoors
     >

    # Keep at least this amount of last backups
    I:keep_backups=1

    # Keep at least one daily backup for this last number of last days
    I:keep_daily_backups=1

    # Keep at least one weekly backup for this last number of weeks
    I:keep_weekly_backups=1

    #########################################################################
    # Worlds
    #-----------------------------------------------------------------------#
    # Add world configurations in the format "B:1=true"
    #########################################################################

    Worlds {
        B:0=true
    }
}
````

**Comment by spacebuilder2020** [comment]
@Nicba1010 Let us know if this solved your problem

**Comment by petrnowak** [comment]
hi, sorry for thread necromancy. I wass looking for explanation of configuration file and I've found nothing. Some parts of config file is a little bit cryptic:

- what does it mean "Worlds B:0=true" ?

- world "world" isn't included in backup, only world inside folder DIM1, DIM2, DIM-1, etc. World itself (i.e. folder "world") is missing.

- to be clear: backup means backuping of SAVED chunks. So its desirable to make some autosaving of world, right?

**Comment by spacebuilder2020** [comment]
Normally there is a backup for world...  So perhaps that is a bug,  We don't reopen closed issues that have been closed for years so, I would recommend creating an issue following our issue format and rules including as much details as possible.  Also, I agree that the config file is cryptic... I have no idea what B:0=true means.  I assume it means Boolean '0' = true but I am not sure.

**Comment by spacebuilder2020** [comment]
As a note, that config is done in the Forge Config format.  S = String, B = Boolean, I = int
```
 S:exclude_patterns <

>
```
is an String array

Worlds {

}
is a sub group

**Comment by petrnowak** [comment]
I got it from other config:  "B:0=true" - "0" is dimension number (i.e. 0=overworld, -1=nether, etc. So "B:0=true" means "backup overworld - yes"). That solved my first and second problem (see above).

The third problem: backup backups all chunks always.

Finally I decided to move to Aroma Backup. Much much much better solution. 

This issue could be closed... thanks.

**Comment by spacebuilder2020** [comment]
Yea, I will agree with you.  FE's backup solution isn't the best backup solution.  FE design is to simply provide a backup option but FE has never been a dedicated backup mod.
