### ISSUE TITLE
1187 has no commands

### ISSUE THREAD

**Issue by BeefyTim** [ForgeEssentials/ForgeEssentials#2117]
Recently installed 1187 to find that there are no commands added or changed. Mod seems to be dormant when installed.

**Comment by spacebuilder2020** [comment]
Give me a copy of your server log.  There should be no issues.

**Comment by spacebuilder2020** [comment]
@BeefyTim Please post your server log so I can determine what your issue is.  If you don't post your log, I can not fix your issue.

**Comment by BeefyTim** [comment]
Apparently the problem has resolved itself, weird.

**Comment by spacebuilder2020** [comment]
Great
