### ISSUE TITLE
Auto promote after auth login?

### ISSUE THREAD

**Issue by KodySalak** [ForgeEssentials/ForgeEssentials#2118]
Hello!
New FE user here, 
I want to know if there is a way to get the /auth login command to auto promote a new user from guest to member so they can use items. I cannot for the life of me figure this out... any help at all would be appreciated!
Thanks!

**Comment by spacebuilder2020** [comment]
Why do you need auth login to autopromote players?

**Comment by Zethalion** [comment]
I suppose you mean "/auth register [pwd]". I find it easy to force new players to walk over a pressure plate on top of a command block to change the membership from guest to a member group.

**Comment by KodySalak** [comment]
I can't get the permissions to work. Like I edit the text file to "true" for certain items and it won't accept it. That's why I wanted the login to autopromote, so it wouldn't be a hassle. But I don't know what's causing it to not read the permissions.

**Comment by Zethalion** [comment]
Have you followed this must read tutorial? https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial

**Comment by KodySalak** [comment]
Yes I have, hasn't helped.

**Comment by spacebuilder2020** [comment]
What file are you editing?  PermissionList.txt?

**Comment by KodySalak** [comment]
No, it's deeper. I don't remember off the top of my head and I'm not at the computer at the moment.

**Comment by spacebuilder2020** [comment]
Good.   PermissionList.txt is the wrong file but a few players think that editing it changes perms.  What happens when you run p reload after changing perms?

**Comment by KodySalak** [comment]
Absolutely nothing haha, it got very annoying! I am currently running my server without FE, will try FE again tonight.

**Comment by spacebuilder2020** [comment]
If the correct file is edited but has a json syntax error, it will fail to update.  Make sure you are updating the permissions.json file in world/FEData.  Finally, you are better off to use commands instead of editing perms directly.

**Comment by KodySalak** [comment]
ok, is there an easier way than adding each item separately?

**Comment by spacebuilder2020** [comment]
First post your permissions.json file so I can see if something is messed up

**Comment by spacebuilder2020** [comment]
Also you can use /p group _GUESTS_ allow [someperm] to give all members of the _GUESTS_ group all perms.

**Comment by KodySalak** [comment]
hey, sorry for the inactivity, but i cannot see a .json in that folder. nor anything with permissions written on it. im on 1.6.4 if that helps (stone age i know) lol

**Comment by spacebuilder2020** [comment]
@KodySalak 
You should have told us that before.  We thought you were on 1.7.10.  All the information on the wiki is for 1.7.10.  Permissions are a very different on 1.6.4.  Also it is no longer supported.  I am looking through the comments to see if I can find the old code and perhaps give you some more information.  But we won't be able to fix any bugs cause it is not supported.

**Comment by spacebuilder2020** [comment]
Last 1.6.4 Release (https://github.com/ForgeEssentials/ForgeEssentials/tree/1.3.0.4_f964_mc164)
