### ISSUE TITLE
Update to Hibernate 5.2

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentials#2120]
Can we look into this for the 1.8.9 branch? Not sure if it would fix our compile errors...

**Comment by spacebuilder2020** [comment]
Good idea.  I have read Hibernate 4.6 does not support java 8.  It was the source of my compilation errors earlier with 1.7.10

**Comment by luacs1998** [comment]
Closed by https://github.com/ForgeEssentials/ForgeEssentials/commit/c2788b1954e788109592e666a2b4a105d18aea5c
