### ISSUE TITLE
picking up where i left off (from #2118)

### ISSUE THREAD

**Issue by KodySalak** [ForgeEssentials/ForgeEssentials#2121]
hey, sorry for the inactivity, but i cannot see a .json for permisions in the world/FEData folder. nor anything with permissions written on it. im on 1.6.4 if that helps (stone age i know) lol

**Comment by spacebuilder2020** [comment]
Duplicate of https://github.com/ForgeEssentials/ForgeEssentials/issues/2118#issuecomment-234755384
