### ISSUE TITLE
server crahses when installing forge essentials

### ISSUE THREAD

**Issue by hotcody147** [ForgeEssentials/ForgeEssentials#2123]
Here is the crash log not sure what I did wrong to crash it.
http://pastebin.com/cX6pqrwe

**Comment by spacebuilder2020** [comment]
You have cauldron installed.  Cauldron is not supported.  If you enable safe-mode you can bypass this crash, but we won't offer any support for cauldron related crashes.  Use at your own risk.

**Comment by hotcody147** [comment]
okay thank you
