### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by ShatteredPixelz** [ForgeEssentials/ForgeEssentials#2124]
I have a very basic understanding of how this mod works, but I am confused on why the prefixes are not working on my server. I am using the Unabridged Mod-pack (without fast craft).
Thanks.
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/383260/modlist.txt)

**Comment by spacebuilder2020** [comment]
Can you post your permissions.json file?

**Comment by ShatteredPixelz** [comment]
Here it is.

`{
  "worldZones": {
    "-1": {
      "dimensionID": -1,
      "areaZones": [],
      "id": 13,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "0": {
      "dimensionID": 0,
      "areaZones": [],
      "id": 20,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-66": {
      "dimensionID": -66,
      "areaZones": [],
      "id": 18,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "1": {
      "dimensionID": 1,
      "areaZones": [],
      "id": 19,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-130": {
      "dimensionID": -130,
      "areaZones": [],
      "id": 22,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "2": {
      "dimensionID": 2,
      "areaZones": [],
      "id": 17,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-131": {
      "dimensionID": -131,
      "areaZones": [],
      "id": 23,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-132": {
      "dimensionID": -132,
      "areaZones": [],
      "id": 35,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-133": {
      "dimensionID": -133,
      "areaZones": [],
      "id": 25,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "69": {
      "dimensionID": 69,
      "areaZones": [],
      "id": 12,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-134": {
      "dimensionID": -134,
      "areaZones": [],
      "id": 26,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-7": {
      "dimensionID": -7,
      "areaZones": [],
      "id": 15,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-135": {
      "dimensionID": -135,
      "areaZones": [],
      "id": 36,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-136": {
      "dimensionID": -136,
      "areaZones": [],
      "id": 37,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-73": {
      "dimensionID": -73,
      "areaZones": [],
      "id": 2,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-137": {
      "dimensionID": -137,
      "areaZones": [],
      "id": 38,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-138": {
      "dimensionID": -138,
      "areaZones": [],
      "id": 39,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-139": {
      "dimensionID": -139,
      "areaZones": [],
      "id": 40,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-76": {
      "dimensionID": -76,
      "areaZones": [],
      "id": 4,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-140": {
      "dimensionID": -140,
      "areaZones": [],
      "id": 28,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-77": {
      "dimensionID": -77,
      "areaZones": [],
      "id": 5,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-141": {
      "dimensionID": -141,
      "areaZones": [],
      "id": 29,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-144": {
      "dimensionID": -144,
      "areaZones": [],
      "id": 31,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-145": {
      "dimensionID": -145,
      "areaZones": [],
      "id": 42,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-146": {
      "dimensionID": -146,
      "areaZones": [],
      "id": 43,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-147": {
      "dimensionID": -147,
      "areaZones": [],
      "id": 32,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-148": {
      "dimensionID": -148,
      "areaZones": [],
      "id": 44,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-149": {
      "dimensionID": -149,
      "areaZones": [],
      "id": 45,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-150": {
      "dimensionID": -150,
      "areaZones": [],
      "id": 46,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-151": {
      "dimensionID": -151,
      "areaZones": [],
      "id": 34,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-88": {
      "dimensionID": -88,
      "areaZones": [],
      "id": 10,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-154": {
      "dimensionID": -154,
      "areaZones": [],
      "id": 24,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-155": {
      "dimensionID": -155,
      "areaZones": [],
      "id": 27,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-156": {
      "dimensionID": -156,
      "areaZones": [],
      "id": 33,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-28": {
      "dimensionID": -28,
      "areaZones": [],
      "id": 41,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-29": {
      "dimensionID": -29,
      "areaZones": [],
      "id": 30,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-30": {
      "dimensionID": -30,
      "areaZones": [],
      "id": 21,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-100": {
      "dimensionID": -100,
      "areaZones": [],
      "id": 14,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-37": {
      "dimensionID": -37,
      "areaZones": [],
      "id": 7,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-38": {
      "dimensionID": -38,
      "areaZones": [],
      "id": 8,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-39": {
      "dimensionID": -39,
      "areaZones": [],
      "id": 9,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-42": {
      "dimensionID": -42,
      "areaZones": [],
      "id": 11,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "42": {
      "dimensionID": 42,
      "areaZones": [],
      "id": 3,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-112": {
      "dimensionID": -112,
      "areaZones": [],
      "id": 16,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-127": {
      "dimensionID": -127,
      "areaZones": [],
      "id": 6,
      "playerPermissions": {},
      "groupPermissions": {}
    }
  },
  "playerGroups": {
    "(2e7cc77d-b7d0-45b3-a842-eb3f87c7a988|ShatteredPixelz)": [
      ""
    ]
  },
  "id": 1,
  "playerPermissions": {
    "(fefefefe-fefe-fefe-fefe-fefefefefefe|$SERVER)": {
      "*": "true",
      "fe.internal.player.known": "true"
    },
    "(fefefefe-fefe-fefe-fefe-fefefefefecc|$RCON)": {
      "*": "true",
      "fe.internal.player.known": "true"
    },
    "(fefefefe-fefe-fefe-fefe-fefefefefecb|$COMMANDBLOCK)": {
      "*": "true",
      "fe.internal.player.known": "true"
    },
    "(fefefefe-fefe-fefe-fefe-fefefefefeec|$FE_ECONOMY)": {
      "fe.economy.command.wallet.*": "true",
      "command.give": "true",
      "fe.internal.player.known": "true"
    },
    "(2e7cc77d-b7d0-45b3-a842-eb3f87c7a988|ShatteredPixelz)": {
      "fe.internal.player.groups": "",
      "fe.internal.prefix": "[TheGodFather]"
    },
    "(2001c9aa-bbf8-306c-9b60-485e8cc6e215|$NPC)": {
      "fe.internal.player.known": "true"
    },
    "(fed35de3-51f7-4355-b931-b2bdb30d887b|Dweeston)": {
      "fe.internal.prefix": "\u00264[Pleb]"
    },
    "(0b883263-4b89-4ab2-bd1c-f60a09470db5|Hoppypoppy)": {
      "fe.internal.prefix": "\u00263[The Moji]"
    },
    "(77456a1f-b9f9-3f84-8863-ddef5b8e2209|[BuildCraft])": {
      "fe.internal.player.known": "true"
    }
  },
  "groupPermissions": {
    "_PLAYERS_": {
      "fe.remote.chat.send": "true",
      "fe.internal.group.priority": "1",
      "fe.internal.group": "true"
    },
    "_NPC_": {
      "fe.internal.group.name": "NPCs",
      "fe.internal.group.priority": "1",
      "fe.internal.group": "true"
    },
    "_FAKEPLAYERS_": {
      "fe.internal.group.priority": "15",
      "fe.internal.group": "true",
      "fe.protection.*": "true"
    },
    "_OPS_": {
      "fe.internal.prefix": "[\u0026cOP\u0026f]",
      "fe.internal.group.priority": "50",
      "fe.internal.group": "true"
    },
    "_ALL_": {
      "fe.remote.chat.send": "false",
      "some.test.permission": "true",
      "fe.chat.usecolor": "true",
      "fe.teleport.warp": "true",
      "fe.internal.group.name": "players",
      "fe.teleport.warp.set": "true",
      "fe.internal.group.priority": "0",
      "fe.internal.group": "true",
      "fe.teleport.tp": "true",
      "fe.commands.craft": "true"
    },
    "_CREATIVE_": {
      "fe.internal.group": "true"
    },
    "_ADVENTURE_": {
      "fe.internal.group": "true"
    },
    "faction_rank_owner": {
      "fe.faction.members.*": "true",
      "fe.faction.leave": "false",
      "fe.faction.ally": "true",
      "fe.faction.friendlyfire": "true",
      "fe.faction.invite": "true",
      "fe.internal.group.priority": "18",
      "fe.internal.group.parents": "faction_rank_op",
      "fe.faction.delete": "true"
    },
    "faction_rank_op": {
      "fe.faction.members.*": "true",
      "fe.faction.ally": "true",
      "fe.faction.friendlyfire": "true",
      "fe.faction.invite": "true",
      "fe.internal.group.priority": "16"
    },
    "_GUESTS_": {
      "fe.internal.prefix": "[GUEST]",
      "fe.internal.group.priority": "10",
      "fe.internal.group": "true"
    },
    "owner": {
      "fe.internal.prefix": "set \u00266[The GodFather]",
      "fe.internal.group.priority": "20",
      "fe.internal.group": "true"
    }
  }
}`

**Comment by spacebuilder2020** [comment]
You are not in any group (not even _GUESTS).  Did you mess around with factions before.  Also what version are you on.

**Comment by ShatteredPixelz** [comment]
I am on version 1.4.4.1887. And no, I have not messed around with factions yet. (what about making just myself have a prefix? ` "(2e7cc77d-b7d0-45b3-a842-eb3f87c7a988|ShatteredPixelz)": { "fe.internal.player.groups": "", "fe.internal.prefix": "[TheGodFather]" } `)

**Comment by spacebuilder2020** [comment]
That should work.  Btw, next time pastebin your file.  It is very hard to read as a comment. 
Also, is it throwing any errors when you do fereload?

**Comment by spacebuilder2020** [comment]
Also, not being in the _GUESTS_ group is a bug that happens when you remove someone from a group.  This has been fixed in the latest build though.

**Comment by ShatteredPixelz** [comment]
sorry... first time really using GitHub... But when I create a prefix by using the command 

`/p user shatteredpixelz prefix set (prefix)` absolutly nothing shows up..... I will try updating and see if that works

**Comment by olee** [comment]
@ShatteredPixelz You know that the prefix will only be visible in chat, not ingame above the head of players?

**Comment by ShatteredPixelz** [comment]
yea... but nothing shows up even when I add people to groups with prefixes

**Comment by ShatteredPixelz** [comment]
so I updated it to build 1190 and still nothing.....

**Comment by spacebuilder2020** [comment]
Sounds like a mod incompatibility issue or a bad permissions.json file.  Try removing all instances of fe.internal.group from your user name.

**Comment by ShatteredPixelz** [comment]
I believe its a Mod incompatibility only because I tried what you said, then decided to try installing build 1190 again on a backup [pre FE] and it did the exact same thing...

**Comment by spacebuilder2020** [comment]
Ok

**Comment by olee** [comment]
The question is which mod is incompatible...
Or maybe @ShatteredPixelz did you disable the FE chat module perhaps?

**Comment by ShatteredPixelz** [comment]
I don't believe I have disabled it unless It comes pre-disabled

**Comment by yuuka-miya** [comment]
Prefixes are confirmed working on 1.10.
