### ISSUE TITLE
Internal Server Error when trying to use bed.

### ISSUE THREAD

**Issue by arsenicCatnyap** [ForgeEssentials/ForgeEssentials#2125]
Searched before I posted this, though I didn't find much. Running the latest nightly build.

Basically, whenever a player tries to click on a bed to sleep, they are kicked out of the server and given a "internal server error" message. We've tried uninstalling FE, deleting FE folders and such but nothing seems to work. Morph and props is also in that log?, we've tried deleting and and reinstalling those aswell. Thought I'd post here seeing as FE comes up in the log. sorry if this is just something silly or the wrong place!
Thanks for any help!

Log: http://pastebin.com/YnpZ68if

* ___ is not a actual user, just blocked their name out

**Comment by luacs1998** [comment]
@spacebuilder2020 I vaguely remember you fixing this...

**Comment by spacebuilder2020** [comment]
yea.... I thought it did fix it.  Give me a sec to see why it is not fixed.

**Comment by olee** [comment]
As there was no response I guess it's fixed.
Closing
