### ISSUE TITLE
[Forge Support] Modpack + Factions.

### ISSUE THREAD

**Issue by Andrew2070** [ForgeEssentials/ForgeEssentials#2128]
Hi.

I have a Custom ModPack server built to use Factions.
However, The Configuration does say we can replace container/door etc arrays to work with forge.
What I am confused is how is it that I place these blocks in to have them protected?

The default configuration for the Container array is as follows:
"materialsContainer": [
    "DISPENSER",
    "CHEST",
    "FURNACE",
    "BURNING_FURNACE",
    "JUKEBOX",
    "BREWING_STAND",
    "ENCHANTMENT_TABLE",
    "ANVIL",
    "BEACON",
    "TRAPPED_CHEST",
    "HOPPER",
    "DROPPER"
  ],

Now How do i list another mod's items in there?
By Id? Name? id/name? what about metadata?

Just a few things I would like to know because I have invested a lot in this server and do not wish to make identical with 1000k other servers using MyTown and MyTown 2 for protection.

For future reference, what about possible forge support like MyTown, where users can create custom built protection json files that are used by Factions to protect from modded lands?

Anyhow, would love if my first question regarding customizing the configuration could be given a reply. 

Thanks!

**Comment by Andrew2070** [comment]
Does this plugin give support for both because i heard it lets forge hook into factions? or vice versas.

**Comment by spacebuilder2020** [comment]
@Andrew2070

**Comment by spacebuilder2020** [comment]
@Andrew2070 Based on your description, it sounds like you are using bukkit (Cauldron/Thermos). Forge Essentials has never been tested on bukkit nor is it designed in any shape or form to work with bukkit.  It has a partially implemented 'factions' component that has no relation to bukkit's 'factions' plugin.  If you want to tie into bukkit 'factions' this is not the right mod to do so.

**Comment by olee** [comment]
Closing this.
@Andrew2070 FE's factions module is not bukkit factions (and it's also still in dev).
It's just an WIP module.
