### ISSUE TITLE
A list of events available for scripting.

### ISSUE THREAD

**Issue by AnrDaemon** [ForgeEssentials/ForgeEssentials#2130]
This is a far-aiming idea, but a list of events available for scripting, similar to those generated for permissions, may be useful as a reference for script writers.

**Comment by luacs1998** [comment]
The way the scripting system works is by "keys".

A key can be called at any time, not just by events.

And besides, each key already has its own subfolder under scripting to store scripts, so I'm not exactly sure what you want.

**Comment by yuuka-miya** [comment]
New jscripting should be pretty flexible, this should be in the docs.
