### ISSUE TITLE
@p and @player don't work in script when using command block

### ISSUE THREAD

**Issue by DomAmato** [ForgeEssentials/ForgeEssentials#2133]
Using @p or @player as an arg will return @ as the player and the script will fail. 

My solution was this:
https://github.com/CityOfLearning/ForgeEssentials/commit/7a5273d145a319bbcbc16a142bb8fd4a04c3c3a3#diff-5209bc7547834412393ab984f4735423R193

**Comment by olee** [comment]
Please can you provide more of an example what you tried to do and what exactly didn't work?

**Comment by spacebuilder2020** [comment]
Fixed

**Comment by spacebuilder2020** [comment]
Wrong issue

**Comment by spacebuilder2020** [comment]
Can you give me an example script that causes this issue?

And the command used in the command block.

**Comment by DomAmato** [comment]
Heres the script
```
{
  "name": "cleardig",
  "usage": "/cleardig [player]",
  "extraPermissions": {
    "fe.commands.cleardig": "OP"
  },
  "permissionLevel": "TRUE",
  "patterns": {
    "": [
      "echo Usage: /cleardig [player]"
    ],
    "@p": [
      "echo clearing dig for player @0",
      "$/doas @p //pos1",
      "echo set pos1",
      "$/doas @p //pos2",
      "echo set pos2",
      "$/doas @p //expand 13 south",
      "echo expand",
      "$/doas @p //expand 3 down",
      "echo expand",
      "$/doas @p //expand 4 up",
      "echo expand",
      "permset user @p allow worldedit.region.replace",
      "echo set pemission for replace",
      "$/doas @p //replace dirt air",
      "echo replace",
      "permset user @p clear worldedit.region.replace",
      "echo set permission back",
      "$/doas @p //sel",
      "echo clear selection"
    ]
  },
  "aliases": []
}
```
and the command block command is pretty straight forward

`/cleardig @p`

**Comment by spacebuilder2020** [comment]
@p should be translated into a uuid or player name by the command block.  I will have to step through this.  Thanks for the script.

**Comment by spacebuilder2020** [comment]
This is no longer relevant since we have switched to jscripting.
