### ISSUE TITLE
ability to bypass permission checking on a PlayerEntity in scripting

### ISSUE THREAD

**Issue by jsrfuture** [ForgeEssentials/ForgeEssentials#2134]
I'm trying to do a simple /claim command, so it claim a 3x3 chunk around the players without giving them worldedit.selection.expand command because I want them to claim chunk, only.

Here's my attempt:
http://pastebin.com/rxscGB9q

It always says "the console cannot run that command".

**Comment by spacebuilder2020** [comment]
This command only works with player entities.  There is no way to specify a player.

**Comment by jsrfuture** [comment]
okey, thanks you. I think i understand what i could do.

**Comment by spacebuilder2020** [comment]
ok

You could try a doas comand.

**Comment by jsrfuture** [comment]
Thanks again, using doas @sender did work, can't hide the chat spam but everything seem to work just like i wanted.

http://pastebin.com/ahkKn5EA

**Comment by spacebuilder2020** [comment]
Do you want the ability to run a command as a player but with the permissions of server?

And ability to hide chat spam?

**Comment by jsrfuture** [comment]
well, yes that pretty much exactly what i want. Is there an alternative?

**Comment by spacebuilder2020** [comment]
Not right now.  But you can turn this issue into a feature request.

**Comment by jsrfuture** [comment]
great!

**Comment by Zethalion** [comment]
Closing this as of 1.7.10 FE changed scripting engine to JS.
