### ISSUE TITLE
ChatComponentTranslationFormatException in "/timedmessage list"

### ISSUE THREAD

**Issue by Techjar** [ForgeEssentials/ForgeEssentials#2138]
This spews out this exception when used in the console, and crashes the client when used in-game.

Full stack trace: https://gist.github.com/58a56b49c48e73f24ddacdfed2393ccb

**Comment by AnrDaemon** [comment]
Which exact command? Does it work without FastCraft?

**Comment by Techjar** [comment]
I said, /timedmessage list. That's the actual command. And I don't see how FastCraft would be causing an issue here since it's related to ChatComponentTranslation, and it crashes the client.

**Comment by AnrDaemon** [comment]
That wasn't clear. You didn't copy the command in the message body, and dechiphering all wrapped around subject isn't the most pleasing task.
Thanks for the report.
