### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by SinzPet** [ForgeEssentials/ForgeEssentials#2145]
Hello, i'm in the process of setting up FE on my server and i cant seem to find any guides/tutorials that are close to being good enough.
It is just unbelieveble to me that there are no tutorials :/

**Comment by Yggdresil** [comment]
There are plenty of good enough tutorials on the matter, it's probably just that you're looking for a FE tutorial when you should really be looking for an MCForge tutorial.

If not, the GitHub project you just posted the issue on has a wiki that explains the different FE features (albeit outdated on some matters but hey, you're always welcome to update it).

**Comment by SinzPet** [comment]
The forge essentials wiki barely helped at all :(
i looked through everything on there b4 i made this post

**Comment by SinzPet** [comment]
And maybe you misunderstood me, i have the mod installed and all, i just dont know how to set up all the features and stuff like that

**Comment by Yggdresil** [comment]
It's true that it is under development and some features aren't all that well documented but hell, I can understand that devs have lives too :)

Is there any particular feature you were looking into ? Might take the time to work on the wiki if it's doable in an evening.
Setting up FE is fairly straightforward unless you're looking at some very specific customization on data persistence and other things like that. Setting up other features is usually done through in-game commands that (usually) have a little help as to how they work.

**Comment by SinzPet** [comment]
well its mostly a tutorial on the permission system i want tbh
much stuff is pretty straight forward as u say, but some things are just teethgrintingly annoying to figure out :/
and thxx man!
