### ISSUE TITLE
Crash on mwtp with fe.protection.inventorygroup set

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentials#2146]
Build: 1.4.4.1197
http://pastebin.com/WL7Nx9nz
world_10 is named "mining"

current inventory included OpenComputers manual, Wireless Crating Terminal and ProjectE items. Baubles are installed.

used commands:
/perm global zone WORLD_10 value fe.protection.inventorygroup warfare
/mwtp mining

After restart the dimension WORLD_10 is loaded and entered. On returning to DIM0 with /mwtp surface, the original inventory is lost.

**Comment by Zethalion** [comment]
Updated to 1203
Same server crash: http://pastebin.com/6HUYmLV8

Is there anything I should change on the fe.protection.inventorygroup config?

**Comment by olee** [comment]
This is weird.
The error happens because in the serialized data there is a NBT-tag-list with a list type of `0` which is the constant for `TAG_END` which is like void.
Can you try if this happens with only FE as well?

**Comment by Zethalion** [comment]
I'll give it a try. Setting up an empty server with FE as the only mod.

**Comment by Zethalion** [comment]
I tried something else. This time I only had wireless crafting terminal in the inventory and I got the crash. 

Any other items are stored and retrieved correctly except for baubles. They are kept between the inventory groups. But maybe I should make another issue for baubles

**Comment by Zethalion** [comment]
The guilty mod is WirelessCraftingTerminal-1.7.10-rv3-1.8.7.1b.jar from https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files

**Comment by olee** [comment]
So it happens only if you have an item from that mod in your inventory?

**Comment by Zethalion** [comment]
Correct. I found no problems with items from other mods.
