### ISSUE TITLE
PlayerLogger fire logging changes

### ISSUE THREAD

**Issue by Techjar** [ForgeEssentials/ForgeEssentials#2149]
Should be pulled to playerlogger/develop branch, would've made a PR but it was inserting a bunch of extra commits because the branch is behind. Will need to be manually pulled.

https://github.com/Techjar/ForgeEssentials/tree/playerlogger-wip

**Comment by luacs1998** [comment]
Just make the PR anyway, it simplifies things a lot when I manually pull.

**Comment by Techjar** [comment]
Implemented in 505197f
