### ISSUE TITLE
/rollback doesn't behave as advertised

### ISSUE THREAD

**Issue by Techjar** [ForgeEssentials/ForgeEssentials#2153]
It does not take a minutes parameter, and the + and - subcommands just adjust by some seemingly random interval, regardless of what minutes and seconds I pass.

@olee I looked at the code, and I think I understand your intentions with the timeStep thing, but it honestly just becomes frustrating when trying to get to a specific time as it behaves in unpredictable ways. I think it should just be a fixed 1 minute step, or a given number of seconds, unless you have a better idea.

**Comment by olee** [comment]
Fixed by https://github.com/ForgeEssentials/ForgeEssentials/commit/5cff1c6970cd052ca32af7ff9bda64df156d42e1
