### ISSUE TITLE
[Scripting] Insertion of arguments does not work

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#2157]
Example is the FE `/god` command.
Using `/god on` will result in `Player  does not exist, or is not online` error.
This seems to happen because no playername was inserted in the action
`permset user @player deny fe.protection.damageby.*`.

@spacebuilder2020 I guess this has to do with your changes - please fix asap!

**Comment by Techjar** [comment]
But `/god off` works the same way, and it works, so that doesn't really explain it.

**Comment by spacebuilder2020** [comment]
/god on used to work.... Give me a sec to diagnose this.

**Comment by spacebuilder2020** [comment]
/god on is technically working.  It sets the permission correctly, but fails at the /heal operation.

I am trying to investigate why it thinks the player is invalid.

**Comment by spacebuilder2020** [comment]
Make sure that you have the correct version of /god

The script on my instance was out of date.  When I deleted the god.json file and let it regen, it worked fine.

**Comment by olee** [comment]
@spacebuilder2020 it should not have changed....

**Comment by spacebuilder2020** [comment]
See https://github.com/ForgeEssentials/ForgeEssentials/commit/33f6ce00b064bad2bbf63421ecd35c6070a3ca8b

**Comment by olee** [comment]
Ah I see now - `/heal` in the command cannot heal the current player any more because it does not seem to be passed to the command maybe?

**Comment by spacebuilder2020** [comment]
Actually, it is being told to run the command as a server

**Comment by spacebuilder2020** [comment]
So it can't heal the server

**Comment by olee** [comment]
Ok after some more checking I noticed, that it probably already didn't work before your changes - and as it seems you fixed it already...
(So it was only the old json file in my env)
