### ISSUE TITLE
My Zone protection doesn't work

### ISSUE THREAD

**Issue by SinzPet** [ForgeEssentials/ForgeEssentials#2158]
Hey, i'm setting up FE on my server, and i set a Zone named Spawn at my server spawn. i then added a bunch of protections against breaking things and allowing the use of beds and stuff like that. It worked perfectly for a day or so, but now it just stopped working and i have no idea why. Now every1 can break things at the spawn all of a sudden.
please help!

**Comment by Yggdresil** [comment]
1. Did you restart the server since? If yes, it might indicate an issue with permission persistence.
2. Are the people it worked on the same that can now break things? If not, it might indicate an issue with group assignement.
3. Querying FE regarding permissions, is FE still aware of them? (ie. does FE return them when asked about permissions on the Spawn zone?) It not, see 1. or you might have accidentally reset them.

What FE version are you running, what backend is FE using?

**Comment by SinzPet** [comment]
what i did was make _ALL_ unable to do anything in the area. and then i made a new group OWNERS and added only myself in it, and gave myself access.
and i have 2 accounts, yes, it worked for my other acc at first, it was unable to do anything, but now it can do all sorts of things there.
And yes, i have restarted the server several times.
yes, FE did return the right permissions and it did still recognize the area as spawn Zone.
what is backend?
im using FE build1187

**Comment by Yggdresil** [comment]
From what you're saying, it seems it should work but I have rarely had that big an issue with the permissions system so I think we'd have to dig a little deeper.

Why don't you try the latest stable build ([n°1215](http://ci.forgeessentials.com/job/FE/lastSuccessfulBuild/artifact/)) before anything else?

**Comment by SinzPet** [comment]
Thanks, i will try that now. and tbh, i deleted my permissions file and will redo it, and hopefully without any wierdness showing up this time

**Comment by Yggdresil** [comment]
Ok, well you should close the issue since it doesn't seem to be one.

**Comment by SinzPet** [comment]
well i'd planned on updating my progress after a while :)

**Comment by SinzPet** [comment]
.... and now i cant use the /getcommandbook command any more.... wth.
i did allow _ALL_ to that command, but my other acc thats not OP still cant use the command

**Comment by SinzPet** [comment]
Cant use the afk command either :(
i think its the fe.commands thats doing something wierd

**Comment by SinzPet** [comment]
modlist is another command in there i'd like to use on _ALL_

**Comment by SinzPet** [comment]
So,
a few questions.
how can i make those FE.commands work, only those that i want, not all of them. Bcus i tried allowing _ALL_ to use the ones i mentioned plus a few others, doesnt work.

And why does my server Kick me for being AFK when i have that thing turned to false in the Settings file?

**Comment by SinzPet** [comment]
And somehow it is only my OP account that gets kicked for AFK, and not the normal one

**Comment by olee** [comment]
Can you post your permissions.json file from world/FEData directory?
Preferrably as a gist or pastebin.

**Comment by SinzPet** [comment]
tbh, idk what gist or pastebin are

**Comment by SinzPet** [comment]
{
  "worldZones": {
    "0": {
      "dimensionID": 0,
      "areaZones": [
        {
          "name": "Spawn",
          "area": {
            "high": {
              "x": -32,
              "y": 256,
              "z": 241
            },
            "low": {
              "x": -95,
              "y": 0,
              "z": 183
            }
          },
          "shape": "BOX",
          "priority": 0,
          "id": 1,
          "playerPermissions": {},
          "groupPermissions": {
            "_ALL_": {
              "fe.internal.zone.exit": "You are now leaving the Spawn Area!",
              "fe.internal.zone.entry": "You are now in the Spawn Area, Welcome!",
              "fe.commands.*": "false",
              "fe.protection.interact.minecraft.crafting_table.*": "true",
              "fe.protection.interact.lotr.tile.lotr.highElvenCraftingTable.*": "true",
              "some.test.permission": "true",
              "fe.protection.interact.lotr.tile.lotr.highElvenBed.*": "true",
              "fe.protection.break.*": "false",
              "fe.protection.place.*": "false",
              "fe.protection.pressureplate": "true",
              "fe.protection.interact.*": "false",
              "fe.protection.interact.lotr.tile.lotr.gateDolAmroth.*": "true",
              "fe.protection.interact.minecraft.chest.*": "true",
              "fe.protection.interact.minecraft.jukebox.*": "true"
            },
            "OWNER": {
              "fe.protection.place.*": "true",
              "fe.commands.*": "true",
              "fe.protection.interact.*": "true",
              "fe.protection.break.*": "true"
            }
          }
        }
      ],
      "id": 6,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "1": {
      "dimensionID": 1,
      "areaZones": [],
      "id": 4,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "100": {
      "dimensionID": 100,
      "areaZones": [],
      "id": 3,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "101": {
      "dimensionID": 101,
      "areaZones": [],
      "id": 2,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-1": {
      "dimensionID": -1,
      "areaZones": [],
      "id": 5,
      "playerPermissions": {},
      "groupPermissions": {}
    }
  },
  "playerGroups": {
    "(2c57620a-4500-4546-8ce7-ba37ec1f756f|SinzPet)": [
      "OWNER"
    ]
  },
  "id": 1,
  "playerPermissions": {
    "(fefefefe-fefe-fefe-fefe-fefefefefefe|$SERVER)": {
      "*": "true",
      "fe.internal.player.known": "true"
    },
    "(fefefefe-fefe-fefe-fefe-fefefefefecc|$RCON)": {
      "*": "true",
      "fe.internal.player.known": "true"
    },
    "(2c57620a-4500-4546-8ce7-ba37ec1f756f|SinzPet)": {
      "fe.internal.player.groups": "OWNER"
    },
    "(fefefefe-fefe-fefe-fefe-fefefefefecb|$COMMANDBLOCK)": {
      "*": "true",
      "fe.internal.player.known": "true"
    },
    "(ed6c510c-5cd1-4276-b27a-23d905ffb00f|Roccorendil)": {
      "fe.internal.player.known": "true"
    },
    "(2001c9aa-bbf8-306c-9b60-485e8cc6e215|$NPC)": {
      "fe.internal.player.known": "true"
    }
  },
  "groupPermissions": {
    "_PLAYERS_": {
      "fe.internal.group": "true",
      "fe.internal.group.priority": "1"
    },
    "_CREATIVE_": {
      "fe.internal.group": "true"
    },
    "faction_rank_op": {
      "fe.faction.invite": "true",
      "fe.faction.friendlyfire": "true",
      "fe.faction.members.*": "true",
      "fe.internal.group.priority": "16",
      "fe.faction.ally": "true"
    },
    "_FAKEPLAYERS_": {
      "fe.internal.group": "true",
      "fe.protection.*": "true",
      "fe.internal.group.priority": "15"
    },
    "_NPC_": {
      "fe.internal.group": "true",
      "fe.internal.group.name": "NPCs",
      "fe.internal.group.priority": "1"
    },
    "_ALL_": {
      "fe.tickets.tp": "false",
      "command.nick": "false",
      "fe.commands.afk.announce": "true",
      "fe.commands.seen": "true",
      "command.whereis": "false",
      "fe.commands.afk": "true",
      "fe.commands.afk.autokick": "false",
      "some.test.permission": "true",
      "fe.internal.group": "true",
      "fe.reimm.compat.cavemap": "false",
      "fe.reimm.compat.radar.other": "false",
      "fe.reimm.compat.radar.player": "false",
      "fe.commands.modlist": "true",
      "fe.commands.rules": "true",
      "fe.reimm.compat.radar.mod": "false",
      "fe.commands.getcommandbook": "true",
      "fe.tickets.view": "false",
      "fe.internal.group.name": "players",
      "fe.internal.group.priority": "0"
    },
    "faction_rank_owner": {
      "fe.faction.invite": "true",
      "fe.faction.friendlyfire": "true",
      "fe.faction.delete": "true",
      "fe.faction.members.*": "true",
      "fe.internal.group.parents": "faction_rank_op",
      "fe.faction.leave": "false",
      "fe.internal.group.priority": "18",
      "fe.faction.ally": "true"
    },
    "_GUESTS_": {
      "fe.internal.group": "true",
      "fe.internal.group.priority": "10"
    },
    "_OPS_": {
      "fe.internal.group": "true",
      "fe.tickets.tp": "true",
      "command.nick": "true",
      "fe.internal.prefix": "[\u0026cOP\u0026f]",
      "command.whereis": "true",
      "fe.tickets.view": "true",
      "fe.commands.afk.autokick": "false",
      "fe.internal.group.priority": "50"
    },
    "_ADVENTURE_": {
      "fe.internal.group": "true"
    },
    "OWNER": {
      "fe.internal.group": "true",
      "fe.internal.group.priority": "20"
    },
    "ELVES": {
      "fe.internal.group": "true",
      "command.difficulty": "true",
      "command.fastTravelTimer": "true",
      "fe.commands.fly": "true",
      "command.alignment": "true",
      "command.tp": "true",
      "command.fastTravelCooldown": "true",
      "command.lotr_time": "true",
      "fe.commands.gamemode": "true",
      "fe.commands.time": "true",
      "fe.internal.group.priority": "20"
    }
  }
}

**Comment by olee** [comment]
@SinzPet THEN GOOGLE IT AT LEAST.... :angry: (fixed your post to be at least readable).

Now we will have to check if there's something wrong in the permissions...

**Comment by SinzPet** [comment]
yea sry im new to this platform :/
but thanks a bunch! i believe this will fix those things!
