### ISSUE TITLE
Build 1215 breaks Thermal Expansion and Botania

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentials#2159]
Somehow Thermal Expansion doesn't like this build. http://pastebin.com/gMDz2JHm

**Comment by Techjar** [comment]
Almost definitely the same issue as #2150

**Comment by Zethalion** [comment]
The bug seems to be introduced after build 1205. That build runs fine with Thermal Expansion. I tried build 1206 which is unusable due log spamming. Tried 1208 which fixes the spamming and that one gives the same crash.

**Comment by olee** [comment]
Can you test it again with latest build? It should work now.

**Comment by Zethalion** [comment]
Build 1217 tested.
fml-server-1.log http://pastebin.com/kDPX0YPS

Something else is going wrong now. The server won't even pass early start-up. Same thing happens without fastcraft too.

**Comment by luacs1998** [comment]
Can you get us a log without fastcraft?

**Comment by Zethalion** [comment]
Here you are: http://pastebin.com/RL4L74CC

**Comment by olee** [comment]
Ok try again with latest version - I tested it myself this time with ThermalExpansion and it worked now.
Will also have to merge this fix up to 1.8.9 now.

**Comment by Zethalion** [comment]
Yay! I can confirm build 1218 works!

Thank you very much @olee and team!
