### ISSUE TITLE
Config files isn't full

### ISSUE THREAD

**Issue by Vandaalite** [ForgeEssentials/ForgeEssentials#2160]
I start a forge server in 1.7.10 (forge-1.7.10-10.13.4.1614.jar) with Java 7, also with Forge Essentials (forgeessentials-1.7.10-1.4.4.1187-server.jar). But, the problem is, that I cannot find the AuthMe part in my config files. I check into the jar files, there is the AuthMe module, but he do not appear in the config files :/
There is also few mods (BiblioCraft and Tinker Construct).

I tried different version, but nothing change, that's why I submit this new issue.
Thanks for help
And sorry if the English isn't correct, I'm french ^^'

**Comment by olee** [comment]
FE has no AuthMe - you are probably confusing some stuff here.
Also remember that FE config is stored in `./ForgeEssentials/` directory.

If you have further questions, ask here.

**Comment by olee** [comment]
FE has no AuthMe - you are probably mixing up some stuff here.
Also remember that all FE configs are stored in `./ForgeEssentials/` directory.

If you have further options just ask here.
