### ISSUE TITLE
Build 1224 breaks on several mods.

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentials#2161]
Crashlog: http://pastebin.com/mcJfADqd
Also build 1222 gave the same crash.

Erroring mods:
- Botania
- ThermalExpansion
- DraconicEvolution
- EnderIO
- enderioaddons
- EnderZoo
- ExtraUtilities
- millenaire
- Railcraft
- OpenBlocks
- RandomThings
- runicdungeons

**Comment by spacebuilder2020** [comment]
What is the last build that it worked?

**Comment by Zethalion** [comment]
It looked it worked well with 1218.

**Comment by spacebuilder2020** [comment]
So to confirm 1218 worked but 1219 did not?

**Comment by Techjar** [comment]
Ok, wait a minute, what? How is EntityLivingBase getting broken before the DeobfuscationTransformer even runs?

**Comment by Zethalion** [comment]
Confirmed 1219 does not run.

**Comment by olee** [comment]
@Zethalion get your a** back in IRC and tell me if it works! :wink:

**Comment by Zethalion** [comment]
Build 1227
Tail of fml-server-latest: http://pastebin.com/ezjWCPbr
crashlog: http://pastebin.com/YngsE8Va

It got better. Only 3 mods of the list errored:
- Botania
- ThermalExpansion
- millenaire

**Comment by luacs1998** [comment]
@olee since it's a recurring issue, please don't close this until we can confirm that everything's fixed once and for all.

**Comment by Techjar** [comment]
Oh come on I swear we fixed this.

**Comment by Zethalion** [comment]
Build 1228 confirmed working.
