### ISSUE TITLE
FE crahs with mods entities

### ISSUE THREAD

**Issue by Diamssword** [ForgeEssentials/ForgeEssentials#2162]
It seems like the last Build of Forge essentials (build 92) conflicts with mods entites for me, I send you a crahs report where thaumcraft is involved, but bassically when I remove Thaumcraft, I got the same crash with entity of an other mod.
[crash-2016-08-26_09.03.15-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/438715/crash-2016-08-26_09.03.15-server.txt)

**Comment by luacs1998** [comment]
Probably something to do with #2161
