### ISSUE TITLE
World Edit help

### ISSUE THREAD

**Issue by SinzPet** [ForgeEssentials/ForgeEssentials#2169]
Hello good people of FE :)
I am trying to figure out how to change a biome from one to another with the World edit that is included in ForgeEssentials, just cant seem to figure it out :/

**Comment by luacs1998** [comment]
http://wiki.sk89q.com/wiki/worldedit

**Comment by SinzPet** [comment]
No, this is not how you do it, The link you gave is to regular world edit. FE WE doesnt work the same way. Thanks for nothing

**Comment by luacs1998** [comment]
It works the same way.

**Comment by SinzPet** [comment]
its Singpleplayer, 
and with WE, you're supposed to be able to do //chunk, and then //setbiome...
none of these work.
instead FE only has the wierd wand that bind to ones hand, no way to select a chunk unless manually selecting the chunk's corners and then doing //expandY. but even then , it has no way to change biome

**Comment by Techjar** [comment]
Well, then you must have deleted WorldEdit from the mods folder, or had an existing config and it did not extract it. Go download it and put it in the mods folder.

**Comment by SinzPet** [comment]
right thx
