### ISSUE TITLE
Setting Spawn does not work

### ISSUE THREAD

**Issue by hanakocz** [ForgeEssentials/ForgeEssentials#2170]
I updated to latest builds and since then I have serious problems with setting spawn and server using it.
I used `/p global spawn here`, 
But it is only sensitive where the /setworldspawn from vanilla MC is setted up. This was not a thing few versions back, when everyone spawned on desired point.

**Comment by AnrDaemon** [comment]
We would really appreciate, if you can be a little more specific.
What was last version for you where it worked, and to which version you upgraded where it stopped working?

**Comment by hanakocz** [comment]
I am sorry, but I needed to take a little pause from MC. Let's go for details.

I originally had FE build 1146, where it worked. But then I updated for later builds and it stopped working. I had my spawn position in other dimension than basic overworld, but first it took the coords where I setted it up and then teleported me to overworld on those coords, totally ignoring that I was setting it up in another dimension.
Dunno if I updated or so after that, but it did not worked with more versions, I tried those ones: 1187, 1234, 1256, 1265.

For checks if it is not just by messing in perms, I also deleted it all and recreated, but nothing worked, only reverting back to (quite a lot) old version.

Still I might have messed something really badly, but I don't know what that would be that would overwrite FE's spawn thingie for good until downgrade.

**Comment by olee** [comment]
I did some changes to spawn handling that it should be able to handle storing orientation for spawn.
It might be that there is a bug in that code.

**Comment by Pymous** [comment]
We do have the same issue with `forgeessentials-1.7.10-1.4.5.1324-server.jar`

`/setworldspawn` work fine, but `/p global spawn here` return a validation message but don't change the spawn-point.

**Comment by olee** [comment]
I will check spawn stuff now and fix it if neccessary.
