### ISSUE TITLE
/sethome

### ISSUE THREAD

**Issue by MCTyler** [ForgeEssentials/ForgeEssentials#2171]
You guys changed it from /home set to /sethome {name}. I love the change but it took awhile to figure this out. My Players will love Multple homes! Please update the Wiki.

**Comment by Techjar** [comment]
What? This wasn't changed. Are you sure you're using ForgeEssentials?

**Comment by MCTyler** [comment]
Yes I just updated with your autoupdate feature.....The wget command for the Dev version...Bad idea?

**Comment by Techjar** [comment]
Oh, I know what happened. We changed the command's name to /fehome and added a default alias for /home. However, because you have a config already, you didn't get this alias. You'll need to add it manually.

**Comment by MCTyler** [comment]
Hmmm, lol, how do I do that?

**Comment by Techjar** [comment]
In the Commands.cfg. This change was done to allow another mod's /home to be used without completely disabling the FE teleport module. You must have another mod adding /home functionality, so that's why it still works.

**Comment by MCTyler** [comment]
oh, ok, so just tell players to use /fehome and I should be set!

**Comment by Techjar** [comment]
Or like I said you can edit Commands.cfg and add the alias yourself.

**Comment by olee** [comment]
It might have been some other mod added a `/sethome` command.

**Comment by MCTyler** [comment]
For some reason when I updated to the latest Dev, and that's all I did, /home set and /warp all quit working and now I have to use fe in front of the commands. No big deal. Oh, BTW FTB Utilities have the sethome command, but I'm not sure why it suddenly came out like that.

**Comment by spacebuilder2020** [comment]
I have always used scripting to make a alias /sethome to /home set

/sethome is a useful alias.  Especially for people migrating from bukkit essentials.

**Comment by MCTyler** [comment]
Here's all the commands (I think) FTB Utilities is duplicating....
`[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command gamemode registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command alias kill of command fekill registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command alias weather of command feweather registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command help registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command alias ? of command help registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command tp registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command alias spawn of command fespawn registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command alias reload of command fereload registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command alias back of command feback registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command alias enchant of command feenchant registered twice
[20:10:37] [Server thread/ERROR] [ForgeEssentials]: Command time registered twice
`

**Comment by Techjar** [comment]
Those errors happen even in my dev environment, so it's not those.

**Comment by olee** [comment]
@MCTyler all the `/fe...` commands should have a default alias without the FE.
This happened in a recent update where the base command name (the one that is always registered) was changed to those `/fe...` to get rid of conflicts.
Check your commands.cfg if it has the alias for those commands.
If not maybe try stopping your server and deleting that file.

**Comment by MCTyler** [comment]
@olee Yes Sir, when I deleted the file yesterday and let it recreate, It updated and prefixed all the commands properly but when I typed **/home set**, it came back as a unknown command,(I assume because FTBU was interfering)...same with **/warp blah**, it came back as unknown warp till I set the warp using FTBU command **/admin setwarp blah**, then I could type **/warp blah**. FTBU sems to be overriding your commands where as before I updated, it did not.

**Comment by olee** [comment]
Then it should work if you use `/fewarp` for example or I think it also has an alias `/w`.
Also I don't know if you can disable / reconfigure commands from FTBU so `/warp` can be registered again.

But I think we can use this issue to add in option in FE to force it overwriting any conflicting commands if wanted.
