### ISSUE TITLE
Release date for ForgeEssentials 1.10.2?

### ISSUE THREAD

**Issue by Geranospiza** [ForgeEssentials/ForgeEssentials#2172]
Hello. This is obviously not an "Issue" but I really didnt knew where else to write.

Do you guys have an ETA for the ForgeEssentials for version 1.10.2?

If so, could you guys make a post in the news section of forgeessentials.com?

Thank you :D

**Comment by luacs1998** [comment]
I'm waiting for some new features to bubble up to 1.8.9, then after that I can discontinue 1.8.9 builds and shift my focus to 1.10.

Now that you mention it, I'll put up something there.
