### ISSUE TITLE
The server is not starting with latest Forge version...?

### ISSUE THREAD

**Issue by ChrisMintjes** [ForgeEssentials/ForgeEssentials#2173]
Is it only possible to use this mod with that exact version of Forge (10.13.4.1448)?

I am limited to selecting just one version in 1.7.10, which is the latest.

This is the problem I found in the console:
`02.09 13:47:02 [Server] Server thread/ERROR [FML]: The mod ForgeEssentials (Forge Essentials) requires mod versions [Forge@[10.13.4.1448,)] to be available
`

**Comment by Zethalion** [comment]
It helps if you tell which version of ForgeEssentials you're trying on which version of forge.

**Comment by ChrisMintjes** [comment]
Well, since I use multicraft with versions set up from my host I can't change the version.
But the last crashlog shows version Minecraft Forge 10.13.2.1291

Is there a version available to work with that version?

**Comment by spacebuilder2020** [comment]
It is built against 1448 or above.  Why can't your host update to the latest version of forge.   1291 is way out of date.   10.13.4.1558 is the recommended build for forge and 10.13.4.1614 is the latest.  I don't know why the minimum is set to 1448, you would have to ask @olee or @luacs1998 but it is probably for a reason since older versions of forge have some major bugs.

**Comment by ChrisMintjes** [comment]
Yeah, it seems the 1558 file is put in the map. But it uses an older version... I have already tried to contact my host.

Thanks though.
Send from Huawei mobile phone

-------- Oorspronkelijk bericht --------
Onderwerp: Re: [ForgeEssentials/ForgeEssentials] The server is not starting with latest Forge version...? (#2173)
Van: Alexander Davis
Aan: ForgeEssentials/ForgeEssentials
Cc: ChrisMintjes ,Author

It is built against 1448 or above.  Why can't your host update to the latest version of forge.   1291 is way out of date.   10.13.4.1558 is the recommended build for forge and 10.13.4.1614 is the latest.  I don't know why the minimum is set to 1448, you would have to ask @olee or @luacs1998 but it is probably for a reason since older versions of forge have some major bugs.

**Comment by ChrisMintjes** [comment]
I have already tried to contact my host, it seems both 4.1558 and 2.1291 are in that map.

Thanks though, I just need to enable the 4.1558 in some way.

**Comment by luacs1998** [comment]
@spacebuilder2020 it was set to 1448 a LONG time ago, I just forgot about it. Fixed in more recent builds.

@ChrisMintjes you'll need to ask your host how to use custom jars to start the server, and launch the server with the 1558 jar instead.
