### ISSUE TITLE
[1.7.10] Upgrading scripts to new scripting

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentials#2174]
Hello,

I just upgraded forge essentials for 1.7.10 from jenkins and I see the Scripting directory is not being created, I've looked trough the changelog and seen something is changing in scripting but the wiki is not updated...should I downgrade? I have some scripts I cannot leave out... please do not break it before moving to newer versions of minecraft-forge and leave it broken just to say "we won't support it anymore" like many mods are doing nowadays.

**Comment by luacs1998** [comment]
It's called JScripting now.

It's been rewritten, but if you have the latest builds there should be an auto-converter so your scripts will work just fine.

I'm not LexManos, I'm a reasonable guy. FE for 1.7.10 still has a pretty long way to go...

**Comment by Ganjalf-Amsterdoom** [comment]
> I'm a reasonable guy. FE for 1.7.10 still has a pretty long way to go...

Thank you, thank you so much. I'm going to copy over the Scripting/ directory in the ForgeEssentials dir and check how it works.
Is the "scripts" directory in the world/map directory the new place to put scripts?

**Comment by olee** [comment]
@Ganjalf-Amsterdoom: @Techjar and I have added a complete new scripting feature based on Javascript.
This basically allows you to do pretty much ANYTHING. Setting blocks, creating explosions, etc etc etc.

This is still a little bit [WIP](https://github.com/ForgeEssentials/ForgeEssentials/issues/2165) but will be stable one of the next days.

There is a command `/fescript upgrade` which you can run to convert your old scripts to some degree to the new system (do NOT just copy the files over - this would do nothing at all).
After that check each generated .js file. If you see some comments in them, it probably the converter couldn't handle these cases yet. Then please just send me the commented lines and I will quickly adjust the converter to be able to handle these cases.

If you want help on the new system I advise you to drop by in our IRC.
The wiki still needs some time to be updated as right now we are still investing all our time finishing this new feature.

**Comment by Zethalion** [comment]
Old engine is no longer supported. Converter is no longer part of FE so I'll close this one.
