### ISSUE TITLE
Feature request: multiworld difficulty level

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentials#2175]
Hello,

is it possible to have different difficulty levels for different multiworld? I ask because I use a flat multiworld to separate spawn from the survival map but lycanite mobs still spawn even with the mobspawning rule set to deny, other mobs don't spawn. If I could set difficulty 0 (peaceful) to the spawn dimension and only to that it would be awesome.

**Comment by olee** [comment]
You can use permissions to disable spawning mobs in the multiworld.
`/p global zone X deny fe.protection.mobspawn.natural.*` should do the trick (replace X with the world zone ID which you can find out with `/p list zones`).

**Comment by Ganjalf-Amsterdoom** [comment]
Excuse my ignorance, without any zone defined if I create a new world (a flat one for example) zones are still empty, I see the dimID for the dimension id but there are no zone listed by the zone list command, I tried using the dimID but I might be misunderstanding something. How do I see servers zones ids? zone list and area list show nothing.

**Comment by Techjar** [comment]
The world zones are named WORLD_<dimID>, dunno why this isn't listed on the wiki anywhere.
