### ISSUE TITLE
Unable to run FE on client and server at the same time.

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentials#2178]
Build 1324:
Using FE on client to setup and test config works great. Except for playerlogger but that's ok. The problem arises right after applying the new configs to a server running FE. The same client is unable to connect to a server running FE. The only solution is to shutdown the client, remove FE from it and reload the client. Because the client also loads a lot of extra resources it takes a lot of time to switch between local FE and server FE.

Can this issue be fixed so a client running FE server mod is capable to connect to a server running FE as well?

**Comment by olee** [comment]
logs

**Comment by Zethalion** [comment]
Tried with build 1326:
Works perfectly
