### ISSUE TITLE
forgeessential issue

### ISSUE THREAD

**Issue by ggbello** [ForgeEssentials/ForgeEssentials#2182]
can anyone say me how to fix this problem?

com.forgeessentials.api.permissions.PermissionEvent$AfterLoad@52861279: this is the error
this is the log it starts from the bottom idk how to reverse it sorry for the inconvenience

29.09 16:21:13 [Multicraft] Server stopped
29.09 16:21:13 [Multicraft] Not restarting crashed server.
29.09 16:21:13 [Multicraft] Server shut down (running)
29.09 16:21:12 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
29.09 16:21:12 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
29.09 16:21:12 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
29.09 16:21:12 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0]
29.09 16:21:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
29.09 16:21:12 [Server] INFO at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
29.09 16:21:12 [Server] INFO at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
29.09 16:21:12 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0]
29.09 16:21:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
29.09 16:21:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
29.09 16:21:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0]
29.09 16:21:12 [Server] INFO at com.forgeessentials.core.ForgeEssentials.serverStarting(ForgeEssentials.java:314) [ForgeEssentials.class:?]
29.09 16:21:12 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
29.09 16:21:12 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
29.09 16:21:12 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_75_ModulePermissions_serverStarting_FEModuleServerInitEvent.invoke(.dynamic) [?:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.permissions.ModulePermissions.serverStarting(ModulePermissions.java:130) [ModulePermissions.class:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.permissions.core.ZonedPermissionHelper.load(ZonedPermissionHelper.java:172) [ZonedPermissionHelper.class:?]
29.09 16:21:12 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
29.09 16:21:12 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
29.09 16:21:12 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_203_PlotManager_permissionAfterLoadEvent_AfterLoad.invoke(.dynamic) ~[?:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.economy.plots.PlotManager.permissionAfterLoadEvent(PlotManager.java:36) ~[PlotManager.class:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.economy.plots.Plot.loadPlots(Plot.java:402) ~[Plot.class:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.api.UserIdent.getFromUuid(UserIdent.java:201) ~[UserIdent.class:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.api.UserIdent.get(UserIdent.java:192) ~[UserIdent.class:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.api.UserIdent.<init>(UserIdent.java:144) ~[UserIdent.class:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.util.UserIdentUtils.resolveMissingUsername(UserIdentUtils.java:53) ~[UserIdentUtils.class:?]
29.09 16:21:12 [Server] INFO at com.forgeessentials.util.UserIdentUtils.fetchData(UserIdentUtils.java:67) ~[UserIdentUtils.class:?]
29.09 16:21:12 [Server] INFO at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374) ~[JsonReader.class:?]
29.09 16:21:12 [Server] INFO java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
29.09 16:21:12 [Server] Server thread/ERROR [FML]: Exception caught during firing event com.forgeessentials.api.permissions.PermissionEvent$AfterLoad@751df2ca:
29.09 16:21:12 [Server] Startup Done (3.845s)! For help, type "help" or "?"
29.09 16:21:11 [Server] Thread-17/INFO [ForgeEssentials]: Listing files for backup of world 0
29.09 16:21:11 [Server] Server thread/INFO Preparing start region for level 0
29.09 16:21:11 [Server] Thread-17/INFO Starting backup of dim 0...
29.09 16:21:11 [Server] Server thread/INFO [STDOUT]: [erebus.world.teleporter.TeleporterHandler:onWorldLoad:60]: added to net.minecraft.world.WorldServer@4d8491ec
29.09 16:21:11 [Server] Thread-16/INFO Backup finished
29.09 16:21:11 [Server] Thread-16/INFO [ForgeEssentials]: Listing files for backup of world 66
29.09 16:21:11 [Server] Server thread/INFO [STDOUT]: [erebus.world.teleporter.TeleporterHandler:onWorldLoad:60]: added to net.minecraft.world.WorldServerMulti@7c82690a
29.09 16:21:11 [Server] Thread-16/INFO Starting backup of dim 66...
29.09 16:21:11 [Server] Server thread/INFO [FML]: Loading dimension 66 (world) (net.minecraft.server.dedicated.DedicatedServer@3a8844b6)
29.09 16:21:11 [Server] Thread-15/INFO Backup finished
29.09 16:21:11 [Server] Thread-15/INFO [ForgeEssentials]: Listing files for backup of world -1
29.09 16:21:11 [Server] Server thread/INFO [STDOUT]: [erebus.world.teleporter.TeleporterHandler:onWorldLoad:60]: added to net.minecraft.world.WorldServerMulti@57bfc591
29.09 16:21:11 [Server] Thread-15/INFO Starting backup of dim -1...
29.09 16:21:11 [Server] Server thread/INFO [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@3a8844b6)
29.09 16:21:11 [Server] Thread-14/INFO Backup finished
29.09 16:21:11 [Server] Thread-14/INFO [ForgeEssentials]: Listing files for backup of world 1
29.09 16:21:11 [Server] Thread-14/INFO Starting backup of dim 1...
29.09 16:21:11 [Server] Server thread/INFO [STDOUT]: [erebus.world.teleporter.TeleporterHandler:onWorldLoad:60]: added to net.minecraft.world.WorldServerMulti@1816f7f3
29.09 16:21:11 [Server] Server thread/INFO [FML]: Loading dimension 1 (world) (net.minecraft.server.dedicated.DedicatedServer@3a8844b6)
29.09 16:21:11 [Server] Server thread/INFO [FML]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@3a8844b6)
29.09 16:21:11 [Server] Server thread/INFO [FML]: Holder lookups applied
29.09 16:21:11 [Server] Server thread/INFO [FML]: Applying holder lookups
29.09 16:21:11 [Server] Server thread/INFO [FML]: Injecting existing block and item data into this server instance
29.09 16:21:11 [Server] Server thread/INFO Preparing level "world"
29.09 16:21:08 [Server] INFO [16:21:08][FINE][noppes.npcs.controllers.LinkedNpcController:61] Done loading Linked Npcs
29.09 16:21:08 [Server] INFO [16:21:08][FINE][noppes.npcs.controllers.LinkedNpcController:40] Loading Linked Npcs
29.09 16:21:08 [Server] Server thread/INFO [FML]: Forge Mod Loader has successfully loaded 24 mods
29.09 16:21:08 [Server] Server thread/INFO [worldedit]: WorldEdit for Forge (version 6.1.1-SNAPSHOT) is loaded
29.09 16:21:08 [Server] Server thread/INFO [ForgeEssentials]: WorldEdit selection provider started.
29.09 16:21:08 [Server] Server thread/INFO [FML]: Itemstack injection complete
29.09 16:21:08 [Server] Server thread/INFO [FML]: Injecting itemstacks
29.09 16:21:08 [Server] Server thread/INFO [ServerTools]: Registering Flat Bedrock Generator
29.09 16:21:08 [Multicraft] Skipped 4 lines due to rate limit (30/s)
29.09 16:21:07 [Server] Server thread/INFO [ForgeEssentials]: Running ForgeEssentials 1.4.4.1187-release (7d9640c)
29.09 16:21:07 [Server] Thread-10/INFO [RefinedRelocation]: Version Checker Status: OUTDATED! Using 1.0.7d, latest 1.1.28, changelog: Slaughtered two crashes and a bug.
29.09 16:21:07 [Server] Server thread/WARN To change this, set "online-mode" to "true" in the server.properties file.
29.09 16:21:07 [Server] Server thread/WARN While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
29.09 16:21:07 [Server] Server thread/WARN The server will make no attempt to authenticate usernames. Beware.
29.09 16:21:07 [Server] Server thread/WARN **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
29.09 16:21:07 [Server] Server thread/INFO Starting Minecraft server on mc33.gamehosting.it:25666
29.09 16:21:07 [Server] Server thread/INFO Generating keypair
29.09 16:21:07 [Server] Server thread/INFO Default game type: SURVIVAL
29.09 16:21:07 [Server] Server thread/INFO Loading properties
29.09 16:21:07 [Server] Server thread/INFO [FML]: Itemstack injection complete
29.09 16:21:07 [Server] Server thread/INFO [FML]: Injecting itemstacks
29.09 16:21:07 [Server] Server thread/INFO [FML]: Holder lookups applied
29.09 16:21:07 [Server] Server thread/INFO [FML]: Applying holder lookups
29.09 16:21:07 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityAntlionBoss.func_70097_a at HEAD
29.09 16:21:07 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityTarantulaMiniboss.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityMobBlock.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityLeech.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityBlackAnt.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityMidgeSwarm.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityAntlionMiniBoss.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityWoodlouse.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityDragonfly.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityAntlion.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityMoth.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityBotFlyLarva.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityBotFly.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityMosquito.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityFly.func_70097_a at HEAD
29.09 16:21:06 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityBombardierBeetle.func_70097_a at HEAD
29.09 16:21:04 [Server] Server thread/INFO [STDOUT]: [com.pixelmonmod.pixelmon.config.PixelmonEntityList:addSpawns:110]: [PIXELMON] Registering entity spawns
29.09 16:21:03 [Server] Server thread/INFO [STDOUT]: [com.pixelmonmod.pixelmon.database.DatabaseHelper:getConnection:66]: Establishing Connection
29.09 16:21:03 [Server] Server thread/INFO [STDOUT]: [com.pixelmonmod.pixelmon.database.DatabaseHelper:getConnection:64]: Loading Database Driver
29.09 16:21:03 [Server] Server thread/INFO [STDOUT]: [com.pixelmonmod.pixelmon.database.DatabaseHelper:copyDatabaseFromJar:80]: Extracting database
29.09 16:21:03 [Server] Server thread/INFO [STDOUT]: [com.pixelmonmod.pixelmon.config.PixelmonItemsTMs:load:24]: PIXELMON: Loading TM/HMs
29.09 16:21:03 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into Entity10CanBreed.func_70097_a at HEAD
29.09 16:21:03 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into Entity6CanBattle.func_70097_a at HEAD
29.09 16:21:03 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into Entity4Textures.func_70097_a at HEAD
29.09 16:21:03 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into Entity3HasStats.func_70097_a at HEAD
29.09 16:21:03 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityTrainer.func_70097_a at HEAD
29.09 16:21:03 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityNPC.func_70097_a at HEAD
29.09 16:21:03 [Server] Server thread/INFO [ForgeEssentials]: Discovering and loading FEMob data...
29.09 16:21:03 [Server] Server thread/INFO [ForgeEssentials]: Requested to disable module ServerVote
29.09 16:21:03 [Server] Server thread/INFO [ForgeEssentials]: Requested to disable module perftools
29.09 16:21:02 [Server] Server thread/INFO [ForgeEssentials]: Modules from ForgeEssentials-1.4.4 are being loaded
29.09 16:21:02 [Server] Server thread/INFO [ForgeEssentials]: Requested to disable module AuthLogin
29.09 16:21:02 [Server] Server thread/INFO [ForgeEssentials]: Discovering and loading modules...
29.09 16:21:02 [Server] Server thread/INFO [ForgeEssentials]: Running ForgeEssentials 1.4.4.1187 (7d9640c)
29.09 16:21:02 [Server] INFO [16:21:02][FINE][noppes.npcs.controllers.ScriptController:64] ECMAScript: .js
29.09 16:21:02 [Server] INFO [16:21:02][FINE][noppes.npcs.controllers.ScriptController:58] Script Engines Available:
29.09 16:21:02 [Server] INFO [16:21:02][FINE][noppes.npcs.LogWriter:71] Thu Sep 29 16:21:02 CEST 2016
29.09 16:21:02 [Server] Server thread/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityNPCInterface.func_70097_a at HEAD
29.09 16:21:02 [Server] Server thread/INFO [FML]: Configured a dormant chunk cache size of 0
29.09 16:21:02 [Server] Server thread/INFO [FML]: Found 0 ItemStackHolder annotations
29.09 16:21:02 [Server] Server thread/INFO [FML]: Identifying ItemStackHolder annotations
29.09 16:21:02 [Server] Server thread/INFO [FML]: Found 341 ObjectHolder annotations
29.09 16:21:02 [Server] Server thread/INFO [FML]: Processing ObjectHolder annotations
29.09 16:21:01 [Server] Server thread/INFO [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, FLabsBF, customnpcs, euriA, euriB, euriC, euriD, euriE, euriF, euriG, ForgeAuth, ForgeEssentials, ironbackpacks, MTRM, picconiop, pixelmon, RefinedRelocation, ServerTools-BACKUP, ServerTools, erebus, worldedit] at SERVER
29.09 16:21:01 [Server] Server thread/INFO [FML]: Attempting connection with missing mods [mcp, FML, Forge, CodeChickenCore, FLabsBF, customnpcs, euriA, euriB, euriC, euriD, euriE, euriF, euriG, ForgeAuth, ForgeEssentials, ironbackpacks, MTRM, picconiop, pixelmon, RefinedRelocation, ServerTools-BACKUP, ServerTools, erebus, worldedit] at CLIENT
29.09 16:21:01 [Server] Server thread/INFO [FML]: FML has found a non-mod file CodeChickenLib-1.7.10-1.1.1.99-universal.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
29.09 16:21:01 [Server] Server thread/INFO [FML]: Forge Mod Loader has identified 24 mods to load
29.09 16:21:00 [Server] Server thread/WARN [MTRM]: Mod MTRM is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
29.09 16:20:58 [Server] Server thread/INFO [FML]: Also searching /mods/1.7.10 for mods
29.09 16:20:58 [Server] Server thread/INFO [FML]: Searching /mods for mods
29.09 16:20:58 [Server] Server thread/INFO [FML]: Found 0 mods from the command line. Injecting into mod discoverer
29.09 16:20:58 [Server] Server thread/INFO [MinecraftForge]: Completed early MinecraftForge initialization
29.09 16:20:58 [Server] Server thread/INFO [FML]: Replaced 183 ore recipies
29.09 16:20:58 [Server] Server thread/INFO [FML]: MinecraftForge v10.13.4.1614 Initialized
29.09 16:20:58 [Server] Server thread/INFO [MinecraftForge]: Attempting early MinecraftForge initialization
29.09 16:20:58 [Server] Server thread/INFO Starting minecraft server version 1.7.10
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityEnderCrystal.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityHorse.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityOcelot.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityWolf.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityBat.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityDragon.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityEnderman.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityPigZombie.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityGhast.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityZombie.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityWitherSkull.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntitySmallFireball.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityFireball.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityLivingBase.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityPlayer.func_70097_a at HEAD
29.09 16:20:57 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityPlayerMP.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityBoat.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityAnimal.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityMinecart.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityItemFrame.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityHanging.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityWither.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityMob.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntitySilverfish.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityXPOrb.func_70097_a at HEAD
29.09 16:20:56 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityItem.func_70097_a at HEAD
29.09 16:20:55 [Server] main/INFO [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
29.09 16:20:55 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into Entity.func_70097_a at HEAD
29.09 16:20:55 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityLivingBase.func_70097_a at HEAD
29.09 16:20:55 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityPlayer.func_70097_a at HEAD
29.09 16:20:55 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into EntityPlayerMP.func_70097_a at HEAD
29.09 16:20:55 [Server] main/INFO [ASM_MethodInjector]: Injecting MixinEntity.attackEntityFrom_event into Entity.func_70097_a at HEAD
29.09 16:20:55 [Multicraft] Skipped 13 lines due to rate limit (30/s)
29.09 16:20:54 [Server] main/INFO [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
29.09 16:20:54 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
29.09 16:20:54 [Server] main/INFO [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
29.09 16:20:54 [Server] main/WARN [FML]: The coremod com.forgeessentials.core.preloader.FELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
29.09 16:20:54 [Server] main/INFO [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
29.09 16:20:54 [Server] main/INFO [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
29.09 16:20:54 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
29.09 16:20:54 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/dom4j-1.6.1.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/hibernate-entitymanager-4.3.7.Final.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/pircbotx-2.0.1.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/jboss-transaction-api_1.2_spec-1.0.0.Final.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/slf4j-api-1.7.5.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/hibernate-jpa-2.1-api-1.0.0.Final.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/jboss-logging-3.1.3.GA.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/antlr-2.7.7.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/javassist-3.18.1-GA.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/hibernate-core-4.3.7.Final.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/hibernate-commons-annotations-4.0.5.Final.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/jboss-logging-annotations-1.2.0.Beta1.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/jandex-1.1.0.Final.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/xml-apis-1.0.b2.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/h2-1.3.175.jar to classpath
29.09 16:20:53 [Server] main/INFO [ForgeEssentials]: Added library /ForgeEssentials/lib/mysql-connector-java-5.1.22.jar to classpath
29.09 16:20:53 [Server] main/INFO [mixin]: SpongePowered MIXIN Subsystem Version=0.5.6 Source=file:/mods/forgeessentials-1.7.10-1.4.4.1187-server.jar Env=SERVER
29.09 16:20:53 [Server] main/INFO [LaunchWrapper]: Calling tweak class com.forgeessentials.core.preloader.FELaunchHandler
29.09 16:20:53 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
29.09 16:20:53 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
29.09 16:20:53 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
29.09 16:20:53 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
29.09 16:20:53 [Server] main/INFO [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
29.09 16:20:52 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
29.09 16:20:52 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
29.09 16:20:52 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
29.09 16:20:52 [Server] main/INFO [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
29.09 16:20:52 [Server] main/INFO [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
29.09 16:20:52 [Server] main/INFO [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
29.09 16:20:52 [Server] main/WARN [FML]: The coremod com.dynious.refinedrelocation.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
29.09 16:20:52 [Server] main/INFO [FML]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.7.10-1.4.4.1187-server.jar
29.09 16:20:52 [Server] main/WARN [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
29.09 16:20:51 [Server] main/INFO [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0, running on Linux:amd64:4.3.2-1.el7.elrepo.x86_64, installed at /java
29.09 16:20:51 [Server] main/INFO [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
29.09 16:20:51 [Server] main/INFO [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
29.09 16:20:51 [Server] main/INFO [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
29.09 16:20:51 [Server] main/INFO [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
29.09 16:20:50 [Multicraft] Loaded config for "Default"
29.09 16:20:50 [Multicraft] Starting server!

**Comment by liach** [comment]
Your json for plots is broken. Try to remove it from your server or post it here for assistance.
