### ISSUE TITLE
/execute Permissions?

### ISSUE THREAD

**Issue by Diamssword** [ForgeEssentials/ForgeEssentials#2184]
I wonder if there is a way to use the /execute vanilla command with Forge Essentials : when I try to execute something, like : /execute @e[type=Item] ~ ~ ~ /say a , of it fail beacause the items don't have te permission to execute à commande.

Any idea of how to solve this problem?

Also, of course, I'm in 1.8.9

**Comment by Zethalion** [comment]
You are trying to run a console command as a player. These commands can only be used in command blocks. But if you do want to run such a command as a player, you should wrap it into a script. Use Server.runCommand() in the script to get that job done.

**Comment by spacebuilder2020** [comment]
Why not try /doas [CONSOLE] (Command)

**Comment by Diamssword** [comment]
for spacebuilder : yes, but I want to use it in commands blocks conceptions to focus specifics entities (like armorstand), also, it seems to work only with real players.

Zethalion : It dosen't work in commands blocks neither, but I will try the scripting, thx.

**Comment by Zethalion** [comment]
Closing for now. If this is still an issue be free to comment.
