### ISSUE TITLE
group permissions

### ISSUE THREAD

**Issue by smerecz** [ForgeEssentials/ForgeEssentials#2185]
we have followed this guide https://github.com/ForgeEssentials/ForgeEssentials/wiki/Guide-%23-Protection-(world-guard)
 from the beginning and have made it to step 3 when we try to input the command line in step 3 it says group does not exist please help

**Comment by luacs1998** [comment]
What FE build are you running?

**Comment by smerecz** [comment]
i think we got it working thanks
