### ISSUE TITLE
[1.7.10] Build 1330 - fe.protection.craft on Tinkers Construct crafting station not triggered

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentials#2186]
Crafting permissions set to prevent items to be crafted function as expected on a vanilla crafting table but the Tinkers Construct crafting station bypasses those perms resulting in users able to craft items they shouldn't be able to.

Using '/p debug' shows fe.protection.craft in the log when using crafting table and it doesn't when using crafting station.

**Comment by luacs1998** [comment]
I can only think that they're not throwing events as they should.

**Comment by Zethalion** [comment]
I asked Boni about it and he replied "if it doesn't work out of the box. ..is anybody actually still developing 1.7?" which means I got no opening from that side. I browsed the github source but I couldn't find where the crafting code is for 1.7 nor 1.10 though. I have no idea if TiC is compatible with FE perms when 1.10 will start. All I can think of if this should be fixed is to hook in to somehow.

**Comment by luacs1998** [comment]
Not going to make special cases - but 1.10 doesn't change much (yet).

**Comment by Mrkol** [comment]
Can confirm this on build 109. Doesn't work with bibliocraft workbenches aswell, but for me in both cases FE seems to not let items be crafted even though it should, according to permissions. The check does not get fired too.

**Comment by Aclay161** [comment]
I have got fe.protection.craft.* with #allows crafting ect.

however the crafting on vanilla crafting tables and inventory crafting doesn't work at all

**Comment by Zethalion** [comment]
Closing for now
