### ISSUE TITLE
1.7.10 crash Reika/DragonAPI/Auxiliary/CoreModDetection

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [ForgeEssentials/ForgeEssentials#2187]
I just added latest forge essentials for 1.7.10 to my server modpack based around Reikas mods, it crash on startup with this in fm-server-latest-log, no crashlog directory or any other logs created:

http://pastebin.com/3Z6cr5sJ

If I remove forge essentials everything works fine.
Thank you for your time and for reference I reported to Reikas MC forum thread too.

**Comment by Techjar** [comment]
ASM conflict.

**Comment by Techjar** [comment]
Interestingly, there's a lot of crap mentioned in this stack trace, so I'm not even sure where the real problem is.

**Comment by Techjar** [comment]
Try removing Blood N Bones and see what that does.

**Comment by Ganjalf-Amsterdoom** [comment]
Disabling BNB lib,  suspended server mod and advanced spawn control mod solved the problem but I actually need those 2 mods.

**Comment by Techjar** [comment]
Well it seems more like BNB lib might be at fault here, based on the stack trace. The getCommonSuperClass appears to be implemented incorrectly and causing a circularity error. We ran into a similar problem with FE but it's been solved. Go bug the developer of BNB lib about it.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you for the help, I went cherry picking the mods and seems to be Suspended Server causing, thank you for your time and pardon to have disturbed.

**Comment by Techjar** [comment]
What exactly is Suspended Server anyways? Sounds like something hacky.

**Comment by Ganjalf-Amsterdoom** [comment]
is to "pause" the server when no players are on, I'm open to suggestions for any similar mod, I tried using a script to stop the server when the last player log out and to start it from linux xinetd on port knoking but it takes ages to start the server that way

**Comment by Techjar** [comment]
Ah, yeah that definitely sounds hacky. Honestly, I never saw a point to stopping/suspending a server when there's no players online. I guess people might have their reasons but I never did.

**Comment by Ganjalf-Amsterdoom** [comment]
I just hate when my players run quarries and leave for a week, I also don't allow chunk loading...that's the thing, and also to avoid people "skipping" on hardcore nights, bloodmoons and lycanite mobs events, but yeah, i'll try live without it, since I must choose I'd rather have FE than SuspendedServer.
