### ISSUE TITLE
Weird Right click problem 

### ISSUE THREAD

**Issue by Elscorpeo** [ForgeEssentials/ForgeEssentials#2188]
How do i disable whatever keeps making me do that whenever i right click

![2016-10-13_17 09 57](https://cloud.githubusercontent.com/assets/22821204/19358451/e37acf54-916d-11e6-8863-acc9709b61c4.png)

**Comment by luacs1998** [comment]
If you're referring to the words at the top of your screen, that's Just Enough Items (or something like that) not FE.
