### ISSUE TITLE
How exactly does inventorygroup work?

### ISSUE THREAD

**Issue by Haigen** [ForgeEssentials/ForgeEssentials#2189]
So I'm trying to use multiworld and everything works smoothly so far but I'm trying to have the players have a different inventory per world? Going by the wiki there's a permission for inventorygroup but I'm not sure I understand how to use it?

Any help is appreciated.

**Comment by mravery108** [comment]
Use /p global zone "zonename" value fe.protection.inventorygroup "inventoryname"

Exampe: /p global zone pvp value fe.protection.inventorygroup pvp

**Comment by Zethalion** [comment]
Should be resolved.
