### ISSUE TITLE
Multiworld creating new World with missing mods?

### ISSUE THREAD

**Issue by Poketechserver** [ForgeEssentials/ForgeEssentials#2191]
Hi,

creating a new world with multiworld leads to a world without mods (e.g. plantmegapack and missing things from other mods like missing trees from pams harvestcraft -crops are there-).
Well im using 130 mods and im sure there are some more missing mods in my generated multiwold.
Is there a solution to generate a multiworld with all the same stuff(mods) from my mainworld? 

Im using version 1.7.10

**Comment by olee** [comment]
If you create a normal multiworld, it should look the same as the default one, including all modded content. Maybe you didn't select the correct world provider.

**Comment by Poketechserver** [comment]
Thanks for your fast answer.
I created a new normal world. Just using /mw create nameofworld. If im listing the worlds, they are listed as normal. I dont even know how to select another world provider xD

**Comment by Zethalion** [comment]
Some mods are hard coded to generate blocks only in dimension 0 aka Overworld.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @Poketechserver

**Comment by Zethalion** [comment]
Actually, closing this as we cant fix this on our side. Refer this issue to any mod that prevents generating blocks in a Multiworld overworld.
