### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MCTyler** [ForgeEssentials/ForgeEssentials#2192]
Is this gonna be updated to 1.10.2?

**Comment by MCTyler** [comment]
Suks....Can't stay stuck in the past forever, Thanks anyway.

**Comment by Techjar** [comment]
You realize there's already a work-in-progress 1.10 branch, right?

**Comment by spacebuilder2020** [comment]
https://github.com/ForgeEssentials/ForgeEssentials/tree/110/develop

**Comment by MCTyler** [comment]
No, I checked this source page and didn't see anything...Thanks!

**Comment by MCTyler** [comment]
Ok...1.8.9...Were Forging that way!
