### ISSUE TITLE
/fe.teleport.warp.<whatever> issue

### ISSUE THREAD

**Issue by LordMikop** [ForgeEssentials/ForgeEssentials#2194]
Hello, Im using your mod forge essentials on mc version 1.7.10 and I cant get /fe.teleport.warp.<whatever> to work... I can only disable it totaly to group (noone can warp nowhere) or absolutly enable it (so anyone can tp everywhere)... I use direwolf20 server. Can you please help me? I think it just ignores the paramether after ...warp!

**Comment by olee** [comment]
Are you writing the warp name after the `fe.teleport.warp.`?

**Comment by LordMikop** [comment]
The syntax of my command is: "/p group (my group) allow fe.teleport.warp.(mywarp)".

**Comment by VulcanForge** [comment]
The actual permission is fe.teleport.warp.warp.warpname
Odd, I know. I only figured it out by using the /p debug command.

**Comment by LordMikop** [comment]
Thanks... I would never figure that one out! :)
