### ISSUE TITLE
Operators don't have any rights / are not added to _OPS_ group

### ISSUE THREAD

**Issue by DarthJimbo** [ForgeEssentials/ForgeEssentials#2195]
Testing the newly released 1334 right now on a 1.7.10 server because I have issues with knockback permission on all older versions (1187 and 1330). Now I resetted the complete mod (by removing the FE-dirs from minecraft server and world dirs) and I'm not able to execute any area or perm commands. Something is wrong here, further tests pending...

**Comment by AnrDaemon** [comment]
Did FE create default files after your removal of existing ones?

**Comment by professortechno** [comment]
The same thing is happening to me. It says you do not have permission to run this command. But I am pary of the OP group and server admin. I still can't create groups yet.

**Comment by olee** [comment]
Please send me a copy of your permission file(s).

**Comment by AnrDaemon** [comment]
Specifically, the `~/world/FEData` directory.

**Comment by Zethalion** [comment]
Same issues confirmed on a clean server instance:

[FEData.zip](https://github.com/ForgeEssentials/ForgeEssentials/files/575173/FEData.zip)
Tail of latest.log: http://pastebin.com/raw/wYET3xUM

**Comment by professortechno** [comment]
> {
  "worldZones": {
    "-1": {
      "dimensionID": -1,
      "areaZones": [],
      "id": 3,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "0": {
      "dimensionID": 0,
      "areaZones": [],
      "id": 4,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "1": {
      "dimensionID": 1,
      "areaZones": [],
      "id": 2,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-5000": {
      "dimensionID": -5000,
      "areaZones": [],
      "id": 9,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2542": {
      "dimensionID": -2542,
      "areaZones": [],
      "id": 7,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2543": {
      "dimensionID": -2543,
      "areaZones": [],
      "id": 19,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2544": {
      "dimensionID": -2544,
      "areaZones": [],
      "id": 15,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2545": {
      "dimensionID": -2545,
      "areaZones": [],
      "id": 13,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2546": {
      "dimensionID": -2546,
      "areaZones": [],
      "id": 8,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2547": {
      "dimensionID": -2547,
      "areaZones": [],
      "id": 10,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2548": {
      "dimensionID": -2548,
      "areaZones": [],
      "id": 16,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2549": {
      "dimensionID": -2549,
      "areaZones": [],
      "id": 12,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2550": {
      "dimensionID": -2550,
      "areaZones": [],
      "id": 17,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2551": {
      "dimensionID": -2551,
      "areaZones": [],
      "id": 14,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2552": {
      "dimensionID": -2552,
      "areaZones": [],
      "id": 18,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2553": {
      "dimensionID": -2553,
      "areaZones": [],
      "id": 21,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-2554": {
      "dimensionID": -2554,
      "areaZones": [],
      "id": 6,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-28": {
      "dimensionID": -28,
      "areaZones": [],
      "id": 20,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-29": {
      "dimensionID": -29,
      "areaZones": [],
      "id": 11,
      "playerPermissions": {},
      "groupPermissions": {}
    },
    "-30": {
      "dimensionID": -30,
      "areaZones": [],
      "id": 5,
      "playerPermissions": {},
      "groupPermissions": {}
    }
  },
  "playerGroups": {},
  "id": 1,
  "playerPermissions": {
    "(fefefefe-fefe-fefe-fefe-fefefefefefe|$SERVER)": {
      "*": "true",
      "fe.internal.player.known": "true"
    },
    "(fefefefe-fefe-fefe-fefe-fefefefefeec|$FE_ECONOMY)": {
      "fe.economy.command.wallet.*": "true",
      "command.give": "true",
      "fe.internal.player.known": "true"
    },
    "(fefefefe-fefe-fefe-fefe-fefefefefecc|$RCON)": {
      "*": "true",
      "fe.internal.player.known": "true"
    },
    "(13e38a12-e2fa-48a2-85ac-0cc853de2880|ProfessorTechno)": {},
    "(fefefefe-fefe-fefe-fefe-fefefefefecb|$COMMANDBLOCK)": {
      "*": "true",
      "fe.internal.player.known": "true"
    }
  },
  "groupPermissions": {
    "_PLAYERS_": {
      "fe.remote.chat.send": "true",
      "fe.internal.group.priority": "1",
      "fe.internal.group": "true"
    },
    "_NPC_": {
      "fe.internal.group.name": "NPCs",
      "fe.internal.group.priority": "1",
      "fe.internal.group": "true"
    },
    "_FAKEPLAYERS_": {
      "fe.internal.group.priority": "15",
      "fe.internal.group": "true",
      "fe.protection.*": "true"
    },
    "_OPS_": {
      "fe.internal.prefix": "[\u0026cOP\u0026f]",
      "fe.internal.group.priority": "50",
      "fe.internal.group": "true"
    },
    "_ALL_": {
      "fe.remote.chat.send": "false",
      "some.test.permission": "true",
      "fe.internal.group.name": "players",
      "fe.internal.group.priority": "0",
      "fe.internal.group": "true"
    },
    "_CREATIVE_": {
      "fe.internal.group": "true"
    },
    "faction_rank_owner": {
      "fe.faction.members.*": "true",
      "fe.faction.leave": "false",
      "fe.faction.ally": "true",
      "fe.faction.friendlyfire": "true",
      "fe.faction.invite": "true",
      "fe.internal.group.priority": "18",
      "fe.internal.group.parents": "faction_rank_op",
      "fe.faction.delete": "true"
    },
    "faction_rank_op": {
      "fe.faction.members.*": "true",
      "fe.faction.ally": "true",
      "fe.faction.friendlyfire": "true",
      "fe.faction.invite": "true",
      "fe.internal.group.priority": "16"
    },
    "_ADVENTURE_": {
      "fe.internal.group": "true"
    },
    "_GUESTS_": {
      "fe.internal.prefix": "[GUEST]",
      "fe.internal.group.priority": "10",
      "fe.internal.group": "true"
    }
  }
}



-- Sorry couldn't add file, wouldn't support file format.. :(

**Comment by professortechno** [comment]
Please contact after 2:15 Pm if you need anything else. :)

**Comment by Techjar** [comment]
I've put your file into a gist for readability. Please do this in the future.

**Comment by professortechno** [comment]
OK sorry.

**Comment by DarthJimbo** [comment]
Sorry, been a bit busy lately. Unfortunately I switched back to 1330 and began already to set it up. I'm gonna use a redstone clock for the knockback as FE seems to be a bit glitchy, if you want to lock players inside an area. (It works great to keep players out though)

**Comment by spacebuilder2020** [comment]
We reverted the code back to 1330 and that solved this issue.
