### ISSUE TITLE
Unknown Mod Compatibility Error

### ISSUE THREAD

**Issue by V3xatious** [ForgeEssentials/ForgeEssentials#2198]
Greetings!

I am currently on my fifth hour of trying to figure this out on my own (it's 3am) and I'm at the point of asking help.

[Crash Report](http://pastebin.com/mCw8JS4s)

I've done everything I could find online. Fastcraft is off. 

In the crash report it mentions there being an issue with AE2 r3 beta, however, the AE2 stuffs mod as far as I can tell is designed to work with it. I'm only getting this error with the ForgeEssentials mod activated, otherwise, the sever boots and I'm able to log on and do what whatever.

Thanks! Hopefully not making a fool of myself.

**Comment by spacebuilder2020** [comment]
Try disabling the irc module of Forge Essentials.  Based on the log it seems to be related to that.

Probably another mod has modified a class that the IRC Handler depends on.  Disabling that module hopefully will fix the error. (Or shed light on the real problem).

**Comment by Techjar** [comment]
Well it seems like you're missing the IRC bot dependency. TRy manually extracting the libraries folder from the FE jar.

**Comment by V3xatious** [comment]
I know some basic C++ programming. I downloaded DirtyJOE and opened up the chatconfig.class file to see if there was a way to disable the IRC module from loading...and failed. So I right clicked on the IRC folder and just deleted it out of the .jar.

It did say this:

13:24:30  [Warn] [ForgeEssentials]: WARNING! Using ForgeEssentials build #1146, latest build is #1334
13:24:30  [Warn] [ForgeEssentials]: We highly recommend updating asap to get the latest security and bug fixes

Which is strange because I thought I used the most recent one and didn't see that warning before deleting the IRC, but maybe I got my files mixed up.

Anyways, I'm watching it finish it's boot process with no problems. It's doing a scanning ores process from a different mod.  Once it finishes up and preps the spawn area I will hop on. I probably forgot to mention I'm using the prepared mod pack REvolution|3.

I did some scrolling through the log and found this as well.

13:26:07  [Error] [ForgeEssentials]: Command gamemode registered twice
13:26:07  [Error] [ForgeEssentials]: Command weather registered twice
13:26:07  [Error] [ForgeEssentials]: Command setspawn registered twice
13:26:07  [Error] [ForgeEssentials]: Command alias kill of command fekill registered twice
13:26:07  [Error] [ForgeEssentials]: Command alias pregen of command fepregen registered twice
13:26:07  [Error] [ForgeEssentials]: Command help registered twice
13:26:07  [Error] [ForgeEssentials]: Command alias ? of command help registered twice
13:26:07  [Error] [ForgeEssentials]: Command enchant registered twice
13:26:07  [Error] [ForgeEssentials]: Command tp registered twice
13:26:07  [Error] [ForgeEssentials]: Command alias sc of command sellcommand registered twice
13:26:07  [Error] [ForgeEssentials]: Command alias r of command reply registered twice
13:26:07  [Error] [ForgeEssentials]: Command warp registered twice
13:26:07  [Error] [ForgeEssentials]: Command back registered twice
13:26:07  [Error] [ForgeEssentials]: Command alias reload of command fereload registered twice
13:26:07  [Error] [ForgeEssentials]: Command home registered twice
13:26:07  [Error] [ForgeEssentials]: Command spawn registered twice
13:26:07  [Error] [ForgeEssentials]: Command time registered twice

So something is do the same things as ForgeEssentials. I'll have to test those commands out in game and see if they still function as intended. 

Logging in from my Minecraft client....

And it seems to be working. Let me test out some of the commands.

Seems like everything is functioning. I appreciate the help! I know it's not something you have to do so from the bottom of my heart, thank you. 

If you need any other information, let me know and I'll grab any kind of log for you.

**Comment by luacs1998** [comment]
Everything OK, I presume.
