### ISSUE TITLE
Forgeessentials update causeing corruption

### ISSUE THREAD

**Issue by cyberwarp535** [ForgeEssentials/ForgeEssentials#2199]
I was running a FTB Regrowth server with forgeessentials 1330 on it just fine, Once I updated the jar file to 1334 all the sudden I was getting a corruption of the save file. I have trouble shot and find that if I run Regrowth with 1330 all seems to be fine. If I do a new Regrowth with 1334 All seems to be fine. If I drop in replace I get corruption. If I drop in replace after deleting the Forgeessentials directory All seems fine. It appears to be a issue with upgradeing only. the relevent portion of minecraft loading can be found at http://dcwc.dynu.com/error.txt

**Comment by spacebuilder2020** [comment]
We reverted back to 1330 due to issues with olee's refactoring.  So this should not be an issue anymore.
