### ISSUE TITLE
1.7.10 /mw commands without any permissions

### ISSUE THREAD

**Issue by Electrodevice** [ForgeEssentials/ForgeEssentials#2202]
If I type anyone of /mw commands - server write next:
You don't have permissions to use this command!
How can I set premission to multiworld commands?

It happen if I use mw in server command line to. Opped player can't use to... Nobody have permissions.

version FE 1.7.10 
Forge (version 6.1.1-SNAPSHOT) is loaded

[bspkrsCore]: Initializing ModVersionChecker for mod bspkrsCore
[21:01:22] [Server thread/INFO] [ForgeEssentials]: Running ForgeEssentials 1.4.5.1334-nightly (d6d5137)
[21:01:31] [Server thread/INFO] [bspkrsCore]: Initializing ModVersionChecker for mod Treecapitator

This is all of installed mods.

**Comment by Electrodevice** [comment]
It brake my brai...
Why I in group _PLAYERS_ if I - op myself?
Why console don't hawe mw and p permissions??

Is anybody know what happen and what can I do?

**Comment by spacebuilder2020** [comment]
ops by default do not have full permission.  You should in most cases have a dedicated admin group that have full permissions but if you want ops to have full permissions, run this command.

`/p group _OPS_  allow *`

if it still does not work let me know.

**Comment by Electrodevice** [comment]
[11:25:57] [Server thread/WARN] [ForgeEssentials]: This should never be called! The subclass FECommandParserArgs should overwrite this.
[11:25:57] [Server thread/ERROR] [ForgeEssentials]: Error writing translation file.
[11:25:57] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: You don't have permissions to use this command!


permission commands broken too.
I clear logs and make one for one session now.

**Comment by Electrodevice** [comment]
Sorry, but ltest.log file not include all text from console. I ctrl+C - +V from window. 
log:
https://gist.github.com/Electrodevice/1da14a45469513f6b1038a0a81e8c6d8

copy-paste from console screen not equal to log and I paste it in next comment

**Comment by Electrodevice** [comment]
Serwer print this:
https://gist.github.com/Electrodevice/3ee2ca04cbf78fcd3174f187f69e08c8

If You need to other logs - just say me that name and where that saved.

**Comment by Electrodevice** [comment]
Not all permission commands is broken. The list command work, so result of p list perms:
http://i.piccy.info/i9/ee26f8f019fc3c11652daad1c85c07cc/1480158360/381386/1090928/permissions.png

Why I in PLAYERS if i opped myself with /op minecraft commands?
Why console have such as player permissions?

**Comment by spacebuilder2020** [comment]
I made a typo in the command... Try it now

**Comment by Electrodevice** [comment]
/p groups _OPS_ allow *
[17:21:09] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Unknown command argument

Problen\m in ops permissions? But I not have group _OPS_ - if I use "op <player> then i get opped in minecraft only, p list perms show me as player not _OPS_

**Comment by Electrodevice** [comment]
/p group _OPS_ allow * was right, but I haven't permissions.

**Comment by spacebuilder2020** [comment]
I thought that would be the case based on your log.  This is a bug with multiworld.

**Comment by Electrodevice** [comment]
Yes, but errors in both look the same. Both groups of commands (/ p and / mw) causing the same reaction in the  server.

**Comment by Electrodevice** [comment]
I replace my FE to latest version from curse - it fix problem. That work all.
[ForgeEssentials]: WARNING! Using ForgeEssentials build #1187, latest build is #1334

/mw haven't any trouble, but it may be interesting -  In the perms operators absent.
proof:
http://i.piccy.info/i9/7cf4159b77be4fe73129be258739e4f5/1480182399/247822/1090928/whereops.png
