### ISSUE TITLE
Problem with pregen command

### ISSUE THREAD

**Issue by wormzjl** [ForgeEssentials/ForgeEssentials#2204]
When I tries to use the pregen command, I got the follwing
§cInvalid arguments. Use [dim] [perTick] [ctrX] [ctrZ] [radius].
Which is apparently different from /pregen start [full-pregen] [dim]
The info on the wiki seems to be outdated
What's the problem here?

**Comment by Zethalion** [comment]
Basically all you need to enter is "/pregen start" to pregen the dimension you are in entering the command.
The arguments you are mentioning were dropped quite some time ago.
