### ISSUE TITLE
World Edit Remove Bedrock

### ISSUE THREAD

**Issue by Generator-X** [ForgeEssentials/ForgeEssentials#2205]
USE:
- FTB Infinity Evolved
- forgeessentials-1.7.10-1.4.5.1334-server.jar
- http://pastebin.com/kzXppNS7

//hpos1
//hpos2
//expand vert
//cut

Hi,

I want to make everything that is labeled was deleted except bedrock.
What should I set to bedrock was not deleted?

**Comment by luacs1998** [comment]
http://wiki.sk89q.com/wiki/WorldEdit
