### ISSUE TITLE
No power to execute commands in console

### ISSUE THREAD

**Issue by minimeistro** [ForgeEssentials/ForgeEssentials#2207]
So I haven't touched a thing in the config files yet when i try to add a group to a player even in the console, whether they are opped are not the server returns that I don't have permissions and "This should never be called!". This happens when I pretty much try to run any permissions command.
I'm in the Direwolf20 pack running MC 1.7.10 on a Windows Server

**Comment by spacebuilder2020** [comment]
What build are you on?  Permissions are broken on builds after 1330, so try downgrading and seeing if that fixes your problem or if this is a separate permission issue.

**Comment by spacebuilder2020** [comment]
This is probably due to Olee's refactoring in 1331 to 1334.   We reverted those changes in later builds so I don't think this is an issue anymore.
