### ISSUE TITLE
version check won't disable

### ISSUE THREAD

**Issue by willis936** [ForgeEssentials/ForgeEssentials#2209]
B:versionCheck=false in main.cfg

There is still a yellow message that says the build is out of date on player login.

**Comment by PotatoSauceVFX** [comment]
What version of FE are you using?

**Comment by willis936** [comment]
Sorry for the late response.

forgeessentials-1.7.10-1.4.5.1330-server

**Comment by luacs1998** [comment]
Fixed in https://github.com/ForgeEssentials/ForgeEssentials/commit/1a5a597cb4327f25cc493c331df82b906c1b2001
