### ISSUE TITLE
I am owner of a ForgeEssentials fork?

### ISSUE THREAD

**Issue by ErikSteiner** [ForgeEssentials/ForgeEssentials#2211]
I realized that I am the owner of a fork of ForgeEssentials. I don't know why, but it seems like there were some commits and some development going on. I can't remember that I created a fork. Could I delete that repository?

**Comment by olee** [comment]
1. Learn git / github
2. You can safely delete that - it does not show any commits that are not in FE yet  
  (maybe you clicked the fork button by accident)
