### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by LoonyBoB** [ForgeEssentials/ForgeEssentials#2212]
I'm sure it's a really stupid mistake on my end that has caused this but I can't place what it is.  

I have FE running on my 1.7.10 server and for some reason none of the commands seem to be so much as registered in the game.  It's almost as if I've not even installed the game.  I don't suppose you have any ideas on why that might be?  All the other mod commands seem to be working fine.

I'm using Forge 10.13.4.1556, if that impacts anything.  About 100 mods but none of them seem to have a home command or anything.

**Comment by spacebuilder2020** [comment]
Please post your full server log.  I can't help you without that.

**Comment by LoonyBoB** [comment]
Couldn't get github to allow me to attach them, even as a zip file, so I've uploaded them - http://www.aiyon.com/keke/serverlogs.zip - I just included the current .log files from the server folder, I'm guessing you don't need the many archives.  I hope that's enough.  If not, let me know.

**Comment by spacebuilder2020** [comment]
You can use pastebin or gist in the future to post logs.

**Comment by spacebuilder2020** [comment]
I think I found your issue.  It seems you are loading the optional client module on your server.

Try again with the server version.

**Comment by LoonyBoB** [comment]
Massive facepalm on my end over that... big stupid on my part.

It seems, however, after I put the server jar into the mods folder (client jar either staying or deleted, tried both) my server will no longer start... it attempts a few times and then stops.  If I delete the server jar then it works fine again.

Tried with no mods and a fresh world, booted fine.
Tried with ONLY the forge essentials mod and a fresh world, got the following...
http://pastebin.com/3ECW6PjE

Don't suppose you could provide assistance on that too? :(  Sorry for being a bother.

**Comment by Zethalion** [comment]
@LoonyBoB You're trying to run FE on J7 while it requires J8

**Comment by luacs1998** [comment]
Sounds like a minor matter - I'll close this then.

**Comment by LoonyBoB** [comment]
Thanks a huge amount for your help, everyone.  It's really appreciated. :)
