### ISSUE TITLE
ForgeEssentials for Forge 1.7.10 - 10.13.4.1614

### ISSUE THREAD

**Issue by Breadabix** [ForgeEssentials/ForgeEssentials#2213]
Hi, could anyone tell me if there is a version of this either released or in development for Forge version 1.7.10 - 10.13.4.1614. Thanks

**Comment by Zethalion** [comment]
The one on Curse is compatible with it an so are the builds on Jenkins. Why do you ask?

**Comment by Breadabix** [comment]
I could not find a version for forge 10.13.4.1614, why else would I be asking.

**Comment by spacebuilder2020** [comment]
Forge essentials has supported 1614 for quite a while now.  Just download the latest stable build.
