### ISSUE TITLE
[Feature Request] FastAsyncWorldEdit or an equivalent

### ISSUE THREAD

**Issue by TheRandomLabs** [ForgeEssentials/ForgeEssentials#2215]
Large WorldEdits can freeze the server for several seconds. If [FastAsyncWorldEdit](https://minecraft.curseforge.com/projects/fastasyncworldedit-forge) was bundled with this mod, or an equivalent was made, this issue could be mitigated. FastAsyncWorldEdit is licensed under GPL so there probably wouldn't be any licensing issues.
Also, irrelevant, but are there any major issues when using the 1.10.2 version with 1.11.2?

**Comment by spacebuilder2020** [comment]
Forge Essentials currently does not support 1.11 in any shape or form.   I have no idea if it will even run if you try to run it on 1.11.  You are welcome to try but you are on your own.

As for FastAsyncWorldEdit, there are no plans to implement such a feature.
