### ISSUE TITLE
Any version above 1.4.4.1187 crashes my server. [1.7.10]

### ISSUE THREAD

**Issue by m0nkm0nk** [ForgeEssentials/ForgeEssentials#2216]
Tried many versions with 1.4.5.xxxx but without luck.
So I'm still on 1.4.4.1187 but would really like to update.

Crashlog:
http://pastebin.com/D5s80g4M

**Comment by Zethalion** [comment]
Remove Ars Magica 2. And if you really want to keep that mod, stay on build 1187.

**Comment by m0nkm0nk** [comment]
Ok thanks! Just wanted to make sure :)
