### ISSUE TITLE
Any way to disable the MajoritySleeping feature?

### ISSUE THREAD

**Issue by Solucent** [ForgeEssentials/ForgeEssentials#2217]
Me and my friends are about to start a moderately big modded server, and we have witchery installed, with vampires and such. But because vampires need to go out in the night, and the Sleeping function shows explicitly who's trying to sleep, people could easily weed out who the vampires on the server are.

Main.cfg allows you to adjust how many people need to sleep, but setting it to 0% just makes it instantly daytime if anyone right clicks on a bed. Basically, is there anyway to disable this feature, or at least remove the playername from the world announcement? Thank you in advance,

**Comment by spacebuilder2020** [comment]
I don't see anywhere in the code that this says the name of the players.  I know Morpheus outs the player names but not here.  Can you give me a screenshot of it making the announcements?

**Comment by luacs1998** [comment]
Did you try setting it to 100%?

**Comment by yuuka-miya** [comment]
@Zethalion and I can confirm that setting it to 100 disables majority sleep.
