### ISSUE TITLE
Fastcraft on, shop, sell doesn't work? 1.7.10

### ISSUE THREAD

**Issue by Demonyo** [ForgeEssentials/ForgeEssentials#2220]
As long as Fastcraft is active, we can get any sell or shop working.. as soon as we remove fastcraft, the server lag like mad, but sell and shops are working?!?!?!

ATM, we are running
Fastcraft 1.23
forgeessentials-1.7.10-1.4.5.1330

Is there any way we can get plot, sell, shop to work while still running fastcraft??? The server is very laggy while Fastcraft is off!

Same message are going to Fastcraft, and I hope for an reply from both

Keep up the good work!! The mods are great!
👍

**Comment by spacebuilder2020** [comment]
Fast craft has never been completely comparable with forge essentials.  Fastcraft modifies a lot of core classes and sometimes it modifies classes that we modify as well.  Since Fastcraft is closed source, it is impossible for us to make our modifications play with his.  Make a bug report with him.
