### ISSUE TITLE
You do not have permission 

### ISSUE THREAD

**Issue by 3razer** [ForgeEssentials/ForgeEssentials#2223]
I Have a mod pack called universal inter dimension escape. I added the forge essential mod.  And when i op my self i can do all commands but when i add perms like set home or home and then try to use the command it says you do not have permission.

**Comment by spacebuilder2020** [comment]
Can you give me more details on installed mods, FE version, etc.  Also, see if https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial solves your issue.

**Comment by 3razer** [comment]
This is the mod pack, https://minecraft.curseforge.com/projects/universal-interdimensional-escape 
I have looked at the tutorial, I do do exactly what the tutorial does but when i try to use a command it says no permission.

**Comment by spacebuilder2020** [comment]
What version of forge essentials are you on?

**Comment by 3razer** [comment]
forgeessentials-1.7.10-1.4.5.1330-server (1).jar

**Comment by spacebuilder2020** [comment]
Can you post a copy of the server log at the point where you attempted to use a permission, and also a copy of your permissions.json file located in world/FEData

**Comment by 3razer** [comment]
Here is the Permission File
http://pastebin.com/UnwkLQD4

When i try a command /home it doesn't even register anything in the console. I can give you access to mcmyadmin via discord pm and you can look

**Comment by spacebuilder2020** [comment]
1)  The permissions for home is fe.teleport.home.  fe.teleport.home.other, and fe.teleport.home.set
2)  You do not have group inheritance set up
         Ideally, you should have your 'Admin' group inherit from for 'Mod' group and have it inherit from '_GUESTS_'
3)  All players are part of the _GUEST_ group by default until you move them into another group.
         For example, to set members to the default group run: `/p group _GUESTS_ include add members`
4)  You should clean up your permissions and remove any invalid or unnecessary permissions or groups
5)  A best practice when setting up permissions is to use deny default to set up the initial guest permissions.  Then you modify the permissions as needed to add or remove things you want players to have access to.
6)  Remember that the ForgeEssentials/PermissionList.txt is unique to your server and will contain mod specific permissions that you might need for white-listing non-forge essentials permissions.  See https://github.com/ForgeEssentials/ForgeEssentials/wiki/PermissionList.txt
7)  Make sure to read all the permission guides as the above details are all detailed in those guides.

**Comment by spacebuilder2020** [comment]
Since I have not heard back from you, I am assuming that the suggestions I gave worked.

Please let me know if this is not the case.
