### ISSUE TITLE
Build 1337 inventorygroup failing on /mwtp

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentials#2228]
I try to have one multiworld dimension have a separate inventorygroup and it almost works correctly

The permission set to make this work is:

Creating the dimension
/mw create normal anarchy 666

Setting up the permission
/perm global zone WORLD_10 value fe.protection.inventorygroup anarchy

So far so good. When a player does /mwtp anarchy it works. But only once. The inventory is swapped.
After returning to the dimension 0 with /mwtp surface the player gets the original inventory back. Then when doing another /mwtp anarchy the player's inventory isn't swapped anymore. Only when disconnecting that moment and reconnect to the server, the inventory is swapped.

Because /perm debug doesn't show anything of fe.protection.inventorygroup I can't post a log of what happens.

**Comment by spacebuilder2020** [comment]
Does this work on any of the older builds (1330)?

**Comment by Zethalion** [comment]
Yes, I can confirm it does the same on build 1330 but I haven't tried it with builds older than that one.

**Comment by spacebuilder2020** [comment]
Yea, there is no actual difference between 1330 and 1337 since the comments there were just a revert back to 1330.  Let me know if you find a build that works.

**Comment by Zethalion** [comment]
I tried builds 1197 and 1230. Both show the same behavior.

**Comment by yuuka-miya** [comment]
Fixed in latest 1.7 and 1.10 builds.
