### ISSUE TITLE
[QUESTION] Plugins support?

### ISSUE THREAD

**Issue by LiskoSlayer63** [ForgeEssentials/ForgeEssentials#2229]
This is not actually a issue, but does this mod still support Bukkit plugins or is there happened something that I don't know about? I'm using the 1.10.2 -version.

**Comment by spacebuilder2020** [comment]
This mod has never supported bukkit plugins.  However, bukkit does not exist for 1.10.2 modded

Last I heard it does interface with sponge, but you will need to get specifics from @luacs1998

**Comment by LiskoSlayer63** [comment]
@spacebuilder2020 My bad, somone somewhere said that ForgeEssentials can run plugins.

**Comment by spacebuilder2020** [comment]
You can't run bukkit plugins anywhere on 1.10 modded.  It does not exist.

However, forge essentials should be compatible with sponge.

**Comment by LiskoSlayer63** [comment]
@spacebuilder2020 Actually it's not compatible with Sponge.

**Comment by luacs1998** [comment]
We have "plugins" support through the scripting module if you know JS/Typescript.

I think this should answer the question.
