### ISSUE TITLE
[1.10.2] Stuck in middle of world border & permission bug

### ISSUE THREAD

**Issue by LiskoSlayer63** [ForgeEssentials/ForgeEssentials#2231]
If using an ellipse-shaped world border and stays in the same spot where you put the center you got stuck and the console just says that "You're not allowed to move past the world border!". This also happens every time when you cross the middle block.

Also, the `wb` command is not available on console, it says that "You do not have permission to use this command".

**Comment by spacebuilder2020** [comment]
Can you give me the exact command you use so I can try to replicate this?

**Comment by spacebuilder2020** [comment]
Yea... Something is messed up with the world border calculations for the eclipse.  It does not even detect when you cross the world border but makes a fuss at the center.

I have also tested this on 1.7.10.  The bug occurs on both versions.

For now, use box shaped world borders.  I will work on fixing the ellipse border.

**Comment by spacebuilder2020** [comment]
With our most recent merge, this issue should be fixed.
