### ISSUE TITLE
[1.10.2] Crash when used with Sponge

### ISSUE THREAD

**Issue by LiskoSlayer63** [ForgeEssentials/ForgeEssentials#2232]
If I'm using ForgeEssetials with Sponge the server will crash on startup, I put the log [here](http://pastebin.com/RLsgpnKh).

It says that I'm using wrong Forge version but after I disable the Forge Essentials it works just fine.

**Comment by luacs1998** [comment]
Should be OK now, I guess?

**Comment by LiskoSlayer63** [comment]
@luacs1998 Still crashing, there's the log: https://pastebin.com/45ZqLJML

**Comment by LiskoSlayer63** [comment]
@luacs1998 It's still crashing so I opened a new issue [here](https://github.com/ForgeEssentials/ForgeEssentials/issues/2254)

**Comment by LiskoSlayer63** [comment]
@spacebuilder2020 Here's the crash log: https://pastebin.com/KPqwsGKw

**Comment by luacs1998** [comment]
I might need a modlist. Do you only have Sponge and FE installed?
