### ISSUE TITLE
[1.10.2] Command permissions do not get checked at all.

### ISSUE THREAD

**Issue by Mrkol** [ForgeEssentials/ForgeEssentials#2235]
The title says it all. I'm using version 10.1.109 from jenkins.
fe.commands.* are not checked for any commands whatsoever. 
Here's the permissions file for my world. If it's intended behavior, I'd really appreciate if you could explain me what am I doing wrong here.
P.S.
Although fe.commands.* are not being checked, fe.economics.cmdprice.* is getting checked properly.

https://pastebin.com/eZbcpRU4

**Comment by luacs1998** [comment]
I might have forgotten to redirect a call to the Permissions API...

**Comment by luacs1998** [comment]
Should be fixed with that commit (and build 111)
