### ISSUE TITLE
[1.10.2] Portal issues.

### ISSUE THREAD

**Issue by Mrkol** [ForgeEssentials/ForgeEssentials#2236]
There actually are two issues at hand, which are probably caused by the same reason. Maybe.
First of all, I am not able to teleport through nether portals when in overworld. The animation for teleporting just goes on forever. This works fine in singleplayer and without FE on the server.
Second, portals created with FE do not work across dimensions if the target dimension is unloaded, i.e. no players are in it.

Using FE 10.1.109

**Comment by Fallouthero** [comment]
Getting this as well.

**Comment by spacebuilder2020** [comment]
We are aware this is an issue.
I just have not gotten around to fixing it.

**Comment by yuuka-miya** [comment]
I have fixed the issue with nether portals not working in the overworld in build 1346.
