### ISSUE TITLE
How do I prevent a certain mob from spawning?

### ISSUE THREAD

**Issue by ThatGuy1oo1** [ForgeEssentials/ForgeEssentials#2240]
I have an issue on my forge server for my custom pack. I added Infernal mobs and Epic siege mod. When I did this, insane amount of wither skeletons began spawning, crashing my server multiple times. I removed the mod from the pack. I am currently using a command block with /cofh killall running once a second so every time a chunk is loaded with wither skeletons that remain, they're cleared. This also means mobs cannot be found. I acquired forge essentials for my server to prevent wither skeletons from spawning and to clear them out of all chunks. Any way to do this?

**Comment by Zethalion** [comment]
Try to deny one or a combination of these 3 permissions:
- /p global deny fe.protection.mobspawn.forced
-/p global deny fe.protection.mobspawn.natural
- /p global deny fe.protection.mobspawn.*

**Comment by ThatGuy1oo1** [comment]
I'll try it, thanks

**Comment by ThatGuy1oo1** [comment]
Seems to have done little. Is there any way to clear all of the wither skeletons? Like /fe butcher witherSkeleton 1000000 but without crashing my server? XD
Thanks for the reply though!

**Comment by Zethalion** [comment]
Set difficulty to peaceful. That should work.

**Comment by luacs1998** [comment]
Solved?
