### ISSUE TITLE
Exporting dimension(s) created with MultiWorld?

### ISSUE THREAD

**Issue by flowtek92** [ForgeEssentials/ForgeEssentials#2241]
Hey, i'm curious if it is possible to export worlds/dimensions that were created with the /mw create command. I already tried to copy-paste `world/FEMultiworld/mapname` folder from my server into my singleplayer save folder but it doesnt show up in game. 

I'd appreciate any help because i want to extract one of my multiworlds from my server and make it a standalone server world on a separate machine.

**Comment by Zethalion** [comment]
You need to replace the region files of a new save game with the ones from a MW dim. That will work.

**Comment by flowtek92** [comment]
Thank you very much, after i created a SP world with the same seed as the MP world and copying the region files into that save it worked perfectly. Only problem i encounter is that the game turns into a massive slideshow once i step a foot into the area i copyed but i think thats coming from a mod i used on the server.

**Comment by luacs1998** [comment]
Seems OK, so I closed it.
