### ISSUE TITLE
[1.10.2] Severe server TPS lag.

### ISSUE THREAD

**Issue by LiskoSlayer63** [ForgeEssentials/ForgeEssentials#2243]
I noticed that when I used this mod my server started to skipping ticks, and a lot. Whole server was unplayable because of that. I loved how your mod altered the chat notifications and loved even more that it can made a ellipse shaped world map with pregen. But because of those massive tick lags this is unusable. I pasted the data to [Pastebin](https://pastebin.com/PSLsxtmx). Is there any changes to get this fixed? If we forget that issue, otherwise your mod is great!

I've read [Tips on performance improvements](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Tips-on-performance-improvements) but FastCraft isn't available for 1.10.2 so used Sponges [ClearMob](https://ore.spongepowered.org/axle2005/ClearMob) and Forges [BetterFps](https://minecraft.curseforge.com/projects/betterfps) but those didn't help at all with ForgeEssentials. Now I can run all my 60+ mods wihout any "Can't keep up!" messages but I still need the ForgeEssentials mod which I can't use (yet).

Please try to optimize some of the code so the server is actually playable.

My Servers specs are following:
**CPU:** Intel Core i7-2700K @ 3.9GHz
**RAM:** 20Gb DDR3 1333/1600 MHz
**HDD:** 750 Gb & 500 Gb HDD
**D/U:** 100/50 Mbps

Also I use IIS external web server for dynmap. That infernal lag (skipping ticks) happens if there's only one player online, sometimes also when the server is "idling" without any players.

**Comment by spacebuilder2020** [comment]
Please keep in mind 1.10 is still not stable.  We are doing all we can to get it stable.

Can you give me some details on what mods are on the server so I can try to replicate this issue.

**Comment by luacs1998** [comment]
Seems to be the mapper module - turn it off in the meantime.
