### ISSUE TITLE
[1.7.10]How can I disable the AFK kick

### ISSUE THREAD

**Issue by indoorsNB** [ForgeEssentials/ForgeEssentials#2250]
In settings.cfg, I set afk kick to be 'false' but I keep getting kick in my server.

**Comment by Zethalion** [comment]
If a permission node value is set to fe.commands.afk.autokick somewhere, you need to clear it.

To see that perms ar in effect on your player use "/p username perms" and browse the result to see where this node is set to true.

**Comment by indoorsNB** [comment]
I use /p global cancel fe.command.afk.autokick to delete this in my global permissions. Then I check settings and already set it to false.

But I still get the AFK kick

**Comment by indoorsNB** [comment]
Maybe set true on S:auto_kick in settings.cfg  is opposite? ( I have no idea why I keep getting kick)

**Comment by Zethalion** [comment]
Try "/p global clear fe.command.afk.autokick" since "cancel" is not valid.
