### ISSUE TITLE
[1.10.2] Crashing with Sponge

### ISSUE THREAD

**Issue by LiskoSlayer63** [ForgeEssentials/ForgeEssentials#2254]
Forge Essentials crashes on startup when used with Sponge. Error says that the Forge version is too old but really it isn't. This happens even when using the exactly version for what Sponge is built to. I also tried to use SpongeBootstrap but that didn't fix the issue. Is there any chances to get this work? I have reported this earlier and thought it was fixed but really it isn't. I tried to start the server with only Sponge and Forge Essentials and still same crash. I don't have very much time at the moment so if you need the full version list for everything and/or the crash log just ask and I will deliver them later.

**Comment by spacebuilder2020** [comment]
You know you can just reopen an existing issue

**Comment by LiskoSlayer63** [comment]
@spacebuilder2020 Now I know.. I will post the log to the old issue.
