### ISSUE TITLE
Mod Compatibility - Moar Signs

### ISSUE THREAD

**Issue by Jo-Mamma75** [ForgeEssentials/ForgeEssentials#2257]
I'm posting on behalf of the rest of the FoolCraft DevTeam and Iskall85 Administration Team.  We were looking to use your mod on our 6 Patron servers but are currently running into a crash upon start due to an exception caught from MoarSigns.  ([Crash Report](https://pastebin.com/JKcPPd8k))

I attempted to disable the the "Signs Module" among a few other items we probably don't need right now and have attached my current config file for you to confirm. ([main.cfg](https://pastebin.com/ET2UwyDY))

We would certainly appreciate any help with this issue and look forward to hearing back from you.
Thanks in advance,
Jo_Mamma75
Iskall85 Community Administrator
FoolCraft DevTeam

**Comment by spacebuilder2020** [comment]
Let me know if http://ci.forgeessentials.com/job/FE-1.10/115/ fixes your issue.

**Comment by Jo-Mamma75** [comment]
Tried and got this crash instead.
https://pastebin.com/m9kne617

**Comment by spacebuilder2020** [comment]
ok.  That is a different bug.

**Comment by spacebuilder2020** [comment]
Since this is a new bug, I have opened a new issue for it.
