### ISSUE TITLE
No access to graves serverrestart

### ISSUE THREAD

**Issue by Marlin994** [ForgeEssentials/ForgeEssentials#2259]
Hey,
since a few days i have the problem that nobody can use any graves after the server has restarted.
befor i registratet this problem i haven't change anything at the server.

**Comment by spacebuilder2020** [comment]
I can't help you without a modlist, FE version, and a instructions on how to replicate the bug.
Also, posting the entire server log including when players try to open their graves will probably be helpful.

**Comment by Marlin994** [comment]
Hey, here are the logs and the modlist (http://173.212.219.141/logs/). For the logs i restartet the server, type / kill in the chat. then i try to open the grave. It's works. Then I type / kill in the chat again, restarted the server and try to open the grave. The head and the fence are normal blocks.

I use the newest version 1614 of forge. I can't say how you can replicate this bug. I have it every time i restart the server.

**Comment by spacebuilder2020** [comment]
Based on your log, it seems that the grave is failing to save.  I will take a look at a pure FE world, but I think that this is probably due to one of the mods you have.

**Comment by spacebuilder2020** [comment]
I have confirmed that this error does not happen on a pure FE installation.   I will look into replicating the modlist and stepping through when I have time.

If you could, I would recommend you to troubleshoot each mod in your set by removing said mod and seeing if the error still occurs.

Also, it looks like you are using an out of date version of Forge Essentials.  I can not give you more support until you upgrade FE to confirm that the issue still exists.

**Comment by Marlin994** [comment]
Okay. I will do it this night.
Every time the Server restarted it saves a grave data at "Minecraft/HauptWelt/FEData/json/Grave". So i thing the problem isn't to save the gave but to lode it.

**Comment by spacebuilder2020** [comment]
Post the saved grave file.  According to the loading log, there is an error in the syntax

**Comment by Marlin994** [comment]
[grave.zip](https://github.com/ForgeEssentials/ForgeEssentials/files/980225/grave.zip)

**Comment by spacebuilder2020** [comment]
add a '}' at line 50
That should allow the file to load properly

**Comment by Marlin994** [comment]
So... I try a lot and find the bad mod. After i deleted CustomNPC the graves works!
I also try your tipp with adding `, "block": "minecraft:skull" }` but this don't work.

**Comment by spacebuilder2020** [comment]
I am not too surprised about that.  CustomNPC's has had problems with FE in the past

**Comment by Marlin994** [comment]
Is there anything i can do?

**Comment by spacebuilder2020** [comment]
Until I can investigate the mod, no.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @Marlin994

**Comment by Marlin994** [comment]
I'm not shure. The server do not exist anymore.
