### ISSUE TITLE
[Bug] auth allow player use FTBU before login

### ISSUE THREAD

**Issue by indoorsNB** [ForgeEssentials/ForgeEssentials#2266]
I use FE's auth  and it allow FTBU GUI before player login to the game 
1.7.10

**Comment by yuuka-miya** [comment]
This might be complicated to fix, so I'll just apply the wontfix label for now while I get it sorted out.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @indoorsNB

**Comment by maximuslotro** [comment]
No response has been given, closing the issue.
