### ISSUE TITLE
[1.7.10] permission deny with storage drawers isn't working

### ISSUE THREAD

**Issue by X-Coder** [ForgeEssentials/ForgeEssentials#2267]
1.7.10, tested with rev. 1330+1341.

I tried to deny access in a zone to a left click on a storage drawer by using /p user ... deny fe.protection.interact.StorageDrawers.fullDrawers4.* but it still gives me the item of the storage drawer when I left click on it. Same with /p group.
Is this a bug? Do you know how I can prevent this?

If I use fe.protection.interact.* it makes no difference. It works fine on other blocks, but not with storage drawers. /protectdebug is printing me the same permission name when I left click on the storage drawer.

/p group _ALL_ zone zonename is listing the permission I set.

[This is the sources to storage drawers](https://github.com/jaquadro/StorageDrawers/blob/1.7.10/src/com/jaquadro/minecraft/storagedrawers/block/BlockDrawers.java#L450), if it helps.
In their sources they used a **onBlockClicked** override.

**Comment by yuuka-miya** [comment]
Use `/p debug` and see what permissions are being checked when you right click a storage drawer.

**Comment by X-Coder** [comment]
On right and left click it prints in red: **fe.protection.interact.StorageDrawers.fullDrawers4.1**

Which I blocked with using /p user <username> zone <zonename> deny fe.protection.interact.StorageDrawers.fullDrawers4.1

The main problem is the left click on the storage drawer, but right click behaves strange too some times, it feels like it is adding a item half way when permission is denied.

Storage drawers has a key based auth system called "personal key" built in, when crafted and placed it allows to restrict single drawers only to the owner.
With FE it would allow a much finer  group and zone based restriction.

I'm the only one with this problem?

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @X-Coder

**Comment by X-Coder** [comment]
Thought this project was dead, good to see you are working again on it, because I like it very much.

Just tested it in 1.12.2, no problems so far for in this version. But the reported 1.7.10 is still bugged, but I don't mind if you can't fix it as I currently don't have much time anyway.

**Comment by Zethalion** [comment]
Thanks for replying and testing on 1.12.2 @X-Coder.
As all focus is now on 1.12.2 I'll close this issue
