### ISSUE TITLE
[1.7.10] auth module is not working with Galacticraft installed

### ISSUE THREAD

**Issue by X-Coder** [ForgeEssentials/ForgeEssentials#2268]
With forge essentials setting B:canMoveWithoutLogin=false and B:forceEnable=true the player is still able to move around and use everything, when not logged in. Without Galacticraft everything is working fine, the player can't move or use any GUI while not logged in.

I can't see any errors in the logs. The chatmessages, login and registration function do still work.

Tested it with these versions and some older ones:
MicdoodleCore-1.7-3.0.12.498
GalacticraftCore-1.7-3.0.12.498.jar
Galacticraft-Planets-1.7-3.0.12.498.jar
forgeessentials-1.7.10-1.4.6.1341-server.jar
forge-1.7.10-10.13.4.1614-1.7.10

https://github.com/micdoodle8/Galacticraft/issues/2765

**Comment by X-Coder** [comment]
Hi, I got a response from Galacticraft's developer @radfast:

> The problem is in ForgeEssentials [this line](https://github.com/ForgeEssentials/ForgeEssentials/blob/1710/develop/src/main/java/com/forgeessentials/auth/AuthEventHandler.java#L65) It would be better if they checked there for any instance of EntityPlayerMP.
>
> Best is to report this to ForgeEssentials and ask them to make that change.
>
> You can alternatively try installing PlayerAPI in your server-side mod list, that should probably work.

[PlayerAPI](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api) works as workaround for me. It would be still nice if you can fix this, so it will work for other server owners too without the need for PlayerAPI.

**Comment by spacebuilder2020** [comment]
Yea... that is a really old line.... I can see when galacticraft is installed, the player's class never equals EntityPlayerMP.   I will fix this as soon as I can get around to it.

**Comment by X-Coder** [comment]
Thank you.
