### ISSUE TITLE
1.11.2

### ISSUE THREAD

**Issue by Mattabase** [ForgeEssentials/ForgeEssentials#2270]
Hey, great to a see a 1.10.2 version out. super dig it. 

I was wondering if a 1.11.2 version was in the works?

Either way, thanks for the 1.10.2 update.

**Comment by spacebuilder2020** [comment]
We will get to 1.11 - 1.12, etc when we can.

However, for now, forge essentials only is supporting 1.7.10 (occasional backports) and 1.10.2
