### ISSUE TITLE
[1.5.2] There was a problem downloading the file (for several dependencies)

### ISSUE THREAD

**Issue by Poikilos** [ForgeEssentials/ForgeEssentials#2271]
Minecraft version: Hexxit server (Minecraft Forge 1.5.2)
OS: Lubuntu 16.04 Xenial
ForgeEssentials Version: ForgeEssentials-ServerComplete-1.5.2-SNAPSHOT.zip via [https://minecraft.curseforge.com/projects/forge-essentials-74735/files?page=2](https://minecraft.curseforge.com/projects/forge-essentials-74735/files?page=2)

Hexxit server was able to load before ForgeEssentials was installed. 
The only errors shown are ForgeModLoader download errors apparently for dependencies introduced by ForgeEssentials.
My ForgeEssentials (just downloaded and installed on my Hexxit server) cannot download 4 required jar files due to broken links ("[SEVERE] [ForgeModLoader] There was a problem downloading the file H2DB.jar automatically. Perhaps you have an environment without internet access. You will need to download the file manually or restart and let it try again").
Upon pasting the links (see bottom of this post) into a browser, all are 404 file not found errors, which confirms the cause of the errors.

So, anyone with an old 1.5.2 server and ForgeEssentials,
please kindly provide:
* metrics-R7-FEMod.jar
* mysql-connector-java-bin.jar
* H2DB.jar

What I've tried already:
* I got pircbotx-1.9.jar myself from maven.
* I tried to find these 3 jar files on Google without success other than:
* I got a random version of mysql-connector-java.jar and H2DB named slightly differently--if you have the files (or at least version numbers for those two) that server 1.5.2 downloaded before the downloads were removed those versions may be needed (I can't test my versions until I get metrics-R7-FEMod.jar)
* alternatives to ForgeEssentials snapshot
Due to the bukkit and cauldron legal issues, most protection projects are Forge server mods (such as Thut Essentials), but are for only newer versions of Minecraft.
Getting a build environment for 1.5.2 has been difficult (I got necessary mediafire links from wayback machine), and the layout of classes in Minecraft seems to have changed quite a bit, so an intense backport of Thut Essentials is hopefully not what I have to create.
I could not find any protections mods compiled for 1.5.2 other than ForgeEssentials snapshot.

These files are no longer downloadable from (these links in my Hexxit server error log):
https://github.com/ForgeEssentials/ForgeEssentialsMain/raw/master/lib/mysql-connector-java-bin.jar
https://github.com/ForgeEssentials/ForgeEssentialsMain/raw/master/lib/H2DB.jar
https://github.com/ForgeEssentials/ForgeEssentialsMain/raw/master/lib/metrics-R7-FEmod.jar
https://github.com/ForgeEssentials/ForgeEssentialsMain/raw/master/lib/pircbotx-1.9.jar

**Comment by yuuka-miya** [comment]
We don't support 1.5 anymore.

The files can be found here: https://www.mediafire.com/folder/dpqhf3ughd4j5/libs
