### ISSUE TITLE
Vanish Pointer

### ISSUE THREAD

**Issue by chorman0773** [ForgeEssentials/ForgeEssentials#2272]
I actually created a vanish. One thing I noticed is that the EntityStatus Packet that "kills" the player, causes ghost items to appear on the recieving clients. I fixed this by sending a DestroyEntity Packet first. Also you can fix all the "Player Reapearring" effects by causing the players who should not See Vanished Players can be fixed by re-enabling vanish whenever either player respawns, a new player joins, or either player change dimensions.

**Comment by spacebuilder2020** [comment]
make a pull request and I will review it

**Comment by yuuka-miya** [comment]
#2273 was a bad PR - I've closed it. Can you make another one with your commits targeted (to the 110/develop branch) beforehand?

**Comment by Zethalion** [comment]
Closing this as on 1.12.2 this is no longer an issue.
