### ISSUE TITLE
1.10.2 Auth not working

### ISSUE THREAD

**Issue by ghost** [ForgeEssentials/ForgeEssentials#2274]
On Forge 2297

Registering/logging in works with forceEnable set to false.

When forceEnable is set to true, using /register <password> doesn't work, just says "Login required. Try /auth help".

Tried with and without B:allowOfflineReg=true.

**Comment by Zethalion** [comment]
Please provide the following: 
- FE Build
- ./ForgeEssentials/Authlogin.cfg (gist or pastebin)
- ./world/FEData/permissions.json (gist or pastebin)

**Comment by Zethalion** [comment]
Closing as this is not an issue on 1.12.2 and for not responding in a long time.
