### ISSUE TITLE
multiworld is crash my server

### ISSUE THREAD

**Issue by minsto** [ForgeEssentials/ForgeEssentials#2278]
im probleme is very simple im use commende /mw name test normal flat to create my multiworld
My waiter(server) closes alone.?

minecraft forge 1.10.2 build2297
forgeessential build:.1356-server

thanks to fix up.

**Comment by spacebuilder2020** [comment]
Can you please post the full crash log as well as the modlist you are using?

**Comment by minsto** [comment]
crash log :https://pastebin.com/MV72ShKb

**Comment by spacebuilder2020** [comment]
Can you post the modlist as well.

Also, please activate debug mode (in the main.cfg file) and replicate the error again.
(The option is annotated with "Activates developer debug mode. Spams your FML logs.")

After doing that, please repost the crash report and the full server log. (fml-server-latest.log)

**Comment by minsto** [comment]
Im activated debug mod on main.cfg
Fml-server-lates.log:https://pastebin.com/iFW8DXqD
Modlist:https://pastebin.com/14mKqy2H

**Comment by spacebuilder2020** [comment]
Make sure to replicate the crash after enabling debug mode.  I don't see the server going down in that log.

**Comment by minsto** [comment]
crash log to my server here:https://pastebin.com/cjkZtS38

**Comment by spacebuilder2020** [comment]
I need the fml-server-latest log after the crash occurs.  That has the most information.

**Comment by minsto** [comment]
https://pastebin.com/324pEbqR

**Comment by spacebuilder2020** [comment]
the server is not crashing in that log.  It is just stopped manually.

**Comment by minsto** [comment]
Exactly the server is stopped and make crash https://pastebin.com/cjkZtS38 Every time that I use this commende /mw test normal flat.

**Comment by spacebuilder2020** [comment]
Someone ran 'stop' according to the log. See line 605 in your pastebin.

**Comment by spacebuilder2020** [comment]
I need a copy of the latest.log file with the command that caused the crash taken after the crash but before the server restarts.

**Comment by spacebuilder2020** [comment]
Make sure it is in debug mode as well.

**Comment by minsto** [comment]
yes latest.log:https://pastebin.com/bqGnrqgK
command is this:/mw create test normal flat   

yes my debug = true on main.cfg

**Comment by spacebuilder2020** [comment]
thanks

**Comment by minsto** [comment]
it's my pleasure.

**Comment by yuuka-miya** [comment]
I have fixed this in build 1361.

Get it from here:

http://ci.forgeessentials.com/job/FE/1361/
