### ISSUE TITLE
[1.10.2] (10.2.1356) fly/god/ftbu questions

### ISSUE THREAD

**Issue by zzyzzyzzx** [ForgeEssentials/ForgeEssentials#2279]
So i am just playing around with FE just trying to get a handle on how things work to maybe set up for a server.

but basically /fly does not work (just says enabled, but capabilities still says false) and user can not fly.

and there is no option for /god anymore

i tried to even edit the capabilities in the console but same thing, nothing happens

dont know if it will matter but here is perms as of writting this:
https://pastebin.com/v6bDh2nd

as for FTBU is it possible to change the loading/claiming of chunks via FE? basically im trying to not use sponge for my server and wanted to do as much as possible with mods

**Comment by spacebuilder2020** [comment]
/god was implemented as a sample script on the old scripting system.  It was never transferred to the new one.

When I have a chance, I will reimplement it.

As for ftbu, I have not messed with it in a while, so I am not sure.  I think you configure the claiming for ftbu in it's config files.

I will also investigate /fly

**Comment by spacebuilder2020** [comment]
Here is a new god script
https://pastebin.com/eCfwHguK

**Comment by spacebuilder2020** [comment]
@zzyzzyzzx I went ahead an reimplemented god in JS.
https://pastebin.com/pLft8jYx
Also,  are you sure /fly is not working.  Cause It is working on a test server (at least the enabling part)
There is an issue with it teleporting you to the top of the world when it is turned off but that sounds like a different issue.

Can you give me some detail on what is happening on the console when you have /fly and what mod you are using

**Comment by zzyzzyzzx** [comment]
I'm on foolcraft I have not started my computer in a couple days ill do it today when I get home from work and check

**Comment by spacebuilder2020** [comment]
There is an issue in /fly that I need to fix, but it is not completely broken (at least vanilla).

**Comment by zzyzzyzzx** [comment]
I do not see anything in logs/console when i do /fly just the bug you said about being shot up/dropped i have not really installed any other mods to the modpack

**Comment by spacebuilder2020** [comment]
ok.  I will investigate fixing /fly when I have time

**Comment by DeadOnAim** [comment]
@spacebuilder2020 is there a way to make this accessible via the console as well? It keeps giving me the error 'TypeError: null has no such function "checkPermission" in at line number 87 at column number 3' so I'm assuming theres a way to write a function for this.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @zzyzzyzzx

**Comment by maximuslotro** [comment]
Issue closed. Open a new issue if the issue persists.
