### ISSUE TITLE
paidcommand and sellcommand dont work?

### ISSUE THREAD

**Issue by dcorc** [ForgeEssentials/ForgeEssentials#2283]
I'm trying to set up shops using command blocks, using the syntax as per the shop setup here https://github.com/ForgeEssentials/ForgeEssentials/wiki/Economy-module

I'm finding that it throws an error, or only enacts the first half of the command, so 

/sellcommand @p minecraft:cobblestone 64 0 /wallet @p add 1

takes the 64 cobblestone (it tells me,though it actually doesn't, but also does not add a coin to my wallet

Any help and advice appreciated.

**Comment by spacebuilder2020** [comment]
Closed for not having enough information
Make sure to follow everything else in the reporting bugs section
https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
Before Reopening this issue

**Comment by Zethalion** [comment]
I'll check this soon, I suspect the second @p isn't parsed. Then again, I need to know which version of FE is in place. A /p debug output is also a nice thing to get started as goes for logs in general.

**Comment by dcorc** [comment]
Thank you Zethalion

It's FE 10.2   minecraft 1.10.2

In the command block,it just says "an error occurred..."

**Comment by Zethalion** [comment]
Build number?
