### ISSUE TITLE
Deathchests are enabled, but spawning in sky?

### ISSUE THREAD

**Issue by AngryBenko** [ForgeEssentials/ForgeEssentials#2284]
I'm running forgeessentials-1.10.2-10.2.1365-server.jar and I'm having issues with deathchests. It doesn't seem to be working even though I have it enabled in Settings.cfg 

`grave {
    # fe.afterlife.deathchest.block = 
    # If set, use this block ID for graves
    S:block=

    # fe.afterlife.deathchest = true
    # Allow creation of deathchests
    S:enable=true

    # fe.afterlife.deathchest.fence = true
    # Put the skull on a spike
    S:fence=true

    # fe.afterlife.deathchest.xp = 0.25
    # Ratio of XP that you want to allow someone to keep in a grave. 1 keeps all XP, 0 disables XP recovery.
    S:recoverable_xp=

    # fe.afterlife.deathchest.safetime = 300
    # Time in seconds a grave is protected. After this time anyone can take all stuff
    S:safetime=300
}`

I have no other mods that would conflict with making deathchests. I'm not sure where to go from here.

EDIT: After testing, I'm figured out that deathchests is working. However, all the deathchests are spawning in the sky.

**Comment by spacebuilder2020** [comment]
Please post the log

**Comment by AngryBenko** [comment]
Which log are you looking for? There wasn't a crash so I don't think you want a crash log.

**Comment by spacebuilder2020** [comment]
Server log

**Comment by AngryBenko** [comment]
Here is the server log: https://pastebin.com/ZPe4Xaue

**Comment by spacebuilder2020** [comment]
Make sure that you replicate the bug while the server is running.  Minecraft makes a new log each time minecraft is ran.  I can't see anything in that log.

Also, for good measure enable debug mode in main.cfg

**Comment by AngryBenko** [comment]
Alright. I've enabled debug mode in main.cfg and replicated the bug. Here is the log: https://pastebin.com/s1b2mdqf.

Taking a glance at it, I didn't see anything new near the end.

**Comment by spacebuilder2020** [comment]
Yea... Well.... So much for an easy fix.

**Comment by AngryBenko** [comment]
I'll mention that it's not only items that will fall from sky, or deathchests spawning in the sky. If I have fly enabled, and I disable it, regardless of the height of my character, I'll teleport to the highest point in the world and start to fall down.

**Comment by spacebuilder2020** [comment]
I know about that one

**Comment by yuuka-miya** [comment]
Please let me know if the issue still happens with build 1368.

**Comment by AngryBenko** [comment]
The issue is fixed with build 1368
