### ISSUE TITLE
fe.protection.fire.destroy is not working

### ISSUE THREAD

**Issue by ErikSteiner** [ForgeEssentials/ForgeEssentials#2289]
Hi guys,

I recently began to integrate my old server to a newer version of Minecraft and finally I was ready to start the Server. I am now fighting with an old problem, that seems to be happening all over again: The fire can destroy blocks permission and/or fire can spread permission.

Unlike #2208 preventing fire from spreading is working, but the block that is on fire is still getting destroyed.

So I set both to false. Fire will not spread, but will destroy the block that is on fire.
          "fe.protection.fire.destroy": "false",
          "fe.protection.fire.spread": "false"

This is the complete permission file: [LINK](https://pastebin.com/mFqSFzuf)

I set the shaded area on fire with a flint and steel.
![fire](https://user-images.githubusercontent.com/2684018/27993031-740e7bb8-64a1-11e7-8f29-0222e5010973.png)

**Information:**
Minecraft: 1.10.2
Forge: 1.10.2 - 12.18.3.2316
Forge Essentials: forgeessentials-1.10.2-10.2.1356-server

P. S.: Is it true, that I have to add that many permissions to the group _GUESTS_ , in order to prevent them from doing anything? Or is it possible to do it in a more efficient manner?

**Comment by ErikSteiner** [comment]
**UPDATE:**
I installed a fresh Server with "_Forge: 1.10.2 - 12.18.3.2316_" and "_forgeessentials-1.10.2-10.2.1370_".

I joined it and switched myself to creative mode. Then before adding any permissions to the config, I set a tree on fire with a flint and steel. It burned and the fire was spreading.
I put the fire out and added the two permissions via the server console to the config. One to prevent fire spread and one to prevent fire damage (destroy). I then set another tree on fire. This time the fire didn't spread, but at the end when the fire burned out the block vanished.

I zipped up the whole server, so you can try it out for yourself. In the server folder, you can find the client log, too. **Client-LOGFILE.txt**

If you have any questions, feel free to ask and I hope I can give you as much information as you need.

Unfortunately this is the only issue that prevents me from playing Minecraft, otherwise my whole map would be turned to ash...

[Server.7z](https://1drv.ms/u/s!AtZMXpcZH7S1icAAlDR2vAmLtC20Lg)

**Comment by yuuka-miya** [comment]
I need to check on our custom fire event injection...

**Comment by yuuka-miya** [comment]
I can't seem to figure out what's going on (nor do I have the time to), so marking this as wontfix in the meantime.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @ErikSteiner

**Comment by ErikSteiner** [comment]
Thank you having a look at the issue. Unfortunately I currently have no Minecraft on my system.

**Comment by maximuslotro** [comment]
Issue Closed. Open a new issue if the issue persists.
