### ISSUE TITLE
How to pre-generate terrain for Dynmap?

### ISSUE THREAD

**Issue by Owizardo** [ForgeEssentials/ForgeEssentials#2290]
Hey there,

Im trying to pre-generate my map for Dynmap so my players can see the whole map without having to explore it. Ive tried doing:

/wb center X Z
/wb size 5000
/wb enable
/pregen start or filler start
(once completed)
/dynmap fullrender 

Dynmap still dosent seem to load the pregenerate area ... Is there a better sequence to this? Am I doing this wrong or maybe I am misunderstanding the use of the pregen ... Anyone have any idea?

**Comment by ErikSteiner** [comment]
You should check your configuration file of Dynmap. There are several events possible to let Dynmap render a map tile: by block update etc. I guess that your configuration file prevents Dynmap from generating a map tile, for the event that a chunk is being generated/updates.
Maybe you can find the issue in your file, but have a look at the commands page, too. https://github.com/webbukkit/dynmap/wiki/Commands
There is an option to render everything of a map with a single command.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @Owizardo

**Comment by ErikSteiner** [comment]
Not able to test it at the moment, will reopen the issue if I can.
