### ISSUE TITLE
Bug with a mode Voxelmap

### ISSUE THREAD

**Issue by darknsided** [ForgeEssentials/ForgeEssentials#2291]
If you do not install on the ForgeEssentials server, then nobody can use the teleport through the map, And if you set ForgeEssentials and Voxelmap, then any player can be teleported using a card, I would like to fix this bug as can be fixed?

**Comment by spacebuilder2020** [comment]
Closed for not following our guidelines [here](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs)!

Please correct your issue to follow these guidelines and then reopen this issue.
