### ISSUE TITLE
Group permissions doesn't work correctly

### ISSUE THREAD

**Issue by Th3Z0n3** [ForgeEssentials/ForgeEssentials#2292]
It seems that the permissions for defined zones doesn't work correctly. The fe.protection.break.*  seems "broken" a little bit. Some blocks can still be destroyed. In my case brick_stairs, bricks and stonebricks.

Here is a screen: https://abload.de/img/2017-07-11_12.47.26p6uxt.png

I used //fewand to define an area. Then i used the /zone command to name this area. Then used /p group _ALL_ zone EnergyOutpost deny fe.protection.break.* fe.protection.place.*  to protect it. And yes i used /p save and /p reload to force the permissions.

I have created a new Group called Members (from your example) and include the _GUEST_ group in it. Could this cause this issue?

**Comment by spacebuilder2020** [comment]
Closed for not following our guidelines [here](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs)!

Please correct your issue to follow these guidelines and then reopen this issue.
