### ISSUE TITLE
1.10.2 FE deathchests not spawning? [SOLVED]

### ISSUE THREAD

**Issue by SilentWolf101** [ForgeEssentials/ForgeEssentials#2295]
I checked to see if this was in the closed and open issues, but I couldn't find it. It may just be me doing something wrong, though... 

I'm trying to get the deathchests to spawn. I initially started with the settings, and all the graves settings are set to true. 

`grave {
    # fe.afterlife.deathchest.block = 
    # If set, use this block ID for graves
    S:block=

    # fe.afterlife.deathchest = enable
    # Allow creation of deathchests
    S:enable=enable

    # fe.afterlife.deathchest.fence = false
    # Put the skull on a spike
    S:fence=true

    # fe.afterlife.deathchest.xp = 1
    # Ratio of XP that you want to allow someone to keep in a grave. 1 keeps all XP, 0 disables XP recovery.
    S:recoverable_xp=1

    # fe.afterlife.deathchest.safetime = 300
    # Time in seconds a grave is protected. After this time anyone can take all stuff
    S:safetime=300` 

Then I saw that it had been moved to permissions. So I did two different commands. 
> /p global allow fe.afterlife.deathchest.make 
> /p global allow fe.afterlife.deathchest 

Still no death chest. Restarting the server, reloading the permissions file and generating a new world do nothing to fix the issue. 

I loaded the debug command, and it says that all the permissions above are true/enabled and that it's checking those for me. I don't know where else to turn... My items just fly out all over the ground. 

EDIT: Forgot to mention, I'm using Essentials 1356.

**Comment by SilentWolf101** [comment]
I figured out that it was the wrong version, and I found the right version on the actual site. I apologize, I was using the latest version from curse forge. For anybody else looking for a solution, here's the site: http://ci.forgeessentials.com/job/FE/

**Comment by yuuka-miya** [comment]
For future reference, I'm trying to track down a few more bugs, then I'll push a new build to CurseForge.
