### ISSUE TITLE
Spawnmob ?

### ISSUE THREAD

**Issue by Spyooy** [ForgeEssentials/ForgeEssentials#2297]
I want to stop spawn mob, passive, hostile but i don't know why, NOTHING WORK i do : 
/p global Zone WORLD_14 fe.protection.mobSpawn.natural.*
/p global Zone WORLD_14 fe.protection.mobSpawn.forced.*
/p global Zone WORLD_14 fe.protection.mobSpawn.forced.Slime
(for example) and NOT WORKING

**Comment by spacebuilder2020** [comment]
Closed for not following our simple rules here
https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
