### ISSUE TITLE
Problem with some commands

### ISSUE THREAD

**Issue by Spyooy** [ForgeEssentials/ForgeEssentials#2298]
I want to stop spawn mob, passive, hostile but i don't know why, NOTHING WORK i do :
/p global Zone WORLD_14 fe.protection.mobSpawn.natural.*
/p global Zone WORLD_14 fe.protection.mobSpawn.forced.*
/p global Zone WORLD_14 fe.protection.mobSpawn.forced.Slime
(for example) and NOT WORKING

**Comment by Zethalion** [comment]
Try this instead:
```
/p global zone WORLD_14 deny fe.protection.mobSpawn.natural.*
/p global zone WORLD_14 deny fe.protection.mobSpawn.forced.*
/p global zone WORLD_14 deny fe.protection.mobSpawn.forced.Slime
```

The last line should not be needed since it is covered on the second line.
