### ISSUE TITLE
Crash on startup NBT data

### ISSUE THREAD

**Issue by KjellK1997** [ForgeEssentials/ForgeEssentials#2299]
Server crashes while starting:

https://pastebin.com/wX3fhM3R

**Comment by rmnaderdev** [comment]
Is it a new map?

**Comment by Zethalion** [comment]
Try in main.cfg mapper=false

**Comment by jrdalaigh** [comment]
I had this same problem and changing mapper in main.cfg worked for me, but what does changing mapper do? Do I lose any features or does it mess with my world at all?

**Comment by Zethalion** [comment]
No, you do not lose any features but your server won't create a png file containing the map of the spawn zone. Mapper functionality is currently not fully functioning. @luacs1998 @spacebuilder2020 Any ideas?

**Comment by spacebuilder2020** [comment]
If you want a map of the world, just use journey map's dynmap feature on your server

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @KjellK1997

**Comment by maximuslotro** [comment]
Issue closed. Open a new issue if the issue persists.
