### ISSUE TITLE
PermissionsList.txt is not populated and non-FE permissions are not working

### ISSUE THREAD

**Issue by ghost** [ForgeEssentials/ForgeEssentials#2300]
My PermissionsList.txt is not populated with new permissions from mods, although the modlist.txt file is being populated, just like the PermissionList_Items.txt and the PermissionList_Blocks.txt. I'm using the forge server for direwolf20 1.10 modpack (minecraft version: 1.10.2).

[My current PermissionsList.txt](https://pastebin.com/PEqdvMs9)
[My current modlist.txt (there are much more mods, really)](https://pastebin.com/xUgiPC7R)
[My current REAL list of mods](https://pastebin.com/ixgVrydA)

I've tried to add a few rules for known permissions (like, for example, the `com.auth.mod.commands.RegisterCommand` permission for AuthMod, but it does not work at all - the console reports that I lack a permission to run this command).

**Comment by ghost** [comment]
Well, looks like it was a conflict with FTBUtilities. After removing FTBUtilities, everything went back to normal. The problem is - how can I achieve normal functionality with both mods active? I really don't want to stop using the chunk claiming system FTBU provides, the team system it uses, etc. Do I have to address this issue to the FTBU devs?

**Comment by spacebuilder2020** [comment]
make sure you are on the latest version of ftb utils.  There was a conflict with forge essentials but I think it was recently fixed.

**Comment by spacebuilder2020** [comment]
Also update to the latest version of forge essentials
Make sure to follow the procedure documented [here](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs).  Failure to follow this procedure will result in your report being closed.

**Comment by ghost** [comment]
There were some useful config setings FTBU devs send me that helped the situation. For anyone wondering, those were:
```json
"ranks": {
    "override_chat": false,
    "override_commands": false,
    "enabled": false
  }
```
at the config.json file (located at <server folder>/local/ftbu/config.json)

**Comment by spacebuilder2020** [comment]
ok.  Great
