### ISSUE TITLE
Corrupted World 1.7.10

### ISSUE THREAD

**Issue by DetectiveMac** [ForgeEssentials/ForgeEssentials#2301]
Hi guys,
 
Hoping someone can help me resolve an issue i've been having when playing on a modded single player with Forge (Via Twitch Client, if that helps).

 The issue is simply - Whenever i log out of a world after playing, the world is completely corrupt - according to Minecraft.

The only time this seems to happen - is when i have both Forge Essentials and Multiworld installed and enabled (since that's what i've been trying to test to have multiple worlds), if i disable them both, i have no issues (that's with the other 70 or so mods installed).

Can't say i've seen an issue like this before - but i can't seem to resolve it, nor would know where to start.

If anyone has any brilliant ideas - that'd be much appriciated.

 If you need any other info, please let me know.

<img width="543" alt="corrupt" src="https://user-images.githubusercontent.com/30386056/28498845-76167f4c-6f9f-11e7-9150-c9c0f97d1372.png">
Thanks.

**Comment by spacebuilder2020** [comment]
Closed for not following our simple rules.
https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

Please at a minimum give a mod list and forge essentials version.
There is nothing I can do to help you without this and you are just wasting my time by submitting this without that.
