### ISSUE TITLE
[1.10.2] Can't Craft Anything

### ISSUE THREAD

**Issue by rmnaderdev** [ForgeEssentials/ForgeEssentials#2302]
Upon setting up a Age of Engineering server I noticed that no one could craft anything. I tried giving myself all permissions and even Op and still nothing. The only way I could craft was removing Forge Essentials. Even with Permission Debug enabled there is nothing printing into console when I try to craft. Any idea what could be causing this?

**Comment by yuuka-miya** [comment]
Are you using FTB utils?

You need to disable the FTBU permission handler.

**Comment by rmnaderdev** [comment]
So are they conflicting?

**Comment by spacebuilder2020** [comment]
Only partially.  Ftb Utils should work fine with FE if you disable the permission handler in FTBU.

See https://github.com/ForgeEssentials/ForgeEssentials/issues/2300#issuecomment-317123462

**Comment by rmnaderdev** [comment]
Thank you! I guess I missed that when looking through the existing issues.

**Comment by spacebuilder2020** [comment]
np
