### ISSUE TITLE
Hello, can i reprinted you mod?

### ISSUE THREAD

**Issue by RGHSSS** [ForgeEssentials/ForgeEssentials#2304]
Hi, i see the mod is reprinted by liach, on china mcbbs. But his article about the mod version is too elder, so i think i need to reprinted the mod to the mcbbs again. Can i have the reprinted permission by the dev team?
(My english is really bad, i hope you can understand my issues.)

**Comment by liach** [comment]
搬运是repost不是reprint
表示我已经弃坑了，欢迎接坑
Yeah, I am not really active on mcbbs. You can continue it as long as you follow @luacs1998 's rules.

**Comment by RGHSSS** [comment]
偶。。。。。我英文太差，有时候很多错词，我就是看了你的帖子才打算接坑了，外加我住的地方无需翻墙所以访问这些资源很方便。最近查看他在昨天发布了新的FE。
Yep,i follow @luacs1998 's rules and i hope the dev team can let me to repost this mod.

**Comment by yuuka-miya** [comment]
有写下我们 Forge Essentials 组的名就可以了。
更好就是放我们网址 www.forgeessentials.com
