### ISSUE TITLE
Cannot craft FTB Infinity Lite

### ISSUE THREAD

**Issue by ZeroCoolAZ** [ForgeEssentials/ForgeEssentials#2305]
Not sure if this is something to do with forge version, etc., but I am currently running FTB Infinity Lite from the curse mod loader, after installing I am unable to use vanilla crafting nor a vanilla crafting table.

I've tested other mods crafting (TinCon workstation, super crafting frame) these work fine. Any ideas? Nothing in the permissions .txt file related to interaction / crafting either.

**Comment by ZeroCoolAZ** [comment]
Couldn't find anything in the FTBU cfg about disabling permissions?

**Comment by spacebuilder2020** [comment]
Duplicate of https://github.com/ForgeEssentials/ForgeEssentials/issues/2300#issuecomment-317123462
