### ISSUE TITLE
Config Resetting to default

### ISSUE THREAD

**Issue by DaGingi** [ForgeEssentials/ForgeEssentials#2308]
Whenever I change the settings.cfg file and restart the server, my config resets to the default values. The specif one that I am having issue with is fe.afterlife.deathchest as I'm trying to disable it, and when I set the value to false and save the file and then reload the server, the config file has been reset and the value set to true. The other thing I was wandering is how to change the name of the guest group, to something like player.
Thanks for your help in advance.
Fraser

**Comment by spacebuilder2020** [comment]
Please make sure that the server is offline before making a change.  Also, for the _GUEST_ group, it is easy to change the prefix.  Follow our permissions tutorial on the wiki for more info.

**Comment by DaGingi** [comment]
When I am making the change to the config the server is offline, however
when I relauch the server after making the change fe.afterlife.deathchest
has gone from false (what I set it as) to true (what the default is).

**Comment by spacebuilder2020** [comment]
Can you post a pastebin of your settings.cfg file after you made the change and before it was overwritten?

**Comment by DaGingi** [comment]
There ya go!
https://pastebin.com/Y21PMwc8
Thanks again,
Fraser

**Comment by spacebuilder2020** [comment]
You are setting the comment to false.  Try Seting line 63 to `S:enable=false`

**Comment by DaGingi** [comment]
You have no idea how stupid I feel, I can't believe I didn't notice the # !
Thanks so much for your time!
Regards,
Fraser

**Comment by spacebuilder2020** [comment]
Np
