### ISSUE TITLE
World Corruption [1.7.10]

### ISSUE THREAD

**Issue by DetectiveMac** [ForgeEssentials/ForgeEssentials#2311]
Hi,

I've been experiencing world corruption when using Forge Essentials.
Forge version 10.13.4.1614 (as installed by Twitch/Curse)
forgeessentials-1.7.10-1.4.6.1341-server.jar

<img width="543" alt="corrupt" src="https://user-images.githubusercontent.com/30386056/29766319-409a9f76-8bd6-11e7-9fc2-63ad00e727f0.png">

I've tried all the versions of forgeessentials on the twitch client - the only one that doesn't seem to corrupt a world (so far - with not much testing, around 10mins or so) is;
forgeessentials-1.7.10-1.4.4.1187

I've attached a grab of all the currently installed mods - that runs no issue (and i've been using for a while now), unless i install forgeessentials. (Forge Essentials not in the list - as i had to uninstall it temporarily to avoid it corrupting any other worlds).

![modlist](https://user-images.githubusercontent.com/30386056/29766671-707dc0dc-8bd7-11e7-8f9c-a5634a3849fc.png)

I installed the latest version as suggested from http://ci.forgeessentials.com/job/FE-1.7.10/ - and continued to have corruption of worlds upon trying to load into them.

I am not having a crash of any kind, so it's not producing a report - whenever i select a world to play - it get the message (posted at the top by image) and it puts me back to the main menu.

This happens with existing worlds, or even when i create a new one, close the game, and try to reopen that world - it's corrupt. Even if i do nothing but spawn, then log out.

Not sure what else i can try - The main reason i want Forge Essentials - is for defining zones and stopping spawns/damage etc. As i have some areas i wanted protected. 

If there is another way of doing this that works on the versions i am running - i can look into that, but i've not found anything yet.

Thanks in advance for any help, hopefully the above gives you a good idea of what is being used/running.

**Comment by Zethalion** [comment]
What happens when you remove fastcraft? This is the first you need to do.

**Comment by DetectiveMac** [comment]
Hello,

Thanks for the suggestions - i removed fastcraft, installed the latest version of forge essentials from the link in my OP. Still the same corruption message when trying to connect to the world. (created a new one to test this, loaded in, played for 10mins or so). Logged out - try to load up again, corrupt.

What would be the next step?

**Comment by Zethalion** [comment]
Can you post the latest-fml-server.log using pastebin or gist?

**Comment by DetectiveMac** [comment]
I'm not running a server, it's a single player game. All loaded through twitch. I have a fml-client-latest log if that will help?

Edit: 
https://gist.github.com/DetectiveMac/d0bfb2bf862b1dd60ea1a8dd830b6610#file-fml-client-latest
If you need it. If not, let me know what will help.

**Comment by Zethalion** [comment]
FE is not supported on the client. It's server only.

**Comment by DetectiveMac** [comment]
Yet it works? Because unless i disconnect from a world and go back in, i can play and use it until that point.

**Comment by Zethalion** [comment]
FE might work fine on single player. If it does, great but any problems with in that case won't receive support since it's server only targeted. The compagnon mod however, is for use one the client. It provides support to show zones and selection by FE server. But as you might guess, they do not work together on the client.

**Comment by DetectiveMac** [comment]
Okay, fair enough. Any suggestions for some kind of mod that allows me to flag zones with no hostile spawns? I know World Guard exists, but apparently doesn't work with forge via twitch from what i've tried.

**Comment by Zethalion** [comment]
You should set up a server with FE installed but if you can't you could add Extra Utilities and craft a Magnum torch. Once placed it prevents hostile mob spawning in a very wide range. Good luck!

**Comment by DetectiveMac** [comment]
I managed to get a server set up, copied over all the mod jar files and played with configs to make sure everything match.

Installed Forge Essentials.

It runs very smoothly, and no issues at all - thanks for your help!
