### ISSUE TITLE
[1.7.10] [1.4.6.1348] Problem with Mekanism

### ISSUE THREAD

**Issue by Ruok2bu** [ForgeEssentials/ForgeEssentials#2312]
ForgeEssentials Version: 1.7.10-1.4.6.1348-server
Forge Version: 1.7.10-10.13.4.1558-1.7.10-universal
Mekanism Version: 1.7.10-9.1.0.281
Minecraft Version: 1.7.10

ForgeEssentials can't pick up interaction events to Mekanism blocks.  I created an area, and gave permission to my members group to interact with the Mekanism blocks.  I gave the following permissions:

`"fe.protection.interact.Mekanism.MachineBlock2.4": "true",
              "fe.protection.use.minecraft.baked_potato": "true",
              "fe.protection.interact.Mekanism.MachineBlock.5": "true",
              "fe.protection.interact.Mekanism.EnergyCube": "true",
              "fe.protection.interact.Mekanism.MachineBlock.6": "true",
              "fe.protection.interact.Mekanism.MachineBlock.13": "true",
              "fe.protection.interact.Mekanism.MachineBlock.15": "true",
              "fe.protection.interact.BiblioCraft.BiblioFancySign.*": "false",
              "fe.protection.interact.MekanismGenerators.Generator.6": "true",
              "fe.protection.interact.Mekanism.EnergyCube.*": "true"`

Then just to be safe, i saved them and stopped and started the server and connected with my members group player.  I was unable to interact with any of the Mekanism blocks (factories, chests, etc.).

To confirm that this is actually the case (that there's an incompatibility), i then added the wooden door interaction permission:

`"fe.protection.interact.minecraft.wooden_door.*": "true",`

Then i saved, stopped and started the server again (as im doing these edits through config files).  With my member account i was able to open and close the wooden door, but still unable to interact with the Mekanism blocks.

P.S. For the member account tests, i did them myself instead of relying on another player so my observations are not error prone.

P.P.S. Mekanism blocks set to public or private still suffer from this problem.

**Comment by Zethalion** [comment]
Try using these ingame commands instead:

```
/p group members allow fe.protection.interact.Mekanism.MachineBlock.*
/p group members allow fe.protection.interact.Mekanism.MachineBlock2.*
/p group members allow fe.protection.interact.Mekanism.MachineBlock3.*
/p group members allow fe.protection.interact.Mekanism.EnergyCube.*
/p group members allow fe.protection.interact.MekanismGenerators.Generator.*
```

**Comment by Ruok2bu** [comment]
I already tried those yesterday when i saw that the specific ones weren't working.  Those dont work either :/

**Comment by Ruok2bu** [comment]
Aha! I figured it out!

It was server.properties spawn-protection that was messing it up.  Setting that variable to 0 fixed it.  Sorry for any wasted time.

**Comment by Zethalion** [comment]
No problem. Great you found the culprit.
