### ISSUE TITLE
Example of onServervote.txt ?

### ISSUE THREAD

**Issue by Baaleos** [ForgeEssentials/ForgeEssentials#2315]
Can we get an example of onServervote.txt 
I can see this as a blank file in the JScripting directory.
But without an example to work from, I don't know how to write a script that takes the players name argument etc.

**Comment by Zethalion** [comment]
``` 
function onServervote(sender) {
    Server.runCommand(sender.doAs(null, true), 'wallet', sender.getPlayer().getName(), 'add', 200);
    sender.chatConfirm('You are rewarded for voting ' + sender.getPlayer().getName() + '!');
}
