### ISSUE TITLE
Turn off worldedit outline?

### ISSUE THREAD

**Issue by Maxxgold** [ForgeEssentials/ForgeEssentials#2316]
Sorry if this is simple. I couldn't find an answer anywhere. I'm using the wand to protect some areas, and I have the client side jar installed, so that I can see the outline.

I can't figure out how to turn off the outline, If anyone could help, I would appreciate it. Thank you!

**Comment by Zethalion** [comment]
FE uses Worldedit for selections so you'll need the Worldedit command `//desel` to clear the selection or outline.
