### ISSUE TITLE
voidworld spawn vanishes

### ISSUE THREAD

**Issue by leytilera** [ForgeEssentials/ForgeEssentials#2319]
i have a server with a void world, forgeessentials and ftb islands. i build a spawn, but afer i die the spawn isnt there. i set the spawnpoint to the spawn and i am at the same coordinates but the spawn isnt there.

**Comment by Zethalion** [comment]
Is this still an issue on 1.12.2 ? Closing this issue in 7 days if no response @MineProjectZ

**Comment by maximuslotro** [comment]
Issue closed. Open a new issue if the issue persists.
