### ISSUE TITLE
"moved too quickly" and throw back

### ISSUE THREAD

**Issue by BlayzerQ** [ForgeEssentials/ForgeEssentials#2321]
With ForgeEssentials installed, Sometimes it throws back when flying. In the console at this moment "Player  moved too quickly!"
How fix this?

**Comment by borrel** [comment]
Please make sure `allowFlight` is `true` in `server.properties`.

It should always be `true` in modded mc.

**Comment by BlayzerQ** [comment]
allowFlight is true. ussue is still.

**Comment by Zethalion** [comment]
This is vanilla behavior. Not within the scope of FE.
