### ISSUE TITLE
Need help with Sleep skips

### ISSUE THREAD

**Issue by SpliTx3** [ForgeEssentials/ForgeEssentials#2326]
Couldn't find any help at Google so i hope it's ok to ask here.
When I go to bed (as OP) or 2 out of 3 Players the Night skips instantly.

I had already found on google that it have something to do with the "essentials.sleepingignored"
permission, but i couldnt find it in the config files anywhere.

thx for ur help and sorry for beeing a noob <.< xD

**Comment by Zethalion** [comment]
You can change the percentage of sleepers in main.cfg
>  # Once this percent of player sleeps, allow the night to pass
>         I:MajoritySleepThreshold=100

Then you reload the config in-game using `/feinfo reload`

**Comment by Zethalion** [comment]
@SpliTx3 , is this still an issue?

**Comment by Zethalion** [comment]
Closed for not responding is a long time
