### ISSUE TITLE
Minecraft forge server crash

### ISSUE THREAD

**Issue by TheGuyThatLivesInSweden** [ForgeEssentials/ForgeEssentials#2327]
When i open my forge universal.jar file it loads in the server and then just crash. i have changed the eula but it just keeps closing.

**Comment by Zethalion** [comment]
Closed for not following our guidelines [here](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs)!

Please correct your issue to follow these guidelines and then reopen this issue.
