### ISSUE TITLE
Unknown Server crash. on MC 1.7.10

### ISSUE THREAD

**Issue by iceman11a** [ForgeEssentials/ForgeEssentials#2330]
When I start up a server with this -> ForgeEssentials{1.4.6} [Forge Essentials] (forgeessentials-1.7.10-1.4.6.1348-server.jar)  and I have the client side version of forgeessentials-1.7.10-1.4.6.1341-client and it seems to load fine. Just my server crashes. I posted the log, Let me know what you fine. Thanks
[crash-2017-12-04_16.11.32-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/1528842/crash-2017-12-04_16.11.32-server.txt)

**Comment by kingdevnl** [comment]
What mods do you have on your server?

**Comment by iceman11a** [comment]
I have over 100 mods. Giving you a list would be a pain. Most of the basic ones. Like Buildcraft. Traincraft, AE2. Mek!. The mods list should be in the crash report. If you look threw it, It should have a complete list of mods.

**Comment by Zethalion** [comment]
FE is not supported to run on anything else than pure Forge. You are using a Cauldron variant which isn't pure Forge.

Sidenote: The file modlist.txt in ./ForgeEssentials contains all mods used by the server in case you would like to continue this thread.

**Comment by Zethalion** [comment]
You might want to change this in main.cfg if you really want to run FE mixed with Bukkit plugins.

`# Activates safe mode with will ignore some errors which would normally crash the game. Please only enable this after being instructed to do so by FE team in response to an issue on GitHub!
    B:safeMode=true`

Again, not supported so you are on your own with it.
