### ISSUE TITLE
Is there a way to deny permission for fe.protection.place and fe.protection.break for op/command user on a server

### ISSUE THREAD

**Issue by Drawnable** [ForgeEssentials/ForgeEssentials#2332]
Title. I've been trying to set up a 2 people server for me and my brother to play together, but my efforts of making the glasses unbreakable (for using gun mods) and blocks indestructible by explosives (grenades) have been wasted. I've tried setting up permission for user [my own username] then deop my player, but I was still able to destroy said block in said selected zone. Can anyone give me an indepth guide?

**Comment by Zethalion** [comment]
Which version of FE are you using? And how did you setup your permissions?

**Comment by Drawnable** [comment]
I'm using the lastest version, and I'm currently setting up my permissions via opping my ingame character and use /p group/user

**Comment by Zethalion** [comment]
Latest version from where? There are two major Minecraft versions supported and two sources to get the mod from. Again which version are you using? 

For setting up users, please provide your exact command and/or permission files as stored in ./world/FEdata.

**Comment by Drawnable** [comment]
forgeessentials-1.10.2-10.3.1375 for minecraft 1.10.2, sorry for not classifying

**Comment by Drawnable** [comment]
I used /p group _ALL_ deny fe.protection.break*

**Comment by Zethalion** [comment]
That denies everything to break anything anywhere. I suggest you dive into https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial

**Comment by Zethalion** [comment]
In case you need to discus anything that's not on the wiki or to be found in the issues, feel free to join https://discord.gg/FNRQjmr

**Comment by Drawnable** [comment]
yeah I'm trying to do that but after doing that, I myself was still allowed to break blocks...
