### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Effectz-End** [ForgeEssentials/ForgeEssentials#2334]
The title says it all
It's minecraft 1.6.4
The pastebin of the console log:
https://pastebin.com/tna28FTq

The pastebin of the crash report:
https://pastebin.com/8ivzU2sB

The pastebin of ForgeModLoader-server-0:
https://pastebin.com/YSAa6YvS

Thx for your help

**Comment by Zethalion** [comment]
Minecraft Version: 1.6.4

I'm sorry but support is currently for 1.7.10 and 1.10.
