### ISSUE TITLE
Kit ?

### ISSUE THREAD

**Issue by Spyooy** [ForgeEssentials/ForgeEssentials#2336]
Hi, i want to create kit, i use this version : forgeessentials-1.10.2-10.1.1343-server.jar
but where or how create kit ??
Thanks for answer ! :)

**Comment by spacebuilder2020** [comment]
https://github.com/ForgeEssentials/ForgeEssentials/wiki/Commands-Module#kit

**Comment by Spyooy** [comment]
Yes, okay but how can i add item in kit ?

**Comment by spacebuilder2020** [comment]
/kit <name> set [timeout-seconds]
Define a kit from your current inventory (fe.commands.kit.admin)

**Comment by spacebuilder2020** [comment]
Once a kit is created, the only way to add an item is to overwrite it
