### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by NightJolt** [ForgeEssentials/ForgeEssentials#2337]
I created Minecraft 1.12.2 forge server and I am using forge 14.23.1.2587 version which is the latest one.
I applied lucky block mod with correct version but I got this error:

https://pastebin.com/tjjLnTcf

Then I tried to launch server without any mods applied but still giving me this error. Currently, I have java version 9.0.1 which is also latest one. I searched for possible solutions but none them worked. Hope you can help me, guys :( I also tried different forge version but all I get is the same error.

**Comment by Zethalion** [comment]
1.12 is not supported (yet)
