### ISSUE TITLE
MULTIWORLD - Server is Crashing

### ISSUE THREAD

**Issue by MarkNoName** [ForgeEssentials/ForgeEssentials#2340]
MULTIWORLD BUG

I type this command into the chat: /mw create test normal FLAT (enter) and then a world is generated and I just keep falling, after a few seconds my server crashes, and does not want to reboot before I do not have the World file in the server delete

Is this a Bug 

Sry for my Bad Englisch

pls help

~Mark

**Comment by Zethalion** [comment]
Update to latest Jenkins build.
