### ISSUE TITLE
Cannot create a warp

### ISSUE THREAD

**Issue by Sven18** [ForgeEssentials/ForgeEssentials#2341]
Hello.

I am server admin and like to create a warp.

If i do /warp test set, it says: Unknown Warp: ´test´!

But why??

Whats the problem? :(

**Comment by Zethalion** [comment]
Which version of FE are you using?

**Comment by Sven18** [comment]
I use the newest version for 1.7.10....

**Comment by Zethalion** [comment]
Which is?

**Comment by Sven18** [comment]
forgeessentials-1.7.10-1.4.6.1341, i guess....?!

**Comment by Zethalion** [comment]
Please upgrade to the latest Jenkins build and test again.

**Comment by Zethalion** [comment]
Is this still an issue on 1.12.2 @Sven18 ?

**Comment by maximuslotro** [comment]
No response. Considering issue as fixed. If issue persists, open a new issue.
