### ISSUE TITLE
Real Train Mod new realise for 1.12.2, Forge 14.23.2, is not able to add contentpacks.

### ISSUE THREAD

**Issue by DFO28** [ForgeEssentials/ForgeEssentials#2347]
Hello. Recently I've installed RTM for 1.12.2, which was published on CurseForge at the beginning of march. Generally mod works properly, but variety of vehicles is not as big as it could, I found lots of packs that add buses and various trams/trains to the game. Unfourtunately it's only avaliable to download in japanese website, which cant be translated at all. As I understood, there are only packs for 1.7.x and 1.10x MC versions, but no idea where to find those for 1.12.2. I downloaded some ZIP files from japanese resource, but MC didnt start working and made an error. How can I add models of vehicles to 1.12.2? 

By the way, in mod there are also traffic lights, and they don't react on lever/redstone and dont work. Is there a way to make them shine?

Advanced thanks for help.

**Comment by Zethalion** [comment]
Wrong github issue tracker. This is ForgeEssentials.
