### ISSUE TITLE
Clock as log reader tool causes problems with Thaumcraft

### ISSUE THREAD

**Issue by UnixRonin** [ForgeEssentials/ForgeEssentials#2348]
The use of the Minecraft clock as a log reader tool, activated by right-click or shift-right-click, causes a problem with Thaumcraft 6.  The clock is used as a component in infusion-crafting the Biothaumic Mind, which requires placing it on an infusion pedestal by right-clicking the pedestal with the clock.  However, with Forge Essentials loaded, all that this does is read the player log, **and there is no way to disable this or change the item.**  It is therefore impossible to craft the Biothaumic Mind with the Forge Essentials player logger enabled.  It probably also interferes with other mods that allow a right-click interaction using a clock.

Suggestions to fix this:
1.  Allow changing the log reader item in the configuration
or
2.  Make the log-read action require sneak-right-click.

In the interim I can find no workaround except to disable the Player Logger feature.

**Comment by olee** [comment]
It is possible to change that by removing the permission to use the clock as playerlogger reader (also I think it's possible to change the config to use another item as well).
Once you do not have to permission to read playerlogger data the clock will work as expected again.

**Comment by olee** [comment]
PS: Remove permission `fe.pl.wand` by using for example `/p global deny fe.pl.wand`
