### ISSUE TITLE
Some perms don't show up in the Permissions.txt? [1.7.10]

### ISSUE THREAD

**Issue by Solucent** [ForgeEssentials/ForgeEssentials#2354]
From a reddit post I found the permissions fe.economy.cmdprice.teleport and fe.economy.cmdprice.home. I checked the permissions list on the Wiki and in my server's own permission text file, and they were on neither. Yet I was able to set prices for both commands on my server. I'm now paranoid that there's a big pool of permissions that I simply cannot see? Any help?

**Comment by Munkeywaxx** [comment]
The Big Pool of permissions you think you might be missing are here in the Wiki:
https://github.com/ForgeEssentials/ForgeEssentials/wiki/PermissionList.txt

**Comment by Zethalion** [comment]
Read the wiki
