### ISSUE TITLE
Forge Essentials 1.10.2  10.3.1375 Keeps crashing.

### ISSUE THREAD

**Issue by Faeroice** [ForgeEssentials/ForgeEssentials#2355]
My server works beautifully prior to installing this, but the moment I install all it does is crash

**Comment by Zethalion** [comment]
Closed for not following our guidelines [here](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs)!

Please correct your issue to follow these guidelines and then reopen this issue.
