### ISSUE TITLE
[1.10.2] Crash when placing piston

### ISSUE THREAD

**Issue by bluepython508** [ForgeEssentials/ForgeEssentials#2361]
(Crashlog)[https://gist.github.com/bluepython508/720b84ff02023cac08f6bcf6303cf7b0]
I'm not sure what causes this, but it happened while I was placing a piston.

**Comment by Zethalion** [comment]
Can you provide all the details to replicate this if this is still an issue?

**Comment by bluepython508** [comment]
I don't think I still have all the stuff anymore. I don't even remember this issue.
