### ISSUE TITLE
Server crash on start 1.12.2-2705

### ISSUE THREAD

**Issue by Sossouille** [ForgeEssentials/ForgeEssentials#2372]
Crash-reports: https://pastebin.com/MYp3GnzC
Logs: https://pastebin.com/b85LpD0U

**Comment by Zethalion** [comment]
Update to Forge 2772
Taken advise from @spacebuilder2020: "Also, if for some reason you can't update forge, you should be able to disable the multiworld module in main.cfg and that will stop the crash."
