### ISSUE TITLE
Permissions in config file but not working

### ISSUE THREAD

**Issue by DirtyDanPI** [ForgeEssentials/ForgeEssentials#2373]
I recently set up a minecraft server with the Enigmatica 2 expert modpack and added forge essentials mainly for the sake of haveing /tpa and /home.  When i went to add the permissions to the server for people to be able to use these commands they were not able to enter the commands.  They were given the prompt of "you do not have permission to use that command".   I checked the permissions.json in the permissions folder and the permissions for "fe.teleport.tpa" were there so I have no clue as to why it didn't work.  After fiddling around I'm quite stumped.  Any help would be appreciated.

[permissions.json.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2591196/permissions.json.txt)
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2591200/modlist.txt)

**Comment by spacebuilder2020** [comment]
Enigmatica 2 has FTBU installed.  In order to use FE, you need to disable ranks, chat override, and command override.  See #2300 for more details.
