### ISSUE TITLE
Forge Essentials on client crash

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [ForgeEssentials/ForgeEssentials#2375]
Hey guys!
Awesome mod! Kind of neccesary on every serious server.
But for now im having a crash, could you please look into this?
[forge essentials crash.log](https://github.com/ForgeEssentials/ForgeEssentials/files/2631061/forge.essentials.crash.log)

**Comment by Zethalion** [comment]
Don't run FE on the client. Run it on a dedicated server instance.
