### ISSUE TITLE
1.5.2  Download error FE 1.2.2 Snapshot

### ISSUE THREAD

**Issue by myxxmikeyxx** [ForgeEssentials/ForgeEssentials#2376]
Is their a way i can get the old files for this version? It keeps trying to download these files but the github links have either changed or been rename/removed.

 *** Download https://github.com/ForgeEssentials/ForgeEssentialsMain/raw/master/lib/mysql-connector-java-bin.jar
*** Download https://github.com/ForgeEssentials/ForgeEssentialsMain/raw/master/lib/H2DB.jar
*** Download https://github.com/ForgeEssentials/ForgeEssentialsMain/raw/master/lib/metrics-R7-FEmod.jar
 *** Download https://github.com/ForgeEssentials/ForgeEssentialsMain/raw/master/lib/pircbotx-1.9.jar

If possible i would also love to get the client version for minecraft 1.5.2 or if it's the same just let me know please.

[ForgeModLoader-server-1.log]
(https://github.com/ForgeEssentials/ForgeEssentials/files/2637603/ForgeModLoader-server-1.log)

**Comment by spacebuilder2020** [comment]
You should be able to find the files here.

https://github.com/ForgeEssentials/ForgeEssentials/tree/1.2.2_f738_mc152/lib

**Comment by myxxmikeyxx** [comment]
Thank you and also i found this link posted and hidden in a text file in the 1.7 branch
https://www.mediafire.com/folder/dpqhf3ughd4j5/libs

**Comment by spacebuilder2020** [comment]
Great
