### ISSUE TITLE
[1.12.2] Crash on Load/Launch.

### ISSUE THREAD

**Issue by MaxineBean** [ForgeEssentials/ForgeEssentials#2381]
Modpack: [SevTech: Ages 3.0.8](https://minecraft.curseforge.com/projects/sevtech-ages/files/2570732)
Forge Version: forge-1.12.2-14.23.4.2707-universal.jar
How to reproduce: launch the modpack with the mod installed.

Server Side:
Crash Report: https://gist.github.com/MaDmaxwell311/636757919bc00780eef3f4f21987acf3
Log: https://gist.github.com/MaDmaxwell311/7e6af8ae4c639b7a1a75233c0b849adf

Client Side:
Crash Report: https://gist.github.com/MaDmaxwell311/cc01166c658253c2707af65946a7a6cf
Log: https://gist.github.com/MaDmaxwell311/3e0b358ec83d8c2800ae9ceec8b05c1b

**Comment by Zethalion** [comment]
from the log:

> Caused by: net.minecraft.util.ReportedException: This is an Unsupported Version of FE designed to work with older versions of Forge.  If you are on a newer version, you should use the official version of FE!

**Comment by Zethalion** [comment]
Side note: Don't use FE on the client. There is a companion mod released for use on the client.
