### ISSUE TITLE
Multiworld dosen´t work

### ISSUE THREAD

**Issue by Parritoso** [ForgeEssentials/ForgeEssentials#2382]
I have a server in version 1.12.2, with the mod forgeessentials-1.12.2-12.3.27-server.jar. I try to create a world with the multiworld function. But once done, the world did not charge and I was floating in an infinite void. The weirdest thing is that the server did not stop.

I'm sorry if this is not well written, but I'm not English and it speaks very badly.

**Comment by spacebuilder2020** [comment]
We can not help you without more details.  Please post the debug.log and the latest.log including the piece with you running the mw command.

**Comment by manticorex** [comment]
Hi guys, i can confim this problem too. I investigate my log files but there is no error during the creation of a new world. I used just the command "/mw create mining" to create a mining world. In earlier version( 1.7.10) it worked very well but in the newest build this problem appears. 

It seems the command create a folder for the world in FEMultiworld but there are no files like regions or the others. If i use the command "/mwtp mining" i where teleportet 2 blocks far from my actual position in the same world and not to the mining world.

minecraft version 1.12
forge: 1.12.2-forge1.12.2-14.23.5.2768
forgeessentials-1.12.2-12.3.30-server.jar

**Comment by Zethalion** [comment]
The command used is not complete. After the name of the world you need to add `normal DEFAULT [seed]` to make it work. Other options can be explored using the tab key after the name.

**Comment by manticorex** [comment]
Strange if i do that like you said, nothing changed. Minecraft tells me the same thing again. But i miss the old message that the world has been created. It also do not tell me that i have to input a level type... It just says it is optional.

**Comment by Zethalion** [comment]
Can you upload the server log on pastebin or gist?

**Comment by manticorex** [comment]
OK, it semms it was my mistake...
With version 30 it worked well. Even if i just enter "/mw create testworld"
The world will created and it teleports me into the new world.
So big thx for fixing it :)
I think it can be closed now :)

**Comment by spacebuilder2020** [comment]
Strange, nothing changed between 27 and 30 in multiworld
