### ISSUE TITLE
Typescripts not loading?

### ISSUE THREAD

**Issue by KevinMagers** [ForgeEssentials/ForgeEssentials#2384]
I'm running a server using forgeessentials-1.7.10-1.4.6.1355-server and I've imported the example /radar scripts from the wiki both .js and .ts however I cannot get any .ts scripts to load. JavaScripts all seem to work fine but I want the advantages of TypeScript to work as well, I can't help but feel I have missed something

**Comment by spacebuilder2020** [comment]
Please read the rules for submitting [issues](https://github.com/ForgeEssentials/ForgeEssentials/tree/1.7.10/develop#reporting-bugs)!
Specifically, please make sure you are on the latest [Jenkins ](http://ci.forgeessentials.com/job/FE-1.7.10/)build before making an issue.
Please update, verify that you are still having issues and if so follow the rest of the rules.

**Comment by Zethalion** [comment]
The scripting engine only loads and executes js files. If you want to make use of TypeScript, follow the instructions as stated on the wiki. These instructions will make sure your ts files will be transpiled into js files.

**Comment by KevinMagers** [comment]
https://github.com/ForgeEssentials/ForgeEssentials/wiki/JS-Scripting
If this is the wiki you refer to. There are only 3 instructions stated on the wiki in regards to using visual studio code with .ts the word transpile or even compile do not come up at all
"Setup for Visual Studio Code
1. Download and install Visual Studio Code
2. In Visual Studio Code, open the directory ./ForgeEssentials/JScripting
3. Create your own .ts file and start coding!"

**Comment by Zethalion** [comment]
That is correct. You'll need to dive into Atom or VScode docs for the rest. It's out of this scope.
