### ISSUE TITLE
Minecraft crashes whenever a block or item is placed with ForgeEssentials installed.

### ISSUE THREAD

**Issue by morchichu** [ForgeEssentials/ForgeEssentials#2385]
Whenever a block/item is placed in the world with ForgeEssentials installed, Minecraft crashes. When I uninstalled ForgeEssentials, the problem went away. However, I really like ForgeEssentials and would like to continue running it on my server as it is very helpful. Can anyone help me out with this issue? My crash log can be found here:

https://pastebin.com/XZKLTziH

Thank you so much in advance!

p.s.
I know that the ForgeEssentials mod is outdated in this crash log, and I tried updating the mod to the latest version, but the same issue occurred.

**Comment by spacebuilder2020** [comment]
Is this a client crash or a server crash?

**Comment by Zethalion** [comment]
Two things are wrong:
1) forgeessentials-1.12.2-12.3.11-server.jar is old. Update it to build 30 from Jenkins
2) FE on a client not supported. It might work but FE is intended for dedicated server use only.

**Comment by morchichu** [comment]
> Is this a client crash or a server crash?

It's a client-side crash.

**Comment by morchichu** [comment]
> Two things are wrong:
> 
> 1. forgeessentials-1.12.2-12.3.11-server.jar is old. Update it to build 30 from Jenkins
> 2. FE on a client not supported. It might work but FE is intended for dedicated server use only.

Thank you! I'm a bit of a newbie to this server stuff.

**Comment by Zethalion** [comment]
I consider this not an issue anymore.
