### ISSUE TITLE
1.12.2 - Forge Essentials - World Edit permissions broken

### ISSUE THREAD

**Issue by Baaleos** [ForgeEssentials/ForgeEssentials#2386]
On a fresh install of my server.
With Op permissions 
When I attempt to do

//pos1
//pos2
//set air

The following nodes are being checked by FE for permissions
fe.economy.cmdprice./set.air = null
fe.economy.cmdprice./set = null

This results in 'You are not permitted  to do that. Are you in the right mode?'
Is this intentional?
It looks like the default setup for Forge Essentials is configured to try and charge users for the use of world edit commands?

Using: forgeessentials-1.12.2-12.3.30-server

**Comment by blacksythe** [comment]
Also encountered this while testing it to see if it was suitable for use on my server

**Comment by Zethalion** [comment]
Try creative mode as op.

**Comment by Baaleos** [comment]
It looks like some commands work and some do not.

//set command complains about not having permissions.
However
//replace command functions correctly.

In all instances, I was the op/admin of the server - and in creative mode.
Tried with world edit cheat mode on and off from the cfg file.

**Comment by Zethalion** [comment]
Can you try this in vanilla + FE without any other mods?

**Comment by Zethalion** [comment]
Also, please follow our guidelines for reporting issues.
https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

**Comment by spacebuilder2020** [comment]
@Baaleos Please update your post to follow our bug report guidelines.
This issue will be closed in 7 days if the guidelines are not followed.

**Comment by Sandbird** [comment]
Having the same problem with: forgeessentials-1.12.2-12.3.73
My modlist: https://pastebin.com/Ti8tj3gF

**Comment by Zethalion** [comment]
Closed for not following guidelines.

**Comment by Sandbird** [comment]
So what exactly failed the specs for error reporting ?
This thread was already here....so i didnt create a new one since i am not the only one having the same problem.
I uploaded my modlist.
There is no crashlog so nothing to upload.
And the file is 1 url file.

**Comment by BrandonSoul** [comment]
having same problem here

**Comment by Zethalion** [comment]
> Closed for not following guidelines.
