### ISSUE TITLE
Minecraft : Game Crashes after i place a block in creative mode

### ISSUE THREAD

**Issue by CherciuRares** [ForgeEssentials/ForgeEssentials#2390]
Everythign else works fine , it started happening after i installed forge essentials mod and my game crashes after i place any block in creative mode . it doesn't happen in survival. My mods are : Pixelmon 5.1.2, journey map and forge essentials . I am in version 1.10.2

**Comment by Zethalion** [comment]
Please follow our guidelines for reporting issues https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

Edit your post

**Comment by spacebuilder2020** [comment]
Closed for not following the guidelines for reporting issues.
