### ISSUE TITLE
//fewand not working because of world edit

### ISSUE THREAD

**Issue by FatalScarlet** [ForgeEssentials/ForgeEssentials#2391]
Whenever I try to use the command //fewand I get the message " WorldEdit is installed. Please use WorldEdit selections (//wand. //set, etc) Please refer to http://wiki.sk89q.com/wiki WorldEdit/Seletion for more info." But I'm not even trying to use world edit I'm just trying to protect an area lol.. I use 1.7.10 Any advice? am I doing something wrong? lol..

**Comment by Zethalion** [comment]
Use //pos1 and //pos2 instead as /fewand is used only if worldedit is removed from the server.
