### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Wladislav** [ForgeEssentials/ForgeEssentials#2393]
[crash-2019-01-23_15.19.54-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2789021/crash-2019-01-23_15.19.54-server.txt)

**Comment by Zethalion** [comment]
Please follow our guidelines for reporting issues https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

Edit your post

**Comment by Wladislav** [comment]
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2789089/modlist.txt)

**Comment by Zethalion** [comment]
Be more specific. Explain what happend, what you did, everything that is needed to understand.

**Comment by Wladislav** [comment]
I cant ganerate the world with last FE mod. Then i replace forgeessentials-1.12.2-12.3.36-server to forgeessentials-1.12.2-12.3.27-server and now works

**Comment by spacebuilder2020** [comment]
Please upload both your latest.log and your debug.log files with version 12.3.36 while generating the world.

**Comment by spacebuilder2020** [comment]
@Wladislav Please downgrade Forge.  At this point in time versions of Forge newer than 2784 are neither tested or supported.

**Comment by spacebuilder2020** [comment]
This should be fixed in build 39.  @Wladislav Please Verify.
