### ISSUE TITLE
Disable world Guard

### ISSUE THREAD

**Issue by blacksythe** [ForgeEssentials/ForgeEssentials#2394]
Hi Not a bug per say but I would love to be able to disable worldguard.

My reasons for this is that many mod packs now use ftb utilities which also has it's own claiming system etc built into it. 

Essentials seems perfect except it intercepts ticking entities (quark explosive arrow was 1 culprit) which downright crashed the test server several times.

Ive been through the wiki and even through all of the config files but it seems to be the one feature that is always on.

**Comment by blacksythe** [comment]
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2796758/modlist.txt)

**Comment by blacksythe** [comment]
Incase you want to troubleshoot I have attached the crash log
[crash-2019-01-25_16.37.27-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2797029/crash-2019-01-25_16.37.27-server.txt)

Vanilla tnt
[crash-2019-01-25_16.58.04-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2797031/crash-2019-01-25_16.58.04-server.txt)

enfl
[crash-2019-01-25_17.02.11-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2797039/crash-2019-01-25_17.02.11-server.txt)

**Comment by spacebuilder2020** [comment]
#2393 is the same crash... My hunch is that this is forge related.  Only 2784 and below are tested and supported at this point in time.

**Comment by spacebuilder2020** [comment]
This should be fixed in build 39.  Please verify

**Comment by blacksythe** [comment]
Testing now

**Comment by blacksythe** [comment]
The fix works fine and can verifiy it on forge version, 2796.

![enfl_test](https://user-images.githubusercontent.com/11398873/51800095-77768800-2222-11e9-8f4b-13d76b829a0b.gif)

However explosions just outside the claim zone (which has deny explosion) Can still affect the zone, any explosion that happens inside the zone is caught and prevented without any issues.

No other protections where applied to that zone.

![2019-01-27_11 00 18](https://user-images.githubusercontent.com/11398873/51800134-e522b400-2222-11e9-8036-3c06ece94511.png)

**Comment by spacebuilder2020** [comment]
I think that is a different issue.   There seems to be a bug with protections outside of a zone.

**Comment by spacebuilder2020** [comment]
I looked into it some more.  The explosion perm only blocks entire explosions.  There is another perm called 'explode'.  That is block by block.
