### ISSUE TITLE
FE Mob Bounty System

### ISSUE THREAD

**Issue by Icebonez** [ForgeEssentials/ForgeEssentials#2397]
I've been trying to set up a bounty system on my server that rewards players for killing certain mobs. For example, when someone kills a zombie, they get 5 currency. I can't seem to get the server to work in this way, even though I have tried to edit the values in configuration files and even tried globally setting the bounty variables with commands. Is this not possible, or can anyone direct me to how I would go about doing this? Thanks!

**Comment by spacebuilder2020** [comment]
Bounties are controlled through permissions.  Look into the permission nodes on your server for bounties.  These are auto generated and saved in the /ForgeEssentials/Permissions_List.txt file.
