### ISSUE TITLE
This is a question not an issue but I do need to know as I can't find out how.

### ISSUE THREAD

**Issue by ATLASSERVERCORP** [ForgeEssentials/ForgeEssentials#2399]
Is there a way to remove all plots on the server?

**Comment by spacebuilder2020** [comment]
Plot can be removed manually by editing the permissions.json file (if using single json).

You also might be able to do /plot list all and delete them individually.

For questions, visit our [Discord](https://discord.gg/FNRQjmr) and if you have a bug to report, follow our bug report [instructions](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs).

**Comment by ATLASSERVERCORP** [comment]
quick question, discord has a timer and I'm waiting, where is the .json file?

**Comment by spacebuilder2020** [comment]
It lives in the world/FEData folder.

All of this stuff is in the wiki though.

**Comment by ATLASSERVERCORP** [comment]
Thank you so much for your help. sorry to trouble you.

**Comment by spacebuilder2020** [comment]
np.  I apologize for the timer but we were forced to implement it as too many people would join and ask a question before reading the rules.
