### ISSUE TITLE
12.2.2 FE causing server to crash on explosion protection event. 

### ISSUE THREAD

**Issue by Dranemra** [ForgeEssentials/ForgeEssentials#2401]
I've set up 2 protected zones in my server so far. One for spawn, and another for a castle attached. Since setting up mobspawn protection, and explosion protection, my server has crashed 4 times - all related to the same issue. 
Entity Creeper explosion event is causing a failure. I've attached my recent crash log as a reference. Once this event triggers, it takes over 10 minutes to wait to load the server again without it crashing repeatedly with the same error. 
[crash-2019-02-06_22.46.23-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/2839145/crash-2019-02-06_22.46.23-server.txt)

**Comment by Zethalion** [comment]
Closed for not following our guidelines https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

**Comment by Dranemra** [comment]
Did you even read the crash report? seriously.

**Comment by Zethalion** [comment]
I have and noticed you did NOT run the latest build from Jenkins which is required for posting issues.

**Comment by spacebuilder2020** [comment]
Make sure to run the latest build from Jenkins before posting issues.  In some cases, (like this one), the bug will have already have been fixed and just not yet released to curse yet.
