### ISSUE TITLE
[1.12][CubicChunks]Death in a room with 2 blocks in height results in deep 1x1 pit generated without grave

### ISSUE THREAD

**Issue by Foghrye4** [ForgeEssentials/ForgeEssentials#2402]
A title is self-explanatory.
I wonder what logic behind this line:
https://github.com/ForgeEssentials/ForgeEssentials/blob/348273a6c7fe76fa7cda3ab256d2b63125bf8161/src/main/java/com/forgeessentials/util/WorldUtil.java#L68

**Comment by spacebuilder2020** [comment]
Fixed in 3c873a6
