### ISSUE TITLE
[1.12.2] Custom NPC Issue

### ISSUE THREAD

**Issue by vin0m** [ForgeEssentials/ForgeEssentials#2406]
Custom NPCs has a scripting API that allows the NPCs, ScriptedBlocks, and PlayerScripts to execute commands.  FE disables this.  It appears that each NPC and Scripting block would need to be granted permissions (see image below).  This is the list I get when typing "/p user [tab]".  Is there any way to allow all commands from custom npcs?

Modlist: [https://pastebin.com/PyxDr0s7](https://pastebin.com/PyxDr0s7)
Screenshot: [https://i.imgur.com/PpSNJVd.png](https://i.imgur.com/PpSNJVd.png)

**Comment by vin0m** [comment]
Any update on this? Is there a way to exempt entire mods from the permissions system?

**Comment by spacebuilder2020** [comment]
All NPC's are part of the built in NPC group
Simply give that group the permissions you need.
