### ISSUE TITLE
Placing blocks in creative crashes my game.

### ISSUE THREAD

**Issue by Xen122** [ForgeEssentials/ForgeEssentials#2409]
Forge Version:  14.23.5.2808
Mod Version: Latest Jenkins Version, aka (build #52)
Crash Log : https://paste.dimdev.org/egohawered.mccrash

Details: Held a grass block in my hand, placed it, my client crashs.

**Comment by Zethalion** [comment]
Remove FE from your client and run it only on a server instance. FE might work on the client but is not supported.
