### ISSUE TITLE
Creepers crashing the server

### ISSUE THREAD

**Issue by Molnes** [ForgeEssentials/ForgeEssentials#2410]
Forge version: 14.23.5.2811
Mod version: [forgeessentials-1.12.2-12.3.36](https://minecraft.curseforge.com/projects/forge-essentials-74735/files/2663739)
Crash log: [https://pastebin.com/MVtDcfcH](https://pastebin.com/MVtDcfcH)

Details: Every time a creeper starts to explode the server crashes.

**Comment by Zethalion** [comment]
Closed for not following https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
If you had, you would have noticed that this bug has been fixed already and never opened this issue.
