### ISSUE TITLE
Teleport don't work for people below 0Y. Make it compatible with cubic chunk.

### ISSUE THREAD

**Issue by SupremeMarshal** [ForgeEssentials/ForgeEssentials#2412]
Teleport don't work for people below 0Y. Make it compatible with cubic chunk.

**Comment by spacebuilder2020** [comment]
Please update your story to follow https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
Also, Compare to build #[20](https://ci.forgeessentials.com/job/FE-1.12.2/20/) as in build 21, I restored the old teleport command that was lost during the 1.8 update.

**Comment by spacebuilder2020** [comment]
This was fixed a while ago!
