### ISSUE TITLE
FTBU & FE & EnderIO chunk claims/loads

### ISSUE THREAD

**Issue by 1time** [ForgeEssentials/ForgeEssentials#2413]
**Target**
So what I want to achieve is claim and load chunks via FTBU, use the protections and the rest from the FE.
I am on MC 1.12.2, with the latest FE 12.3.56, FTBU 5.3.0.82 is FTBlib 5.4.1.84
The ranks on FTBU are disabled and all the "duplicated" commands.

**The issue**
So despite changing the number of chunks a player can claim/load the info doesn't change on their screen (FTBU)
Because I was setting up a server with Project Ozone 3 at the time I didn't have the time to fiddle with it because I wanted to get the server up and running even with that issue, but I did a bit later.

So I installed MC FTBU & FE and everything worked, (if I am not mistaken and remember correctly) then I started installing one mod after the other and I was checking the claim/load thing, and at the end I believe I found the issue. 
As soon as I installed EnderIO, the changes to the claims/loads the players could do wasn't working any more, the version of EnderIO was/is 5.0.40 and enderIO energy 5.0.40

So now I am to a point were I have to see if there is or if there will be a solution to the problem or if I will have to skip plain forge server and move my setup to something else so I could make the claims and the chunks to work as they should or just abandon FE and rely only on FTBU.

Any input would be much appreciated.

**Comment by spacebuilder2020** [comment]
This is still on our radar.  However, it was de-prioritized as no issue was created for this specific issue until now.  As I also am a fan of EnderIO I will work on diagnosing the issue when I have some free time.

**Comment by darkcamo12** [comment]
this issue still exists wondering if there is any progress on this

**Comment by HenryLoenwind** [comment]
devs: What is failing here? From the ticket it sounds like it's either your config system or network syncing, but it would be very weird for Ender IO to have any influence on that...

**Comment by darkcamo12** [comment]
> **Target**
> So what I want to achieve is claim and load chunks via FTBU, use the protections and the rest from the FE.
> I am on MC 1.12.2, with the latest FE 12.3.56, FTBU 5.3.0.82 is FTBlib 5.4.1.84
> The ranks on FTBU are disabled and all the "duplicated" commands.
> 
> **The issue**
> So despite changing the number of chunks a player can claim/load the info doesn't change on their screen (FTBU)
> Because I was setting up a server with Project Ozone 3 at the time I didn't have the time to fiddle with it because I wanted to get the server up and running even with that issue, but I did a bit later.
> 
> So I installed MC FTBU & FE and everything worked, (if I am not mistaken and remember correctly) then I started installing one mod after the other and I was checking the claim/load thing, and at the end I believe I found the issue.
> As soon as I installed EnderIO, the changes to the claims/loads the players could do wasn't working any more, the version of EnderIO was/is 5.0.40 and enderIO energy 5.0.40
> 
> So now I am to a point were I have to see if there is or if there will be a solution to the problem or if I will have to skip plain forge server and move my setup to something else so I could make the claims and the chunks to work as they should or just abandon FE and rely only on FTBU.
> 
> Any input would be much appreciated.

1time, i was talking with LatvianModder the dev for FTB utilities and we worked out what the issue was and an easy way to resolve it, so whats happening is just mod loading order 

so to temp fix it i change the name of enderio file to zenderio and it changed the load order

**Comment by spacebuilder2020** [comment]
Good to know...  Main reason not much has happened is I no longer have much time for modding

**Comment by LatvianModder** [comment]
throw in "after:ftbutilities" in dependencies in `@Mod` and that should fix it. Or "before:ftbutilities"? Not sure which one

**Comment by spacebuilder2020** [comment]
Ok, thanks for the advice.  I will try that.
