### ISSUE TITLE
Missing perms

### ISSUE THREAD

**Issue by netEdwards** [ForgeEssentials/ForgeEssentials#2414]
I have installed the Server version of FE (12.3.56) and i left the world edit that it installed itself in their. Now i would like to use the world edit mod and when i typed the //set command it said i had no perms to do so , though i was OP on the server. So i investigated with the perms.txt file and pasted the world.edit perm code from the website into the permissions.txt folder then when i launched the server the file was overwritten and the world edit perms were removed from the perms file. Then joined the server and was not able to do //set as OP. Not only that but alot of mods are missing from the perms file, like ProjectE, Vanilla Minecraft commands Ender.IO and more. I play on 1.12.2 FTB Direwolf Modpack.

**Comment by spacebuilder2020** [comment]
Have you read through the wiki, specifically, the permissions tutorial?
https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial

**Comment by netEdwards** [comment]
Yes i have now. When i use the TAB function on /p global allow <PERM> it only list FE and mc which both of the perm nodes are missing some permissions. On my old host i had other nodes like Project e, and minecraft not just mc (which the only command on mc is mc./help) so do i need to download a certain version or.... because i would like to edit the perms but most of them are missing from the file itself and from what i read the tutorial doesnt help

**Comment by spacebuilder2020** [comment]
What version of the DireWolf 20 pack are you running?

**Comment by netEdwards** [comment]
2.4.0

**Comment by SpartaWarsec** [comment]
I`ve got the same problem at my server .  I get the mod pack ("All The Mods 3") and i can use all commands from worldedit. But  when i use "//set"  i will get the answer that i dont have permission for that.  


My version of FE is
server (Build #62 (26.06.2019 04:49:56)  forgeessentials-1.12.2-12.3.62-server.jar)

client (Build #62 (26.06.2019 04:49:56)  forgeessentials-1.12.2-12.3.62-client.jar

**Comment by RealSlimefrog** [comment]
I have same problem, i had /p global allow command.etc but now its just fe.etc and mc.help

**Comment by RealSlimefrog** [comment]
Solved 
Zethalion Today (7/21/19) at 6:38 PM
In case you have FTB Utilities (FTBU) and FE loaded on your server, understand FTBU usually is prioritized in registering as the Forge permission manager. This will disable most of FE's functionality. FE however, is capable to manage all the permissions of FTBU but requires some configuration on your side. Change the following in ./cfg/ftbutilities.cfg:
- Disable ranks (B:enabled=false)
- Disable AFK
- Disable  Commands (B:back=false
B:fly=false
B:heal=false
B:home=false
B:mute=false
B:nick=false
B:ranks=false
B:tpa=false
B:warp=false)
This will ensure near perfect compatibility between FTBU and FE

**Comment by Zethalion** [comment]
@Lateralus46n2 Does this work for you?

**Comment by netEdwards** [comment]
Sorry i never responded, but all i did was remove FTB Utils completely. As its permission system was interfering
