### ISSUE TITLE
Multi World causes console spam

### ISSUE THREAD

**Issue by Price-MA-Butta** [ForgeEssentials/ForgeEssentials#2415]
I am using Forge Essentials 1.7.10-1.4.4.1187. Whenever I create a multi-world no matter what id I use, what I name it, or what world type I use, it spams my console. Whenever it is deleted the world, it stops right away like nothing happened. This started (I think) when I copied and pasted a structure with flans guns and golden bags of holding from my main world to the multi-word. I did it once before with other similar items but I did //undo and it stopped. I can't undo it or remove the structure to fix it. This happens on new multi-worlds as well. I even deleted the files with FileZilla we well. I can't update because of AM2 so I'm looking for another idea or any suggestions on what the spam means. Here is the spam message. 
[spam.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/3052038/spam.txt)

**Comment by Zethalion** [comment]
That version is no longer supported in any way. Update to the latest 1.7.10 release and try again.

**Comment by Price-MA-Butta** [comment]
I already tryed that. I removed AM2 so it would work as well and it just does the same spam.

**Comment by Zethalion** [comment]
Thus update and if needed open an issue with the latest 1.7.10 release.
