### ISSUE TITLE
permissions issue of forge essentials

### ISSUE THREAD

**Issue by BeatingLawrence** [ForgeEssentials/ForgeEssentials#2420]
hi everyone, i'm in trouble with forge essentials mod 1.12.2. 
i used to have an older version (1.6.4) that i updated to 1.12.2 because of the amount of bugs that contains... and now it seems nothing changed...maybe it's my bad but i cannot set me as an administrator because it tells me "you don't have permissions to use this command " or "you cannot do that, are you in the right mode?"or something like that. 
this doesn't  happen for all the commands but only for some of these, and i can't figure it out..
obviously i'm an operator for the server, and only forge essentials command don't get working..

Rcon doesn't work too... it return me "you don't have permissions to use this command" at EVERY command.. "help" too

i tried to create groups, set permissions ecc. but naturally. commands to do that are unusable...

ant help will be appreciated

**Comment by Zethalion** [comment]
I'll point you to this first https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

**Comment by BeatingLawrence** [comment]
thank you, but what have i to do with this?

**Comment by BeatingLawrence** [comment]
ok i've found the way to solve this problem...
only one thing.. how can i assign to an admin ALL the permissions?
how can i assign to all players the auth permission, so they could log in ? it says now that for every command to use..i have to log in...and the problem is that the ability to autenticate is restricted by the same auth module....
so to log in i have to log in first...

**Comment by spacebuilder2020** [comment]
Well, you biggest issue was not specifying what build of Forge Essentials you were using.

The version of Minecraft is not enough information to help you.

Lastly, 1.6.4 is a very old version and not supported at all.

Also, the wiki and discord are the first point of contact as they contain a ton of information about configuring things like permissions and what not.

Another thing to note, is OPs do not have all permissions, they work for most commands but there are some that you need to explicitly provide permissions for.
