### ISSUE TITLE
Unable to give anyone perms

### ISSUE THREAD

**Issue by daneleo** [ForgeEssentials/ForgeEssentials#2421]
the groups are working as the prefixes show however even if I give my self every permission, it wont allow me to use any commands running on feed the beast Ultimate reloaded 1.12.2

the config is setup exactly how the config shows as well as only using the commands In game

**Comment by Zethalion** [comment]
Disable FTBUtils ranks and overlapping commands.

**Comment by daneleo** [comment]
yep I figured that out, forgot to reply
