### ISSUE TITLE
unable to start server while FE is installed

### ISSUE THREAD

**Issue by damianjyates** [ForgeEssentials/ForgeEssentials#2424]
I recently installed FE to utilize some of its many features on my regrowth server and the server crashed on restart. 
[fml-server-2.log](https://github.com/ForgeEssentials/ForgeEssentials/files/3219810/fml-server-2.log)

I have parsed through the included log and found an exception at line 692, but I am unable to decipher its meaning.  Could you provide some insight?

Sincerely,

Damian Yates
on discord as damianjyates

**Comment by Zethalion** [comment]
Easy. You're loading MC 1.7.10 and FE 1.12.2 together. Replace FE 1.12.2 with FE 1.17.10

**Comment by damianjyates** [comment]
Thank you for the prompt response
