### ISSUE TITLE
Forge Essentials crash

### ISSUE THREAD

**Issue by Minecraft2020** [ForgeEssentials/ForgeEssentials#2428]
My server was fine, but i install the mod "forge essentials" and it started to crash when i break blocks in creative mode or if i press"tab" to see commands. I think the problem are the permissions.
(My server doesn´t crash, only mi game)

Crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.145.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  wings (Wings-Mod-1.12.2.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/9/19 1:42 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.forgeessentials.api.permissions.ServerZone.getAdditionalPlayerGroups(ServerZone.java:327)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:404)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:409)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.getPlayerGroups(ZonedPermissionHelper.java:904)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.hasPermission(ZonedPermissionHelper.java:783)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:95)
	at net.minecraft.command.CommandHandler.checkPerms(CommandHandler.java:597)
	at net.minecraft.command.CommandHandler.redirect$tabComplete$zzl000(CommandHandler.java:542)
	at net.minecraft.command.CommandHandler.func_180524_a(CommandHandler.java:183)
	at net.minecraftforge.client.ClientCommandHandler.autoComplete(ClientCommandHandler.java:139)
	at net.minecraft.util.TabCompleter.func_186838_a(TabCompleter.java:65)
	at net.minecraft.util.TabCompleter.func_186841_a(TabCompleter.java:47)
	at net.minecraft.client.gui.GuiChat$ChatTabCompleter.func_186841_a(SourceFile:190)
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:70)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.forgeessentials.api.permissions.ServerZone.getAdditionalPlayerGroups(ServerZone.java:327)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:404)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:409)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.getPlayerGroups(ZonedPermissionHelper.java:904)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.hasPermission(ZonedPermissionHelper.java:783)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:95)
	at net.minecraft.command.CommandHandler.checkPerms(CommandHandler.java:597)
	at net.minecraft.command.CommandHandler.redirect$tabComplete$zzl000(CommandHandler.java:542)
	at net.minecraft.command.CommandHandler.func_180524_a(CommandHandler.java:183)
	at net.minecraftforge.client.ClientCommandHandler.autoComplete(ClientCommandHandler.java:139)
	at net.minecraft.util.TabCompleter.func_186838_a(TabCompleter.java:65)
	at net.minecraft.util.TabCompleter.func_186841_a(TabCompleter.java:47)
	at net.minecraft.client.gui.GuiChat$ChatTabCompleter.func_186841_a(SourceFile:190)
	at net.minecraft.client.gui.GuiChat.func_73869_a(SourceFile:70)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: net.optifine.gui.GuiChatOF

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TuPaps_Isaias'/400412, l='MpServer', x=24.23, y=79.00, z=249.80]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (59,64,261), Chunk: (at 11,4,5 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 224202339 game time, 1181306 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 44 total; [MoCEntitySnail['Snail'/2435, l='MpServer', x=-11.92, y=63.00, z=256.85], MoCEntityAnt['Ant'/2436, l='MpServer', x=-12.29, y=65.00, z=323.01], EntityCreeper['Creeper'/400131, l='MpServer', x=-47.50, y=53.00, z=253.50], MoCEntitySnail['Snail'/2565, l='MpServer', x=98.56, y=69.00, z=280.94], MoCEntitySnail['Snail'/2567, l='MpServer', x=100.79, y=69.00, z=305.67], EntitySheep['Oveja'/2570, l='MpServer', x=100.79, y=70.00, z=314.49], EntitySpider['Araña'/399626, l='MpServer', x=-50.91, y=52.00, z=264.91], MoCEntityWraith['Wraith'/399625, l='MpServer', x=-49.88, y=54.27, z=264.25], MoCEntityBird['Bird'/261264, l='MpServer', x=81.86, y=68.00, z=175.50], EntitySkeleton['Esqueleto'/399761, l='MpServer', x=-38.50, y=24.00, z=273.50], EntitySkeleton['Esqueleto'/400657, l='MpServer', x=-45.50, y=24.00, z=277.50], EntitySkeleton['Esqueleto'/401425, l='MpServer', x=-49.50, y=24.00, z=287.50], MoCEntityAnt['Ant'/262822, l='MpServer', x=-55.35, y=69.00, z=251.87], EntitySkeleton['Esqueleto'/399136, l='MpServer', x=-52.50, y=61.00, z=260.50], EntityWitch['Bruja'/397743, l='MpServer', x=-53.50, y=35.00, z=204.50], MoCEntitySnail['Snail'/2475, l='MpServer', x=9.51, y=64.00, z=303.13], MoCEntityGrizzlyBear['GrizzlyBear'/2476, l='MpServer', x=11.57, y=64.00, z=329.15], EntityArmorStand['Soporte para armaduras'/2488, l='MpServer', x=22.50, y=64.00, z=244.50], MoCEntitySnail['Snail'/2489, l='MpServer', x=16.08, y=64.00, z=304.92], EntityItem['item.item.string'/400071, l='MpServer', x=-36.43, y=52.00, z=267.15], EntityChicken['Gallina'/2498, l='MpServer', x=32.52, y=63.00, z=191.77], EntityZombie['Zombi'/398529, l='MpServer', x=-48.31, y=30.00, z=287.70], MoCEntityCricket['Cricket'/2376, l='MpServer', x=-50.53, y=57.03, z=195.39], MoCEntityMaggot['Maggot'/2377, l='MpServer', x=-48.98, y=65.00, z=231.14], MoCEntitySnail['Snail'/2379, l='MpServer', x=-50.93, y=70.00, z=253.61], EntityItem['item.item.egg'/395723, l='MpServer', x=32.15, y=63.00, z=191.44], EntityChicken['Gallina'/2509, l='MpServer', x=54.80, y=64.00, z=324.14], MoCEntityAnt['Ant'/2382, l='MpServer', x=-44.99, y=71.00, z=263.98], EntityCow['Vaca'/2385, l='MpServer', x=-50.54, y=66.00, z=304.20], EntityChicken['Gallina'/2525, l='MpServer', x=78.14, y=64.00, z=315.50], EntitySpider['Araña'/400985, l='MpServer', x=-52.50, y=52.00, z=259.50], EntitySkeleton['Esqueleto'/399846, l='MpServer', x=-51.50, y=62.00, z=257.50], MoCEntitySnail['Snail'/2401, l='MpServer', x=-38.86, y=67.00, z=231.84], MoCEntitySnail['Snail'/2402, l='MpServer', x=-39.68, y=67.00, z=231.18], MoCEntitySnail['Snail'/2403, l='MpServer', x=-43.76, y=68.00, z=227.25], MoCEntityMaggot['Maggot'/2407, l='MpServer', x=-38.76, y=71.00, z=257.45], MoCEntityFlameWraith['FlameWraith'/397422, l='MpServer', x=-51.34, y=55.13, z=261.23], MoCEntityMaggot['Maggot'/2409, l='MpServer', x=-45.20, y=69.00, z=281.13], MoCEntityWerewolf['Werewolf'/399594, l='MpServer', x=-52.41, y=33.62, z=256.90], EntityPlayerSP['TuPaps_Isaias'/400412, l='MpServer', x=24.23, y=79.00, z=249.80], MoCEntityGrizzlyBear['GrizzlyBear'/2546, l='MpServer', x=87.34, y=71.00, z=301.08], EntityCreeper['Creeper'/401394, l='MpServer', x=100.50, y=19.00, z=306.50], EntitySpider['Araña'/399345, l='MpServer', x=-52.70, y=52.00, z=265.90], EntitySheep['Oveja'/277247, l='MpServer', x=-28.57, y=71.00, z=278.81]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 946924648 bytes (903 MB) / 2919235584 bytes (2784 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 8 total; -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version              | Source                                                          | Signature                                |
	|:------ |:--------------- |:-------------------- |:--------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft       | 1.12.2               | minecraft.jar                                                   | None                                     |
	| UCHIJA | mcp             | 9.42                 | minecraft.jar                                                   | None                                     |
	| UCHIJA | FML             | 8.0.99.99            | forge-1.12.2-14.23.5.2768.jar                                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge           | 14.23.5.2768         | forge-1.12.2-14.23.5.2768.jar                                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | ambientsounds   | 3.0                  | AmbientSounds_v3.0.9_mc1.12.2.jar                               | None                                     |
	| UCHIJA | jei             | 4.14.3.248           | jei_1.12.2-4.14.3.248.jar                                       | None                                     |
	| UCHIJA | appleskin       | 1.0.9                | AppleSkin-mc1.12-1.0.9.jar                                      | None                                     |
	| UCHIJA | baubles         | 1.5.2                | Baubles-1.12-1.5.2 (2).jar                                      | None                                     |
	| UCHIJA | bookshelf       | 2.3.569              | Bookshelf-1.12.2-2.3.569.jar                                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | zawa            | 1.12.2-1.6.0         | zawa+-+1.6.0+(1.12.2).jar                                       | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| UCHIJA | bookworm        | 1.12.2-2.2.0         | bookworm+-+2.2.0+(1.12.2).jar                                   | None                                     |
	| UCHIJA | cfm             | 6.2.0                | cfm-6.2.0-mc1.12.2.jar                                          | None                                     |
	| UCHIJA | classiccombat   | 1.0.0                | ClassicCombat-1.12-1.0.0.jar                                    | None                                     |
	| UCHIJA | clumps          | 3.1.2                | Clumps-3.1.2.jar                                                | None                                     |
	| UCHIJA | ctm             | MC1.12.2-0.3.3.22    | CTM-MC1.12.2-0.3.3.22.jar                                       | None                                     |
	| UCHIJA | customspawner   | 3.11.4               | CustomMobSpawner-3.11.4.jar                                     | None                                     |
	| UCHIJA | cxlibrary       | 1.6.1                | cxlibrary-1.12.1-1.6.1.jar                                      | None                                     |
	| UCHIJA | mocreatures     | 12.0.5               | DrZharks MoCreatures Mod-12.0.5.jar                             | None                                     |
	| UCHIJA | eplus           | 5.0.175              | EnchantingPlus-1.12.2-5.0.175.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | placebo         | 1.5.1                | Placebo-1.12.2-1.5.1.jar                                        | None                                     |
	| UCHIJA | enderbags       | 2.1.0                | Ender+Bags-1.12.2-2.1.0.jar                                     | None                                     |
	| UCHIJA | fastfurnace     | 1.2.1                | FastFurnace-1.12.2-1.2.1.jar                                    | None                                     |
	| UCHIJA | fastbench       | 1.6.0                | FastWorkbench-1.12.2-1.6.0.jar                                  | None                                     |
	| UCHIJA | worldedit       | 6.1.8                | worldedit-forge-mc1.12-6.1.8-dist.jar                           | None                                     |
	| UCHIJA | forgeessentials | 12.3                 | forgeessentials-1.12.2-12.3.56-server.jar                       | None                                     |
	| UCHIJA | gargoyles       | 1                    | Gargoyles+mod+1.12.2+patch+1.jar                                | None                                     |
	| UCHIJA | gravestone      | 1.10.1               | gravestone-1.10.1.jar                                           | None                                     |
	| UCHIJA | guideapi        | 1.12-2.1.8-63        | Guide-API-1.12-2.1.8-63.jar                                     | None                                     |
	| UCHIJA | waila           | 1.8.26               | Hwyla-1.8.26-B41_1.12.2 (1).jar                                 | None                                     |
	| UCHIJA | inventorytweaks | 1.64+dev.145.16d98f2 | InventoryTweaks-1.64+dev.145.jar                                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest       | 1.12.2-7.0.56.840    | ironchest-1.12.2-7.0.56.840.jar                                 | None                                     |
	| UCHIJA | journeymap      | 1.12.2-5.5.2         | journeymap-1.12.2-5.5.2.jar                                     | None                                     |
	| UCHIJA | levelup2        | ${version}           | Level+Up!+2-1.1.22-1.12.jar                                     | None                                     |
	| UCHIJA | malisiscore     | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                                    | None                                     |
	| UCHIJA | malisisdoors    | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                                   | None                                     |
	| UCHIJA | radixcore       | 1.12.x-2.2.1         | RadixCore-1.12.x-2.2.1-universal.jar                            | None                                     |
	| UCHIJA | mca             | 1.12.2-5.3.1         | MCA-1.12.x-5.3.1-universal.jar                                  | None                                     |
	| UCHIJA | mcef            | 0.9                  | mcef-1.12.2-0.9.jar                                             | None                                     |
	| UCHIJA | mobends         | 0.24                 | mobends-0.24_for_MC-1.12.jar                                    | None                                     |
	| UCHIJA | morefurnaces    | 1.10.5               | MoreFurnaces-1.12.2-1.10.6.jar                                  | None                                     |
	| UCHIJA | llibrary        | 1.7.15               | llibrary-1.7.15-1.12.2.jar                                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJA | mowziesmobs     | 1.5.3                | mowziesmobs-1.5.3.jar                                           | None                                     |
	| UCHIJA | oreexcavation   | 1.4.140              | OreExcavation-1.4.140.jar                                       | None                                     |
	| UCHIJA | harvestcraft    | 1.12.2zb             | Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update (1).jar | None                                     |
	| UCHIJA | scenter         | 1.12-3.11.0          | scenter-1.12.2-3.12.0.jar                                       | None                                     |
	| UCHIJA | sparkshammers   | @VERSION@            | sparkshammers-1.12.2-1.9.2.jar                                  | None                                     |
	| UCHIJA | torchmaster     | 1.7.1.74             | torchmaster_1.12.2-1.7.1.74.jar                                 | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHIJA | twilightforest  | 3.8.689              | twilightforest-1.12.2-3.8.689-universal.jar                     | None                                     |
	| UCHIJA | uncrafted       | 3.0.1                | Uncrafted+1.12++(v.3.0.1).jar                                   | None                                     |
	| UCHIJA | waystones       | 4.0.67               | Waystones_1.12.2-4.0.67.jar                                     | None                                     |
	| UCHIJA | webdisplays     | 1.0                  | webdisplays-1.12.2-1.0.jar                                      | None                                     |
	| UCHIJA | wings           | 1.1.4                | Wings-Mod-1.12.2.jar                                            | None                                     |
	| UCHIJA | bauble_wings    | 1.0.0                | Wings-Mod-1.12.2.jar                                            | None                                     |
	| UCHIJA | mobends_wings   | 1.0.0                | Wings-Mod-1.12.2.jar                                            | None                                     |
	| UCHIJA | wolfarmor       | 2.2.3.6              | wolfarmor-1.12.2-2.2.3.1798-universal.jar                       | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.145.jar)
  invtweaks.forge.asm.ContainerTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
wings (Wings-Mod-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	ForgeEssentials: Running ForgeEssentials 12.3.56 (fccdc2d). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Soartex_Fanver.zip
	Current Language: Español (México)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD A4-6300 APU with Radeon(tm) HD Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 430.64
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by Zethalion** [comment]
Remove FE from your client and use the FE client mod on your client.
