### ISSUE TITLE
bootloop when i add forge essentials to my server

### ISSUE THREAD

**Issue by officialkristv** [ForgeEssentials/ForgeEssentials#2430]
[crash-2019-06-21_10.28.45-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/3315118/crash-2019-06-21_10.28.45-server.txt)

**Comment by darkcamo12** [comment]
You have 2 versions of worldedit in you mods folder

**Comment by officialkristv** [comment]
I added world edit as it said I needed it for forge essentials I only added
1 and it was still crashing before I added world edit

**Comment by darkcamo12** [comment]
From the crash log


Duplicate Mods:
    worldedit : /home/server126159/./mods/worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist (1).jar
    worldedit : /home/server126159/./mods/worldedit-forge-mc1.12-6.1.8-dist.jar
