### ISSUE TITLE
PaidCommand and SellCommand

### ISSUE THREAD

**Issue by Elfzenon** [ForgeEssentials/ForgeEssentials#2431]
Just wondering what the proper way to structure the syntax of the commands is in a command block as I am in 1.12 and the commands take out the money or take out the thing I am selling but then do not complete the second section of the command at all meaning it can't function properly.
Please just tell me straight how to do it, no links, just a simple example for 1.12 and then if its a problem specifically rather than a logic error then I can give details on logs and version numbers etc. 

Cheers

**Comment by Elfzenon** [comment]
Modlist: # --- ModList ---



Minecraft;1.12.2;
Minecraft Coder Pack;9.42;http://www.modcoderpack.com/website/
Forge Mod Loader;8.0.99.99;https://github.com/MinecraftForge/FML/wiki
Minecraft Forge;14.23.5.2806;http://minecraftforge.net
MovingWorld CORE;;
Bonsai Trees;1.1.3;https://github.com/thraaawn/BonsaiTrees
CraftTweaker2;4.1.18;http://minetweaker3.powerofbytes.com
Just Enough Items;4.14.4.264;https://github.com/mezz/JustEnoughItems
CraftTweaker JEI Support;2.0.3;
CraftTweaker Utils;0.5;
Moving World;1.12-6.342;
Davinci's Vessels;@DVESSELSVER@;http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2364835
Effortless Building;1.12.2-2.12;https://minecraft.curseforge.com/projects/effortless-building
WorldEdit;6.1.10-SNAPSHOT;http://wiki.sk89q.com/wiki/WorldEdit
Forge Essentials;12.3;
Inventory Tweaks;1.63+release.109.220f184;https://github.com/Kobata/inventory-tweaks
Minecraft Chromium Embedded Framework;0.9;https://github.com/montoyo/mcef
Railcraft;12.0.0;http://railcraft.info/
WebDisplays;1.0;https://montoyo.net/wd2.php
MTQ fix;1.1.0;

**Comment by Elfzenon** [comment]
The $FE_USER has also got all OP permissions

**Comment by Zethalion** [comment]
Linking to #2346
