### ISSUE TITLE
Help: How to add a folder to be backed up in the backup.config file.

### ISSUE THREAD

**Issue by ovingiv** [ForgeEssentials/ForgeEssentials#2434]
Hello,

I don't understand how to add an additional folder to be backed up when Forge Essentials backups the world DIMs. I've tried to read the wiki but it doesn't properly explain where to add it nor what to put down to add said folder. I would like to backup player data alongside world data.

What do I add to the config file to have it backup that folder too?

**Comment by Zethalion** [comment]
The backup module only backups dimension data. If you want to backup more, best to add a mod like Aroma Backup or use a system wide backup tool.
