### ISSUE TITLE
Server Crashed Upon Startup

### ISSUE THREAD

**Issue by ShawnStrawman** [ForgeEssentials/ForgeEssentials#2439]
The server crashed when I start it up: Crash report:
https://pastebin.com/MtwmzbPQ
Used: Latest 1.7.10 Forge Version, on Minecraft 1.7.10.

**Comment by Zethalion** [comment]
If you searched the issue tracker, you would have known that Ars Magika is not compatible. Remove AM2 and try again. If you really want to have this fixed. Link this issue to theirs.

**Comment by Zethalion** [comment]
Side note: "Latest" is not accurate. A newer version can be released which might have some changes, invalidating your "latest" claim. Better use the actual version number for further reference. @ShawnStrawman

**Comment by ShawnStrawman** [comment]
Why is AM2 not compatible? Is there any way to make it work with AM2?

**Comment by Zethalion** [comment]
Revert to build FE 1.17.10 1187 or below. You'll be missing out some big changes though. Have fun!
