### ISSUE TITLE
disable /noclip all together?

### ISSUE THREAD

**Issue by WarriorGamingserv** [ForgeEssentials/ForgeEssentials#2440]
hi, so i've ran into a problem with a private server i'm running, i have this mod called speedster hero's where you move very fast and can vibrate through walls (basically the flash) yet when i try to do the vibrate thing the chat spams with 'noclip auto-disabled player not flying' i want to completely disable the noclip function all together, is there a way todo that?

**Comment by TheRealBotcrusher** [comment]
Attempting to use Hydraulic platforms from Galacticraft also yields the same console spam, and of course stops working.

**Comment by RufousFox** [comment]
i also have that problem. lycanite's mobs give effect that spam in chat and leads to a player freeze or teleportation. How can i disable that "noclip auto-disabling".

**Comment by simobambino** [comment]
Is there a fix to this? I am trying to play RLCraft with friends but the fear effect from reapers keeps glitching out immensley!!

**Comment by docteurzoidberg** [comment]
Same here with galacticraft:

With forgeessentials-1.12.2-12.3.65-server.jar, on forge 2838, mc 1.12.2 client, I got a "NoClip auto-disabled: the targeted player is not flying" message in chat when trying to use a Galacticraft Hydraulic Platform block (kind of elevator). and it prevents me from using it.

How i can avoid this and use my cool elevators on my server :slight_smile: ? Many thanks by advance for your help!
(Source involved: Method "CheckClip" in src/main/java/com/forgeessentials/commands/player/CommandNoClip.java)

**Comment by spacebuilder2020** [comment]
No clip has been updated to not process if the player does not have permission to use noclip.

**Comment by docteurzoidberg** [comment]
with latest build FE .66, it still doesn't work when op, i tried:
/p group _OPS_ deny fe.commands.noclip fe.commands.noclip.*
/p group _ALL_ deny fe.commands.noclip fe.commands.noclip.*
without success (but works if i de-op myself)

**Comment by spacebuilder2020** [comment]
Can you post your permissions.json file?  That command should have worked.

**Comment by docteurzoidberg** [comment]
i didn't have it (no file at all on server), i found that the mod doesn't create the singlejson file anymore
I switched to h2 and the results aren't better, i got file, but the deny perm still doesn't work

fe.commands.noclip not being in permissionlist.txt maybe related?

**Comment by spacebuilder2020** [comment]
Well, it should have that file unless another mod is messing with FE.  In that case you are on your own.

**Comment by FoxRomeo** [comment]
I had this problem too.
It's working for me with build .66 and after entering the following commands:

```
/p group _OPS_ deny fe.commands.noclip fe.commands.noclip.*
/p group _ALL_ deny fe.commands.noclip fe.commands.noclip.*
```
