### ISSUE TITLE
FTB Utilities and FE permissions conflict [solved]

### ISSUE THREAD

**Issue by RufousFox** [ForgeEssentials/ForgeEssentials#2445]
hi, i have some problems with pex, i configured permiisions with tutorial. I created new group and set up default permissions. Player in this group can use /home, /spawn, /sethome, but cant use /tpa
.in permission.json on this group: fe.teleport.tpa, fe.teleport.tpa.here fe.teleport.tpa.sendrequest on true

**Comment by Zethalion** [comment]
You say /sethome. That command is not part of FE. Do you have FTB Utilities installed as well?

**Comment by RufousFox** [comment]
yes, i have

**Comment by Zethalion** [comment]
In case you have FTB Utilities (FTBU) and FE loaded on your server, understand FTBU usually is prioritized in registering as the Forge permission manager. This will disable most of FE's functionality. FE however, is capable to manage all the permissions of FTBU but requires some configuration on your side. Change the following in ./cfg/ftbutilities.cfg:
- Disable ranks (B:enabled=false)
- Disable AFK
- Disable  Commands (B:back=false
B:fly=false
B:heal=false
B:home=false
B:mute=false
B:nick=false
B:ranks=false
B:tpa=false
B:warp=false)
This will ensure near perfect compatibility between FTBU and FE

**Comment by RufousFox** [comment]
okay, im fullu deleted ftb, i have acces to /tpa, but i dont have perm for /no and /yes. What perm for this command?
