### ISSUE TITLE
Pixelmon Commands

### ISSUE THREAD

**Issue by osmanosman88** [ForgeEssentials/ForgeEssentials#2448]
I read the wiki multiple times over and wondering if I am just dumb or what but I can't get pixelmon commands to work. Before I had forge essentials on the server and could get everything working except /checkspawns which required op or some permission plugin to use it. 
I am just not too sure what I have been doing wrong but its to a point where I want to pull all my hair out xD.

**Comment by Zethalion** [comment]
I'll point you to this first https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

**Comment by Zethalion** [comment]
Closed for not following our rules on reporting bugs. See https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
You may re-open this issue when you acknowledge.
