### ISSUE TITLE
Nullpointerexception crash on server

### ISSUE THREAD

**Issue by i70attackers** [ForgeEssentials/ForgeEssentials#2450]
Hello, this is a client-side crash I'm getting on my own server. It seems to happen when I try to place a block when in creative mode.

here's the report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/27/19 10:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.forgeessentials.api.permissions.ServerZone.getAdditionalPlayerGroups(ServerZone.java:327)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:404)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:409)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.getPlayerGroups(ZonedPermissionHelper.java:904)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.hasPermission(ZonedPermissionHelper.java:783)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:95)
	at net.minecraft.entity.player.EntityPlayer.func_189808_dh(EntityPlayer.java:2765)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.forgeessentials.api.permissions.ServerZone.getAdditionalPlayerGroups(ServerZone.java:327)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:404)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:409)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.getPlayerGroups(ZonedPermissionHelper.java:904)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.hasPermission(ZonedPermissionHelper.java:783)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:95)
	at net.minecraft.entity.player.EntityPlayer.func_189808_dh(EntityPlayer.java:2765)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['i70attackers'/88474, l='MpServer', x=58.67, y=81.81, z=206.78]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (28,91,249), Chunk: (at 12,5,9 in 1,15; contains blocks 16,0,240 to 31,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1859213 game time, 1769942 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 200 total; [EntitySpider['Spider'/88584, l='MpServer', x=110.50, y=79.00, z=246.50], EntityPig['Pig'/1034, l='MpServer', x=24.32, y=71.00, z=160.50], EntitySheep['Sheep'/1035, l='MpServer', x=31.45, y=68.00, z=171.94], EntitySheep['Sheep'/1036, l='MpServer', x=26.66, y=71.00, z=169.77], EntitySheep['Sheep'/1037, l='MpServer', x=27.77, y=71.00, z=175.48], EntitySheep['Sheep'/1038, l='MpServer', x=16.19, y=71.00, z=173.68], EntitySheep['Sheep'/1039, l='MpServer', x=26.80, y=71.00, z=184.63], EntityPig['Pig'/1040, l='MpServer', x=26.28, y=71.00, z=183.59], EntitySheep['Sheep'/1041, l='MpServer', x=22.40, y=71.00, z=184.69], EntityItem['item.item.string'/83472, l='MpServer', x=89.10, y=43.00, z=211.98], EntitySheep['Sheep'/1042, l='MpServer', x=18.24, y=71.00, z=176.79], EntityPig['Pig'/1043, l='MpServer', x=25.49, y=71.00, z=189.67], EntityItem['item.tile.sapling.oak'/84501, l='MpServer', x=85.00, y=71.00, z=211.88], EntityPig['Pig'/1046, l='MpServer', x=35.04, y=70.00, z=212.47], EntityBat['Bat'/86550, l='MpServer', x=71.57, y=45.00, z=191.37], EntityBat['Bat'/86552, l='MpServer', x=65.95, y=49.39, z=203.99], EntityCreeper['Creeper'/87068, l='MpServer', x=67.50, y=45.00, z=211.50], EntitySheep['Sheep'/1081, l='MpServer', x=42.49, y=67.00, z=137.70], EntitySheep['Sheep'/1082, l='MpServer', x=32.74, y=64.00, z=135.46], EntityTurkey['Turkey'/1083, l='MpServer', x=40.47, y=65.00, z=144.22], EntityDeer['Deer'/1084, l='MpServer', x=35.96, y=64.00, z=140.95], EntityDeer['Deer'/1085, l='MpServer', x=39.41, y=64.00, z=146.13], EntityDeer['Deer'/1086, l='MpServer', x=40.50, y=64.00, z=145.50], EntityDeer['Deer'/1087, l='MpServer', x=38.65, y=64.00, z=147.24], EntityItem['item.item.string'/86078, l='MpServer', x=51.48, y=23.00, z=265.15], EntityTurkey['Turkey'/1088, l='MpServer', x=40.50, y=64.00, z=146.53], EntityPig['Pig'/1089, l='MpServer', x=36.71, y=67.00, z=179.42], EntityPig['Pig'/1090, l='MpServer', x=34.87, y=69.00, z=180.35], EntityTurkey['Turkey'/1091, l='MpServer', x=28.55, y=70.00, z=232.45], EntityPig['Pig'/1092, l='MpServer', x=36.46, y=70.00, z=210.75], EntityTurkey['Turkey'/1093, l='MpServer', x=44.43, y=72.00, z=229.31], EntityTurkey['Turkey'/1094, l='MpServer', x=37.38, y=66.00, z=204.88], EntityPig['Pig'/1095, l='MpServer', x=44.72, y=71.00, z=235.61], EntityDeer['Deer'/1096, l='MpServer', x=37.30, y=71.00, z=214.40], EntityPlayerSP['i70attackers'/88474, l='MpServer', x=58.67, y=81.81, z=206.78], EntitySheep['Sheep'/1126, l='MpServer', x=50.45, y=72.00, z=136.16], EntitySheep['Sheep'/1127, l='MpServer', x=50.48, y=68.00, z=131.23], EntitySheep['Sheep'/1128, l='MpServer', x=52.50, y=79.00, z=146.70], EntityTurkey['Turkey'/1129, l='MpServer', x=49.50, y=69.00, z=147.71], EntitySheep['Sheep'/1130, l='MpServer', x=54.49, y=79.00, z=145.27], EntityTurkey['Turkey'/1131, l='MpServer', x=50.50, y=72.00, z=170.38], EntitySheep['Sheep'/1132, l='MpServer', x=61.11, y=91.00, z=165.27], EntityTurkey['Turkey'/1133, l='MpServer', x=62.56, y=91.00, z=160.59], EntityItem['item.item.string'/85104, l='MpServer', x=56.74, y=22.00, z=200.88], EntitySkeleton['Skeleton'/87667, l='MpServer', x=18.50, y=18.00, z=195.50], EntityDeer['Deer'/1139, l='MpServer', x=54.91, y=69.00, z=202.97], EntityPig['Pig'/1140, l='MpServer', x=74.51, y=71.38, z=200.45], EntityPig['Pig'/1141, l='MpServer', x=42.50, y=71.92, z=213.52], EntityTurkey['Turkey'/1142, l='MpServer', x=55.53, y=71.00, z=239.29], EntityDeer['Deer'/1143, l='MpServer', x=53.99, y=71.00, z=238.16], EntityTurkey['Turkey'/1144, l='MpServer', x=59.72, y=72.00, z=219.53], EntityDeer['Deer'/1145, l='MpServer', x=63.50, y=75.00, z=226.50], EntityDeer['Deer'/1146, l='MpServer', x=62.50, y=76.00, z=229.96], EntityTurkey['Turkey'/1149, l='MpServer', x=61.70, y=69.00, z=250.51], EntityPig['Pig'/1150, l='MpServer', x=61.52, y=69.00, z=248.67], EntityItem['item.item.pawpawitem'/86143, l='MpServer', x=110.89, y=73.00, z=212.69], EntityBat['Bat'/88704, l='MpServer', x=16.53, y=16.27, z=166.02], EntityBat['Bat'/88714, l='MpServer', x=71.41, y=21.55, z=250.08], EntityDeer['Deer'/1168, l='MpServer', x=78.01, y=83.00, z=129.05], EntityDeer['Deer'/1170, l='MpServer', x=65.01, y=91.00, z=153.86], EntityTurkey['Turkey'/1171, l='MpServer', x=72.26, y=90.00, z=153.48], EntitySheep['Sheep'/1172, l='MpServer', x=77.29, y=91.00, z=158.39], EntityDeer['Deer'/1173, l='MpServer', x=67.20, y=92.00, z=164.76], EntityTurkey['Turkey'/1174, l='MpServer', x=77.50, y=92.00, z=166.23], EntityTurkey['Turkey'/1175, l='MpServer', x=58.78, y=90.00, z=167.51], EntitySheep['Sheep'/1176, l='MpServer', x=73.44, y=93.00, z=164.45], EntityDeer['Deer'/1177, l='MpServer', x=78.50, y=93.00, z=181.50], EntityItem['item.tile.sapling.oak'/87192, l='MpServer', x=83.21, y=71.00, z=210.11], EntityTurkey['Turkey'/1178, l='MpServer', x=70.72, y=92.00, z=171.51], EntityDeer['Deer'/1179, l='MpServer', x=44.94, y=72.00, z=231.02], EntityPig['Pig'/1180, l='MpServer', x=71.77, y=81.00, z=249.89], EntityTurkey['Turkey'/1181, l='MpServer', x=58.32, y=72.00, z=213.77], EntityDeer['Deer'/1182, l='MpServer', x=75.03, y=82.00, z=240.00], EntityItem['item.tile.sapling.oak'/85151, l='MpServer', x=107.88, y=71.00, z=212.84], EntityButterfly['Butterfly'/82593, l='MpServer', x=-1.74, y=73.88, z=198.93], EntityPig['Pig'/1185, l='MpServer', x=70.29, y=79.00, z=245.80], EntityDeer['Deer'/1186, l='MpServer', x=72.76, y=81.00, z=249.50], EntityTurkey['Turkey'/1187, l='MpServer', x=64.68, y=81.00, z=251.50], EntitySkeleton['Skeleton'/87719, l='MpServer', x=7.50, y=77.00, z=256.50], EntitySkeleton['Skeleton'/87219, l='MpServer', x=67.50, y=22.00, z=273.50], EntityItem['item.tile.sapling.oak'/85173, l='MpServer', x=84.85, y=71.00, z=208.20], EntitySheep['Sheep'/1208, l='MpServer', x=95.44, y=90.00, z=131.48], EntitySheep['Sheep'/1209, l='MpServer', x=87.80, y=89.00, z=132.50], EntityTurkey['Turkey'/1210, l='MpServer', x=93.31, y=87.00, z=136.52], EntityDeer['Deer'/1211, l='MpServer', x=80.71, y=86.00, z=150.72], EntitySheep['Sheep'/1213, l='MpServer', x=80.29, y=92.00, z=174.49], EntityDeer['Deer'/1215, l='MpServer', x=72.92, y=77.00, z=231.87], EntityDeer['Deer'/1217, l='MpServer', x=85.96, y=66.00, z=251.89], EntityTurkey['Turkey'/1218, l='MpServer', x=91.71, y=70.00, z=247.50], EntityDeer['Deer'/1219, l='MpServer', x=82.00, y=80.00, z=235.50], EntityTurkey['Turkey'/1220, l='MpServer', x=78.45, y=78.00, z=246.17], EntityDeer['Deer'/1221, l='MpServer', x=92.36, y=66.00, z=264.38], EntityBat['Bat'/88264, l='MpServer', x=65.31, y=41.10, z=177.28], EntityBat['Bat'/87756, l='MpServer', x=20.72, y=22.05, z=192.95], EntityItem['item.item.egg'/87761, l='MpServer', x=2.27, y=72.00, z=206.64], EntityZombie['Zombie'/88786, l='MpServer', x=134.72, y=82.00, z=259.48], EntityCreeper['Creeper'/88789, l='MpServer', x=15.23, y=71.00, z=154.50], EntityZombie['Zombie'/88790, l='MpServer', x=69.50, y=92.00, z=161.50], EntityPig['Pig'/1240, l='MpServer', x=97.52, y=91.00, z=129.49], EntitySheep['Sheep'/1241, l='MpServer', x=101.48, y=90.00, z=135.70], EntityTurkey['Turkey'/1242, l='MpServer', x=112.24, y=91.00, z=141.69], EntitySheep['Sheep'/1243, l='MpServer', x=109.71, y=88.00, z=154.45], EntitySheep['Sheep'/1244, l='MpServer', x=102.02, y=86.00, z=155.31], EntityCreeper['Creeper'/88284, l='MpServer', x=47.70, y=78.00, z=226.30], EntityDeer['Deer'/1245, l='MpServer', x=99.97, y=86.00, z=151.98], EntityTurkey['Turkey'/1246, l='MpServer', x=105.27, y=87.00, z=153.54], EntityItem['item.tile.sapling.oak'/87777, l='MpServer', x=67.58, y=78.00, z=206.57], EntityDeer['Deer'/1248, l='MpServer', x=99.50, y=72.00, z=213.50], EntitySpider['Spider'/87776, l='MpServer', x=62.30, y=75.10, z=227.30], EntityTurkey['Turkey'/1249, l='MpServer', x=98.25, y=74.00, z=232.13], EntityDeer['Deer'/1250, l='MpServer', x=105.88, y=71.00, z=239.99], EntitySpider['Spider'/86253, l='MpServer', x=24.00, y=57.00, z=216.51], EntitySheep['Sheep'/1266, l='MpServer', x=116.61, y=90.00, z=147.88], EntitySheep['Sheep'/1267, l='MpServer', x=126.67, y=89.00, z=154.11], EntitySheep['Sheep'/1268, l='MpServer', x=123.84, y=89.00, z=157.81], EntitySheep['Sheep'/1269, l='MpServer', x=117.80, y=88.00, z=157.55], EntityTurkey['Turkey'/1270, l='MpServer', x=134.36, y=89.00, z=146.84], EntityTurkey['Turkey'/1271, l='MpServer', x=118.71, y=90.00, z=147.50], EntityTurkey['Turkey'/1272, l='MpServer', x=124.45, y=89.00, z=160.55], EntityTurkey['Turkey'/1273, l='MpServer', x=108.46, y=87.00, z=171.74], EntityDeer['Deer'/1274, l='MpServer', x=124.14, y=71.00, z=205.93], EntityDeer['Deer'/1275, l='MpServer', x=120.50, y=85.00, z=197.13], EntityTurkey['Turkey'/1277, l='MpServer', x=121.19, y=78.00, z=250.68], EntityCreeper['Creeper'/88835, l='MpServer', x=76.50, y=27.00, z=139.50], EntityCreeper['Creeper'/88837, l='MpServer', x=83.50, y=75.00, z=246.50], EntitySkeleton['Skeleton'/88842, l='MpServer', x=84.50, y=83.00, z=276.50], EntityDeer['Deer'/1296, l='MpServer', x=123.50, y=90.00, z=142.50], EntitySheep['Sheep'/1297, l='MpServer', x=134.84, y=89.00, z=139.99], EntitySkeleton['Skeleton'/88339, l='MpServer', x=35.54, y=64.00, z=130.25], EntityDeer['Deer'/1298, l='MpServer', x=128.25, y=90.00, z=144.25], EntityTurkey['Turkey'/1299, l='MpServer', x=130.69, y=89.00, z=147.15], EntityTurkey['Turkey'/1300, l='MpServer', x=133.93, y=89.00, z=145.92], EntityTurkey['Turkey'/1301, l='MpServer', x=133.70, y=89.00, z=155.86], EntityDeer['Deer'/1302, l='MpServer', x=136.46, y=89.00, z=145.19], EntitySheep['Sheep'/1303, l='MpServer', x=130.82, y=89.00, z=154.82], EntityTurkey['Turkey'/1306, l='MpServer', x=132.81, y=90.00, z=167.84], EntityTurkey['Turkey'/1307, l='MpServer', x=136.49, y=90.00, z=162.78], EntitySheep['Sheep'/1308, l='MpServer', x=138.83, y=90.00, z=166.28], EntityTurkey['Turkey'/1310, l='MpServer', x=136.49, y=89.00, z=161.55], EntityPig['Pig'/1311, l='MpServer', x=133.91, y=90.00, z=172.25], EntitySheep['Sheep'/1312, l='MpServer', x=128.45, y=89.00, z=177.55], EntitySheep['Sheep'/1313, l='MpServer', x=130.56, y=90.00, z=168.70], EntityPig['Pig'/1314, l='MpServer', x=137.75, y=90.00, z=169.67], EntitySheep['Sheep'/1315, l='MpServer', x=119.81, y=89.00, z=170.48], EntitySheep['Sheep'/1318, l='MpServer', x=136.45, y=89.00, z=177.45], EntityPig['Pig'/1321, l='MpServer', x=139.41, y=89.00, z=176.87], EntitySkeleton['Skeleton'/88875, l='MpServer', x=84.53, y=86.00, z=135.73], EntityTurkey['Turkey'/1326, l='MpServer', x=139.50, y=65.00, z=238.50], EntityTurkey['Turkey'/1327, l='MpServer', x=136.74, y=70.00, z=241.49], EntityTurkey['Turkey'/1329, l='MpServer', x=134.69, y=76.00, z=246.50], EntitySpider['Spider'/88886, l='MpServer', x=52.50, y=19.00, z=195.50], EntityItem['item.tile.sapling.oak'/84803, l='MpServer', x=107.41, y=71.00, z=210.18], EntityCreeper['Creeper'/87877, l='MpServer', x=68.50, y=77.00, z=253.50], EntityItem['item.tile.mushroom'/87879, l='MpServer', x=85.88, y=71.00, z=205.96], EntityItem['item.tile.mushroom'/87878, l='MpServer', x=83.39, y=71.00, z=202.60], EntityZombie['Zombie'/88906, l='MpServer', x=30.50, y=71.00, z=232.50], EntityItem['item.item.string'/87886, l='MpServer', x=1.13, y=74.00, z=166.76], EntityZombie['Zombie'/88916, l='MpServer', x=-16.50, y=70.00, z=145.50], EntityItem['item.item.minecraft:apple'/88931, l='MpServer', x=105.66, y=72.82, z=210.95], EntitySheep['Sheep'/883, l='MpServer', x=-16.67, y=68.00, z=178.40], EntityDeer['Deer'/888, l='MpServer', x=-17.37, y=71.00, z=264.98], EntityItem['item.tile.mushroom'/87940, l='MpServer', x=84.96, y=71.00, z=204.76], EntityCreeper['Creeper'/85385, l='MpServer', x=12.59, y=21.00, z=189.78], EntitySkeleton['Skeleton'/87960, l='MpServer', x=76.30, y=91.00, z=158.58], EntityChicken['Chicken'/922, l='MpServer', x=-8.36, y=72.00, z=136.13], EntitySheep['Sheep'/924, l='MpServer', x=-4.26, y=69.00, z=192.41], EntityTurkey['Turkey'/928, l='MpServer', x=-15.10, y=66.00, z=238.45], EntityTurkey['Turkey'/929, l='MpServer', x=-11.08, y=75.00, z=267.75], EntityTurkey['Turkey'/930, l='MpServer', x=-12.17, y=75.00, z=266.91], EntityTurkey['Turkey'/931, l='MpServer', x=-12.50, y=75.00, z=270.33], EntityTurkey['Turkey'/932, l='MpServer', x=-10.71, y=75.00, z=269.43], EntityTurkey['Turkey'/936, l='MpServer', x=-13.45, y=72.00, z=278.55], EntitySheep['Sheep'/937, l='MpServer', x=-8.10, y=74.00, z=275.45], EntitySpider['Spider'/87976, l='MpServer', x=93.99, y=90.85, z=131.10], EntityTurkey['Turkey'/938, l='MpServer', x=-12.22, y=73.00, z=275.50], EntityTurkey['Turkey'/939, l='MpServer', x=-12.51, y=74.00, z=272.22], EntityDeer['Deer'/940, l='MpServer', x=11.09, y=77.00, z=283.38], EntityDeer['Deer'/941, l='MpServer', x=-6.98, y=74.00, z=277.04], EntityTurkey['Turkey'/942, l='MpServer', x=-7.18, y=74.00, z=278.03], EntityItem['item.item.string'/82863, l='MpServer', x=24.02, y=24.00, z=191.26], EntityPig['Pig'/943, l='MpServer', x=-5.45, y=74.00, z=277.90], EntityPig['Pig'/944, l='MpServer', x=1.23, y=74.00, z=276.31], EntitySkeleton['Skeleton'/87987, l='MpServer', x=40.50, y=66.00, z=131.27], EntityPig['Pig'/946, l='MpServer', x=-19.21, y=69.00, z=286.51], EntityPig['Pig'/980, l='MpServer', x=-2.30, y=74.00, z=159.50], EntityPig['Pig'/981, l='MpServer', x=6.45, y=71.00, z=175.80], EntitySheep['Sheep'/982, l='MpServer', x=12.82, y=71.00, z=173.22], EntitySheep['Sheep'/983, l='MpServer', x=13.24, y=71.00, z=178.52], EntitySheep['Sheep'/984, l='MpServer', x=2.76, y=71.00, z=185.39], EntitySheep['Sheep'/985, l='MpServer', x=6.81, y=71.00, z=186.58], EntityChicken['Chicken'/986, l='MpServer', x=17.20, y=71.00, z=187.57], EntityChicken['Chicken'/987, l='MpServer', x=4.73, y=71.00, z=188.86], EntityPig['Pig'/989, l='MpServer', x=1.52, y=72.00, z=192.76], EntityChicken['Chicken'/990, l='MpServer', x=1.77, y=72.00, z=206.50], EntityPig['Pig'/991, l='MpServer', x=5.73, y=72.00, z=198.46], EntityPig['Pig'/992, l='MpServer', x=7.77, y=71.00, z=197.44], EntityPig['Pig'/993, l='MpServer', x=11.59, y=71.00, z=192.65], EntityPig['Pig'/996, l='MpServer', x=-6.45, y=70.00, z=209.80], EntityItem['item.item.string'/85476, l='MpServer', x=54.52, y=47.00, z=214.78], EntityTurkey['Turkey'/1000, l='MpServer', x=1.46, y=74.00, z=283.22]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 753366744 bytes (718 MB) / 1241513984 bytes (1184 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version      | Source                                        | Signature                                |
	|:------ |:--------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp             | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | biomesoplenty   | 7.0.1.2427   | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar | None                                     |
	| LCHIJA | customspawner   | 3.11.4       | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | evep            | 1.0.3        | evep-1.0.3.jar                                | None                                     |
	| LCHIJA | familiarfauna   | 1.0.11       | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
	| LCHIJA | worldedit       | 6.1.8        | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| LCHIJA | forgeessentials | 12.3         | forgeessentials-1.12.2-12.3.60-server.jar     | None                                     |
	| LCHIJA | jei             | 4.15.0.268   | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| LCHIJA | harvestcraft    | 1.12.2zb     | Pam's+HarvestCraft+1.12.2ze.jar               | None                                     |
	| LCHIJA | waystones       | 4.0.72       | Waystones_1.12.2-4.0.72.jar                   | None                                     |
	| LCHIJA | weeeflowers     | 1.12.2b      | Weee!+Flowers+1.12.2b.jar                     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4727' Renderer: 'Intel(R) HD Graphics 520'
	ForgeEssentials: Running ForgeEssentials 12.3.60 (db2fdd8). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4727, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Vanillatweak
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz

**Comment by Zethalion** [comment]
Client side installation of Forge Essentials Server is not supported. Closing
