### ISSUE TITLE
Worldedit

### ISSUE THREAD

**Issue by Phinlorian** [ForgeEssentials/ForgeEssentials#2456]
How do I remove a tool in worldedit e.g. //brush from a pick

**Comment by Zethalion** [comment]
Those are WorldEdit kind of questions. Ask them. Not sure given the lack of info this is FE related. Elaborate please.

**Comment by spacebuilder2020** [comment]
Ask WorldEdit questions at their [discord](https://discord.gg/enginehub).  They should be able to answer your questions.
