### ISSUE TITLE
Permission file not created 

### ISSUE THREAD

**Issue by docteurzoidberg** [ForgeEssentials/ForgeEssentials#2460]
I did not manage to get the singlejson permission file created by the mod, i had to use SQL/h2 file for permissions to work

FE confirm permissions are added without throwing errror and when you list permissions they are empty!

build: .66

**Comment by docteurzoidberg** [comment]
developer advice here: test for errors before logging success in console may help people figuring why nothing works ****

**Comment by Zethalion** [comment]
Closed for not following our rules on reporting bugs. See https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
You may re-open this issue when you acknowledge.
