### ISSUE TITLE
my game is crash when I put a block

### ISSUE THREAD

**Issue by ssnowboy** [ForgeEssentials/ForgeEssentials#2467]
when I put a block my game crach and put me this

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCore (MovingWorld-Mod-1.12.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 10/5/19 7:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.forgeessentials.api.permissions.ServerZone.getAdditionalPlayerGroups(ServerZone.java:327)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:404)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:409)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.getPlayerGroups(ZonedPermissionHelper.java:904)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.hasPermission(ZonedPermissionHelper.java:783)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:95)
	at net.minecraft.entity.player.EntityPlayer.func_189808_dh(EntityPlayer.java:2765)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.forgeessentials.api.permissions.ServerZone.getAdditionalPlayerGroups(ServerZone.java:327)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:404)
	at com.forgeessentials.api.permissions.ServerZone.getPlayerGroups(ServerZone.java:409)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.getPlayerGroups(ZonedPermissionHelper.java:904)
	at com.forgeessentials.permissions.core.ZonedPermissionHelper.hasPermission(ZonedPermissionHelper.java:783)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:95)
	at net.minecraft.entity.player.EntityPlayer.func_189808_dh(EntityPlayer.java:2765)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['snowboy'/4389, l='MpServer', x=96.53, y=62.00, z=-449.20]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-97,14,-478), Chunk: (at 15,0,2 in -7,-30; contains blocks -112,0,-480 to -97,255,-465), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 14797247 game time, 2961 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 124 total; [EntityPlayerSP['snowboy'/4389, l='MpServer', x=96.53, y=62.00, z=-449.20], EntitySpider['Araignée'/4610, l='MpServer', x=131.50, y=61.00, z=-373.50], EntityChicken['Poule'/263, l='MpServer', x=19.91, y=64.00, z=-463.22], EntityZombie['Zombie'/4879, l='MpServer', x=174.50, y=26.00, z=-457.50], EntityZombie['Zombie'/4880, l='MpServer', x=174.50, y=26.00, z=-454.50], EntityCreeper['Creeper'/4629, l='MpServer', x=175.48, y=43.00, z=-461.84], EntityChicken['Poule'/4631, l='MpServer', x=159.87, y=64.00, z=-528.31], EntityChicken['Poule'/4637, l='MpServer', x=172.15, y=64.00, z=-528.12], EntityHorse['Cheval'/4638, l='MpServer', x=160.02, y=64.00, z=-529.91], EntityBat['Chauve-souris'/4639, l='MpServer', x=157.51, y=24.05, z=-505.41], EntityHorse['Cheval'/4640, l='MpServer', x=149.00, y=65.00, z=-516.89], EntitySkeleton['Squelette'/4649, l='MpServer', x=148.69, y=64.00, z=-403.49], EntityPig['Cochon'/4650, l='MpServer', x=156.24, y=64.00, z=-420.50], EntityCow['Vache'/4652, l='MpServer', x=170.31, y=69.00, z=-392.17], EntityItemFrame['entity.ItemFrame.name'/4419, l='MpServer', x=35.03, y=66.50, z=-318.50], EntityItemFrame['entity.ItemFrame.name'/4420, l='MpServer', x=37.97, y=66.50, z=-318.50], EntityItemFrame['entity.ItemFrame.name'/4421, l='MpServer', x=37.97, y=66.50, z=-309.50], EntityItemFrame['entity.ItemFrame.name'/4422, l='MpServer', x=35.03, y=66.50, z=-309.50], EntityItemFrame['entity.ItemFrame.name'/4424, l='MpServer', x=44.97, y=78.50, z=-322.50], EntityItemFrame['entity.ItemFrame.name'/4425, l='MpServer', x=45.50, y=78.50, z=-323.03], EntityItemFrame['entity.ItemFrame.name'/4426, l='MpServer', x=46.03, y=78.50, z=-322.50], EntityItemFrame['entity.ItemFrame.name'/4427, l='MpServer', x=35.03, y=72.50, z=-329.50], EntityItemFrame['entity.ItemFrame.name'/4428, l='MpServer', x=37.97, y=72.50, z=-329.50], EntityZombie['Zombie'/4429, l='MpServer', x=45.70, y=23.00, z=-425.36], EntityWitch['Sorcière'/4430, l='MpServer', x=45.49, y=24.00, z=-428.34], EntityGate['Gate'/4431, l='MpServer', x=60.50, y=64.00, z=-457.50], EntitySkeleton['Squelette'/4432, l='MpServer', x=37.50, y=26.00, z=-398.50], EntitySquid['Poulpe'/4433, l='MpServer', x=45.97, y=62.26, z=-390.69], EntitySquid['Poulpe'/4434, l='MpServer', x=45.60, y=61.79, z=-391.60], EntitySquid['Poulpe'/4435, l='MpServer', x=37.90, y=60.78, z=-394.47], EntityZombie['Zombie'/4948, l='MpServer', x=16.50, y=21.00, z=-440.50], EntityBat['Chauve-souris'/4437, l='MpServer', x=36.69, y=34.10, z=-412.79], EntitySkeleton['Squelette'/3414, l='MpServer', x=24.28, y=14.00, z=-390.49], EntityWolf['Loup'/4438, l='MpServer', x=70.64, y=73.00, z=-509.60], EntityChicken['Poule'/4439, l='MpServer', x=80.18, y=72.00, z=-513.64], EntityPig['Cochon'/4440, l='MpServer', x=75.38, y=70.54, z=-528.68], EntityChicken['Poule'/4441, l='MpServer', x=73.08, y=72.00, z=-523.14], EntityPig['Cochon'/4442, l='MpServer', x=86.20, y=72.00, z=-519.32], EntityChicken['Poule'/4443, l='MpServer', x=53.80, y=69.00, z=-497.80], EntityChicken['Poule'/4444, l='MpServer', x=54.68, y=69.00, z=-496.31], EntityChicken['Poule'/4445, l='MpServer', x=60.78, y=77.00, z=-500.51], EntityWolf['Loup'/4446, l='MpServer', x=54.09, y=69.00, z=-496.60], EntitySquid['Poulpe'/4447, l='MpServer', x=43.40, y=61.43, z=-483.71], EntityZombie['Zombie'/4448, l='MpServer', x=75.85, y=37.00, z=-528.12], EntityCreeper['Creeper'/4450, l='MpServer', x=63.84, y=38.00, z=-526.49], EntitySquid['Poulpe'/4453, l='MpServer', x=42.60, y=57.42, z=-499.60], EntitySquid['Poulpe'/4454, l='MpServer', x=38.79, y=59.53, z=-501.60], EntityItem['item.item.egg'/4457, l='MpServer', x=79.50, y=72.00, z=-485.00], EntityChicken['Poule'/4458, l='MpServer', x=66.87, y=75.00, z=-494.55], EntityItem['item.item.egg'/4459, l='MpServer', x=68.76, y=70.00, z=-490.11], EntityChicken['Poule'/4460, l='MpServer', x=65.81, y=78.00, z=-495.58], EntityItem['item.item.egg'/4461, l='MpServer', x=61.44, y=64.00, z=-464.39], EntityPig['Cochon'/4462, l='MpServer', x=76.44, y=73.00, z=-511.01], EntityCow['Vache'/4463, l='MpServer', x=77.29, y=73.00, z=-509.78], EntityPig['Cochon'/4464, l='MpServer', x=63.20, y=72.00, z=-508.72], EntityChicken['Poule'/4465, l='MpServer', x=77.86, y=73.00, z=-504.60], EntityItem['item.item.egg'/4466, l='MpServer', x=66.21, y=75.00, z=-504.99], EntityChicken['Poule'/4467, l='MpServer', x=71.08, y=77.00, z=-494.25], EntityItem['item.item.egg'/4468, l='MpServer', x=68.04, y=76.00, z=-503.75], EntitySquid['Poulpe'/4469, l='MpServer', x=53.56, y=59.98, z=-491.60], EntityChicken['Poule'/4470, l='MpServer', x=45.52, y=64.00, z=-498.24], EntityChicken['Poule'/4471, l='MpServer', x=48.80, y=64.00, z=-495.80], EntityBat['Chauve-souris'/4727, l='MpServer', x=17.26, y=24.57, z=-384.43], EntityCow['Vache'/4472, l='MpServer', x=57.34, y=71.00, z=-492.55], EntityItem['item.item.egg'/4473, l='MpServer', x=48.88, y=64.00, z=-495.21], EntityChicken['Poule'/4474, l='MpServer', x=59.50, y=64.00, z=-477.81], EntityChicken['Poule'/4475, l='MpServer', x=51.12, y=64.00, z=-489.52], EntityChicken['Poule'/4476, l='MpServer', x=57.51, y=64.00, z=-490.22], EntityChicken['Poule'/4477, l='MpServer', x=65.51, y=64.00, z=-485.78], EntityCreeper['Creeper'/4491, l='MpServer', x=88.50, y=22.00, z=-413.50], EntityCreeper['Creeper'/4492, l='MpServer', x=62.39, y=67.00, z=-381.30], EntityZombie['Zombie'/4495, l='MpServer', x=92.80, y=20.00, z=-416.50], EntityCreeper['Creeper'/4496, l='MpServer', x=63.30, y=65.00, z=-396.70], EntityItemFrame['entity.ItemFrame.name'/4497, l='MpServer', x=50.50, y=78.50, z=-323.03], EntityItemFrame['entity.ItemFrame.name'/4498, l='MpServer', x=49.97, y=78.50, z=-322.50], EntityItemFrame['entity.ItemFrame.name'/4499, l='MpServer', x=51.03, y=78.50, z=-322.50], EntityCreeper['Creeper'/4500, l='MpServer', x=110.47, y=27.00, z=-387.78], EntityCreeper['Creeper'/4501, l='MpServer', x=105.50, y=26.00, z=-390.50], EntitySpider['Araignée'/4503, l='MpServer', x=100.50, y=16.00, z=-403.50], EntityChicken['Poule'/4504, l='MpServer', x=66.61, y=64.00, z=-449.83], EntityChicken['Poule'/4506, l='MpServer', x=89.09, y=74.00, z=-488.87], EntityItem['item.item.egg'/4507, l='MpServer', x=75.10, y=64.00, z=-464.59], EntitySkeleton['Squelette'/4763, l='MpServer', x=95.50, y=19.00, z=-499.50], EntityChicken['Poule'/4508, l='MpServer', x=70.74, y=64.00, z=-469.60], EntitySkeleton['Squelette'/4764, l='MpServer', x=93.50, y=19.00, z=-502.50], EntityZombie['Zombie'/1437, l='MpServer', x=27.50, y=26.00, z=-400.50], EntityCreeper['Creeper'/4766, l='MpServer', x=26.80, y=31.00, z=-391.48], EntitySkeleton['Squelette'/4767, l='MpServer', x=135.50, y=35.00, z=-495.50], EntitySkeleton['Squelette'/3490, l='MpServer', x=27.50, y=31.00, z=-427.50], EntityCow['Vache'/4520, l='MpServer', x=74.87, y=64.00, z=-445.13], EntityItem['item.item.egg'/4779, l='MpServer', x=64.02, y=78.00, z=-496.15], EntityPig['Cochon'/4525, l='MpServer', x=123.45, y=72.00, z=-530.55], EntityCreeper['Creeper'/4530, l='MpServer', x=101.23, y=35.00, z=-524.43], EntityCreeper['Creeper'/4531, l='MpServer', x=100.70, y=35.00, z=-522.41], EntityHorse['Cheval'/4532, l='MpServer', x=102.01, y=72.00, z=-521.91], EntityCow['Vache'/4533, l='MpServer', x=92.70, y=72.00, z=-523.43], EntityCreeper['Creeper'/4534, l='MpServer', x=81.80, y=44.00, z=-497.41], EntityItem['item.item.egg'/4536, l='MpServer', x=84.62, y=72.00, z=-508.30], EntityCow['Vache'/4540, l='MpServer', x=90.55, y=70.00, z=-515.55], EntityCow['Vache'/4541, l='MpServer', x=98.49, y=72.00, z=-526.18], EntityChicken['Poule'/4542, l='MpServer', x=92.43, y=73.00, z=-513.87], EntityChicken['Poule'/4543, l='MpServer', x=82.86, y=72.00, z=-522.32], EntityChicken['Poule'/4544, l='MpServer', x=86.81, y=71.00, z=-531.15], EntityPig['Cochon'/4545, l='MpServer', x=83.48, y=72.00, z=-519.29], EntityCow['Vache'/4546, l='MpServer', x=95.23, y=72.00, z=-526.55], EntityChicken['Poule'/4552, l='MpServer', x=97.60, y=72.00, z=-526.07], EntityCreeper['Creeper'/4563, l='MpServer', x=123.20, y=60.00, z=-391.56], EntitySkeleton['Squelette'/4564, l='MpServer', x=108.50, y=61.00, z=-384.71], EntityZombie['Zombie'/4565, l='MpServer', x=112.47, y=60.00, z=-387.12], EntityCreeper['Creeper'/4566, l='MpServer', x=106.50, y=25.00, z=-377.50], EntitySkeleton['Squelette'/4567, l='MpServer', x=102.26, y=23.00, z=-376.46], EntityZombie['Zombie'/4580, l='MpServer', x=138.62, y=23.00, z=-521.94], EntityBat['Chauve-souris'/4581, l='MpServer', x=130.73, y=40.08, z=-519.61], EntityCreeper['Creeper'/4587, l='MpServer', x=129.50, y=49.00, z=-528.50], EntityZombie['Zombie'/4590, l='MpServer', x=121.70, y=44.00, z=-519.52], EntityZombie['Zombie'/4591, l='MpServer', x=125.50, y=61.00, z=-514.50], EntityPig['Cochon'/4592, l='MpServer', x=113.66, y=64.00, z=-478.50], EntityBat['Chauve-souris'/4082, l='MpServer', x=34.92, y=16.91, z=-397.60], EntityCreeper['Creeper'/4594, l='MpServer', x=123.43, y=61.00, z=-373.80], EntityCreeper['Creeper'/4595, l='MpServer', x=125.50, y=61.00, z=-373.50], EntityBat['Chauve-souris'/4596, l='MpServer', x=129.22, y=63.13, z=-370.44], EntityCow['Vache'/4597, l='MpServer', x=132.43, y=68.00, z=-403.22], EntityCow['Vache'/4598, l='MpServer', x=140.16, y=69.00, z=-402.48], item.vehicleSpawner.9::248 @ -15.89, 77.00, -385.32  -- y:1.70 p:0.00 -- m: 0.00, 0.00, 0.00]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 419099440 bytes (399 MB) / 1421869056 bytes (1356 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 5 total; -XX:+UseG1GC -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1 -Xmx6144M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version          | Source                                        | Signature                                |
	|:------ |:-------------------------------------------- |:---------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2           | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                                          | 9.42             | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99        | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2838     | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                  | minecraft.jar                                 | None                                     |
	| LCHIJA | ambientsounds                                | 3.0              | AmbientSounds_v3.0.9_mc1.12.2.jar             | None                                     |
	| LCHIJA | codechickenlib                               | 3.2.1.351        | CodeChickenLib-1.12.2-3.2.1.351-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare                               | 1.12.2-2.7.0.772 | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | ancientwarfarestructure                      | 1.12.2-2.7.0.772 | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | ancientwarfarevehicle                        | 1.12.2-2.7.0.772 | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | ancientwarfarenpc                            | 1.12.2-2.7.0.772 | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | ancientwarfareautomation                     | 1.12.2-2.7.0.772 | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCHIJA | customnpcs                                   | 1.12             | CustomNPCs_1.12.230Jan1.jar                   | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.342       | MovingWorld-Mod-1.12.jar                      | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@    | davincisvessels-1.12-6.337-full.jar           | None                                     |
	| LCHIJA | forgeessentials                              | 12.3             | forgeessentials-1.12.2-12.3.60-server.jar     | None                                     |
	| LCHIJA | moreplayermodels                             | 1.12.2           | MorePlayerModels_1.12.2-29Sep19.jar           | None                                     |
	| LCHIJA | rustic                                       | 1.1.1            | rustic-1.1.1.jar                              | None                                     |

	Loaded coremods (and transformers): 
MovingWorldCore (MovingWorld-Mod-1.12.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13543 Compatibility Profile Context 25.20.15002.58' Renderer: 'AMD Radeon (TM) R9 380 Series'
	ForgeEssentials: Running ForgeEssentials 12.3.60 (db2fdd8). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WorldBorder, factions, mapper
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R9 380 Series GL version 4.6.13543 Compatibility Profile Context 25.20.15002.58, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, programer_art
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor

**Comment by Zethalion** [comment]
Forge Essentials is only for use on servers. It might work on a client but is not supported.
