### ISSUE TITLE
[1.12.2] [BUG] Mod not loading at all

### ISSUE THREAD

**Issue by Mokrator** [ForgeEssentials/ForgeEssentials#2468]
I have installed a MC Server with forge-1.12.2-14.23.5.2847-universal
any other mod is loaded briefly, the server seem to work normaly.

If i add the mod forgeessentials-1.12.2-12.3.60-server.jar (or .56) and start the server, just nothing happens according to forge essentials.

I expected to be able to use the commands like /mv or /p in the serverconsole but they are unknown.

I am using a Win10 Computer as a Server with Java x64 build 1.8.0_191-b12

I assume i am doing totaly wrong but YTVideos how to install it didn't fit to the version i use and the Wiki https://github.com/ForgeEssentials/ForgeEssentials/wiki/Getting-started refers to the Minecraftversion 1.7
(I assume the ForgeEssentials is programmed very good but the documentation lags on how to start or check if it is installed properly)

So please Help and don't flame me that i am stupid just because i don't find the right hint.

**Comment by Zethalion** [comment]
Closed for not following our rules on reporting bugs. See https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
You may re-open this issue when you acknowledge.
The contents of the wiki applies to FE from 1.7.10 to 1.12.2

**Comment by Zethalion** [comment]
Actually, you may not reopen this issue as you did not even paid attention to the BUG REPORT TEMPLATE provided. You WILL follow the directions by the template in order for your report to be accepted.
