### ISSUE TITLE
[1.12.2] [BUG] Trying to use with RLcraft

### ISSUE THREAD

**Issue by xRyuukii** [ForgeEssentials/ForgeEssentials#2470]
Problem:
- Running RLcraft on gtxgaming using forge 1.12.2
- All other mods in RLcraft have access, However ForgeEssentials gives "unknown command" when trying to use simple commands such as /home here

Mod has been added to /mods/ Folder inside the server.

**Comment by Zethalion** [comment]
Closed for not following our rules on reporting bugs. See https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs
You WILL follow the directions by the BUG REPORT template in order for your report to be accepted.
