### ISSUE TITLE
[1.12.2] [FEATURE]

### ISSUE THREAD

**Issue by theoparis** [ForgeEssentials/ForgeEssentials#2471]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I'd like the forgessentials configuration/data 
To be stored outside of the world files for servers. I've had to delete the world on my server and I lost all of my permissions. My idea is if only for servers, you store the data in a folder in the server folder.
**Describe alternatives you've considered**

**Additional context**

**Comment by Zethalion** [comment]
The decision to store the permissions inside the world folder was made because they make part of that world. As they can include zones based on landscape, and therefor inherently linked to that world, it is unwanted to store permissions outside of the world. We will not change this.

**Comment by Zethalion** [comment]
Side note. You can store the permissions in a MySQL server as an option. This is made available a long time ago. That enables you to store the permissions for multiple servers in a unison way.
