### ISSUE TITLE
[1.12.2] Plots disappearing on server restart

### ISSUE THREAD

**Issue by ShinQdan** [ForgeEssentials/ForgeEssentials#2473]
- I'm using forgeessentials-1.12.2-12.3.70
- #2370 shows some similarities
- [modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/3921974/modlist.txt)
- [latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/3921975/latest.log)
- [debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/3921976/debug.log)
- [debug-2.log.gz (debug before restart)](https://github.com/ForgeEssentials/ForgeEssentials/files/3921980/debug-2.log.gz)
- [2019-12-04-5.log.gz (log before restart)](https://github.com/ForgeEssentials/ForgeEssentials/files/3921981/2019-12-04-5.log.gz)
- [debug-1.log.gz (debug after restart)](https://github.com/ForgeEssentials/ForgeEssentials/files/3921982/debug-1.log.gz)
- [2019-12-04-6.log.gz (log after restart)](https://github.com/ForgeEssentials/ForgeEssentials/files/3921983/2019-12-04-6.log.gz)
- [permissions.zip (permissions file after restart)](https://github.com/ForgeEssentials/ForgeEssentials/files/3922013/permissions.zip)

**Describe the bug**
I'm experiencing a problem with plots - when server is restarted it seems that the only plot that is loaded is the one that was created last. At the same time zones are loading correctly. These plots are still existing inside permissions.json but when entering the area where the plot should be there is no entry message and trying to use /plot commands gives an error message "There is no plot at this position.". They are also not appearing on the plots list when using /plot list all.
What is more when trying to claim new plot on the exact same area where the disappeared one was, this new one is behaving strangely - it seems to cover whole world except other plots and zones (this also occurs randomly for newly claimed plots for no known reason). Claiming new plot in an area where there was no plot before works fine. I also noticed same strange behavior when creating new plot on the same area where there was deleted one unless the /p save command was executed before reclaiming the area.
Also when in debug mode while entering the area where the plot was before restart message appears suggesting that there is still zone over there (screenshot1).
Temporary solution to this issue is to delete all the plots in permissions.json, restart and reclaim them again. But it's annoying to reclaim your plots every time the server restarts.

**To Reproduce**
1. Start server
2. Claims some plots
3. Restart server
4. Plots disappeared

**Expected behavior**
Plots still being where they were before restart.

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/52013808/70145456-6a2af500-16a0-11ea-8e24-1f8673e8bb95.png)

**Comment by spacebuilder2020** [comment]
Plots are currently not supported and are known to have issues.
It is a goal of ours to replace plots and factions with something better but that day has not yet come yet.

It is recommended that you use a different solution for claiming like FTBU.

(Make sure to read all pins on our discord about setting up FTBU with FE)
