### ISSUE TITLE
Unknown Command (Anything that starts with "/p")

### ISSUE THREAD

**Issue by RZhu04** [ForgeEssentials/ForgeEssentials#2475]
as the title says, I cant run any commands that start with /p. It says "unknown command. Try /help for a list of commands" I am oped on the server so I dont know whats wrong. Without these commands, I cant even set up permissions or groups for my server. Please help

**Comment by Codingale** [comment]
Try updating both Forge Essentials and if you have FTB Utilities, that too.

If you have FTB Utilities do the following:

In case you have FTB Utilities (FTBU) and FE loaded on your server, understand FTBU usually is prioritized in registering as the Forge permission manager. This will disable most of FE's functionality. FE however, is capable to manage all the permissions of FTBU but requires some configuration on your side. Change the following in ./cfg/ftbutilities.cfg:
- Disable ranks (B:enabled=false)
- Disable AFK
- Disable  Commands (
`B:back=false`
`B:fly=false`
`B:heal=false`
`B:home=false`
`B:mute=false`
`B:nick=false`
`B:ranks=false`
`B:tpa=false`
`B:warp=false`
)

From Zethalion in discord, other than that. I'm not sure, does the server say anything else in the log?

**Comment by spacebuilder2020** [comment]
This was fixed in build 72

As always, it is recommended to follow the instructions [here](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs) before making a bug report.
