### ISSUE TITLE
[1.12.2]older mixin subsystem version cause incompatible  with more_planets mod

### ISSUE THREAD

**Issue by sorasoras** [ForgeEssentials/ForgeEssentials#2481]
Initial Steps

- [x]  I have updated to the latest build from Jenkins before reporting a bug

- [x] I have checked, if the bug was not already reported by using the search.
- [x] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log

- [ ]  Also, attached are the client logs (if applicable)
The bug
Mixin config mixins.more_planets.json requires mixin subsystem version 0.7.11 but 0.7.10 was found. 
To Reproduce Steps to reproduce the behavior:
when I put More-Planets-1.12.2-2.1.10-GC238 with forge essentials together, the server will not boot at all. If I remove forge-essential, the server boot-up normally.

Expected behavior
The server should boot normally

Desktop (please complete the following information):

OS: [Windows 10]
Version [forge-1.12.2-14.23.5.2847]
----------------------------------------------------------------------------------------
it looks to me  that forgeessentials is incompatible with more-planets mod. more planets require mixin 0.7.11  but forge essentials is using 0.7.10.
[debuglog.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4046527/debuglog.txt)
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4046542/modlist.txt)

**Comment by spacebuilder2020** [comment]
Please update your issue to follow the [bug report template](https://github.com/ForgeEssentials/ForgeEssentials/blob/1.12.2/develop/.github/ISSUE_TEMPLATE/bug_report.md) and the bug report [rules](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs)

**Comment by sorasoras** [comment]
> 
> 
> Please update your issue to follow the [bug report template](https://github.com/ForgeEssentials/ForgeEssentials/blob/1.12.2/develop/.github/ISSUE_TEMPLATE/bug_report.md) and the bug report [rules](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs)

I already modified the bug report according to the template.

**Comment by spacebuilder2020** [comment]
Thanks, I will work on updating mixin in the near future.

**Comment by spacebuilder2020** [comment]
Looks like both mods are embedding Mixin in the jar files.  Try renaming the more planet jar to  `_More-Planets-1.12.2-2.1.10-GC238.jar`.  This should force more planets to load first and thus use the mixin system provided by more planets.

**Comment by sorasoras** [comment]
> Looks like both mods are embedding Mixin in the jar files. Try renaming the more planet jar to `_More-Planets-1.12.2-2.1.10-GC238.jar`. This should force more planets to load first and thus use the mixin system provided by more planets.

It's a good workaround, thanks.

**Comment by spacebuilder2020** [comment]
Closed as FE is no longer on Mixin 0.7.10
