### ISSUE TITLE
no commands work unless op? theres nothing on youtube or the wiki on how to fix pls help

### ISSUE THREAD

**Issue by Yrahcxz** [ForgeEssentials/ForgeEssentials#2482]

**Comment by spacebuilder2020** [comment]
Please visit our [discord](https://discord.gg/FNRQjmr) and we will assist you.

Also, if reporting bugs, please make sure to follow the rules here: https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs and make sure to fill out the bug template.
