### ISSUE TITLE
[1.12.2] [BUG] Once you tempban a player you cannot un-tempban them.

### ISSUE THREAD

**Issue by AMDBartek** [ForgeEssentials/ForgeEssentials#2485]
**Initial Steps**
- [x] I have updated to the latest build from Jenkins before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [ ] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log (No error in logs but modlist is attached)
- [ ] Also, attached are the client logs (if applicable) (No error in client logs)

**Describe the bug**

Once you use the tempban command to ban a player there is no command to un-tempban the player

**To Reproduce**
1. Use the tempban command to ban  a player
2. Try to use pardon to un-tempban the player
3. It returns "Could not unban player [USERNAME]"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [79.0.3945.117]

**Additional context**
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4050806/modlist.txt)

**Comment by spacebuilder2020** [comment]
This is not a bug, that is a feature.  Please to add a feature request for an pardontempban command.

Also, you can pardon temp bans simply by running tempban with a value of 0
