### ISSUE TITLE
[1.12.2] [BUG] The requestpayment command does not work

### ISSUE THREAD

**Issue by AMDBartek** [ForgeEssentials/ForgeEssentials#2486]
**Initial Steps**
- [x] I have updated to the latest build from Jenkins before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [ ] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log (No error in log, but modlist is attached)
- [ ] Also, attached are the client logs (if applicable) (No error in client log)

**Describe the bug**

I have read on the wiki that there is a requestpayment command, however when I attempt to use the command it returns "Unknown command. Try /help for a list of commands"

**To Reproduce**
1. Use the requestpayment command
2.  The server returns "Unknown command. Try /help for a list of commands"

**Expected behavior**

The command requests a payment from a player

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [79.0.3945.117]

**Additional context**
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4050815/modlist.txt)

**Comment by spacebuilder2020** [comment]
Request Payment is currently not registered as a command in forge essentials.

**Comment by AMDBartek** [comment]
Ok, thank you for the response.

**Comment by spacebuilder2020** [comment]
This has been added to 1.12.  It seems the command was finished but never registered.
