### ISSUE TITLE
[1.12.2] [FEATURE] Localized Chat is my mod, need help.

### ISSUE THREAD

**Issue by kreezxil** [ForgeEssentials/ForgeEssentials#2490]
What do I need to do to Localized Chat to make it compatible with your chat mod features.

What my mod does is limit the range a player can talk on a server to other players. Only players within range of the player talking can hear them. Inter-dimensional talking costs hunger points. Operators if configured ignore these ranges.

That's all my mod does. However, when coupled with any other mod that supports colorized nicknames, titles, etc in chat, it gets in the way of those and removes all the special frills and thrills these mods add.

This includes your mod.

Can you tell me what I need to do at the minimum to make my mod behave nicely with your mod?

I put this as a feature request because I don't actually see it as a bug.

**Comment by kreezxil** [comment]
For reference: https://www.curseforge.com/minecraft/mc-mods/localized-chat

**Comment by XVOMercy** [comment]
Hello! I'm a user who uses Localized Chat, and I also use forge essentials. Please allow compatibility between the two mods, so my users can have nicknames and also chat with a radius! Thank you!

**Comment by spacebuilder2020** [comment]
Thanks, I will look into determining the best way to provide compatibility.

**Comment by spacebuilder2020** [comment]
@kreezxil
Try lowering your event priority so you event happens after FE's event. FE's event is set to LOW.

See [ModuleChat.java (Line 205)](https://github.com/ForgeEssentials/ForgeEssentials/blob/1.12.2/develop/src/main/java/com/forgeessentials/chat/ModuleChat.java#L205)

Also, note, FE's chat module will only cancel the chat event in a few cases, (a) if a message is sent directly to a user (with permission `fe.chat.range`), (b) A player does not have permission to write in chat, (c) A player is muted or (d) A player uses /pm.  All other cases use event.setComponents to update the event.

**Comment by spacebuilder2020** [comment]
Lastly, make sure that if you are sending a message directly to a user to cancel your event so the user does not receive two messages.

**Comment by kreezxil** [comment]
Thank you for this information. :)

**Comment by kreezxil** [comment]
Just noticed your permission node. FE chat supports ranged chat? which is what my mod provides. is that correct?

**Comment by spacebuilder2020** [comment]
Yea, it does.  That said, It sounds like your mod adds some extra stuff to make a more thematic ranged chat.    
As long as the node is not applied, it the FE ranged chat should not interfere with your mods ranged chat.

**Comment by kreezxil** [comment]
thanks for all the fish. :)
