### ISSUE TITLE
[1.12.2] [BUG] The /perm user [USERNAME] perms command does not work if the player is offline

### ISSUE THREAD

**Issue by AMDBartek** [ForgeEssentials/ForgeEssentials#2491]
**Initial Steps**
- [x] I have updated to the latest build from Jenkins before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [x] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [ ] Also, attached are the client logs (if applicable)

**Describe the bug**
The /perm user [USERNAME] perms command does not work when the player is offline

**To Reproduce**
1. Use /perm user [USERNAME] perms. While the player is offline
2. Check error in the server log

**Expected behavior**
The perm command to list all of the permissions for that player

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [79.0.3945.130]

**Additional context**
[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4109475/latest.log)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4109477/debug.log)
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4109484/modlist.txt)

**Comment by Zethalion** [comment]
FE only works on online users because of UUID translation of usernames. This cannot be resolved in FE and therefor be closed.
