### ISSUE TITLE
Blocks and items can be blocked on the server?

### ISSUE THREAD

**Issue by DeusCaper143** [ForgeEssentials/ForgeEssentials#2492]
I am new with this mod and it has taken me a bit to understand everything I am using this mod on an Rpg Server and I would like to block some things that I consider are not appropriate for the server my question is if there is any command or some way in which Can I completely deny or block that block or item?
Thank you very much for such a wonderful mod! and I wait for an answer

**Comment by spacebuilder2020** [comment]
See https://github.com/ForgeEssentials/ForgeEssentials/wiki/Permissions-tutorial and https://github.com/ForgeEssentials/ForgeEssentials/wiki/Guide-%23-Protection-(world-guard)

You can deny permission to access any block through FE's protection system.
