### ISSUE TITLE
[1.12.2] [BUG] Replacing worlds to import doesn't work

### ISSUE THREAD

**Issue by Matthysse** [ForgeEssentials/ForgeEssentials#2499]
**Initial Steps**
- Create new world using /mw create test
- Replace in world/FeMultiworld/test the content of the file from the world I want
- Restart server, and see that the world didn't changed.

**Describe the bug**
Import existing worlds from my computer doesn't work. The multiworld feature is for me really badly made. When doing the /mw list command it shows only the world created with ForgeEssentials, and not the others like the normal "world" world that is automatically generated by forge or other dimensions. So we can't teleport to them easily.
It's also easier to have a Mohist server and use the Multiverse2 plugin, the only problem is that it corrupts modded worlds IDs and change all blocks. That's why I wanted to use ForgeEssentials, as it is meant to use with mods, but it doesn't work as expected.
I tried like listed before to import a world by replacing the folder I created with /mw create test, but the world, after restart, is always the same.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by DarkWhiteParadox** [comment]
I am also having this issue, driving me crazy,

tried multiple different ways but whatever happens, when I restart the server ( even having completely deleted the "test" world and replaced it with the "imported" world) the world hasn't changed to the imported one and is still the one created using /mw create test.

Is there a different location that these files are being loaded from other than inside the world folder?

**Comment by Zethalion** [comment]
in `world/FEMultiworld` you'll need to replace `level.dat` with the one you created in SSP. That file is used to generate that dimension.
ps. `/mwtp surface` brings you to the normal overworld.

**Comment by DarkWhiteParadox** [comment]
I have done that and when I restart the server, and /mwtp test, the world hasn't changed to the imported one at all. Is it possible it's being backed up somewhere and loaded?

I just tested it now, 

in world/FEMultiworld/test I just replaced level.dat with the one I created in SSP (called "importworld")

restarted the server, performed /mwtp test and the world is not the imported one.

**Comment by Zethalion** [comment]
To be clear, the server must be offline. replacing the `level.dat` file while the server is running will replace the overwritten file with the one in memory of the server when restarting.

**Comment by DarkWhiteParadox** [comment]
Ayyyy this worked! Now my issue is that the imported worlds dynamic trees have been replaced with random blocks, is this an incompatibility or am I doing something wrong?

**Comment by Matthysse** [comment]
I had the same problem as you, and I solved it on Mohist (plugin+mods) but I think it works for forgeessentials too. You will need to download the mod JustEnoughIDs, it removes the ID limit of Minecraft in 1.12.2. Then your world will not corrupt the IDs which are in it.

**Comment by Zethalion** [comment]
I consider this issue to be resolved.
