### ISSUE TITLE
[1.12.2] [FEATURE] Make “/fly [NAME]” toggle another players flying

### ISSUE THREAD

**Issue by AMDBartek** [ForgeEssentials/ForgeEssentials#2500]
**Is your feature request related to a problem? Please describe.**
Yes, when players are flying there is no way to turn off their flying.

**Describe the solution you'd like**
The “/fly [NAME]” command to toggle the specified players flying.

**Describe alternatives you've considered**
Using the /doas command but that is inconvenient.

**Additional context**

**Comment by Zethalion** [comment]
You answered the solution to your issue already, even you consider it inconvenient, it will do the job.
