### ISSUE TITLE
[1.12.2] [BUG] Interacting with some tile entities causes the action of both interacting with the tile entity and the action of the item in your hand

### ISSUE THREAD

**Issue by Hakkinio** [ForgeEssentials/ForgeEssentials#2501]
**Initial Steps**
- [X] I have updated to the latest build from Jenkins before reporting a bug
- [X] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [X] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4288444/modlist.txt)
- [] Also, attached are the client logs (if applicable)

**Describe the bug**
Interacting with some tile entities causes the action of both interacting with the entity and the action of the usable item in your hand. With redstone you'll place the redstone near the crafting table/chest etc, with for example a dank/null it will place the block selected. For example with the P2P-tunnels you'll shift right-click to save a channel with a memory card, but the double-click will instantly clear the memory card, making it impossible to use P2P-tunnels. 

**To Reproduce**
1. In FTB Revelations with ForceEssentials installed, look at a crafting table with redstone or string in hand.
2. Click on the crafting table or chest and the redstone or string will be placed at the same time.
3. See error

**Expected behavior**
The expected behavior is to just open or interact with the entity. Use crafting table, not place redstone at the same time. Open chest, not set it on fire with the flint & steel. 

**Additional context**
FTB Revelation version 3.21 and latest version of FTB Essentials. The bug does not happen in a single-player world where FE isn't installed, so it is definitely FE that is the cause. This bug happened with the default FE and with additional tweaks to remove the problem, like disabling a lot of the modules we thought could cause it (basically everything but playerlogging and factions), it still occurs.

**Comment by Zethalion** [comment]
Linked to https://github.com/ForgeEssentials/ForgeEssentials/issues/2432
