### ISSUE TITLE
[1.12.2] [BUG] Major compat issue with dynamic trees

### ISSUE THREAD

**Issue by Sunconure11** [ForgeEssentials/ForgeEssentials#2502]
https://pastebin.com/XB03Ls4k

Players keep running into this on my server when near a specific tree. I believe this is happening since DT trees can spread over time via dropping seeds.

**Comment by Zethalion** [comment]
@Sunconure11 Please update to FE build 79 and verify. Also, if you keep getting this crash with build 79 as well, enable safemode in main.cfg

**Comment by Sunconure11** [comment]
Crash happens at random, and can usually be traced to one faulty plant. I'll apply this build tomorrow though.

**Comment by Sunconure11** [comment]
Do you have a link to this build?

**Comment by Zethalion** [comment]
https://ci.forgeessentials.com/job/FE-1.12.2/

**Comment by Sunconure11** [comment]
BTW, do you have builds with updated mixins?

**Comment by Sunconure11** [comment]
Most mods on 1.12 updated mixins to 0.8 so I can't use this on a server currently.

**Comment by Zethalion** [comment]
Still waiting on your testing with the most recent build from jenkins. Mixins are another subject.

**Comment by Sunconure11** [comment]
Unfortunately, due to the server using multiple mods with mixins, I cannot test further until mixins are updated in FE. I tried to run that build and just crashed instead. However, the issue has not resurfaced yet, even before this build was shown to me.

**Comment by Zethalion** [comment]
@Sunconure11 , is this still an issue with build 83?

**Comment by Sunconure11** [comment]
I think the issue is gone.
