### ISSUE TITLE
[1.12.2] [BUG] mobspawn deny not working

### ISSUE THREAD

**Issue by SlimefrogSocial** [ForgeEssentials/ForgeEssentials#2503]
I am trying to stop spawn for zombies skeletons and creepers natural, not forced. I want to still find these in dungeons and etc.
I have done these commands:
/p global deny fe.protection.mobspawn.natural.minecraft:zombie.*
says it takes effect but creatures still spawn
/p global zone _SERVER_ deny fe.protection.mobspawn.natural.minecraft:zombie.* 
says there is no zone server, but I hit tab to auto-fill so this is exactly the same as what the zone is
/p global deny fe.protection.mobspawn.natural.minecraft:zombie
removed the *, didnt do anything
and did same with skeletons and creepers, still not working, any ideas?

**Comment by traso56** [comment]
Hello there!, in the meantime while you get this sorted I just wanted to tell you that I achieved this using the custom spawner mod, and setting the can spawn flag in the config to false, that means mobs can't naturally spawn but you can still use eggs or spawners

**Comment by Zethalion** [comment]
Use this form https://github.com/ForgeEssentials/ForgeEssentials/issues/new?assignees=&labels=needs-verification%2C+potential+bug&template=bug_report.md&title=%5B1.12.2%5D+%5BBUG%5D

Make sure you fill out every part of the form. Either update this issue with the form or close this one and open a new one using the form.

**Comment by SlimefrogSocial** [comment]
> Hello there!, in the meantime while you get this sorted I just wanted to tell you that I achieved this using the custom spawner mod, and setting the can spawn flag in the config to false, that means mobs can't naturally spawn but you can still use eggs or spawners

Can you send a link to this mod? I searched a little and can't find it.

**Comment by traso56** [comment]
> 
> 
> > Hello there!, in the meantime while you get this sorted I just wanted to tell you that I achieved this using the custom spawner mod, and setting the can spawn flag in the config to false, that means mobs can't naturally spawn but you can still use eggs or spawners
> 
> Can you send a link to this mod? I searched a little and can't find it.

it's this one https://www.curseforge.com/minecraft/mc-mods/custom-mob-spawner

**Comment by SlimefrogSocial** [comment]
> > > Hello there!, in the meantime while you get this sorted I just wanted to tell you that I achieved this using the custom spawner mod, and setting the can spawn flag in the config to false, that means mobs can't naturally spawn but you can still use eggs or spawners
> > 
> > 
> > Can you send a link to this mod? I searched a little and can't find it.
> 
> it's this one https://www.curseforge.com/minecraft/mc-mods/custom-mob-spawner

Thanks! I installed it, but it disables mob spawners as well, which i would like to still have enabled so i'm going to keep this installed temporarily and make a new issue with the forum that Zethalion sent. Thank you!
