### ISSUE TITLE
[1.12.2] [BUG] mobspawn not working

### ISSUE THREAD

**Issue by SlimefrogSocial** [ForgeEssentials/ForgeEssentials#2505]
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4345143/modlist.txt)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4345146/debug.log)
[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4345147/latest.log)

I disabled /p global deny fe.protection.mobspawn.natural.minecraft:zombie.* and same for creeper and skeleton and they are still spawning naturally.
I don't know how to reproduce this, i guess run this command in a server will all my other mods in and then it may do that?

**Comment by SlimefrogSocial** [comment]
Hey just commenting to follow up, I assume the coronavirus has halted a lot and may be the cause of delay

**Comment by Zethalion** [comment]
Drop the `:` in your node. use tab-complete to fill out the command. Don't assume you know how to type it.
