### ISSUE TITLE
[1.12.2] [BUG] Server crash with Corail Tombstone mod and Forge Essentials

### ISSUE THREAD

**Issue by ferchux** [ForgeEssentials/ForgeEssentials#2506]
**Describe the bug**
Server crash in the start:

// I just don't know what went wrong :(

Time: 3/23/20 11:42 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Corail Tombstone (tombstone)
Caused by: java.lang.RuntimeException: Corail Tombstone Exception : you loaded an incompatible grave mod : ForgeEssentials
	at ovh.corail.tombstone.ModTombstone.onServerStarted(ModTombstone.java:102)

**To Reproduce**
mod ForgeEssentials and CorailTombstone installed

**Comment by jsaneu** [comment]
It's a Tombstone problem.  Tombstone checks if ForgeEssentials is installed and throws an  exception

**Comment by ferchux** [comment]
Thank you for your answer, i cheched the config of the corail tombstone mod and i cant find the check to diasable it

**Comment by spacebuilder2020** [comment]
FE afterlife does not play well with other grave mods.  It is recommended to disable afterlife if you are using another grave mod.  That said, please make a bug report on the tombstone mod as it should not force a crash if FE is installed since you can disable Forge Essentials afterlife.

**Comment by alexlarraga1** [comment]
You only disable afterlife module in main.cfg

**Comment by ghost** [comment]
Disabling the afterlife module won't be enough, because now my mod rejects forge essentials until it's compatible about the drop event (all explainations are on my issue).
Thinking that players can change a config easily and having this option afterlife enabled by default is not really an ideal way to be compatible, i'll just mention this recent post on my page about how one user tried to change a config as [an example](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone?comment=851)

**Comment by kerber027** [comment]
hello, I was experiencing the same error that you comment so I had to remove the mod from my servers. I read the previous comments and they don't make it clear to me what if I disable afterlife module in main.cfg the Tombstone mod works again. Please someone who has already done it and it works that you can confirm me. I need to apply forgeEssentials on my server. thanks

**Comment by jnr432** [comment]
I disable the module afterlife and it still doesn't work, i need help

**Comment by spacebuilder2020** [comment]
Blame @Corail31.  I gave him an option to check if the mod is enabled before forcing a crash...  Something that is incredibly unprofessional.  I am willing to change afterlife to be disabled by default but I don't see a reason to make both components work together cause there is no need to have afterlife enabled when you have another grave mod.

**Comment by spacebuilder2020** [comment]
I am also considering adding an api to disable modules.  Currently, there exists a method to check if a module is enabled but it is not part of an api yet.

**Comment by ghost** [comment]
if you blame corail, it means you didn't read what i put in my issue or don't want to.
Perhaps a lack of understanding on your side why i do this...

**Comment by spacebuilder2020** [comment]
I can work on updating afterlife to have the drop events work with other grave mods, my question is what is the point when you can easily disable afterlife itself...  It is basically just another mod that is part of FE.   Also, my only problem is forcing a crash when FE is installed.

**Comment by samip5** [comment]
What is the current situation?

@Corail31 Do I really need to re-compile your mod so that it does not crash if ForgeEssentials is detected?

Gist of my crash log: https://gist.github.com/samip5/7c6046f85ade397e9ee9a2bfd87e995c

**Comment by ghost** [comment]
@samip5 i hope you're joking, tombstone is all right reserved.
If you're not able to update tombstone, don't be then a troll.

**Comment by Zethalion** [comment]
@samip5 I think @Corail31 means that you're using an outdated version of Tombstone. Update and verify. Builds 82 and 83 of FE are compatible. When done checking, can this issue be closed @ferchux ?

**Comment by Zethalion** [comment]
Fixed in the current builds of both mods.
