### ISSUE TITLE
[1.12.2] [BUG] Forge Essentials makes other pixelmon sidemods not load

### ISSUE THREAD

**Issue by gmassami** [ForgeEssentials/ForgeEssentials#2511]
I have installed the following mods:

Tournaments-1.12.2-2.6.2
PixelmonBroadcasts-1.12.2-0.4.1

They work properly, but when I install the forgeessentials-1.12.2-12.3.60-server.jar

both of tournaments and broadcasts stop working and the commands stop to get recognized in the console.

**Comment by Zethalion** [comment]
Update your report using this form https://github.com/ForgeEssentials/ForgeEssentials/issues/new?assignees=&labels=needs-verification%2C+potential+bug&template=bug_report.md&title=%5B1.12.2%5D+%5BBUG%5D

**Comment by Zethalion** [comment]
Thanks for reporting an issue. It's a shame I need to close it while not resolving your issue. That is you ignored the required template for reporting issues. Create a new issue using the provided template if you're still in need of help.
