### ISSUE TITLE
[1.12.2] [BUG]

### ISSUE THREAD

**Issue by gmassami** [ForgeEssentials/ForgeEssentials#2512]
**Initial Steps**
- [ ] I have updated to the latest build from Jenkins before reporting a bug
- [ ] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [ ] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [ ] Also, attached are the client logs (if applicable)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Zethalion** [comment]
I consider this a none issue @gmassami
