### ISSUE TITLE
[1.7.10] [BUG] FE 1.7.10 crashing server on startup

### ISSUE THREAD

**Issue by rubenavrebelo** [ForgeEssentials/ForgeEssentials#2513]
Hi! I've been trying to use the FE 1.7.10-1.4.6.1362 with the last version of Forge for 1.7.10 ( 1.7.10-10.13.4.1614) and the FE keeps crashing my server on startup.

I don't have the AR2 mod and I've looked at the log and issues at GitHub and I haven't found anything that could help.

Here's the crash log:

https://pastebin.com/WLyZVvpA

Thanks!

**Comment by Zethalion** [comment]
ForgeEssentials is not ment for usage on clients.

**Comment by rubenavrebelo** [comment]
I'm not loading it on client - the error is happening on the server and the .jar that it's on the mods folder is also the server version. "forgeessentials-1.7.10-1.4.6.1362-server.jar"

**Comment by Zethalion** [comment]
Looking deeper into the log I see this line:
`at com.wildmobsmod.entity.bases.EntityLargePredator.func_70636_d(EntityLargePredator.java:179)`
Nothing pointing at ForgeEssentials at all.

I suggest to drop this at wildmobsmod and reference to this issue.
