### ISSUE TITLE
[1.12.2] [PROBLEM] Permissions add

### ISSUE THREAD

**Issue by Vizis** [ForgeEssentials/ForgeEssentials#2515]
**Initial Steps**
forge-1.12.2-14.23.5.2847-universal
PixelExtras-1.12.2-2.5.7-universal
Pixelmon-1.12.2-7.2.2-universal
forgeessentials-1.12.2-12.3.79-server
**Describe the bug**
Can't asign permisions. on Fresh instalation i used comamnds:
/p user lnverno allow fe.perm.*
(*)/p user lnverno allow pixelextras.command.wiki
but /wiki didnt worked.
the i used 
/p user lnverno allow *
so it started to worked but it grant permission for all commands what i dont what.
also if in step (*) i tried to add /p user lnverno allow fe.teleport.warp    it also didnt worked.

i think i just doing sth wrong :S 

**Expected behavior**
working commands

**Desktop (please complete the following information):**
 - OS: server on debian, client on windows
but i check on personal server windows <. windows and same thing

**Comment by spacebuilder2020** [comment]
Sounds like a mod compatibility issue.  Permissions work perfectly fine on a pure forge install.

**Comment by JackCarterSmith** [comment]
I've a same issue with some others mods : only the primary perm node of the mod is handled by FE like /cofh.

**Comment by spacebuilder2020** [comment]
Closing cause dev's don't seem to want to work with us to be compatable.
