### ISSUE TITLE
[1.12.2] [BUG] Server crashes when i start

### ISSUE THREAD

**Issue by WithExtraDip** [ForgeEssentials/ForgeEssentials#2516]
**Initial Steps**
- [ Yes] I have updated to the latest build from Jenkins before reporting a bug
- [ Yes] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [ Yes] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [ Yes] Also, attached are the client logs (if applicable)

**Describe the bug**
When I start the server it crashes and I dont know why.

**To Reproduce**

**Expected behavior**
The Server should start with ForgeEssentials and the other mods on the Server.

**Desktop (please complete the following information):**
 - OS: server on debian, client on windows

**Additional context**
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4496085/modlist.txt)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4496086/debug.log)
[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4496088/latest.log)

**Comment by SLDDL** [comment]
same problem.
[crash-2020-04-24_01.59.59-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4525938/crash-2020-04-24_01.59.59-server.txt)
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4525942/modlist.txt)

**Comment by Zethalion** [comment]
For now use build 79 as builds 80 and 81 are buggy/broken. This also means you'll need to use an older version of OpenCubicChunks

**Comment by SLDDL** [comment]
Hello, sadly i can't downgrade OpenCubicChunk because i use the BTE modpack and Terra1:1 need the latest version of OpenCubicChunk to work properly.

**Comment by spacebuilder2020** [comment]
Builds 82 and 83 have been released that fix this crash
Build 82 is for mods that use Mixin 7.x where build 83 is for Mixin 8.1
