### ISSUE TITLE
[1.12.2] [Issue] Rollback specific date 

### ISSUE THREAD

**Issue by LLjo** [ForgeEssentials/ForgeEssentials#2517]
I can rollback with the command /rb start 00:00:00  to specific time stamps but not 2 days earlier and so on. Is it implemented?

**Comment by Zethalion** [comment]
Thanks for reporting an issue. It's a shame I need to close it while not resolving your issue. That is you ignored the required template for reporting issues. Create a new issue using the provided template if you're still in need of help.
