### ISSUE TITLE
[1.12.2] [Dont work with spongeforge-1.12.2-2838-7.2.0]

### ISSUE THREAD

**Issue by JanisPlayer** [ForgeEssentials/ForgeEssentials#2521]
spongeforge-1.12.2-2838-7.2.0
forgeessentials-1.12.2-12.3.82
Since a server + plugin up
date, versions no longer work together.
Apparently both mods use a different mixin version.

These two mods have always worked together:
forgeessentials-1.12.2-12.3.73-server
spongeforge-1.12.2-2838-7.1.8
I replaced it with thutessentials-1.12.2-2.2.23 until the mods work together again.

[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4565795/debug.log)
or
[debug.log](https://download.heldendesbildschirms.dynv6.net/index.php/s/3BaRSafLNic4a3P)

**Comment by Zethalion** [comment]
Use build 83. Build 82 is for legacy compatibility.

**Comment by JanisPlayer** [comment]
I have now updated to the new Sponge version(spongeforge-1.12.2-2838-7.2.1).
Where can I find build 83?
https://github.com/ForgeEssentials/ForgeEssentials/commit/82c7faba97b30a311f80482ba4def420d9747e61
At least this version doesn't work. forgeessentials-1.12.2-12.3.82
I got it from this site:
https://www.curseforge.com/minecraft/mc-mods/forge-essentials-74735/files/all

**Comment by Zethalion** [comment]
http://ci.forgeessentials.com/job/FE/ as found on https://github.com/ForgeEssentials/ForgeEssentials/wiki

**Comment by JanisPlayer** [comment]
You can also download it here.
https://www.curseforge.com/minecraft/mc-mods/forge-essentials-74735/files/2659142
But unfortunately not for 1.12.2 as it looks.
Too bad, maybe the update for my MC version will come soon.
Thanks anyway for the tip.
Edit:
https://ci.forgeessentials.com/job/FE-1.12.2/
Maybe I can find her here. : D
Yes its work TY. :)

**Comment by Zethalion** [comment]
Sorry I pointed to the 1.10 builds. On the same build server you need to get it here https://ci.forgeessentials.com/job/FE-1.12.2/

Close issue if satisfied please
