### ISSUE TITLE
[1.12.2] [BUG] Crash When Starting Server (ver. 12.3.83)

### ISSUE THREAD

**Issue by OCEAN02** [ForgeEssentials/ForgeEssentials#2522]
The first time I started my server after installing FE there were no issues and I was able to use it as intended. After restarting the server, it always crashes now.

I've tried deleting the ForgeEssentials folder, redownloading the .jar, and removing mods but nothing seems to be working.

[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4567925/modlist.txt)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4567926/debug.log)
[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4567927/latest.log)
[crash-2020-05-02_09.31.16-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4567928/crash-2020-05-02_09.31.16-server.txt)

**Comment by Zethalion** [comment]
Why do you load `OptiFine_1.12.2_HD_U_E3.jar` on your server?
Also `CTM-MC1.12.2-1.0.2.31.jar` and `Xaeros_Minimap_1.16_Forge_1.12.jar` are client only mods too.

**Comment by OCEAN02** [comment]
> Why do you load `OptiFine_1.12.2_HD_U_E3.jar` on your server?
> Also `CTM-MC1.12.2-1.0.2.31.jar` and `Xaeros_Minimap_1.16_Forge_1.12.jar` are client only mods too.

I see, thanks for the heads up. I went ahead and removed those from the server and the issue persists. I'm including the updated documentation.

[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4567997/modlist.txt)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4567999/debug.log)
[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4568001/latest.log)
[crash-2020-05-02_10.32.31-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4568002/crash-2020-05-02_10.32.31-server.txt)

**Comment by Zethalion** [comment]
2 Questions:

Can you run your server without the Obfuscate mod?
Is there anything in your `./world/FEdata` folder and if so, can you upload it to gist?

**Comment by OCEAN02** [comment]
I deleted the `./world/FEdata` folder and that seems to have been the issue. I believe it might have been caused by an incorrect permission syntax.

Thanks for your help @Zethalion
