### ISSUE TITLE
[1.12.2] [BUG] Command blocks disappear when placed.

### ISSUE THREAD

**Issue by StridentDefender32** [ForgeEssentials/ForgeEssentials#2524]
**Initial Steps**
- [x] I have updated to the latest build from Jenkins before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [x] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4595244/modlist.txt)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4595245/debug.log)
- [x] Also, attached are the client logs (if applicable)

**Describe the bug**

**To Reproduce**
On Rebirth of the Night modpack:
1. create new world, with all FE modules disabled in main.cfg
2. OP self
3. Enable command blocks in MC config
4. Start server
5. Try to place a command block
6. Command block instantly disappears on place
7. Also unable to access any command blocks in the world, despite being OP (command blocks worked fine before adding FE, cannot place or interact with existing ones after FE).

**Expected behavior**
Placing command blocks should work if OP.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.04)
 - Version 12.3.83 (latest jenkins build)

**Comment by CunninghamPatrick** [comment]
Disregard I'm an idiot... I left FTBUtilities installed on the server as I'm in the process of migrating off it to FE.

No idea what the actual problem is, but that interaction was what was causing the issues. Disabling FTBUtil solved it.

**Comment by StridentDefender32** [comment]
wow I'm dumb. I left FTBUtilities installed, and that was causing the problem.

Nothing to see here folks. Sorry.
