### ISSUE TITLE
Spamming with message Login required.

### ISSUE THREAD

**Issue by officialdakari** [ForgeEssentials/ForgeEssentials#2525]
Hello!

In the ForgeEssentials config I'm enabled AuthLogin module.
How to disable the spamming with message **Login Required. Try /auth help**

**Comment by BrandonSoul** [comment]
(Continues Waiting)

**Comment by Zethalion** [comment]
Thanks for reporting an issue. It's a shame I need to close it while not resolving your issue. That is you ignored the required template for reporting issues. Create a new issue using the provided template if you're still in need of help.
