### ISSUE TITLE
Forge Essentials ... Cant Interact With Enchanting Tables in Spawn for Default Groups ...

### ISSUE THREAD

**Issue by BrandonSoul** [ForgeEssentials/ForgeEssentials#2526]
Im using forge essentials in my ftb infinity evolved server (1.7.10)

i have the enchanting tables placed in the defined area (MainSpawn)
https://imgur.com/a/T6ffnSy

I set the permissions to interact true for all groups in that specified zone

[my permissions.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4601291/my.permissions.txt)

Im trying to make it so that everyone in the default group can simply use the enchanting tables in the area but not break them. Thank you

**Comment by Zethalion** [comment]
https://github.com/ForgeEssentials/ForgeEssentials/wiki/FTBU-Compatibility-Guide

**Comment by BrandonSoul** [comment]
Hey just wanted to say i fixed the problem, it was because my spawn protection in the main server settings was set to 16, default spawn protection was blocking it.

Has nothing to do with ftbu at all, but thanks for trying atleast

**Comment by BrandonSoul** [comment]
First time i ever try using this for help, disappointing to see someone just roll their eyes post a link (that doesnt even help) and closes the issue. i dont know if whoever closed it is a dev or mod but this is sad lol

**Comment by Zethalion** [comment]
The pack you are using contains FTBU, therefor you need to alter FTBU config to make FE work. I just pointed to the page with the changes you need to make.

**Comment by Zethalion** [comment]
In your defense, that page isn't listed on the wiki landing page. Anyway, FTBU ranks conflicts with FE permissions. That's why you need to disable FTBU ranks.

**Comment by BrandonSoul** [comment]
It took me a bunch of researching when I was trying to figure out the solution, beforehand i learned about the ftbu cause I read like every page of the fe commands and permissions page, somehow my ftbu has the commands active and works fine with fe, doesnt effect the economy or afterlife deathchest setting, so far the permission nodes are working as they should for the defined areas, currently right now I'm working on setting up fe.protection.potion commands for zones and then going to try setting up some sort of paid commands section along with the shop, I didnt realise one person setting this up would be so long and difficult lol, I guess if you know what your doing this goes faster, I'm learning as I go

**Comment by Zethalion** [comment]
Great you figured it was vanilla spawn protection. Still a user error ;)
