### ISSUE TITLE
[1.12.2]java.lang.NullPointerException at FEModuleServerInitEvent[BUG]

### ISSUE THREAD

**Issue by ZimmermannFlorian** [ForgeEssentials/ForgeEssentials#2534]
**latest.log**:
https://pastebin.com/QFxpZCKc

**debug.log** (onedrive because of size)
https://1drv.ms/u/s!AhNBj5xe9s4QiehAzJUkJDD3sS2JXw?e=DmcyFA

**modlist**:
https://pastebin.com/7xPL4ZSw

**Steps**:
Installed mod into an old server(not a new setup, old world etc.)
Started and configured ingame permisions
running for some days
shutting down (without changing anything)

starting up <- doesnt start

**Tested things**:
server starts without the mod
set the file permissions to 777 because it sounded like an permision problem (UserIdentUtils.fetchData)
removing mod, starting server, adding mod

**Specs**:
OS: Ubuntu 18.04.4 LTS
4GB Ram for the server

Java:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

**Comment by Zethalion** [comment]
It looks like a corruption occurred with your permissions.json file in ./world/FEdata
Pastebin that as well

**Comment by ZimmermannFlorian** [comment]
permissions.json
https://pastebin.com/GV05sBzs

**Comment by ZimmermannFlorian** [comment]
i found the cause of  the crash, in the file was a player specified (Stephanie2010 and Stephie2010) she didn't had a uuid set because i added her to a group without her being on the server. That was fine during the server was running but after the restart, that caused the problem i just removed every entry in the file "permissions.json" and it started again, thanks for the tip with the permisions.json
