### ISSUE TITLE
Multi-World Import turns into rocks and void mess & seed not taking

### ISSUE THREAD

**Issue by SlimefrogSocial** [ForgeEssentials/ForgeEssentials#2535]
I am trying to import a world me and my family and friends have been building in for a while as a Multi World.
I have run the command:
 /mw create imported normal DEFAULT -3703330306208790592
with the seed set to the seed of the world I am importing just to remain consistent.
When I do this, it says:
Creating a Multiworld named "imported", provided by "normal", with a world type of "DEFAULT", generator options set to "-3703330306208790592" and the seed set to "(a bunch of random numbers I do not want to retype)"
I don't know why the seed isn't taking because that is the command posted in the wiki...

When I try to continue anyway and copy the world files into the correct multiworld folder, I load the world to see this:
![2020-05-19_13 35 09](https://user-images.githubusercontent.com/62226424/82359837-73054e00-99d6-11ea-8a66-e9bc4977797f.png)
Is there something I am missing or a way to fix this?

**Comment by Zethalion** [comment]
Thanks for reporting an issue. It's a shame I need to close it while not resolving your issue. That is you ignored the required template for reporting issues. Create a new issue using the provided template if you're still in need of help.
