### ISSUE TITLE
[1.12.2] Polygon Zone Creation[FEATURE]

### ISSUE THREAD

**Issue by achrabieh** [ForgeEssentials/ForgeEssentials#2539]
**Is your feature request related to a problem? Please describe.**
Area/Zone Selection does not work for `//sel poly`  polygon selections

**Describe the solution you'd like**
Add a feature that allows to create zones based on the worldedit selected area/blocks

**Comment by Zethalion** [comment]
FE zone system is not based not WorldEdit. WorldEdit integration is limited to rectangles only. FE can only support `//sel poly` if the whole portion of zone selection is rewritten. FE staff is not able at this time to dive into this code to make this happen in a certain time frame. I'm sure you'll figure out the workaround.
