### ISSUE TITLE
[1.12.2] [BUG] No Clip interfering with Galacticraft

### ISSUE THREAD

**Issue by filthydevl** [ForgeEssentials/ForgeEssentials#2540]
Essentials auto noclip feature is forcing galactic craft hydraulic platform to bug out and disable noclip. 

have essentials and galaticcraft installed then set up 
hydraulic platform
press space to go up
shift to go down
error occurs
"NoClip auto-disabled: the targeted player is not flying"

expected no gamerule interferance

Windows
Chrome

**Comment by iRwatching** [comment]
Having the same issue. Minecraft version 1.12.2 forge essential server version 12.3.83

**Comment by williamistGitHub** [comment]
I also get this with the Vamprism mod when trying to enter a coffin as a vampire.

**Comment by spacebuilder2020** [comment]
This is because noclip is a built-in functionality of Minecraft and FE just uses it.  I will look into maintaining a state so that FE will only disable noclip if it was enabled with the noclip command.
