### ISSUE TITLE
Cannot view playerlogger actions

### ISSUE THREAD

**Issue by xSetrox** [ForgeEssentials/ForgeEssentials#2541]
Hi,
I cannot view playerlogger actions. There are no errors or anything. 
When I left-click or right-click the clock somewhere, the server simply freezes and I time out. After a bit I am able to reconnect like usual.
This is a problem, because I really need to see who griefed blocks during the time the server was up, but cannot.
The db has amassed around 9.3 GB. I'm not sure if this is supposed to be the case but I didn't tamper with any options prior to it. 

I have tried purging out useless data, but this freezes the server even worse, to where I need to actually restart.
What can I try and how can I view the DB outside of the server? I downloaded the .db (not the .lock.db) while the server was stopped, now I just need to somehow view it and find out who was breaking blocks.

**Comment by Zethalion** [comment]
Closing for not following our guidelines. See https://github.com/ForgeEssentials/ForgeEssentials/issues/new?assignees=&labels=needs-verification%2C+potential+bug&template=bug_report.md&title=%5B1.12.2%5D+%5BBUG%5D
