### ISSUE TITLE
[1.12.2] [FEATURE]

### ISSUE THREAD

**Issue by PyroSweets** [ForgeEssentials/ForgeEssentials#2542]
Hi! I'm helping a friend manage his modded war server, and we recently found ForgeEssentials as a solution to our problem of offline griefing. However, ForgeEssentials has much more than just block logging, as it comes with economy and plot claims. Is there any way to suppress these features?
**Describe the solution wanted**
I want a way to suppress certain commands and features of ForgeEssentials
**Describe alternatives considered**
I've tried using other block loggers such as CoreProtect, Block Log, and Fast Log Block, but they all either crash the server on startup or they aren't compatible with forge.
**Server Specifications**
Hosted by Apex and MultiCraft
Minecraft 1.12.2
Forge 14.23.5.2854

**Comment by spacebuilder2020** [comment]
Simply deny permissions to use plots.  That is how you suppress them.  Also, if you have no need for economy at all, you can simply disable it.  Currently, plots are part of the economy module so if you don't need either, disabling economy will disable plots.
To disable a module, go to './ForgeEssentials/main.cfg'.

Lastly, Plots are no longer supported anyway and are not recommended for use.
