### ISSUE TITLE
[1.12.2] [BUG] - CustomNPCs cant run commands with FE installed (Continuation of closed issue 2293)

### ISSUE THREAD

**Issue by Bysokar** [ForgeEssentials/ForgeEssentials#2546]
**Initial Steps**
- [x ] I have updated to the latest build from Jenkins before reporting a bug
- [x ] My bug was already reported as : https://github.com/ForgeEssentials/ForgeEssentials/issues/2293 but closed without being resolved.

**Describe the bug**
When attempting to run a command via an NPC, ForgeEssentials does not allow this.
It also attempts to treat all NPCs individually, rather than as a mod - aka. one NPC I have is called Walter Harriman, it comes up as User $NPC_@CUSTOMNPCS-WALTER HARRIMAN during debug, but cannot be assigned any permissions.

**To Reproduce**
1. Install CustomNpcs (1.12.2, October 2019 release)
2. Install ForgeEssentials (All builds including latest as of 4/7/2020)
3. Attempt to get NPCs to run a command

**Expected behavior**

One of the following:

- Permissions should be able to be turned off so server owners can use the other modules without it
- Have FE allow CustomNPCs to run commands.

**Screenshots**
Screenshots not necessary.

**Desktop (please complete the following information):**
 My Desktop specs not relavent.

**Additional context**
Happy to asssist in any way i can.

**Comment by Zethalion** [comment]
Please check https://github.com/ForgeEssentials/ForgeEssentials/issues/2406 as it should be the answer you seek.

**Comment by Bysokar** [comment]
@Zethalion Your a legend. Thanks!!!
