### ISSUE TITLE
[1.12.2] [FEATURE] Corail Tombstone support is not needed. It was removed from Curse without a word.

### ISSUE THREAD

**Issue by MagmaSlime123** [ForgeEssentials/ForgeEssentials#2547]
Title says all. The Corail Tombstone mod was utterly removed from Curse without a word.

**Comment by Zethalion** [comment]
In FE was never a change made specifically for Corail's mod support. The change made only provides better compatibility with modded deathchest mods in general. No need to revert the change.

**Comment by spacebuilder2020** [comment]
In regards to the change, it was indeed made as part of a bargain with Corail to get him to unban FE from his crash to desktop ban list.  (He did not want to unban even though FE's grave module could be disabled).  However, that change also increases compatibility with other grave mods so it shall stay in the code base.
