### ISSUE TITLE
[1.12.2] [BUG]Can't change the default maximum claims/chunkloaded chunks values from ftbutilities a rank can have

### ISSUE THREAD

**Issue by jinkhya** [ForgeEssentials/ForgeEssentials#2551]
**Initial Steps**
- [x] I have updated to the latest build from Jenkins before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [x] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log

**Describe the bug**
Giving the ftbutilities.claims.max_chunks and ftbutilities.chunkloader.max_chunks nodes doesn't work.
After discussing with Zethalion on discord, I tried downgrading Ftbutilities to 5.3.0.68 (didn't work) then downgraded ForgeEssentials to 82 (didn't work either).

**To Reproduce**
1. On the server install FTBUtilities, FTBlib, ForgeEssentials
2. Give a rank some values (like 200 for example) to ftbutilities.chunkloader.max_chunks and ftbutilities.claims.max_chunks
3. Give yourself that rank
4. restart the server (Read somewhere on github it was needed to apply those nodes)
5. Create an FTB team, check how many chunks you can claim/load in the ftbutilities map.

**Expected behavior**
Expecting those values to be applied properly :)

**Screenshots**

**Desktop (please complete the following information):**
Server: 
 - OS: Centos
 - Version: 7.7.1908

Client:
  - OS: Manjaro
  - version 20.0.3
  - firefox

**Additional context**
It looks like the max_chunks doesn't even exist. When you press tab after ftbutilities.claims. here are the only options : https://imgur.com/ZshrQ7p

Modlist : https://paste.gg/p/anonymous/9f4e8db9fa3b49eba8a7753ebabaf8f7
permissions.json : https://paste.gg/p/anonymous/79379bf8ba474eb29bd06d91c335dec5
latest.log : https://paste.gg/p/anonymous/afd85e677c964935b7bf7984973d67ce
debug.log : https://paste.gg/p/anonymous/88cf4ce6dd124b4fa09560863b0952db

**Comment by SpartaWarsec** [comment]
Same Issue here 
So I've tried a few things now and looked in the bug history but didn't find what works and I've searched my Permissionlist.txt

Forge Essentials VERSION forgeessentials-1.12.2-12.3.84-server fresh from jenkins

Server :Windows server 2019 
            All the mods 3 version 6.0.0 game Version 1.12.2

[PermissionsList.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5079280/PermissionsList.txt)

**Comment by spacebuilder2020** [comment]
This was fixed a few builds ago
