### ISSUE TITLE
[1.12.2] Command block disappears [BUG]

### ISSUE THREAD

**Issue by SpartaWarsec** [ForgeEssentials/ForgeEssentials#2553]
Command block disappears i dont can set it in op and gamemode 1 

do I have to set something wrong in a config or so do I see something?

snooper-enabled=true
level-type=BIOMESOP
hardcore=false
enable-command-block=true
max-players=100
network-compression-threshold=256
resource-pack-sha1=

**Comment by Zethalion** [comment]
Closing for not following our guidelines. See https://github.com/ForgeEssentials/ForgeEssentials/issues/new?assignees=&labels=needs-verification%2C+potential+bug&template=bug_report.md&title=%5B1.12.2%5D+%5BBUG%5D
