### ISSUE TITLE
[1.12.2] forgeessentials-1.12.2-12.3.84-server [BUG]Command block disappears

### ISSUE THREAD

**Issue by SpartaWarsec** [ForgeEssentials/ForgeEssentials#2554]
Forge Essentials VERSION  forgeessentials-1.12.2-12.3.84-server  fresh from jenkins 

Server : All the mods 3 version 6.0.0 game Version 1.12.2

Command block disappears i dont can set a command block  but i am in op mode and in gamemode 1 

that is my  config ("server.properties")

snooper-enabled=true
level-type=BIOMESOP
hardcore=false
enable-command-block=true
max-players=100
network-compression-threshold=256
resource-pack-sha1=

[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5078875/modlist.txt)
[server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5078899/server.txt)  props

logs
[2020-08-15-2.log](https://github.com/ForgeEssentials/ForgeEssentials/files/5078905/2020-08-15-2.log)

do you need more infos ?

**Comment by Zethalion** [comment]
How does build 84 for you?
Have you correctly changed FTBU config to make it FE compatible?

**Comment by SpartaWarsec** [comment]
Have you correctly changed FTBU config to make it FE compatible? 
   -I have not found how do I do it?
      -but if you say I have to make it compatible then please explain how
         -I haven't worked with FTBU that often

How does build 84 for you?
  -I've used 82 before ,and this has the same issue


my last server was on MC version 1.7.10 ^^ and this run the last 4 years

**Comment by SpartaWarsec** [comment]
Do you mean this here  

ranks {
    B:crash_client_side_permissions=false

    # Enables ranks and adds command.x permissions and allows ranks to control them.
    B:enabled=true
    B:load_from_config_folder=false

    # Adds chat colors/rank-specific syntax.
    B:override_chat=false

    # Allow to configure commands with ranks. Disable this if you want to use other permission mod for that.
    B:override_commands=false
    B:print_command_errors=true
}

**Comment by Zethalion** [comment]
See https://github.com/ForgeEssentials/ForgeEssentials/wiki/FTBU-Compatibility-Guide

**Comment by SpartaWarsec** [comment]
nice it works  big thanks ,but I still have one question. Can I still adjust the claimed chunk number via FE?

**Comment by Zethalion** [comment]
Yes you can.

**Comment by SpartaWarsec** [comment]
So I've tried a few things now and looked in the bug history but didn't find what works and I've searched my Permissionlist.txt


/p group members allow ftbutilities.claims.max_chunks: 500
/p group members value ftbutilities.claims.max_chunks 9


For example /p user Spacebuilder2020 value ftbutilities.claims.max_chunks 9 will set my user's max_chunk value to 9.
