### ISSUE TITLE
[1.12.2] Permission is not changing

### ISSUE THREAD

**Issue by sofi115187** [ForgeEssentials/ForgeEssentials#2555]
When I try to change the fe.chat.usecolor permission to only OP, it doesn't change. I tried restarting the server and  it still didn't work.

**Comment by Zethalion** [comment]
Closing for not following our guidelines. See https://github.com/ForgeEssentials/ForgeEssentials/issues/new?assignees=&labels=needs-verification%2C+potential+bug&template=bug_report.md&title=%5B1.12.2%5D+%5BBUG%5D
