### ISSUE TITLE
[WEB] [PROBLEM] Outdated link

### ISSUE THREAD

**Issue by JadianRadiator** [ForgeEssentials/ForgeEssentials#2559]
The link for the main curseforge page is outdated used on the optional client mod's curseforge page is outdated.
the optional client mod's link still leads to
http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735/

The correct link is actually this
https://www.curseforge.com/minecraft/mc-mods/forge-essentials-74735/
I suspect you merely forgot to update to update the link after curseforge changed navigating url's to what it is now.

**Comment by Zethalion** [comment]
Thanks? Not clear is which page is now outdated as I followed both your links. Indeed the second one lands on the correct page for the main mod but can you clarify where the supposed wrong link is posted?

**Comment by JadianRadiator** [comment]
the main curseforge link on the [optional client mod](https://www.curseforge.com/minecraft/mc-mods/forge-essentials-client)'s page goes to http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735/
_That's_ the outdated link.
Curse changed how the urls for minecraft are formatted.
The outdated link on the [optional client mod](https://www.curseforge.com/minecraft/mc-mods/forge-essentials-client)'s page uses the old format that doesn't work anymore.

**Comment by JadianRadiator** [comment]
This is from the client mod's page is pointing to the old curseforge format
[For more information about the ForgeEssentials project, visit our main CurseForge page](http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735/).

**Comment by JadianRadiator** [comment]
This text/link from the [client mod's page](https://www.curseforge.com/minecraft/mc-mods/forge-essentials-client) is pointing to curseforge's old url format, which doesn't work anymore.

> [For more information about the ForgeEssentials project, visit our main CurseForge page](http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735/).

You need to update the link's url to this, as it's the current url of the main mod in curseforge's new/current url format.
https://www.curseforge.com/minecraft/mc-mods/forge-essentials-74735/

**Comment by spacebuilder2020** [comment]
Thanks for the tip...  I never noticed that the old link didn't exist.
