### ISSUE TITLE
[1.12.2] [BUG] PlayerLogger isn't immune to server WatchDog.

### ISSUE THREAD

**Issue by DesolateIntention** [ForgeEssentials/ForgeEssentials#2560]
**Initial Steps**
- [Yes] I have updated to the latest build from Jenkins before reporting a bug.
- [Yes] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [Yes] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log

**Describe the bug.**
PlayerLogger crashes the server due to tick time maxing out, even though it was working in the background. It just lagged the server.

**To Reproduce**
**| 1 |** Use `pl purge 5` (requires big `playerloggerh2.db` file).
**| 2 |** Wait through the maximum tick time.
**| 3 |** Server Watchdog will kill the server.

**Expected behavior.**
The server shouldn't crash.

**Screenshots.**
![2020-09-22 00_29_03-WH - BuildingChile](https://user-images.githubusercontent.com/63953363/93841673-ba446980-fc6a-11ea-8218-c0ce6572d103.png)

**Desktop.**
 - OS: Windows 7.
 - Browser: Chrome.
 - Version. I still don't undertand what you are referring to.

[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5259061/modlist.txt)
[2020-09-21-5.log](https://github.com/ForgeEssentials/ForgeEssentials/files/5259063/2020-09-21-5.log)
[debug-2.log.gz](https://github.com/ForgeEssentials/ForgeEssentials/files/5259069/debug-2.log.gz)

**Comment by Zethalion** [comment]
In `server.properties` change `max-tick-time` to a value much higher than 60000
