### ISSUE TITLE
JS Scripting

### ISSUE THREAD

**Issue by CIKOMELANTIK** [ForgeEssentials/ForgeEssentials#2561]
hello, i m trying to learn how to make js scripting with this mod.

the example in this github is radar for all players.

i want to make get player location with input player name

is there any examples? i m trying to click the examples directory in the github but 404 not found.

and also how to

FEServer.registerCommand({
    name: 'radar',
    usage: '/radar: Show all player in this world',
    permission: 'commands.radar',
    opOnly: false,
    processCommand: radarCommandHandler,
}); use parameter if we already set the parameter on the function?

**Comment by Zethalion** [comment]
The examples can be found here https://github.com/ForgeEssentials/FEJSScripts
