### ISSUE TITLE
How To change ranks/permissions manually

### ISSUE THREAD

**Issue by Wang-Hao-Shi** [ForgeEssentials/ForgeEssentials#2562]
hello i have a question how could i change ranks manually without commands because im using the mod but in single player mode so i dont have a console to do it and i cant seem to find on the internet where are the people's ranks stored and the permissions for every rank does anyone knows how could i do it?

**Comment by Zethalion** [comment]
1) Your setup is unsupported.
2) We have a wiki where you could have found the answer.
3) Look in your saves folder
