### ISSUE TITLE
AFK-Detection [1.12.2] [BUG]

### ISSUE THREAD

**Issue by Petschko** [ForgeEssentials/ForgeEssentials#2567]
**Initial Steps**
- [x] I have updated to the latest build from Jenkins before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [ ] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [ ] Also, attached are the client logs (if applicable)

**Describe the bug**
Tinkers-Construct allows players to jump endlessly on a Slime-Block, which never sets the player as AFK, as they moved. It its suggested by a TC member to implement a proper AFK-Check instead of letting them disable that feature via Settings.
Learn more about my reported feature request here: https://github.com/SlimeKnights/TinkersConstruct/issues/4213

**To Reproduce**
1. Have Tinkers-Construct enabled & AFK-Detection in Essentials
2. Place a Congealed Slime-Block
3. Jump on the Slime Block once
4. Go AFK
5. You will never set to AFK

**Expected behavior**
The Player should set AFK, when they don't press any key for X Amount of AFK-Time (From the settings)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Not relevant
 - Version: Not relevant

**Additional context**
https://github.com/SlimeKnights/TinkersConstruct/issues/4213

As suggested, check for the player if they press an actual key instead of movement

**Comment by Zethalion** [comment]
After checking what can be achieved server side on this matter, there is no way to detect key presses and/or mouse movements server side only. What can be checked is player mutations. Thus this issue is impossible to be resolved and therefor closed.
