### ISSUE TITLE
[1.12.2] [BUG] Server crashes on startup

### ISSUE THREAD

**Issue by MickJesper** [ForgeEssentials/ForgeEssentials#2570]
- [Yes ] I have updated to the latest build from Jenkins before reporting a bug
- [ Yes] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [ Yes] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log

**Describe the bug**
Server crashes on startup once i add forge essentials

**To Reproduce**
Start server
Server starts up
Crashes

**Expected behavior**
Server loads up with forge essentials active

**Additional context**
[debug-4.log](https://github.com/ForgeEssentials/ForgeEssentials/files/5561917/debug-4.log)
[crash.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5561692/crash.txt)
[mods.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5561782/mods.txt)

**Comment by Zethalion** [comment]
I can't find FE in your logs. Correct your logs and use the correct files. A partial crashlog listing mods which doesn't even include FE is useless.

**Comment by MickJesper** [comment]
@Zethalion Sorry added the wrong debug log not too experienced with servers this should be the correct one.

**Comment by Zethalion** [comment]
You have not updated to the latest build. You are on build 82. Use the Jenkins build before submitting issues. See https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs Closing.
