### ISSUE TITLE
[1.12.2] [BUG]Permission to teleport in Journeymap GUI

### ISSUE THREAD

**Issue by LokiTHK** [ForgeEssentials/ForgeEssentials#2571]
Hi, i'm working on my minecraft server (Engineer's life modpack), i have changed mods config ecc, but i have a problem since day one, only opped player can use the teleport button in the JM.
Every permission seems alright, infact players can use /tp x y z normally, but they can't in the JM.
This is most of the permission that they have:
![1](https://user-images.githubusercontent.com/22498303/99567464-7ea9ef80-29ce-11eb-88f4-9fa83bfdfb53.PNG)
This is the setting on the JM:
![3](https://user-images.githubusercontent.com/22498303/99567616-a600bc80-29ce-11eb-8722-f7e7e9b625f0.png)
This is the command that the JM use:
![2](https://user-images.githubusercontent.com/22498303/99567667-b87af600-29ce-11eb-8920-2e9ebefdcf24.PNG)
I have even created an alias for the /tp command, and tried to change it in the upper showed setting, obv it worked for op, but not for normal user.
That's what happen when I try to use the JM tp without the OP:
![4](https://user-images.githubusercontent.com/22498303/99568481-c1b89280-29cf-11eb-896f-cbd722e3a203.png)

I tryed everything any suggestion will be much appriciated.

(FE version: forgeessentials-1.12.2-12.3.82-server, JM versio: journeymap-1.12.2-5.7.1)

**Comment by Zethalion** [comment]
What you need is to use `/p debug` prior to the JM tp. That will show you which permission node needs to be enabled.

**Comment by LokiTHK** [comment]
I LOVE U. btw is command.jtp
