### ISSUE TITLE
[1.12.2] [BUG] Major crash every time anyone teleports crossdim (Incompatibility with Better Portals)

### ISSUE THREAD

**Issue by SlimefrogSocial** [ForgeEssentials/ForgeEssentials#2573]
**Initial Steps**
- [Check ] I have updated to the latest build from Jenkins before reporting a bug
- [Check ] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [Check ] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5631780/modlist.txt)

- [X ] Also, attached are the client logs (if applicable)
[crash-2020-12-02_14.11.37-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5631770/crash-2020-12-02_14.11.37-server.txt)

[2020-12-02-6.log](https://github.com/ForgeEssentials/ForgeEssentials/files/5631776/2020-12-02-6.log)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/5631777/debug.log)

**Describe the bug**
Every time anyone teleports crossdim (/back /bed /tpa) the entire server crashes. OP people still crash the server so I do not believe it to be a permission issue.

**To Reproduce**
1. Go to 'any dimension, Nether perticularly'
2. Click on '/spawn or /tpa [A player not in the nether] or /back [to a place not in the nether] or any other form of teleporting from FE'
3. See error

**Expected behavior**
Expected to teleport crossdim to wherever it is that one would be teleporting to.

**Screenshots**
Non applicable

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [forgeessentials-1.12.2-12.3.85-server.jar]

Please help this has been a major hindrance on the server...

**Comment by Zethalion** [comment]
Try again without `zzzbetterportals-0.3.7.7.jar`

**Comment by SlimefrogSocial** [comment]
Fixed the issue, incompatibility I guess. Do you know of a way to fix it? This is not a critical mod in the server but it is useful.

**Comment by Zethalion** [comment]
You can open an issue on the Better Portals issue tracker and link to this one. There's no saying what solution will be.

**Comment by SlimefrogSocial** [comment]
Thank you! They said the same thing, but to you. Is there a way y'all to colab a solution?
https://github.com/Johni0702/BetterPortals/issues/581

**Comment by SlimefrogSocial** [comment]
Ok they said that it can be fixed on your end by doing something they said in that other issue.

**Comment by Vladilion90** [comment]
Здравствуйте, я так и не понял как решить эту проблему с телепортом из мира в мир, я могу умереть в аду и воскреснуть возле кровати и сервер крашится,

Hello, I did not understand how to solve this problem with the teleport from world to world, I can die in hell and rise again near the bed and the server crashes,

**Comment by SlimefrogSocial** [comment]
Make sure you have updated Forge Essentials to the latest release, they put out a fix for it a while back. Unless something broke again in newer releases that should work. I am not using the latest release but I am far enough to fix this issue!

Убедитесь, что вы обновили Forge Essentials до последней версии, они исправили ее некоторое время назад. Если что-то не сломалось снова в новых выпусках, это должно сработать. Я не использую последнюю версию, но мне достаточно, чтобы исправить эту проблему!

I used google translate for this sorry if my grammar and such are off...

Я использовал Google Translate для этого, извините, если моя грамматика и тому подобное не работают ...

https://www.curseforge.com/minecraft/mc-mods/forge-essentials-74735
