### ISSUE TITLE
[1.12.2] Unknowkn hibernate issue [BUG]

### ISSUE THREAD

**Issue by Taknax** [ForgeEssentials/ForgeEssentials#2574]
**Initial Steps**
- [X ] I have updated to the latest build from Jenkins before reporting a bug
- [X ] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [X ] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [X ] Also, attached are the client logs (if applicable)

**Describe the bug**
The log is in the serverconsole. Its not causing problems, but i want to figure out what it is

**To Reproduce**

**Link for exact issue example**
[https://pastebin.com/1m2sdJMP](url)

**Comment by spacebuilder2020** [comment]
This can be ignored.  This is normal due to non-Minecraft libraries including exit().  Forge handles it and gives a warning.

This only an issue if it is included in a mod jar.
