### ISSUE TITLE
[1.12.2] [BUG] Permissions not working whatsoever

### ISSUE THREAD

**Issue by JoshJOkayguy** [ForgeEssentials/ForgeEssentials#2576]
**Describe the bug**
I have Forge Essentials installed on a server with a custom modpack (Yes, FTBU is installed but I followed the proper compatibility steps). The issue is that, with any group, denying or allowing any permission does not work, ever, despite the fact that it says it worked. Is it possible that this is an issue with the beta I was not aware of?

**To Reproduce**
1. /p group Test allow fe.commands.gamemode
2. /p save (not sure if necessary)
3. /gamemode survival
4. "You do not have permission to use this command"

**Expected behavior**
I expect to be able to use /gamemode.

**Desktop (please complete the following information):**
 - OS: Windows 10 (Server running on Debian 10)
 - Browser: Chrome
 - Version: FE 12.3.83

[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/5779494/latest.log)
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5779495/modlist.txt)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/5779492/debug.log)

**Comment by Zethalion** [comment]
1) Update to latest build from Jenkings
2) Use `/p debug`

**Comment by JoshJOkayguy** [comment]
> 1. Update to latest build from Jenkings
> 2. Use `/p debug`

Looks like updating fixed a lot of my issues. The only one that still stands is /gamemode not working. Using the debug command it shows that /gamemode is set to false for me, even though I set it to true using the commands.

**Comment by Zethalion** [comment]
``In Java Edition, a player with operator permissions on a server or cheats enabled is able to open a GUI by pressing F3 and F4, which then allows the player to cycle through the four available gamemodes available with /gamemode by pressing F4.``
https://minecraft.gamepedia.com/Gameplay#Game_modes

Only available for OP

**Comment by gewenzsko** [comment]
This does not make any sense. It worked with older builds. I just updated the server from .83 to .117 and my users are complaining that they can't use gamemode anymore even though they could easily use it before WITHOUT being OP.

Whats the deal? I am confused

**Comment by spacebuilder2020** [comment]
@gewenzsko There was a change in how command aliases worked in the newer builds.  This had a downstream effect on permissions.  As a result, you will need to use the node `fe.commands.fegamemode` for the time being.  A fix will be provided later so the old node works, but this node should fix your issue!
