### ISSUE TITLE
[1.12.2] [BUG] Cant start server

### ISSUE THREAD

**Issue by Taknax** [ForgeEssentials/ForgeEssentials#2578]
**Initial Steps**
- [x] I have updated to the latest build from Jenkins before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [ ] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [x] Also, attached are the client logs (if applicable)

**Describe the bug**
I installed the v88 of FE on a fresh forge 2855 server and its not loading. The server is hosted on ApexHosting.

**To Reproduce**
1. Go to 'serverconsole'
2. Click on 'restart'
3. Scroll down to 'the bottom and'

**Expected behavior**
Server start.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome]
 - Version []

**Additional context**
[https://pastebin.com/FJK3b1MF](url)

**Comment by Zethalion** [comment]
Run your server locally on your pc to troubleshoot the issue. Also you didn't include any complete logs.

**Comment by Taknax** [comment]
Was because a corrupted jar. Fix it with clean my jar up. But know i have weird hibernate issue.
Ty for your patient.

[https://pastebin.com/LXbzWbeT](url)

**Comment by Zethalion** [comment]
That's not an issue. That message is generated by a library jar, not FE itself.

Good to see your initial problem is solved.
