### ISSUE TITLE
I can't connect via rcon on the Server?

### ISSUE THREAD

**Issue by Johann-vln** [ForgeEssentials/ForgeEssentials#2580]
Hi,
I made a Minecraft Forge Server on the 1.12.2 with forge essentials and i cant use the rcon?
Why?
Thanks for Help

**Comment by Zethalion** [comment]
Closing for not following our guidelines. See https://github.com/ForgeEssentials/ForgeEssentials/issues/new?assignees=&labels=needs-verification%2C+potential+bug&template=bug_report.md&title=%5B1.12.2%5D+%5BBUG%5D
