### ISSUE TITLE
Give Rcon Permissions

### ISSUE THREAD

**Issue by Johann-vln** [ForgeEssentials/ForgeEssentials#2581]
Hi how can i give my rcon all the permissions?
Thanks For Help

**Comment by Zethalion** [comment]
> Hi,
> I made a Minecraft Forge Server on the 1.12.2 with forge essentials and i cant use the rcon?
> Why?
> Thanks for Help
Same as https://github.com/ForgeEssentials/ForgeEssentials/issues/2580
