### ISSUE TITLE
[1.12.2] [BUG] Pixelmon Broadcasts notify permission

### ISSUE THREAD

**Issue by Mnesikos** [ForgeEssentials/ForgeEssentials#2583]
**Initial Steps**
- [x] I have updated to the latest build from Jenkins before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [x] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/6217174/modlist.txt)
[debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/6217213/debug.log)
[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/6217214/latest.log)

**Describe the bug**
Pixelmon Broadcasts uses a permission for broadcasted chat messages, such as "pixelmonbroadcasts.notify" ([link](https://pixelmonmod.com/wiki/Pixelmon_Broadcasts)), that are not recognized by Forge Essentials. The only node that generates in Essentials' PermissionsList.txt is "command.pixelmonbroadcasts", this is an unrelated node. OPs receive the broadcasts, anyone else does not.

**To Reproduce**
1. Give global access to "pixelmonbroadcasts.notify" (unrelated to command.pixelmonbroadcasts)
2. In config/PixelmonBroadcasts/settings.conf set "normalCatchOptions = chat" and save, run "/pixelmonbroadcasts reload"
3. As an OP'd player, catch a pokemon. On successful capture, you will see a broadcast of your catch.
4. As a de-OP'd player, catch another pokemon. On successful capture, you will not see a broadcast.

**Expected behavior**
A permission node for this notify broadcast should generate in PermissionsList.txt, and allow chat broadcasts to users that have the permission enabled.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 87.0 (64-bit)
 - Version: _sorry.. not sure what version specifically this is asking for, so;_ forgeessentials-1.12.2-12.3.88-server.jar

**Additional context**
N/A

**Comment by spacebuilder2020** [comment]
This is probably cause Pixelmon Broadcasts is not registering permissions properly in Forge.  As long as a permission has been registered, it should show up in FE.  (This is specific to Boolean permissions only.  Forge Permission api does not support non Boolean permissions).  I recommend making a bug report on the Pixelmon side and referencing this issue.  In the case of a non Boolean permission, the mod will need to check FE's extended permission handler.

**Comment by spacebuilder2020** [comment]
@Mnesikos I am closing this cause I tried to work with the Pixelmon devs on compatibility but they were very resistant.

The mod doesn't even use the Forge Permission api so that is definitely bound to cause problems.

**Comment by spacebuilder2020** [comment]
I am reopening cause I heard from the PixelMon developers that they are working on switching to the Forge Permission API.

For now, PixelMon is not supported by FE but hopefully once it implements the permission api, it will be compatible with Forge Essentials.

**Comment by spacebuilder2020** [comment]
@Mnesikos Please test with build 89 (https://ci.forgeessentials.com/job/FE-1.12.2/89/artifact/build/libs/forgeessentials-1.12.2-12.3.89-server.jar).  I have updated Forge Essentials to understand Sponge based permission as documented in https://docs.spongepowered.org/stable/en/plugin/permissions.html#for-forge-mods.  Since this is how PixelMon checks permissions, it should provide compatibility with PixelMon.

**Comment by spacebuilder2020** [comment]
I have seen reports of people being able to allow access to pixelmon permissions as of build 89+, so I am closing this for now.  @Mnesikos if you encounter any other issues related to pixelmon permissions, feel free to reopen this issue!
