### ISSUE TITLE
[1.12.2] [BUG]

### ISSUE THREAD

**Issue by rsslbnvj** [ForgeEssentials/ForgeEssentials#2584]
MajorSleeping working in overworld dimension, but when i transfer into other dimension using MultiWorld MajorSleeping won't work

**Comment by Zethalion** [comment]
Closing for not following our guidelines. See https://github.com/ForgeEssentials/ForgeEssentials/issues/new?assignees=&labels=needs-verification%2C+potential+bug&template=bug_report.md&title=%5B1.12.2%5D+%5BBUG%5D
