### ISSUE TITLE
[1.12.2] [BUG] Noclip not being enabled

### ISSUE THREAD

**Issue by gordongman666** [ForgeEssentials/ForgeEssentials#2586]
I have a problem with English, so here’s the video: https://www.youtube.com/watch?v=_JiJRqNEHSI

**Comment by Zethalion** [comment]
Do you have the client companion mod installed? https://ci.forgeessentials.com/job/FE-1.12.2/88/artifact/build/libs/forgeessentials-1.12.2-12.3.88-client.jar

**Comment by Zethalion** [comment]
@gordongman666 Please respond

**Comment by gordongman666** [comment]
yes

**Comment by spacebuilder2020** [comment]
I have determined that this issue is being caused by vanilla code setting noclip each tick to the value of isSpectator.  I will work on a fix later.
