### ISSUE TITLE
[1.12.2] [BUG] MultiWorld OTG Crash

### ISSUE THREAD

**Issue by jcc10** [ForgeEssentials/ForgeEssentials#2588]
**Initial Steps**
- [*] I have updated to the latest build from Jenkins before reporting a bug
- [*] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [*] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [ ] Also, attached are the client logs (if applicable)

- [modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/6487518/modlist.txt)
- [debug.log](https://github.com/ForgeEssentials/ForgeEssentials/files/6487516/debug.log)
- [latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/6487517/latest.log)

**Describe the bug**
Soft Crash when trying to create a new dimension.

**To Reproduce**
1. With `Open Terrain Generator` and `Traveler's Dream` (compact) both installed and enabled, try to create any kind of dimension (such as FLAT or OTG).
2. World Creation will fail part way through. (though it will try to back it up.)

**Expected behavior**
It shouldn't fail?

**Screenshots**

**Server (please complete the following information):**
 - OS: MX Linux Debian
 - Browser ???
 - Version 1.12.2-12.3.88

**Additional context**
PG85/OpenTerrainGenerator#639

**Comment by Zethalion** [comment]
Try the solution from https://github.com/ForgeEssentials/ForgeEssentials/issues/2499
It might work for OTG as well

**Comment by jcc10** [comment]
#2499 does not work, The world actually generates files in the `server/TravelersDreamCompact/FEMultiworld` (Equv of `server/world/FEMultiworld`) directory, but none in the `server/TravelersDreamCompact/FEData/json/Multiworld` directory. It also does not list any worlds when running `/mw list` or `/mw list worlds`. Resulting in no worlds to teleport to.

I could try manually inserting JSON's there if someone can give me a example one for a flat world with parameters. Worst case scenario is it doesn't load which is where I am right now so, nothing lost but time and we rule out a bit of where the problem is.

**Comment by Zethalion** [comment]
You misunderstood the direction. Create a DEFAULT mw and stop the server. Replace the generated `level.dat` with the OTG SSP one. FE MW will create the MW based on the `level.dat` file and ignoring anything in the configs as they are only used if there isn't a `level.dat` file already.

**Comment by jcc10** [comment]
That did not work, however using the world creation menu I did not know was built into OTG did, so I'm closing the issue. (thanks for the help).
