### ISSUE TITLE
[1.12.2] [BUG] Version issue

### ISSUE THREAD

**Issue by ThePyeGuy** [ForgeEssentials/ForgeEssentials#2589]
In short im running a mod pack using forge 2847

The pack is Tekxit 3 1.12.2 (Official) 

The only issue im facing is the correct version to download and use on my server. 

What version do i need for forge 2847 (forge-1.12.2-14.23.5.2847-universal.jar) ?

you cant even provide a version to help? easy question. just tell me the forge compatible version. none of your FE versions specify what forge version they use.

**Comment by Zethalion** [comment]
Yikes! That sounds problematic. Also, we can't help you for not following our guidelines. See https://github.com/ForgeEssentials/ForgeEssentials/issues/new?assignees=&labels=needs-verification%2C+potential+bug&template=bug_report.md&title=%5B1.12.2%5D+%5BBUG%5D
Closing this one and please do a proper report.

**Comment by spacebuilder2020** [comment]
Forge Essential is compatible with most versions of Forge.  Build 88 was build with Forge 2784.  However, we recently updated to forge 2847 in build 89.
