### ISSUE TITLE
[1.12.2] [FEATURE] Personal Warp

### ISSUE THREAD

**Issue by Dzentelmenn** [ForgeEssentials/ForgeEssentials#2603]
Hi, 
I have a question about /pwarp.
Is there any possibility for people to be able to teleport on their pwarps?

**Comment by spacebuilder2020** [comment]
Personal warps are only for the specified player, however the act just like a normal warp and that player can teleport to any of their defined positions.

Ex: `/pwarp miningspot set` will set a warp named mining spot.
The player can then teleport to that spot with `/pwarp miningspot`.

See https://github.com/ForgeEssentials/ForgeEssentials/wiki/Players-Guide-to-ForgeEssentials for more details of such commands.
