### ISSUE TITLE
[1.7.10] [BUG] Failure when attempting to load a world, attempting to backup Proxima (Chromaticraft)

### ISSUE THREAD

**Issue by Shahelion** [ForgeEssentials/ForgeEssentials#2606]
Log files: https://gist.github.com/Zsashas/3cdbcd248428dfd8a8daa63ef5c87942 (This has a mod list, latest log, the specific error, and the full log containing said error)
Version: 1.4.6 (Latest available from Curseforge for 1.7.10)

**Describe the bug**
Game loads up fine, but fails when attempting to make a backup of Chromaticraft's Proxima (Dim 60) on load. I have disabled backups on load, but it still fails with the same report.

**To Reproduce**
1. Start up the game
2. Attempt to load a world
3. Watch it fail trying to backup Proxima
4. Kicks the user back to the main menu with a fatal error message

**Expected behavior**
For it not to disconnect me

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I am currently awaiting information from another user on Discord, who claims that he uses this setup to regularly make backups of Proxima, but only when the dimension is unloaded. That's exactly what I'm trying to do. I'd like to have backups of everything else regularly, but Dim 60 needs to only be when unloading it.

**Comment by Zethalion** [comment]
Don't use FE on your client. That configuration is unsupported. FE is server only.

**Comment by Shahelion** [comment]
So there's no way to use it for a single-player world or for LAN?

**Comment by spacebuilder2020** [comment]
Forge Essentials is server side only! If you need a backup tool for single player, I recommend [Aroma Backup](https://www.curseforge.com/minecraft/mc-mods/aromabackup/files/all?filter-game-version=2020709689%3A4449)!

As for other FE features, they may work in single player but you are on your own!
