### ISSUE TITLE
[1.7.10]Register have been disabled in Auth Module

### ISSUE THREAD

**Issue by Romacat2** [ForgeEssentials/ForgeEssentials#2618]
My friend went to my server with ForgeEssantions, but when he registered, an error appeared: Register have been disabled.
How to fix it?

**Comment by maximuslotro** [comment]
@Romacat2 
```
 if (ModuleAuth.isEnabled() && !ModuleAuth.allowOfflineRegistration)
                    throw new TranslatedCommandException("Registrations have been disabled.");
```
This code is what is throwing the error.
The causes could be:

1.  The Auth module isn's enabled.
2. allowOfflineReg is set to false in the AUTH config. ("Allows people to register usernames while server is offline. Don't allow this for primarily Online servers.")
3. or both the Auth module is disabled and allowOfflineReg is set to false in the AUTH config.

Try enabling the module or changing the config option.

**Comment by Romacat2** [comment]
Thank you, @maximuslotro

**Comment by maximuslotro** [comment]
@Romacat2 
I will now count this issue as closed An hour from now, unless the above hasn't worked for you.

**Comment by maximuslotro** [comment]
Issue Resolved.
