### ISSUE TITLE
Feature Request: Rei's Minimap options to permission node

### ISSUE THREAD

**Issue by gominecraft** [ForgeEssentials/ForgeEssentials#324]
Remove the Rei's Minimap config options from the main.cnf and turn them into permission nodes.

eg:

ForgeEssentials.Reis.cavemap
ForgeEssentials.Reis.radar.animal
ForgeEssentials.Reis.radar.mod
ForgeEssentials.Reis.radar.other
ForgeEssentials.Reis.radar.player
ForgeEssentials.Reis.radar.slime
ForgeEssentials.Reis.radar.squid

Default: Deny for all, allow for "Owners" default rank.

**Comment by Nozgo** [comment]
I realize this is an old post, but can anyone tell me the functionality of the 
ForgeEssentials.Reis.radar.other
perm?
I would assume it shows other players.... but....
