### ISSUE TITLE
[Bug] Respawn In nether

### ISSUE THREAD

**Issue by ghost** [ForgeEssentials/ForgeEssentials#697]
If you die In a Dimension you will respawn in the nether. It does not give a error
Minecraft: 1.4.7 server
Forge Version: 6.6.2.534
Forge Essentials version: 1.2.0.44

**Comment by ghost** [comment]
This is still happening to me but only to a certain player

**Comment by spacebuilder2020** [comment]
Please Open a new issue for a current supported version of Forge Essentials (1.12.2) following all the applicable bug report criteria.  This issue is for Minecraft 1.4.7 and has been closed for almost 6 years.
