### ISSUE TITLE
AuthModule Automation

### ISSUE THREAD

**Issue by LargePrime** [ForgeEssentials/ForgeEssentials#708]
If one assumes FE has a client side presence.
Client side AuthModule could send Per Server Login information automatically for instant seem-less SECURE logins

Also...
Improved Security.  Authorization setup, Login AND password could be automatically generated and sent without RUNTIME user participation.  Client side Config File can hold and store all needed Client information.  Password could be RANDOMLY generated and stored for the client.

Key exchange.  Login password could be VERY SECURE Key exchange, (For Staff?) all generated and exchanged automatically with no RUNTIME user participation from Client Configs.

**Comment by olee** [comment]
Actually got a nice idea: Why not remove that whole complicated password stuff and just do it this way:
1. Require FE client for auth module
2. On first launch FE client generates a UUID and saves it
3. When connecting to the server client sends the UUID and the server remembers it
4. When server goes into offline mode, it requires players connecting to have their UUID in the server's user list

Would probably reduce the needed code for auth to 50% and we could also immediately kick players that do not send a UUID (missing FE client), so we don't need to care about unlogged players doing stuff on the server any more.

**Comment by evernife** [comment]
But, for exemple, if i actualize my modpack and get lost of all my config folder, will i lost my account?

**Comment by luacs1998** [comment]
You may, you may not. It could be possible for us to leave a tokens file in the save-dir...

But @olee if you want it done that way then I'm open to a rewrite of auth-core.

**Comment by olee** [comment]
Well the code would be easy to write.
The **only** downside is, that it is not possible to authenticate without client mod any more.
However for a server wanting easy and automatic offline-play via auth-module, this should be no problem and instead be a welcomed change imho.
Auth-module would not even need a command any more and would be a lot safer.

**Comment by luacs1998** [comment]
I remember you having moral objections to auth-module so I'll handle it instead.

**Comment by olee** [comment]
Well not really morale objects, but I just didn't know what was the meaning behind auth module.

**Comment by evernife** [comment]
For modpacks. If the auth module become a Client side mod too (OR the entiry ForgeEssentials), there will be a phew problemns.

First problem, it will limitate the update frequenci of the ForgeEssentials, for now, we can just download the ServerSide ForgeEssentails.jar and update easily. But, if the process become client side, we will need to re-make the client constantly, and this is really not viable.

************
"You may, you may not. It could be possible for us to leave a tokens file in the save-dir..."
************
Even if the file was save in onther place, there will be no way for a client join the server from a different Computer, lets simulate:  I am in my home, i play in the "FinalCraft Server", but, now i want to play in the same server in my friend's home, if the auth was client automated, this will became impossible.

Another exemple, if i had to format my computer, will i lose my account for ever?
Even if this bring more safety, in my vision, the problem will increase.

**Comment by olee** [comment]
Hm you are right... we really need to think through all possible solutions once again...

**Comment by bit2shift** [comment]
Guys, please, keep your minds focused.
1. To tackle with the "modpack issue", having *FE on the client must be optional*.
2. About the tokens file, put it on the root of the modpack installation and (optionally) inform the user of its absolute path.
3. The "play on a different computer" problem is *exclusively* theoretical. Most (if not all) people either stick with their desktop at home or carry their laptop around.
4. For the rare case of someone playing on a different computer (seriously, noone does this, it takes time to reconfigure all the options just for that time you play with Bob at his house on his computer), it's upto to the user to carry the tokens file in a flash drive around, given the fact the file remains unchanged for a considerable period of time.

**Comment by evernife** [comment]
Sorry to say, but, here in Brazil this is ABSOLUTELY NORMAL and COMMOM.
And not only here, Portugal and some other countries.

But, if this client-side WILL BE OPTIONAL, for me its really ok. Just pointing that you have the trouble to make two AuthModules system, the normal, only server side, and the cliente integration.

For me, just wasted time.
(What is the purpose of AuthModule? Lock your server account from others users of the same minecraft account!) 

For exemple: Myself, (and a lot people in my server), i have a brother, and i don't want him to play in my account, so, o lock it. 

{If you want to make this, the ONLINE version is better, because allow different Computers to login)}

PS: Not everyone has his own MACbook :D
PS²: There is something called "LAN-HOUSE"

**Comment by cullorblind** [comment]
I actually play on three different computers regularly, and occasionally on my laptop.  My nephew also plays on two of those same computers, so it's not a theoretical problem from my point of view.  I keep him from logging into my account by setting up windows profiles, and he has his own desktop.  I do agree that most people do play from a single computer though because most people only have one.

In my mind some sort of caching of legitimate mojang auth tokens(if that's legal/possible) might be better, unless I'm missing the point of the auth module?  It seems fairly rare that Mojangs auth servers go down lately anyway.

**Comment by evernife** [comment]
cullorblind , i dont agre with you, i think that this module is really useful. But, as you said, you play from THREE DIFFERENT COMPUTERS, and this is just an exemple. As i said, we need to take care with this mod. And as olee said, "we really need to think through ALL POSSIBLE SOLUTIONS once again..."

I really dont see (For now) the necessity of this Automation, in fact, will only bring more work.

**Comment by luacs1998** [comment]
The one major rule is:

**DON'T TRUST THE CLIENT. THE CLIENT CAN LIE.**

Which is why all authentication should be done server-side, using either username/password combinations managed by the server, or a defined 3rd party authentication provider trusted by, and preferably configured by the server (or its staff).

**Comment by bit2shift** [comment]
@luacs1998 I've worked on a (now defunct) project that pretty much covered what we're talking about in here.
The token was provided to a player through the forum website on the profile section, and then inserted on the "add server" GUI.
On the server-side, there was a daemon using MySQL and talking with each MC server.
Call it "dynamic whitelist" if you want, while having the regular whitelist for maintenance.

**Comment by olee** [comment]
@evernife 
> What is the purpose of AuthModule? Lock your server account from others users of the same minecraft account!

Well. Normally you are supposed to have your own account anyway. At least **no one** should give his account login to someone he does not trust so this is irrelevant (for 99.9% of the MC players).

@bit2shift 
> 1. To tackle with the "modpack issue", having FE on the client must be optional.
> 2. About the tokens file, put it on the root of the modpack installation and (optionally) inform the user of its absolute path.
> 3. The "play on a different computer" problem is exclusively theoretical. Most (if not all) people either stick with their desktop at home or carry their laptop around.
> 4. For the rare case of someone playing on a different computer (seriously, noone does this, it takes time to reconfigure all the options just for that time you play with Bob at his house on his computer), it's upto to the user to carry the tokens file in a flash drive around, given the fact the file remains unchanged for a considerable period of time.

Good feedback.
 1. You don't even need the file. The token should be about 16 characters maybe an can be saved as a note / mail / whatever if one wants to use it on another PC.
 2. If the client-mod is not present, we could jail the player and he needs to do something like  
  `/auth <TOKEN>` with the token he copied from the file / mail / whatever
 3. In comparison to the current implementation, I think we should definetly try to remove the need to create a password / make the registration automatically.

A username should not be necessary as we expect the user to login with the *same* username every time / we should be able to use the UUID (if one selects offline play in MC client, I think it uses the last known Mojang-account UUID - *needs verification*)

How about that?

**Comment by luacs1998** [comment]
I said already, leave it to me.

**Comment by evernife** [comment]
*****
DON'T TRUST THE CLIENT. THE CLIENT CAN LIE.
*****

#Leave#to#luacs1998

(But, if you could fix #1428 before you do your work i will be really gratefull, if it is not a waste of time, of course)

**Comment by luacs1998** [comment]
Continue in #1940
