### ISSUE TITLE
/bed and bed respawning ignores current dimension

### ISSUE THREAD

**Issue by Mysteryem** [ForgeEssentials/ForgeEssentials#876]
Using the /bed command in any dimension other than the overworld, teleports the player (to presumably the same coordinates), but in the dimension they are currently in.

Using /bed in the nether is an easy way to first lag the server while it generates a bunch of chunks (as it's quite likely to be far away from you) and then kill you by falling(teleport/spawn in mid air)/suffocating(teleport/spawn in a block)/lava(teleport/spawn in mid air or lava).

Alternatively, the same occurs when dying in non overworld dimensions if the player has a bed set.

Occurs with both 1.5.2-SNAPSHOT.183 and Build 1.2.1.275.

**Comment by DPxKnightxZero** [comment]
Alright my players keep crashing and having what I call rolling deaths. I am using 479 but the symptoms are as follows ... people set a spawn and I made sure they didn't have any obstructions ... but when they re-spawn or wake up they get murdered. By suffocation or falling through the world.

**Comment by olee** [comment]
Please open a new issue for this one.
I would also like to test this on your server.
It would help me a lot if you could call out to me on IRC.

**Comment by DPxKnightxZero** [comment]
I keep asking how do I get to IRC

**Comment by olee** [comment]
First: http://lmgtfy.com/?q=how+to+connect+to+irc
It is a piece of cake to do this, isn't it?

And even though I should not was time for this, here a simple way to connect to IRC:
If your browser supports it (i.e. firefox) just use this as link: irc://irc.esper.net/forgeessentials
Or use this one: http://chat.mibbit.com/?channel=%23forgeessentials&server=irc.esper.net

**Comment by DPxKnightxZero** [comment]
Alright thank you. I have been super busy so I don't know when I will get on.

**Comment by olee** [comment]
@DPxKnightxZero your issue should also be fixed by https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/b36ce7ec88b87f5ce230bc282af1b99f42e560d6
Update to latest version.
