### ISSUE TITLE
FE  1.6.4-1.3.0 causing bed issue

### ISSUE THREAD

**Issue by Gunner76th** [ForgeEssentials/ForgeEssentials#979]
If only one person is online, and tries to use their bed, instead of the bed working like normal, and setting their spawn point and making it day after they "sleep" in their bed, it instantly turns it to day, and fails to set their spawn point. If more than one person is online, the beds appear to operate as expected.

I have tried this with  
        # If +50% of players sleep, make it day.
        B:MajoritySleep=false
set to both true and false, and the results are the same. As soon as I disabled the forge essentials main jar file, the beds operated as expected with just one player online. This was not an issue in 1.3pre5, it only started happening with 1.6.4-1.3.0.

**Comment by asmerkin** [comment]
I have the same issue Here. 

Using ForgeEssentials 1.8
